FROM ubuntu:22.04

WORKDIR /root

ARG cpuType

# 设置环境变量
ENV TINI_VERSION=v0.19.0
ENV DEBIAN_FRONTEND=noninteractive

# 先安装系统依赖和tini，这层可以被缓存
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${cpuType} /tini
RUN apt-get update && apt-get install -y --no-install-recommends \
    locales tzdata netcat curl gdb vim tmux less \
    net-tools valgrind openjdk-11-jdk rsync jq \
    sqlite3 ca-certificates && \
    locale-gen en_US.UTF-8 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    chmod +x /tini

# 接收构建参数
ARG pkgFile
ARG dirName
RUN echo ${pkgFile} && echo ${dirName}

# 处理大文件包 - 只有当包文件变化时才重新构建这层
COPY ${pkgFile} /root/
RUN tar -zxf $(basename ${pkgFile}) && \
    cd /root/${dirName}/ && \
    /bin/bash install.sh -e no && \
    cd /root && \
    rm /root/$(basename ${pkgFile}) && \
    rm -rf /root/${dirName}

# 设置运行时环境变量
ENV LD_LIBRARY_PATH=/usr/lib \
    LC_CTYPE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

COPY ./bin/* /usr/bin/

ENTRYPOINT ["/tini", "--", "/usr/bin/entrypoint.sh"]

VOLUME [ "/var/lib/taos", "/var/log/taos", "/etc/taos", "/corefile" ]