name: Node.js Enterprise

on:
  push:
    branches:
      - "main"
      - "3.0"
  pull_request:
    branches:
      - "main"
      - "3.0"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x, 20.x]
    steps:
      - name: Get TDengine
        run: wget "${{ secrets.NIGHTLY_TDENGINE_ENTERPRISE_BASE_URL }}/tsdb-nightly-main.tar.gz?v=$(date +%s)" -O tsdb-nightly-main.tar.gz

      - name: Install TDengine
        run: |
          tar -zxf tsdb-nightly-main.tar.gz
          rm -rf tsdb-nightly-main.tar.gz
          cd tsdb-nightly-main
          sudo ./install.sh

      - name: Start TDengine
        run: |
          sudo mkdir -p /etc/taos
          sudo mkdir -p /var/log/taos
          nohup sudo taosd &
          nohup sudo taosadapter &

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "nodejs-connector"
          clean: true
          set-safe-directory: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        working-directory: nodejs-connector/nodejs
        env:
          TDENGINE_CLOUD_URL: ${{ secrets.TDENGINE_CLOUD_URL }}
          TDENGINE_CLOUD_TOKEN: ${{ secrets.TDENGINE_CLOUD_TOKEN }}
          TEST_ENTERPRISE: true
        run: |
          npm install
          npm list
          npm run example
          npm run test
