[package]
name = "sink-parquet"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
futures.workspace = true
taos.workspace = true
parquet.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
