#!/bin/bash

csudo=""
if command -v sudo > /dev/null; then
    csudo="sudo "
fi

# only remove package to call preun.sh, not but update(2)
${csudo}rm -f /usr/bin/taosdump      || :
${csudo}rm -f /usr/bin/taosBenchmark || :
${csudo}rm -f /usr/bin/taosdemo      || :
${csudo}rm -f /usr/bin/TDinsight.sh  || :

${csudo}rm -f /usr/local/bin/taosdump      || :
${csudo}rm -f /usr/local/bin/taosBenchmark || :
${csudo}rm -f /usr/local/bin/taosdemo      || :
${csudo}rm -f /usr/local/bin/TDinsight.sh  || :
