CMAKE_MINIMUM_REQUIRED(VERSION 3.0)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/os)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/util)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/common)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/client)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mgmt)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mnode)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/monitor)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/transport)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/scheduler)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/mnode/impl/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/qcom)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/catalog)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/planner)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/nodes)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/sync)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/wal)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/tfs)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/stream)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/vnode/src/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mnode/sdb)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/cJson)
INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/src/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/mnode/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/dnode/inc)
INCLUDE_DIRECTORIES(inc)

LIST(APPEND LIB_SRC ./src/grantMain.c)

IF (BUILD_WITH_CFG_GRANTS)
  ADD_DEFINITIONS(-DGRANTS_CFG)
  #ADD_LIBRARY(grant STATIC ${LIB_SRC} ./src/wmachine.c)
ENDIF ()

IF(TD_ENTERPRISE)
  IF (TD_LINUX_64)
    IF (TD_NINGSI)
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_ningsi.o)
      ELSEIF (TD_ARM_64)  
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_arm64.o)
    ELSEIF (TD_ARM_32)   
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_arm32.o)
    ELSEIF (TD_ALPINE)
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_alpine64.o)
    ELSEIF (TD_MIPS_64)
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_mips64.o)
    ELSE ()
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_linux64.o)
    ENDIF ()
  ELSEIF (TD_DARWIN_64)
    IF (TD_ARM_64)
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_darwin_m1.o)
    ELSE ()
      ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_darwin.o)
    ENDIF ()
  ELSEIF (TD_ARM_64)  
    ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_arm64.o)
  ELSEIF (TD_ARM_32)  
    ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_arm32.o)
  ELSEIF (TD_WINDOWS_64)  
    ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_windows64.o)
  ELSEIF (TD_WINDOWS_32)  
    ADD_LIBRARY(grant STATIC ${LIB_SRC} ${TD_SOURCE_DIR}/enterprise/contrib/grant-lib/machine_windows32.o)
  ELSEIF (TD_DARWIN)  
    ADD_LIBRARY(grant STATIC ${LIB_SRC} ./src/wmachine.c)
  ELSE()
    MESSAGE (FATAL_ERROR "grant-lib error: unknown platform")
  ENDIF ()
ENDIF ()

target_link_libraries(grant util sdb mnode)