CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/src/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/mnode/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/dnode/inc)
INCLUDE_DIRECTORIES(inc)

#AUX_SOURCE_DIRECTORY(imp LIB_SRC)
LIST(APPEND LIB_SRC ./src/grantMain.c)

#AUX_SOURCE_DIRECTORY(imp BIN_SRC)
#LIST(APPEND BIN_SRC tools/taosGrant.c)
#ADD_EXECUTABLE(taosGrant ${BIN_SRC})
#TARGET_LINK_LIBRARIES(taosGrant tutil)

IF (TD_LINUX_64)  
  IF (TD_NINGSI)
    ADD_LIBRARY(grant ${LIB_SRC} ./src/machine_ningsi.o)
  ELSE ()
    ADD_LIBRARY(grant ${LIB_SRC} ./src/machine_linux64.o)
  ENDIF ()
ELSEIF (TD_ARM_64)    
  ADD_LIBRARY(grant ${LIB_SRC} ./src/machine_arm64.o)
ELSEIF (TD_ARM_32)    
  ADD_LIBRARY(grant ${LIB_SRC} ./src/machine_arm32.o)
ELSEIF (TD_WINDOWS)  
  ADD_LIBRARY(grant ${LIB_SRC} ./src/wmachine.c)
ENDIF ()
