[package]
name = "source-opc"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
csv.workspace = true
csv-async.workspace = true
futures-util.workspace = true
itertools.workspace = true
serde.workspace = true
taos.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-process-terminate.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
arrow.workspace = true
arrow-schema.workspace = true
cfg-if.workspace = true
toml.workspace = true
ringbuf.workspace = true
bytes.workspace = true
regex.workspace = true
serde_json.workspace = true
linked-hash-map.workspace = true
base64.workspace = true
tokio-stream.workspace = true
futures.workspace = true

taosx-core.workspace = true
taosx-ipc.workspace = true

[lints]
workspace = true
