select now();
insert into test.d10 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d10.csv';
insert into test.d11 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d11.csv';
insert into test.d12 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d12.csv';
insert into test.d13 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d13.csv';
insert into test.d14 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d14.csv';
insert into test.d15 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d15.csv';
insert into test.d16 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d16.csv';
insert into test.d17 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d17.csv';
insert into test.d18 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d18.csv';
insert into test.d19 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d19.csv';
insert into test.d60 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d60.csv';
insert into test.d61 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d61.csv';
insert into test.d62 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d62.csv';
insert into test.d63 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d63.csv';
insert into test.d64 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d64.csv';
insert into test.d65 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d65.csv';
insert into test.d66 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d66.csv';
insert into test.d67 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d67.csv';
insert into test.d68 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d68.csv';
insert into test.d69 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/1/d69.csv';
select now();