[package]
name = "source-mongodb"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
mongodb.workspace = true
chrono.workspace = true
linked-hash-map.workspace = true
serde_json.workspace = true
taos.workspace = true
tokio-util.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true
flume.workspace = true
arrow.workspace = true
arrow-schema.workspace = true
itertools.workspace = true

taosx-core.workspace = true
taosx-ipc.workspace = true

[lints]
workspace = true
