all:
	gcc -g httpTest.c -o httpTest -lpthread
	gcc -g httpTestSqlt.c -o httpTestSqlt -lpthread
	gcc -g httpTestSqlUtc.c -o httpTestSqlUtc -lpthread

clean:
	rm httpTest
	rm httpTestSqlt
	rm httpTestSqlUtc