#!/bin/bash
header=$(echo -n '{"typ":"JWT","alg":"HS256","kid":"0001"}' | base64 | tr '+\/' '-_' | tr -d '=')
header=$(echo $header|tr -d ' ')
body=$(echo -n '{"name":"query","sub":"root","pass":"taodata","iss":"www.taosdata.com","ssion":"1234","sslot":"1"}' | base64 | tr '+\/' '-_' | tr -d '=')
body=$(echo $body|tr -d ' ')
HEADER_PAYLOAD="$header"."$body"
sum=$(echo -n $HEADER_PAYLOAD | openssl dgst -binary -sha256 -hmac taosdata | base64 | tr '+\/' '-_' | tr -d '=')
sum=$(echo $sum|tr -d ' ')
token="$header"."$body"."$sum"
echo "token is: " $token

