export { default as javaEN } from "./en/java.vue";
export { default as grafanaEN } from "./en/grafana.vue";
export { default as TDCLIEN } from "./en/cli.vue";
export { default as pythonEN } from "./en/python.vue";
export { default as goEN } from "./en/go.vue";
export { default as nodeEN} from "./en/node.vue";
export { default as rustEN} from "./en/rust.vue";
export { default as csharpEN } from "./en/csharp.vue";
export { default as restIN } from "./en/restin.vue";
export { default as restOUT } from "./en/restout.vue";
export { default as benchmarkEN } from "./en/taosbenchmark.vue";
export { default as dumpEN } from "./en/taosdump.vue";
export { default as prometheusEN} from "./en/prometheus.vue";
export { default as telegrafEN } from "./en/telegraf.vue";
export { default as gdsEN } from "./en/gds.vue";
export { default as influxDB } from "./en/schmalessinfluxdb.vue";
export { default as opentsJSON } from "./en/opentsdbjson.vue";
export { default as opentsTelnet } from "./en/opentsdbjson.vue";
