---
kind: pipeline
name: hello-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: en
  image: clangbuiltlinux/ubuntu
  commands:
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

---
kind: pipeline
name: hello-on-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

---
kind: pipeline
name: goodbye

platform:
  os: linux
  arch: amd64

steps:
- name: en
  image: alpine
  commands:
  - echo goodbye
  - echo world

- name: es
  image: alpine
  commands:
  - echo adios
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo au revoir
  - echo monde

depends_on:
- hello-on-arm64
- hello-on-amd64