---
kind: pipeline
name: hello-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y cmake build-essential git
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 

- name: test
  image: python:3.8
  commands:
  - pip3 install psutil
  - pip3 install guppy3
  - pip3 install src/connector/python/linux/python3/
  - cd tests
  - ./test-all.sh smoke


- name: crash_gen
  image: python:3.8
  commands:
  - pip3 install requests
  - pip3 install psutil
  - pip3 install guppy3
  - cd tests/pytest 
  - ./crash_gen.sh -a -p -t 4 -s 200

---
kind: pipeline
name: hello-on-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: gcc
  commands:
  - cat /proc/cpuinfo
  - apt-get update
  - apt-get install -y cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch64 > /dev/null
  - make 
---
kind: pipeline
name: hello-on-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: gcc
  commands:
  - cat /proc/cpuinfo
  - apt-get update
  - apt-get install -y cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch32 > /dev/null
  - make 

---
kind: pipeline
name: goodbye

platform:
  os: linux
  arch: amd64

steps:
- name: en
  image: alpine
  commands:
  - echo goodbye
  - echo world

- name: es
  image: alpine
  commands:
  - echo adios
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo au revoir
  - echo monde

depends_on:
- hello-on-arm64
- hello-on-amd64