---
kind: pipeline
name: test_amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y cmake build-essential 
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: test_arm64_bionic

platform:
  os: linux
  arch: arm64
steps:
- name: build
  image: arm64v8/ubuntu:bionic
  commands:
  - apt-get update
  - apt-get install -y cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch64 > /dev/null
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
    - 2.0
---
kind: pipeline
name: test_arm64_focal

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: arm64v8/ubuntu:focal
  commands:
  - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  - apt-get update 
  - apt-get install -y -qq cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch64 > /dev/null
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
    - 2.0
---
kind: pipeline
name: test_arm64_centos7

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: arm64v8/centos:7
  commands:
  - yum install -y gcc gcc-c++ make cmake git
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch64 > /dev/null
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
    - 2.0
---
kind: pipeline
name: test_arm64_centos8

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: arm64v8/centos:8
  commands:
  - dnf install -y gcc gcc-c++ make cmake epel-release git libarchive
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch64 > /dev/null
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
    - 2.0
---
kind: pipeline
name: test_arm_bionic

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: arm32v7/ubuntu:bionic
  commands:
  - apt-get update
  - apt-get install -y cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. -DCPUTYPE=aarch32 > /dev/null
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: build_trusty

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:trusty
  commands:
  - apt-get update
  - apt-get install -y gcc cmake3 build-essential git binutils-2.26
 
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: build_xenial

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:xenial
  commands:
  - apt-get update
  - apt-get install -y gcc cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master

---
kind: pipeline
name: build_bionic
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - apt-get update
  - apt-get install -y gcc cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: build_centos7
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ansible/centos7-ansible
  commands:
  - yum install -y gcc gcc-c++ make cmake
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master

