use std::{io::Write, str::FromStr};

use sqlx::migrate::Migrator;
static MIGRATOR: Migrator = sqlx::migrate!();

async fn init_sqlx(dsn: &str) -> Result<(), sqlx::Error> {
    let options = sqlx::sqlite::SqliteConnectOptions::from_str(&dsn)?.create_if_missing(true);
    let pool = sqlx::SqlitePool::connect_with(options).await?;
    MIGRATOR.run(&pool).await?;
    Ok(())
}

// generated by `sqlx migrate build-script`
fn main() {
    dotenv::dotenv().ok();
    shadow_rs::new().unwrap();

    if let Ok(dsn) = std::env::var("DATABASE_URL") {
        let file = dsn.replacen("sqlite:", "", 1);
        println!("cargo:rerun-if-changed={file}");
        sqlx::test_block_on(init_sqlx(&dsn)).unwrap();
    } else {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let root = std::path::Path::new(&manifest_dir);
        let target = root.join("target");
        if !target.exists() {
            std::fs::create_dir_all(&target).unwrap();
        }
        let db = target.join("taosx.dev.db");
        let file = db.display();
        println!("cargo:rerun-if-changed={file}");

        let dsn = format!("sqlite:{}", file);
        std::env::set_var("DATABASE_URL", &dsn);

        let dotenv = root.join(".env");
        if dotenv.exists() {
            let mut file = std::fs::File::options().append(true).open(dotenv).unwrap();
            file.write_fmt(format_args!("DATABASE_URL=sqlite:{}\n", db.display()))
                .unwrap();
        } else {
            let mut file = std::fs::File::create(dotenv).unwrap();
            file.write_fmt(format_args!("DATABASE_URL=sqlite:{}\n", db.display()))
                .unwrap();
        }

        sqlx::test_block_on(init_sqlx(&dsn)).unwrap();
    }
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    // trigger recompilation when dotenv changed
    println!("cargo:rerun-if-changed=.env");
}
