[workspace]
members = [
  "taosx-ipc",
  "taosx-core",
  "taosx-agent",
]

[workspace.dependencies]
arrow = { version = "38.0.0", features = ["chrono-tz"] }
arrow-flight = { version = "38.0.0" }
parquet = "38.0.0"

tonic = "0.9"

taos = { version = "0.8.5", default-features = false, features = ["ws", "deadpool"] }
taos-query = { version = "0.8.5", default-features = false, features = ["deadpool"] }

[package]
name = "taosx"
version = "0.5.1"
build = "build.rs"
edition = "2021"
exclude = ["/docs", "TODO.md", "*.json", ".vscode"]
homepage = "https://taosdata.com"
description = "taosX - TDengine data integration tool"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow = { workspace = true }
arrow-flight = { workspace = true }
async-compression = { version = "*", features = ["all"] }
async-trait = "0.1"
bitflags = "1"
chrono = "0.4"
clap = { version = "4.0.11", features = ["default", "derive"] }
clap-verbosity-flag = "2.0.0"
config = "0.13.2"
convert_case = "0.6.0"
csv-async = { version = "1.2.4", features = ["tokio"] }
dashmap = "5.4.0"
futures = "0.3"
itertools = "0.10.4"
lazy_static = "1.4"
linked-hash-map = { version = "0.5.6", features = ["serde_impl"] }
log = "0.4"
parquet = { workspace = true }
parse_duration = "2.1"
pretty_env_logger = "0.4"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
sha2 = "0.10"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
toml = "0.7.2"
zstd = "0.12.1"

actix-cors = "0.6.4"
actix-web = "4"
serde_json = { version = "1.0", features = ["raw_value"] }
sqlx = { version = "0.6", features = ["sqlite", "chrono", "json"] }
utoipa = { version = "3", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["actix-web"] }

# tonic version is restricted by arrow-flight
socket2 = "0.5"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { workspace = true, features = ["tls", "tls-roots"] }

# lru = "0.7.5"
const_format = "0.2.30"
metrics = "0.20.1"
metrics-exporter-prometheus = { version = "0.11.0", default-features = false, features = ["push-gateway"] }
# palaver = "0.2.8"
shadow-rs = "0.21.0"
sysinfo = "0.28.0"

async-backtrace = "0.2.2"
dotenv = "0.15.0"
tracing = "0.1"

flume = "0.10"
futures-util = "0.3"
r2d2 = "0.8.10"
serde_with = "2.3.1"
tokio-cron-scheduler = "0.9.4"

async-process = "1.6"
bitvec = "1"
mimalloc = { version = "0.1.34", default-features = false, optional = true }
tempfile = "3"

bytes = "1.4.0"
jsonwebtoken = "8.3"
rand = "0.8"

reqwest = "0.11.15"
taosx-ipc = { path = "./taosx-ipc" }

taos = { workspace = true }
taosx-core = { path = "./taosx-core", default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[build-dependencies]
sqlx = { version = "0.6", features = ["sqlite", "chrono"] }
dotenv = "0.15.0"
shadow-rs = "0.21.0"

[dev-dependencies]
tower = "0.4"

[features]
default = ["optin", "rustls"]
optin = ["taos/optin", "taosx-core/optin"]
sys = ["taos/native", "taosx-core/sys"]
rustls = ["sqlx/runtime-tokio-rustls", "taos/ws-rustls", "taosx-core/rustls"]
native-tls = ["sqlx/runtime-tokio-native-tls", "taos/ws-native-tls", "taosx-core/native-tls"]
disable-enterprise-only-validation = ["taosx-core/disable-enterprise-only-validation"]
disable-enterprise-connector-validation = ["taosx-core/disable-enterprise-connector-validation"]
