[workspace]
members = [
    "taosx-ipc",
    "taosx-core",
    "taosx-agent",
    "taosx-metrics",
    "crates/arrow-compute-ext",
    "crates/futures-ext",
]

exclude = [
    "crates/transform/parsers/hebeipower",
]

[workspace.dependencies]
chrono = { version = "0.4.37" }
chrono-tz = { version = "0.8.3" }
shadow-rs = { version = "0.33.0" }
itertools = { version = "0.13.0" }

clap = { version = "4.4.7", features = ["default", "derive"] }

regex = { version = "1.9" }
arrow = { version = "50.0.0", features = ["chrono-tz", "ipc_compression"] }
arrow-flight = { version = "50.0.0" }
arrow-schema = { version = "50.0.0", features = ["serde"] }
arrow-compute-ext = { path = "crates/arrow-compute-ext" }
faststr = { version = "0.2.19", features = ["serde"] }
rayon = { version = "1" }
parquet = "50.0.0"
metrics-exporter-prometheus = { version = "0.12.0", default-features = false }
metrics-tracing-context = "0.15.0"
tonic = "0.10"
zerocopy = { version = "0.7.34", features = ["derive"] }

metrics = "0.22.0"
metrics-util = "0.16.0"
bytes = "1.4.0"
sysinfo = "0.30.5"

[workspace.dependencies.taos]
# path = "../taos-connector-rust/taos"
version = "0.12"
git = "https://github.com/taosdata/taos-connector-rust.git"
default-features = false
features = ["ws", "optin", "deadpool"]

[workspace.package]
version = "1.7.0"
rust-version = "1.78.0"

[package]
name = "taosx"
version.workspace = true
build = "build.rs"
edition = "2021"
exclude = ["/docs", "TODO.md", "*.json", ".vscode"]
homepage = "https://taosdata.com"
description = "taosX - TDengine data integration tool"
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow = { workspace = true }
arrow-flight = { workspace = true }
faststr = { workspace = true }
zerocopy = { workspace = true }

shadow-rs = { workspace = true }
strum = { version = "0.25", features = ["derive"] }
multi_index_map = "0.11.0"
semver = "1.0.22"
humantime = "2.1"

twelf = { version = "0.13.0", default-features = false, features = [
    "toml",
    "env",
    "clap",
] }

async-compression = { version = "*", features = ["all"] }
async-trait = "0.1"
bitflags = "2"
chrono = { workspace = true }
clap = { workspace = true, features = ["default", "derive", "env"] }
clap-verbosity-flag = "2.0.0"
config = "0.13.2"
convert_case = "0.6.0"
csv-async = { version = "1.2.4", features = ["tokio"] }
dashmap = "5.4.0"
futures = "0.3"
itertools = { version = "0.13.0" }
lazy_static = "1.4"
linked-hash-map = { version = "0.5.6", features = ["serde_impl"] }
log = { version = "0.4", features = ["serde"] }
parquet = { workspace = true }
parse_duration = "2.1"
regex = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
sha2 = "0.10"
thiserror = "1"
tokio = { version = "1.39.3", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "io-std",
    "net",
    "time",
    "process",
    "macros",
    "sync",
    "signal",
    "fs",
] }
tokio-util = { version = "0.7" }
toml = "0.8.5"
zstd = "0.13.0"
csv = "1.2"

actix-cors = "0.7.0"
actix-web = "4"
actix-ws = "0.2.5"
actix-multipart = "0.6.0"
actix-files = "0.6.2"
base64 = "0.21.2"
cfg-if = "1.0.0"
uuid = { version = "1.4.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
serde_json = { version = "1.0", features = ["raw_value"] }
sqlx = { version = "0.7", features = ["sqlite", "chrono", "json"] }
utoipa = { version = "4.2.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }

# tonic version is restricted by arrow-flight
socket2 = "0.5"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { workspace = true, features = ["tls", "tls-roots", "gzip"] }

# lru = "0.7.5"
const_format = "0.2.30"
metrics = { workspace = true }
metrics-util = { workspace = true }
metrics-exporter-prometheus = { version = "0.12.0", default-features = false, features = [
    "push-gateway",
] }
metrics-tracing-context = { workspace = true }
sysinfo = { workspace = true }

async-backtrace = "0.2.2"
dotenv = "0.15.0"

flume = "0.11.0"
futures-util = "0.3"
r2d2 = "0.8.10"
serde_with = { version = "3", features = ["chrono"] }
tokio-cron-scheduler = { git = "https://github.com/zitsen/tokio-cron-scheduler.git" }

bitvec = "1"
mimalloc = { version = "0.1.39", default-features = false, optional = true }
tempfile = "3"

bytes = { workspace = true }
jsonwebtoken = "9.1.0"
rand = "0.8"

time = { version = "0.3", features = ["formatting", "macros"] }
tracing-subscriber = { version = "0.3", features = [
    "time",
    "local-time",
    "env-filter",
] }
tracing-appender = "0.2.3"
tracing = { version = "0.1", features = ["log"] }
atty = "0.2.14"
file-rotate = "0.7.5"
opentelemetry = { version = "0.21.0" }
opentelemetry_sdk = { version = "0.21.0" }
opentelemetry-otlp = { version = "0.14.0" }
tracing-opentelemetry = { version = "0.22.0" }
tracing-actix-web = "0.7"
console-subscriber = { version = "0.4.0", optional = true }
reqwest = { version = "0.12.7", features = ["json"] }
taosx-ipc = { path = "./taosx-ipc" }
md5 = "0.7.0"

taos = { workspace = true }
taosx-core = { path = "./taosx-core", default-features = false }
taosx-metrics = { path = "./taosx-metrics" }
gethostname = "0.4.3"
prettytable = "0.10.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }
tikv-jemalloc-sys = { version = "0.6.0", features = [
    "unprefixed_malloc_on_supported_platforms",
    "stats",
    "profiling",
], optional = true }
tikv-jemalloc-ctl = { version = "0.6.0", optional = true }
jemalloc_pprof = { version = "0.4.2", git = "https://github.com/polarsignals/rust-jemalloc-pprof.git", optional = true }

[build-dependencies]
sqlx = { version = "0.7", features = ["sqlite", "chrono", "mysql"] }
dotenv = "0.15.0"

shadow-rs = { workspace = true }

[dev-dependencies]
tower = "0.4"

[features]
default = ["native-tls", "mimalloc"]
optin = []
jemallocator = [
    "tikv-jemallocator",
    "tikv-jemalloc-sys",
    "tikv-jemalloc-ctl",
    "jemalloc_pprof",
]
rustls = ["sqlx/runtime-tokio-rustls", "taos/ws-rustls", "taosx-core/rustls"]
native-tls = [
    "sqlx/runtime-tokio-native-tls",
    "taos/ws-native-tls",
    "taosx-core/native-tls",
]
disable-enterprise-only-validation = [
    "taosx-core/disable-enterprise-only-validation",
]
disable-enterprise-connector-validation = [
    "taosx-core/disable-enterprise-connector-validation",
]

tokio-tracing = ["tokio/tracing", "console-subscriber"]

[profile.sani]
inherits = "release"
debug = 2

[profile.production]
inherits = "release"
codegen-units = 1
debug = 2
split-debuginfo = "packed"
strip = "debuginfo"
