CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

SET(TD_COMMUNITY_DIR ${PROJECT_SOURCE_DIR}/community)
SET(TD_ENTERPRISE_DIR ${PROJECT_SOURCE_DIR}/enterprise)
MESSAGE(STATUS "Community source directory: " ${TD_COMMUNITY_DIR})
MESSAGE(STATUS "Enterprise source directory: " ${TD_ENTERPRISE_DIR})

SET(TD_CLUSTER TRUE)
SET(TD_ACCOUNT TRUE)
SET(TD_GRANT TRUE)
SET(TD_VPEER TRUE)
#SET(TD_MPEER TRUE)
SET(TD_COVER FALSE)
SET(TD_PAGMODE_LITE FALSE)
SET(TD_GODLL FALSE)
SET(TD_MEM_CHECK FALSE)

INCLUDE(community/cmake/input.inc)
INCLUDE(community/cmake/platform.inc)
INCLUDE(community/cmake/env.inc)
INCLUDE(community/cmake/define.inc)
INCLUDE(community/cmake/install.inc)

ADD_SUBDIRECTORY(enterprise)
ADD_SUBDIRECTORY(community/deps)
ADD_SUBDIRECTORY(community/src)
ADD_SUBDIRECTORY(community/tests)

INCLUDE(CPack)
