version: "3.9"

services:
  build:
    image: taosx/dev:${RUST_VERSION}
    volumes:
      - $HOME/.cargo/registry:/root/.cargo/registry
      - $HOME/.cargo/git:/root/.cargo/git
      - $PWD:$PWD
      - ../taos-connector-rust:/taos-connector-rust
      - ./:/app/
      - ./target/centos7:/app/target
    command:
      - cargo
      - build
      - --profile production
      - -p taosx
      - -p taosx-agent
      # - --offline
      # - --features jemallocator
      # - --features disable-enterprise-only-validation

