[config]
load_cargo_aliases = true
skip_core_tasks = false
default_to_workspace = false

[tasks.taosx]
command = "cargo"
args = ["build", "--release"]

[tasks.taosx-agent]
command = "cargo"
args = ["build", "--release", "-p", "taosx-agent"]

[tasks.plugins]
dependencies = ["taosx-influxdb", "taosx-opentsdb", "taosx-mqtt", "taosx-opc"]

[tasks.clean-plugins]
script = """
set -ex
rm -rf plugins/influxdb/target
rm -rf plugins/opentsdb/target
rm -rf plugins/mqtt/dist
rm -rf plugins/opc/taosx-opc
"""

[tasks.taosx-influxdb]
command = "mvn"
args = ["package", "-f", "plugins/influxdb/pom.xml"]

[tasks.taosx-opentsdb]
command = "mvn"
args = ["package", "-f", "plugins/opentsdb/pom.xml"]

[tasks.taosx-mqtt]
script = """
commit=$(git rev-parse HEAD | cut -c 1-8)
built=$(date +"%F %T %:z")
path=github.com/taosdata/taosx/plugins/mqtt
go build -C plugins/mqtt \
  -o dist/taosx-mqtt \
  -ldflags "-X $path/version.Commit=${commit} -X '$path/version.BuildTime=$built'"
"""

[tasks.taosx-opc]
script = """
commit=$(git rev-parse HEAD | cut -c 1-8)
built=$(date +"%F %T %:z")
go build -C plugins/opc \
  -o taosx-opc \
  -ldflags "-X collector/version.CommitID=${commit} -X 'collector/version.BuildAt=$built'"
"""

[tasks.package]
# script = { file = "./scripts/package.sh" }
# dependencies = ["build-all"]
script = """
PKG=target/packaging/linux
[ -d $PKG ] && rm -rf $PKG
mkdir -p $PKG/usr/bin
mkdir -p $PKG/usr/local/taosx/plugins/influxdb
mkdir -p $PKG/usr/local/taosx/plugins/opentsdb
mkdir -p $PKG/usr/local/taosx/plugins/mqtt
mkdir -p $PKG/usr/local/taosx/plugins/opc

mkdir -p $PKG/etc/systemd
mkdir -p $PKG/etc/taos

cp target/release/taosx target/release/taosx-agent $PKG/usr/bin
cp plugins/influxdb/target/taosx-influxdb.jar $PKG/usr/local/taosx/plugins/influxdb
cp plugins/opentsdb/target/taosx-opentsdb.jar $PKG/usr/local/taosx/plugins/opentsdb
cp plugins/mqtt/dist/taosx-mqtt $PKG/usr/local/taosx/plugins/mqtt/
cp plugins/opc/taosx-opc $PKG/usr/local/taosx/plugins/opc/
cp packaging/uninstall.sh $PKG/usr/local/taosx/

cp target/*.service $PKG/etc/systemd/
cp taosx-agent/examples/agent.toml $PKG/etc/taos/agnt.example.toml

cd $PKG
version=$(./usr/bin/taosx --version|cut -f 2 -d " ")
tar cavf ../taosx-$version.tar.gz ./*
ln -f ../taosx-$version.tar.gz ../taosx-latest.tar.gz
"""

[tasks.install]
cwd = "target/packaging"
dependencies = ["package"]
script = """
sudo tar -C / --no-same-owner -xvf taosx-latest.tar.gz
"""

[tasks.uninstall]
script = """
/usr/local/taosx/uninstall.sh
"""

[tasks.build-all]
dependencies = ["taosx", "taosx-agent", "plugins"]

[tasks.build-sanitizer]
command = "cargo"
env = { "RUSTFLAGS" = "-Zsanitizer=address --cfg tokio_unstable" }
args = [
  "build",
  "--release",
  "--target",
  "x86_64-unknown-linux-gnu",
  "-Zbuild-std",
]

[tasks.clean-all]
dependencies = ["clean-plugins", "clean"]

[tasks.docker-cloud]
script = """
version=$(toml get Cargo.toml workspace.package.version -r)
docker build -t image.cloud.taosdata.com/taosx/serve:$version .
"""
dependencies = ["plugins"]
