[config]
load_cargo_aliases = false
skip_core_tasks = true
default_to_workspace = false

[tasks.taosx]
command = "cargo"
args = ["build", "--release"]

[tasks.taosx-agent]
command = "cargo"
args = ["build", "--release", "-p", "taosx-agent"]

[tasks.plugins]
dependencies = ["taosx-influxdb", "taosx-opentsdb", "taosx-mqtt", "taosx-opc"]

[tasks.clean-plugins]
script = """
set -ex
rm -rf plugins/influxdb/target
rm -rf plugins/opentsdb/target
rm -rf plugins/mqtt/dist
rm -rf plugins/opc/taosx-opc
"""

[tasks.taosx-influxdb]
command = "mvn"
args = ["package", "-f", "plugins/influxdb/pom.xml"]

[tasks.taosx-opentsdb]
command = "mvn"
args = ["package", "-f", "plugins/opentsdb/pom.xml"]

[tasks.taosx-mqtt]
cwd = "plugins/mqtt"
script = """
commit=$(git rev-parse HEAD | cut -c 1-8)
built=$(date +"%F %T %:z")
path=github.com/taosdata/taosx/plugins/mqtt
go mod tidy
go build -o dist/taosx-mqtt \
  -ldflags "-X $path/version.Commit=${commit} -X '$path/version.BuildTime=$built'"
"""

[tasks.taosx-opc]
cwd = "plugins/opc"
script = """
commit=$(git rev-parse HEAD | cut -c 1-8)
built=$(date +"%F %T %:z")
go mod tidy
go build -o taosx-opc \
  -ldflags "-X collector/version.CommitID=${commit} -X 'collector/version.BuildAt=$built'"
"""

[tasks.package]
# script = { file = "./scripts/package.sh" }
# dependencies = ["build-all"]
script = """
PKG=target/packaging/linux
[ -d $PKG ] && rm -rf $PKG
mkdir -p $PKG/usr/bin
mkdir -p $PKG/usr/local/taos/plugins/influxdb
mkdir -p $PKG/usr/local/taos/plugins/opentsdb
mkdir -p $PKG/usr/local/taos/plugins/mqtt
mkdir -p $PKG/usr/local/taos/plugins/opc

mkdir -p $PKG/etc/systemd
mkdir -p $PKG/etc/taos

cp target/release/taosx target/release/taosx-agent $PKG/usr/bin
cp plugins/influxdb/target/taosx-influxdb.jar $PKG/usr/local/taos/plugins/influxdb
cp plugins/opentsdb/target/taosx-opentsdb.jar $PKG/usr/local/taos/plugins/opentsdb
cp plugins/mqtt/dist/taosx-mqtt $PKG/usr/local/taos/plugins/mqtt/
cp plugins/opc/taosx-opc $PKG/usr/local/taos/plugins/opc/
cp packaging/uninstall.sh $PKG/usr/local/taos/

cp target/*.service $PKG/etc/systemd/
cp taosx-agent/examples/agent.toml $PKG/etc/taos/agnt.example.toml

cd $PKG
version=$(./usr/bin/taosx --version|cut -f 2 -d " ")
tar cavf ../taosx-$version.tar.gz ./*
ln -f ../taosx-$version.tar.gz ../taosx-latest.tar.gz
"""

[tasks.dev-install-plugins]
script = """
sudo cp plugins/influxdb/target/taosx-influxdb.jar /usr/local/taos/plugins/influxdb/
sudo cp plugins/opentsdb/target/taosx-opentsdb.jar /usr/local/taos/plugins/opentsdb/
sudo cp plugins/mqtt/dist/taosx-mqtt /usr/local/taos/plugins/mqtt/
sudo cp plugins/opc/taosx-opc /usr/local/taos/plugins/opc/
"""
[tasks.install]
cwd = "target/packaging"
dependencies = ["package"]
script = """
sudo tar -C / --no-same-owner -xvf taosx-latest.tar.gz
"""

[tasks.uninstall]
script = """
echo $@
sudo rm /usr/local/taos/bin/taos-explorer
sudo rm /usr/local/taos/bin/taosx
sudo rm /usr/local/taos/bin/taosx-agent
sudo rm /etc/systemd/systemd/taos-explorer.service
sudo rm /etc/systemd/systemd/taosx.service
sudo rm /etc/systemd/systemd/taosx-agent.service
sudo systemctl daemon-reload
if [ "$1" == "--all" ]; then
  sudo rm -rf /var/lib/taos/taosx/
fi
"""

[tasks.build-all]
dependencies = ["taosx", "taosx-agent", "plugins"]

[tasks.build-sanitizer]
command = "cargo"
env = { "RUSTFLAGS" = "-Zsanitizer=address --cfg tokio_unstable" }
args = [
  "build",
  "--release",
  "--target",
  "x86_64-unknown-linux-gnu",
  "-Zbuild-std",
]

[tasks.clean-all]
dependencies = ["clean-plugins", "clean"]

[tasks.docker-cloud]
script = """
option="$1"
commit=$(git rev-parse HEAD | cut -c 1-8)
version=$(toml get Cargo.toml workspace.package.version -r)
docker build -t image.cloud.taosdata.com/taosx/serve:$version-$commit .
if [ "$option" = "--push" ] || [ "$option" = "-p" ]; then
  docker push image.cloud.taosdata.com/taosx/serve:$version-$commit
fi
"""
dependencies = ["plugins"]

[tasks.docker-push]
script = """
commit=$(git rev-parse HEAD | cut -c 1-8)
version=$(toml get Cargo.toml workspace.package.version -r)
docker push image.cloud.taosdata.com/taosx/serve:$version-$commit
"""

[tasks.build-all-and-cloud]
dependencies = ["build-all", "docker-cloud"]

[tasks.build-and-push-docker-cloud]
dependencies = ["build-all", "docker-cloud", "docker-push"]
