python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJson-illegalData.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJsonSml-illegalData.py 
python3 ./test.py  -f  5-taos-tools/taosbenchmark/taosdemoTestQueryWithJson.py
#python3 ./test.py -f 5-taos-tools/taosdump/taosdumpTestColTag.py 
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJsonStmt-illegalData.py 
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJson.py
#python3 ./test.py -f 5-taos-tools/TD-12478.py 
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJsonSml.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJson-chinese.py
python3 ./test.py -f 5-taos-tools/basic.py 
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJsonStmt-otherPara.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJsonStmt.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJson-autoCreate.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJson-otherPara.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJson-childTable.py
python3 ./test.py -f 5-taos-tools/taosbenchmark/taosdemoTestInsertWithJsonSml-otherPara.py 
