[package]
name = "sink-csv"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
arrow-schema.workspace = true
bytes.workspace = true
chrono.workspace = true
csv.workspace = true
faststr.workspace = true
futures-util.workspace = true
notify.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
taos.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
flume.workspace = true
csv-async.workspace = true
scc.workspace = true
flate2.workspace = true
glob.workspace = true
tempfile.workspace = true

taosx-core.workspace = true
taosx-ipc.workspace = true

[lints]
workspace = true
