[package]
name = "taos-explorer"
version = "1.10.0"
edition = "2021"
description = "TDengine Explorer UI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors.workspace = true
actix-embed = "0.1.0"
actix-files.workspace = true
actix-web.workspace = true
actix-ws.workspace = true
rustls = { workspace = true, default-features = false, features = ["ring"] }
rustls-pemfile.workspace = true
reqwest = { version = "0.11", default-features = false, features = [
  "stream",
  "json",
  "deflate",
  "rustls-tls",
] }
clap-verbosity-flag = { workspace = true }
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
sqlx = { workspace = true, features = ["sqlite", "chrono", "runtime-tokio"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["compat"] }
tokio-stream.workspace = true
log = { workspace = true, features = ["serde"] }
http-auth-basic = "0.3"
rust-embed = "6.8.1"
serde = { workspace = true, features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-actix-web = "0.7.11"
tracing-subscriber.workspace = true
sha1 = "0.10.6"
rand.workspace = true
lazy_static.workspace = true
captcha = "1"
deadpool.workspace = true
const_format.workspace = true
shadow-rs = { workspace = true }
geos = { version = "10.0.0", features = ["static"] }
hex.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
scc = { workspace = true }
bitfield.workspace = true
taoslog = { workspace = true, features = ["ansi"] }
http.workspace = true
serde_with.workspace = true
assert_cmd.workspace = true
assert_fs.workspace = true
regex.workspace = true

mimalloc = { workspace = true, optional = true }
futures.workspace = true
pin-project-lite.workspace = true
faststr.workspace = true

[dependencies.taos]
workspace = true

[build-dependencies]
shadow-rs = { workspace = true }

[dev-dependencies]
mockito = "1.6.1"

[lints]
workspace = true

[features]
default = ["mimalloc"]
