[package]
name = "taos-explorer"
version = "1.10.0"
edition = "2021"
description = "TDengine Explorer UI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-embed = "0.1.0"
actix-files = "0.6.6"
actix-web = { version = "4.7.0", features = ["rustls-0_23"] }
rustls = { version = "0.23.18", default-features = false, features = ["ring"] }
rustls-pemfile = "2.1.2"
reqwest = { version = "0.11.27", default-features = false, features = [
  "stream",
  "json",
  "deflate",
  "rustls-tls",
] }
clap-verbosity-flag = { workspace = true }
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
sqlx = { version = "0.8", features = ["sqlite", "chrono", "runtime-tokio"] }
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
tokio-stream.workspace = true
log = { version = "0.4", features = ["serde"] }
http-auth-basic = "0.3"
rust-embed = "6.8.1"
serde = { workspace = true, features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
thiserror = "1"
toml = "0.8.8"
tracing.workspace = true
tracing-actix-web = "0.7.11"
tracing-subscriber = "0.3"
sha1 = "0.10.6"
rand.workspace = true
lazy_static = "1.4.0"
captcha = "0.0.9"
deadpool = "0.10"

const_format = "0.2.32"
shadow-rs = { workspace = true }
geos = { version = "10.0.0", features = ["static"] }
hex = "0.4.3"
chrono = "0.4"
chrono-tz = "0.10.0"
scc = { workspace = true }


bitfield = "0.18.1"

taoslog = { workspace = true, features = ["ansi"] }
http = "0.2.12"
serde_with = "3.9.0"
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
regex = "1"

mimalloc = { version = "0.1.43", default-features = false, optional = true }

[dependencies.taos]
workspace = true

[build-dependencies]
shadow-rs = { workspace = true }

[dev-dependencies]
mockito = "1.6.1"

[lints]
workspace = true

[features]
default = ["mimalloc"]
