python3 ./test.py -f 2-query/ts_hidden_column.py
python3 ./test.py -f 2-query/union-order.py
python3 ./test.py -f 2-query/session_two_stage.py
python3 ./test.py -f 2-query/timeline_agg_func_groupby.py
python3 ./test.py -f 2-query/constant_compare.py
python3 ./test.py -f 2-query/ts_2016.py
python3 ./test.py -f 2-query/function_mavg.py
python3 ./test.py -f 2-query/escape.py
python3 ./test.py -f 2-query/func_compare.py
python3 ./test.py -f 2-query/diff_ignore_negative.py
python3 ./test.py -f 2-query/diff_funcs.py
python3 ./test.py -f 2-query/lower_func.py
python3 ./test.py -f 2-query/upper_func.py
python3 ./test.py -f 2-query/ltrim_func.py
python3 ./test.py -f 2-query/rtrim_func.py
python3 ./test.py -f 2-query/substr_func.py
python3 ./test.py -f 2-query/TD-13246.py
python3 ./test.py -f 2-query/TD-6347.py
python3 ./test.py -f 2-query/math_funcs.py
python3 ./test.py -f 2-query/function_histogram.py
python3 ./test.py -f 2-query/TD-13946.py
