python3 ./test.py -f 2-query/ts_hidden_column.py
python3 ./test.py -f 2-query/union-order.py
python3 ./test.py -f 2-query/session_two_stage.py
python3 ./test.py -f 2-query/timeline_agg_func_groupby.py
python3 ./test.py -f 2-query/constant_compare.py
python3 ./test.py -f 2-query/ts_2016.py
python3 ./test.py -f 2-query/escape.py
python3 ./test.py -f 2-query/function_mavg.py
python3 ./test.py -f 2-query/func_compare.py
python3 ./test.py -f 2-query/TD-13246.py
