[package]
name = "taosx-tools"
edition = "2021"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
crossterm = { version = "0.28.1", default-features = false, features = [
    "event-stream",
] }
csv = "1.3.1"
encoding_rs.workspace = true
flate2.workspace = true
flume.workspace = true
fundu.workspace = true
futures.workspace = true
faststr.workspace = true
lz4.workspace = true
rand.workspace = true
rayon.workspace = true
rdkafka = { version = "0.38.0", features = ["cmake-build"] }
serde = { workspace = true, features = ["derive"] }
rumqttc.workspace = true
serde_json = { version = "1.0.132", features = ["raw_value"] }
serde_with.workspace = true
snafu.workspace = true
snap.workspace = true
taos.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["full"] }
tokio-util.workspace = true
toml.workspace = true
zstd.workspace = true
arrow = { workspace = true }
arrow-schema = { workspace = true }
parquet = { workspace = true }
bytes = { workspace = true }
signal-hook = "0.3.17"
socket2.workspace = true
num-traits = "0.2"
num-integer = "0.1"
num-bigint = "0.4"
prost.workspace = true
paste.workspace = true
shadow-rs.workspace = true
orc-rust.workspace = true
duckdb = { workspace = true, features = ["appender-arrow", "bundled"] }
async-compression = { workspace = true }
taosx-core = { path = "../../taosx-core" }

[build-dependencies]
shadow-rs.workspace = true

[lints]
workspace = true

[[bin]]
name = "read-parquet"
path = "src/bin/read_parquet.rs"

[[bin]]
name = "perf-report"
path = "src/bin/perf_report.rs"

[[bin]]
name = "backup-parser"
path = "src/bin/backup_parser.rs"
