[package]
name = "ha-core"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
arrow-schema.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
taos.workspace = true
jsonwebtoken.workspace = true

[lints]
workspace = true
