[package]
name = "taosx-ipc"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
flume = { version = "0.11" }
futures = { version = "0.3" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = "1.0.38"
tracing = "0.1"
zstd = "0.12.1"

arrow = { workspace = true }
taos-query = { workspace = true }
tonic = { workspace = true }
shadow-rs = { workspace = true }

metrics = "0.21.0"
[dev-dependencies]
actix-web = "4"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tracing-actix-web = { version = "0.7" }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }

taos = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true }
