[package]
name = "tmq-to-td"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
faststr.workspace = true
humantime.workspace = true
linked-hash-map.workspace = true
serde.workspace = true
serde_json.workspace = true
taos.workspace = true
tokio-util.workspace = true
tracing.workspace = true
deadpool.workspace = true
flume.workspace = true
chrono.workspace = true
semver.workspace = true
awaitgroup.workspace = true
tracing-subscriber.workspace = true
lazy_static.workspace = true
regex.workspace = true
async-trait.workspace = true

taosx-core.workspace = true
legacy-to-taos.path = "../legacy-to-taos"

[lints]
workspace = true
