{
 "title": "TaosKeeper Prometheus Dashboard",
 "tags": [
  "TDengine",
  "Prometheus",
  "TaosKeeper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(taos_dn_cpu_taosd, cluster)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(taos_dn_cpu_taosd{cluster=\"$cluster\"}, fqdn)"
    }
   },
   {
    "name": "dnodeid",
    "label": "with DNode ID:",
    "query": {
     "query": "label_values(taos_dn_cpu_taosd{cluster=\"$cluster\"}, dnodeid)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(taos_vgroups_info_status{cluster=\"$cluster\"}, database_name)"
    }
   },
   {
    "name": "firstEp",
    "query": {
     "query": "label_values(taos_cluster_info_first_ep{cluster=\"$cluster\"}, value)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(taos_cluster_info_version{cluster=\"$cluster\"}, value)"
    }
   },
   {
    "name": "interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "-- OVERVIEW --",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center>TDengine Cluster Dashboard (First EP: ${firstEp}, Version: ${version})</center></h1>"
   },
   "targets": [
    {
     "alias": "mnodes",
     "formatType": "Time series",
     "sql": "show mnodes",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "First EP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_first_ep{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "sql": "label_values(taos_cluster_info_first_ep{cluster=\"$cluster\"}, value)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_version{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "sql": "select last(version) from log.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master Uptime",
   "type": "stat",
   "description": "MNode 被选举后经过的时长",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_master_uptime{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "sql": "select last(master_uptime) from log.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Expire Time",
   "type": "stat",
   "description": "企业版授权到期时间",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taos_grants_info_expire_time{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "sql": "select last(expire_time) from log.grants_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Used Meassuring Points",
   "type": "bargauge",
   "description": "企业版授权已用测点数",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "taos_dnodes_info_disk_engine",
     "formatType": "Time series",
     "legendFormat": "used",
     "sql": "select max(timeseries_used) as used ,max(timeseries_total) as total from log.grants_info where ts >= $from and ts <= $to interval(30s)",
     "target": "select metric",
     "type": "timeserie"
    },
    { "expr": "taos_dnodes_info_disk_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "description": "数据库个数",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "expr": "count(taos_vgroups_info_status{cluster=\"$cluster\"})",
     "formatType": "Time series",
     "legendFormat": "databases",
     "sql": "show databases;",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "stat",
   "description": "所有数据库的表数量之和",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "expr": "sum(taos_tables_per_database{cluster=\"$cluster\"})",
     "formatType": "Time series",
     "sql": "show databases;",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select connections_total from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes",
   "type": "bargauge",
   "description": "当前TDengine集群DNode数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_dnodes_total",
     "formatType": "Time series",
     "sql": "select dnodes_total as total,dnodes_alive as alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes",
   "type": "bargauge",
   "description": "当前TDengine集群MNode数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_mnodes_total{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "sql": "select mnodes_total as total,mnodes_alive as alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups",
   "type": "bargauge",
   "description": "当前TDengine集群 VGroups 数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(taos_vgroups_info_status{cluster=\"$cluster\"}) by (vgroup_id))",
     "formatType": "Time series",
     "sql": "select vgroups_total as total, vgroups_alive as alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes",
   "type": "bargauge",
   "description": "当前TDengine集群 VNodes 数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(taos_vgroups_info_online_vnodes{cluster=\"$cluster\"})",
     "formatType": "Time series",
     "sql": "select vnodes_total as total, vnodes_alive as alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "taos_cluster_info_dnodes_alive / taos_cluster_info_dnodes_total",
     "formatType": "Time series",
     "sql": "select avg(dnodes_alive)/avg(dnodes_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "taos_cluster_info_mnodes_alive / taos_cluster_info_mnodes_total",
     "formatType": "Time series",
     "sql": "select avg(mnodes_alive)/avg(mnodes_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "taos_cluster_info_vgroups_alive / taos_cluster_info_vgroups_total",
     "formatType": "Time series",
     "sql": "select avg(vgroups_alive)/avg(vgroups_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "taos_cluster_info_vnodes_alive / taos_cluster_info_vnodes_total",
     "formatType": "Time series",
     "sql": "select avg(vnodes_alive)/avg(vnodes_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Messuring Points Used Percent Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "taos_grants_info_timeseries_used / taos_grants_info_timeseries_total {cluster=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "percent",
     "sql": "select avg(timeseries_used)/avg(timeseries_total) as percent from log.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Grants Expire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "taos_grants_info_expire_time",
     "formatType": "Time series",
     "sql": "select last(expire_time) as expire_time from log.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "错误率（每秒错误数）",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "deriv(taos_dnodes_info_errors{cluster=\"$cluster\"}[1m])",
     "formatType": "Time series",
     "sql": "select derivative(errors, 1s, 1) as errors from (select sum(errors) as errors from log.dnodes_info where ts >= $from and ts <= $to interval(1s))",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "DNodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "DNodes Lifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "colNameFormatStr": "{{groupValue}}",
     "colNameToGroup": "dnode_ep",
     "expr": "taos_dnodes_info_uptime{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "{{dnode_ep}}",
     "sql": "select last(uptime) from log.dnodes_info where ts >= now -1m and ts <= now group by dnode_ep",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "taos_cluster_info_dnodes_total{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "total",
     "sql": "select avg(dnodes_total) as total, avg(dnodes_alive) as alive from log.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "taos_cluster_info_dnodes_alive{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "alive",
     "sql": "select avg(dnodes_total) as total, avg(dnodes_alive) as alive from log.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "taos_cluster_info_mnodes_total{cluster=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "total",
     "sql": "select avg(mnodes_total) as total, avg(mnodes_alive) as alive from log.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "taos_cluster_info_mnodes_alive{cluster=\"$cluster\"}",
     "legendFormat": "alive"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (Inserts)",
     "type": "graph",
     "description": "Include two parts:",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_insert{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "insert_count - {{dnode_ep}}",
       "sql": "select sum(req_insert) as insert_count, sum(req_insert_success) as insert_success, sum(req_insert_batch) as insert_batches, sum(req_insert_batch_success) as insert_batch_success from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_insert_success{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "insert_success - {{dnode_ep}}",
       "sql": "select sum(req_insert_success)  / sum(req_insert) as success_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_insert_batch{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "insert_batches - {{dnode_ep}}",
       "sql": "select sum(req_insert) as total_inserts, sum(req_insert_batch) as total_batches from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "expr": "sum(taos_dnodes_info_req_insert_batch_success{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "insert_batches_success - {{dnode_ep}}",
       "sql": "select sum(req_insert_success)  / sum(req_insert) as success_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "expr": "sum(taos_dnodes_info_req_insert_success{cluster=\"$cluster\"}) by (dnode_ep) / sum(taos_dnodes_info_req_insert{cluster=\"$cluster\"}) by (dnode_ep)",
       "legendFormat": "success_rate - {{dnode_ep}}"
      },
      {
       "expr": "sum(taos_dnodes_info_req_insert_batch_success{cluster=\"$cluster\"}) by (dnode_ep) / sum(taos_dnodes_info_req_insert_batch{cluster=\"$cluster\"}) by (dnode_ep)",
       "legendFormat": "batch_success_rate - {{dnode_ep}}"
      }
     ]
    },
    {
     "title": "Requests Rate (Inserts per Second)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "expr": "avg(taos_dnodes_info_req_insert_rate{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "insert_rate - {{dnode_ep}}",
       "sql": "select avg(req_insert_rate) as insert_rate, avg(req_insert_batch_rate) as batch_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "avg(taos_dnodes_info_req_insert_batch_rate{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "batch_rate - {{dnode_ep}}",
       "sql": "select avg(insert_rate) as cluster_insert_rate, avg(batch_rate) as cluster_batch_rate from (select sum(req_insert_rate) as insert_rate,  sum(req_insert_batch_rate) as batch_rate from log.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "expr": "avg(taos_dnodes_info_req_insert_rate{cluster=\"$cluster\"})",
       "legendFormat": "cluster_insert_rate"
      },
      {
       "expr": "avg(taos_dnodes_info_req_insert_batch_rate{cluster=\"$cluster\"})",
       "legendFormat": "cluster_batch_rate"
      }
     ]
    },
    {
     "title": "Requests (Selects)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_select{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "req_select - {{dnode_ep}}",
       "sql": "select sum(req_select) as req_select from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_select{cluster=\"$cluster\"})",
       "formatType": "Time series",
       "legendFormat": "cluster_req_select",
       "sql": "select sum(req_select) as total from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "avg(taos_dnodes_info_req_select_rate{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "req_select_rate - {{dnode_ep}}",
       "sql": "select avg(req_select_rate) as req_select_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "avg(taos_dnodes_info_req_select_rate{cluster=\"$cluster\"})",
       "formatType": "Time series",
       "legendFormat": "cluster_req_select_rate",
       "sql": "select avg(req_select_rate) as req_select_rate from (select sum(req_select_rate) as req_select_rate from log.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Requests (HTTP)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_http{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "req_http - {{dnode_ep}}",
       "sql": "select sum(req_http) as req_http from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "sum(taos_dnodes_info_req_http{cluster=\"$cluster\"})",
       "formatType": "Time series",
       "legendFormat": "cluster_req_http",
       "sql": "select sum(req_http) as req_http from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "expr": "avg(taos_dnodes_info_req_http_rate{cluster=\"$cluster\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "req_http_rate - {{dnode_ep}}",
       "sql": "select avg(req_http_rate) as req_http_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "expr": "avg(taos_dnodes_info_req_http_rate{cluster=\"$cluster\"})",
       "formatType": "Time series",
       "legendFormat": "cluster_req_http_rate",
       "sql": "select avg(req_http_rate) as req_http_rate from (select sum(req_http_rate) as req_http_rate from log.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Database: [ $database ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "database",
   "collapsed": true,
   "panels": [
    {
     "title": "STables",
     "type": "stat",
     "description": "超级表的个数",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "taos_stables_per_database{cluster=\"$cluster\", database=\"$database\"}",
       "formatType": "Time series",
       "sql": "show $database.stables;",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 3, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colName": "vgroup_id",
       "expr": "sum(taos_vgroups_info_tables_num{cluster=\"$cluster\", database_name=\"$database\"})",
       "formatType": "Time series",
       "sql": "select last(tables_num) as tables_num from (select last(ts) as ts, sum(tables_num) as tables_num from log.vgroups_info where ts > $from and ts <= $to and database_name = '$database' group by ts) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Tables Number Foreach VGroups",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colName": "vgroup_id",
       "colNameFormatStr": "vgoup{{groupValue}}",
       "colNameToGroup": "vgroup_id",
       "expr": "taos_vgroups_info_tables_num",
       "formatType": "Time series",
       "legendFormat": "vgroup_{{vgroup_id}}",
       "sql": "select max(tables_num) as tables_num from log.vgroups_info where ts > $from and ts <= $to and database_name = '$database' interval($interval) fill(null) group by vgroup_id"
      }
     ]
    },
    {
     "title": "Total Tables",
     "type": "stat",
     "description": "所有普通表的个数（包括超级表的子表）",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "taos_tables_per_database{cluster=\"$cluster\",database=\"$database\"}",
       "formatType": "Time series",
       "sql": "select last(tables_num) from (select last(ts) as ts, sum(tables_num) as tables_num from log.vgroups_info where ts > $from and ts <= $to and database_name = '$database' group by ts)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Sub Tables",
     "type": "stat",
     "description": "超级表的所有子表个数",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "taos_tables_per_database{cluster=\"$cluster\",database=\"$database\"}",
       "formatType": "Time series",
       "sql": "show $database.stables;",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "DNode Usage [ $fqdn ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "fqdn",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "启动时长",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "expr": "taos_dnodes_info_uptime{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "sql": "select last(uptime) as uptime  from log.dnodes_info where dnode_ep = '$fqdn'",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Has MNode?",
     "type": "stat",
     "description": "是否有MNode",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "taos_dnodes_info_has_mnode{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "sql": "select last(has_mnode) as has_mnode  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "CPU 核数",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "taos_dnodes_info_cpu_cores{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "sql": "select last(cpu_cores) as uptime  from log.dnodes_info where dnode_ep = '$fqdn' interval ($interval)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Number",
     "type": "stat",
     "description": "VNodes 数量",
     "gridPos": { "h": 6, "w": 2, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "taos_dnodes_info_vnodes_num{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "sql": "select last(vnodes_num) as vnodes_num  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Masters",
     "type": "stat",
     "description": "Master VNodes 数量",
     "gridPos": { "h": 6, "w": 2, "x": 10, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "taos_dnodes_info_masters{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "sql": "select last(masters) as masters  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Current CPU  Usage of taosd",
     "type": "gauge",
     "description": "当前 taosd 线程 CPU 使用率",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "mem_taosd",
       "expr": "taos_dnodes_info_cpu_engine{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Table",
       "sql": "select  last(cpu_engine)  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Current Memory Usage of taosd",
     "type": "gauge",
     "description": "当前 taosd 线程 内存 使用率",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "memory",
       "expr": "taos_dnodes_info_mem_engine{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "legendFormat": "taosd",
       "sql": "select  last(mem_engine) as taosd, last(mem_total) as total  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "alias": "memory",
       "expr": "taos_dnodes_info_mem_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "legendFormat": "total",
       "sql": "select  last(mem_engine) as taosd, last(mem_total) as total  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "expr": "taos_disks_info_datadir_l0_used/taos_disks_info_datadir_l0_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "legendFormat": "level0",
       "sql": "select last(disk_used) as used, last(disk_total) as total,  last(disk_used) / last(disk_total) as percent  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "disk_used",
       "expr": "taos_disks_info_datadir_l1_used/taos_disks_info_datadir_l1_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "legendFormat": "level1",
       "sql": "select last(disk_used) as used, last(disk_total) as total,  last(disk_used) / last(disk_total) as percent  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "disk_used",
       "expr": "taos_disks_info_datadir_l2_used/taos_disks_info_datadir_l2_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}",
       "formatType": "Time series",
       "legendFormat": "level2",
       "sql": "select last(disk_used) as used, last(disk_total) as total,  last(disk_used) / last(disk_total) as percent  from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU 资源占用情况。",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "percent", "label": "使用占比" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(taos_dnodes_info_cpu_engine{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "taosd",
       "sql": "select  avg(cpu_engine) as taosd, avg(cpu_system) as system from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts < $to  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_dnodes_info_cpu_system{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "system",
       "sql": "select  avg(cpu_engine) as taosd, avg(cpu_system) as system from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts < $to  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "description": "内存资源占用情况",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "decmbytes", "label": "使用占比" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(taos_dnodes_info_mem_engine{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "taosd",
       "sql": "select avg(mem_engine) as taosd, avg(mem_system) as system, avg(mem_total) as total from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts < $to  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_dnodes_info_mem_system{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "system",
       "sql": "select avg(mem_engine) as taosd, avg(mem_system) as system, avg(mem_total) as total from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts < $to  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_dnodes_info_mem_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "total",
       "sql": "select avg(mem_engine) as taosd, avg(mem_system) as system, avg(mem_total) as total from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts < $to  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(taos_disks_info_datadir_l0_used{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "level0_used",
       "sql": "select avg(datadir_l0_used) as level0_used, avg(datadir_l0_total) as level0_total, avg(datadir_l1_used) as level1_used, avg(datadir_l1_total) as level1_total, avg(datadir_l2_used) as level2_used, avg(datadir_l2_total) as level2_total from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_disks_info_datadir_l1_used{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "level1_used",
       "sql": "select avg(datadir_l0_used)/avg(datadir_l0_total) as level0_percent, avg(datadir_l1_used)/avg(datadir_l1_total) as level1_percent , avg(datadir_l2_used)/avg(datadir_l2_total) as level2_percent  from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_disks_info_datadir_l2_used{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "level2_used",
       "sql": "select avg(datadir_l0_used)/avg(datadir_l0_total) as level0_percent, avg(datadir_l1_used)/avg(datadir_l1_total) as level1_percent , avg(datadir_l2_used)/avg(datadir_l2_total) as level2_percent  from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_disks_info_datadir_l0_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "level0_total",
       "sql": "select avg(datadir_l0_used) as level0_used, avg(datadir_l0_total) as level0_total, avg(datadir_l1_used) as level1_used, avg(datadir_l1_total) as level1_total, avg(datadir_l2_used) as level2_used, avg(datadir_l2_total) as level2_total from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_disks_info_datadir_l1_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "level1_total",
       "sql": "select avg(datadir_l0_used) as level0_used, avg(datadir_l0_total) as level0_total, avg(datadir_l1_used) as level1_used, avg(datadir_l1_total) as level1_total, avg(datadir_l2_used) as level2_used, avg(datadir_l2_total) as level2_total from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_disks_info_datadir_l2_total{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$__interval])",
       "formatType": "Time series",
       "legendFormat": "level2_total",
       "sql": "select avg(datadir_l0_used) as level0_used, avg(datadir_l0_total) as level0_total, avg(datadir_l1_used) as level1_used, avg(datadir_l1_total) as level1_total, avg(datadir_l2_used) as level2_used, avg(datadir_l2_total) as level2_total from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used Increasing Rate per Minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "alias": "level0",
       "expr": "deriv(rate(taos_disks_info_datadir_l0_used{cluster=\"$cluster\", dnode_ep=\"$fqdn\"}[1m])[5m:1s])  * 1024",
       "formatType": "Time series",
       "legendFormat": "level0",
       "sql": "select derivative(value, 1m, 0) from (select avg(datadir_l0_used) * 1024 as value from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "level1",
       "expr": "deriv(rate(taos_disks_info_datadir_l1_used{cluster=\"$cluster\", dnode_ep=\"$fqdn\"}[1m])[5m:1s])  * 1024",
       "formatType": "Time series",
       "legendFormat": "level1",
       "sql": "select derivative(value, 1m, 0) from (select avg(datadir_l1_used) * 1024 as value from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "level1",
       "expr": "deriv(rate(taos_disks_info_datadir_l2_used{cluster=\"$cluster\", dnode_ep=\"$fqdn\"}[1m])[5m:1s])  * 1024",
       "formatType": "Time series",
       "legendFormat": "level2",
       "sql": "select derivative(value, 1m, 0) from (select avg(datadir_l1_used) * 1024 as value from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts < $to interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "description": "io",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "MBs", "label": "IO Rate" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(taos_dnodes_info_io_write_disk{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
       "formatType": "Time series",
       "legendFormat": "io_write_disk",
       "sql": "select  avg(io_read_disk) as io_read_taosd, avg(io_write_disk) as io_write_taosd from log.dnodes_info where dnode_ep = '$fqdn' and ts >= now-1h and ts < now  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_dnodes_info_io_read_disk{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
       "formatType": "Time series",
       "legendFormat": "io_read_disk",
       "sql": "select  avg(io_read_disk) as io_read_taosd, avg(io_write_disk) as io_write_taosd from log.dnodes_info where dnode_ep = '$fqdn' and ts >= now-1h and ts < now  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Net",
     "type": "graph",
     "description": "io",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "yaxes": [
      { "format": "Mbits", "label": "IO Rate" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(taos_dnodes_info_net_in{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
       "formatType": "Time series",
       "legendFormat": "net_in",
       "sql": "select  avg(net_in) as net_in, avg(net_out) as net_out from log.dnodes_info where dnode_ep = '$fqdn' and ts >= now-1h and ts < now  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "avg_over_time(taos_dnodes_info_net_out{cluster=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
       "formatType": "Time series",
       "legendFormat": "net_out",
       "sql": "select  avg(net_in) as net_in, avg(net_out) as net_out from log.dnodes_info where dnode_ep = '$fqdn' and ts >= now-1h and ts < now  interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Login History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Login Counts per Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "alias": "logins",
       "expr": "count_over_time(taos_logs_content{cluster=\"$cluster\"}[1m])",
       "formatType": "Time series",
       "sql": "select count(*) from log.logs where ts >= $from and ts < $to interval (1m)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  }
 ]
}