CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

ADD_SUBDIRECTORY(dnodeCluster)
ADD_SUBDIRECTORY(httpAdmin)
ADD_SUBDIRECTORY(mnodeAccount)
ADD_SUBDIRECTORY(mnodeBalance)
ADD_SUBDIRECTORY(mnodeCluster)
ADD_SUBDIRECTORY(sdbReplica)
ADD_SUBDIRECTORY(multilevelStorage)
ADD_SUBDIRECTORY(vnodeCluster)
ADD_SUBDIRECTORY(vnodeReplica)