CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/os)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/util)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/common)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/client)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mgmt)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mnode)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/monitor)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/transport)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/scheduler)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/mnode/impl/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/qcom)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/catalog)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/planner)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/nodes)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/sync)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/wal)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/tfs)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/stream)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/vnode/src/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mnode/sdb)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/cJson)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/query/inc)
INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/src/inc)
INCLUDE_DIRECTORIES(inc)
AUX_SOURCE_DIRECTORY(src SRC)
  
ADD_LIBRARY(topic ${SRC})
TARGET_LINK_LIBRARIES(topic)
