[package]
name = "source-kafka"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
arrow-schema.workspace = true
chrono.workspace = true
faststr.workspace = true
itertools.workspace = true
linked-hash-map.workspace = true
scc.workspace = true
serde.workspace = true
serde_json.workspace = true
taos.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
futures-util.workspace = true
flume.workspace = true
uuid.workspace = true
pin-project-lite.workspace = true

taosx-core.workspace = true
taosx-ipc.workspace = true
futures-ext.workspace = true

rdkafka = { version = "0.37.0", features = ["cmake-build", "ssl", "tracing"] }
[target.'cfg(not(windows))'.dependencies]
rdkafka = { version = "0.37.0", features = [
    "cmake-build",
    "ssl",
    "gssapi-vendored",
] }


[lints]
workspace = true
