[advisories]
unmaintained = "none"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]
exceptions = [{ allow = ["OpenSSL"], name = "aws-lc-sys" }]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/taosdata/tokio-tungstenite.git",
    "https://github.com/taosdata/tungstenite-rs.git",
]
