PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/client)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/common)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/os)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/util)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mgmt)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/mnode)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/dnode/qnode)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/monitor)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/metrics)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/transport)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/sync)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/wal)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/libs/tfs)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/mgmt/node_mgmt/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/mgmt/mgmt_dnode/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/source/dnode/mgmt/node_util/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/cJson)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/iconv)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/libuv/include)

IF(TD_WINDOWS)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/msvcregex)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/contrib/pthread)
ENDIF()

IF(DEFINED GRANT_CFG_INCLUDE_DIR)
  add_definitions(-DGRANTS_CFG)
ENDIF()

IF(BUILD_DM_MODULE)
  LIST(APPEND SRC ./src/dmodule.c)
  ADD_LIBRARY(dmodule ${SRC})
  DEP_ext_libuv(dmodule)
  DEP_ext_cjson(dmodule)
ENDIF()
