PROJECT(TDengine)

# Set c++ compiler options
SET(COMMON_CXX_FLAGS "${COMMON_FLAGS} -std=c++11")
SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${COMMON_CXX_FLAGS} ${DEBUG_FLAGS}")
SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${COMMON_CXX_FLAGS} ${RELEASE_FLAGS}")
#INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/inc)
#INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/client/inc)
#INCLUDE_DIRECTORIES(${TD_OS_DIR}/inc)
#INCLUDE_DIRECTORIES(inc)

#IF (TD_WINDOWS_64)
#  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/deps/pthread)
#ENDIF ()
SET(EXECUTABLE_OUTPUT_PATH ${TD_ENTERPRISE_DIR}/tests/jenkins)
AUX_SOURCE_DIRECTORY(. SRC)
ADD_EXECUTABLE(tjenkins ${SRC})
#TARGET_LINK_LIBRARIES(pthread )
