[profile.default]
retries = 1
test-threads = "num-cpus"
slow-timeout = { period = "5m", terminate-after = 1 }

[[profile.default.overrides]]
filter = 'test(with_taos)'
retries = { backoff = "exponential", count = 5, delay = "3s", jitter = true }

[profile.ci]
fail-fast = false

[profile.ci.junit] # this can be some other profile, too
path = "taosx-unit-tests.xml"
store-success-output = true
store-failure-output = true

[profile.perf_test]
retries = 0
slow-timeout = { period = "24h" }
