[package]
name = "xnoded"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
snafu.workspace = true
arrow.workspace = true
arrow-flight.workspace = true
axum.workspace = true
axum-extra = {workspace = true, features = ["with-rejection"]}
tower-http = { workspace = true, features = [ "trace" ] }
clap.workspace = true
dotenv.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
mimalloc = {workspace = true, optional = true}
shadow-rs.workspace = true
const_format.workspace = true
bitfield.workspace = true
tokio = { workspace = true, features = [ "net", "rt-multi-thread", "sync", "time" ] }
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tonic.workspace = true
flume.workspace = true
parking_lot.workspace = true
taos.workspace = true
futures.workspace = true
itertools.workspace = true

ha-core.workspace = true
ha-rpc-client.workspace = true
taoslog.workspace = true
futures-ext.workspace = true
taosx-utils.workspace = true

[build-dependencies]
shadow-rs.workspace = true

[lints]
workspace = true

[features]
default = ["mimalloc"]
