[package]
name = "taos-explorer"
version = "1.7.0"
edition = "2021"
description = "TDengine Explorer UI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-embed = "0.1.0"
actix-files = "0.6.6"
actix-web = { version = "4.7.0", features = ["rustls-0_23"] }
rustls = { version = "0.23.10", default-features = false }
rustls-pemfile = "2.1.2"
reqwest = { version = "0.11.27", default-features = false, features = [
	"stream",
	"json",
	"deflate",
	"rustls-tls",
] }
anyhow = "1"
atty = "0.2.14"
clap = { version = "4", features = ["derive", "env"] }
clap-verbosity-flag = "2.2.0"
sqlx = { version = "0.7", features = ["sqlite", "chrono", "runtime-tokio"] }
tokio-util = "0.7.10"
tokio-stream = "0.1.14"
log = { version = "0.4", features = ["serde"] }
futures-util = "0.3.30"
http-auth-basic = "0.3"
rust-embed = "6.8.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1"
thiserror = "1"
toml = "0.8.8"
tracing = "0.1"
tracing-actix-web = "0.7.11"
tracing-subscriber = "0.3"
utoipa = "4.2.3"
sha1 = "0.10.6"
rand = "0.8.4"
lazy_static = "1.4.0"
captcha = "0.0.9"
deadpool = "0.10"

const-str = "0.5.7"
const_format = "0.2.32"
shadow-rs = { version = "0.33", default-features = false }
geos = { version = "9.0.0", features = ["static"] }
hex = "0.4.3"
chrono = "0.4"
chrono-tz = "0.9.0"
scc = "2.1.16"

taoslog = { git = "https://github.com/taosdata/taoslog-rs.git", rev = "b0c53e27fff15f97237e808f83d9a7f113ee6463", features = [
	"ansi",
] }
http = "0.2.12"
bitfield = "0.16.1"
serde_with = "3.9.0"

[dependencies.taos]
# path = "../taos-connector-rust/taos"
version = "0.12"
git = "https://github.com/taosdata/taos-connector-rust.git"
default-features = false
features = ["ws-rustls", "optin", "deadpool"]

[build-dependencies]
shadow-rs = { version = "0.33", default-features = false }

[dev-dependencies]
zstd = "0"
