CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/os)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/util)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/client)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/include/common)
INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/src/inc)
INCLUDE_DIRECTORIES(inc)
AUX_SOURCE_DIRECTORY(src SRC)
  
IF (TD_LINUX)
  ADD_LIBRARY(module ${SRC})
  TARGET_LINK_LIBRARIES(module)

  ADD_LIBRARY(moduleTest1 SHARED test/moduleTest1.c)
  ADD_LIBRARY(moduleTest2 SHARED test/moduleTest2.c)
ENDIF ()
