select last(*) from dbnew.stb0;
select last(ts) from dbnew.stb0;
select last(c0) from dbnew.stb0;
select last(c1) from dbnew.stb0;
select last(c2) from dbnew.stb0;
select last(c3) from dbnew.stb0;
select last(c4) from dbnew.stb0;
select last(c5) from dbnew.stb0;
select last(t0) from dbnew.stb0;
select last(t1) from dbnew.stb0;
#insert into dbnew.stb0_1  select * from dbnew.stb0_0;
#compact database dbnew;
select last_row(*) from dbnew.stb0;
select last_row(ts) from dbnew.stb0;
select last_row(c0) from dbnew.stb0;
select last_row(c1) from dbnew.stb0;
select last_row(c2) from dbnew.stb0;
select last_row(c3) from dbnew.stb0;
select last_row(c4) from dbnew.stb0;
select last_row(c5) from dbnew.stb0;
select last_row(t0) from dbnew.stb0;
select last_row(t1) from dbnew.stb0;
#insert into dbnew.stb0_101 select * from dbnew.stb0_100;
select last(*) from dbnew.stb0 group by tbname;
select last(ts) from dbnew.stb0 group by tbname;
select last(c0) from dbnew.stb0 group by tbname;
select last(c1) from dbnew.stb0 group by tbname;
select last(c2) from dbnew.stb0 group by tbname;
select last(c3) from dbnew.stb0 group by tbname;
select last(c4) from dbnew.stb0 group by tbname;
select last(c5) from dbnew.stb0 group by tbname;
select last(t0) from dbnew.stb0 group by tbname;
select last(t1) from dbnew.stb0 group by tbname;
#insert into dbnew.stb0_201 select * from dbnew.stb0_200;
select last(*) from dbnew.stb0 partition by tbname;
select last(ts) from dbnew.stb0 partition by tbname;
select last(c0) from dbnew.stb0 partition by tbname;
select last(c1) from dbnew.stb0 partition by tbname;
select last(c2) from dbnew.stb0 partition by tbname;
select last(c3) from dbnew.stb0 partition by tbname;
select last(c4) from dbnew.stb0 partition by tbname;
select last(c5) from dbnew.stb0 partition by tbname;
select last(t0) from dbnew.stb0 partition by tbname;
select last(t1) from dbnew.stb0 partition by tbname;
#insert into dbnew.stb0_301 select * from dbnew.stb0_300;
select last_row(*) from dbnew.stb0 group by tbname;
select last_row(ts) from dbnew.stb0 group by tbname;
select last_row(c0) from dbnew.stb0 group by tbname;
select last_row(c1) from dbnew.stb0 group by tbname;
select last_row(c2) from dbnew.stb0 group by tbname;
select last_row(c3) from dbnew.stb0 group by tbname;
select last_row(c4) from dbnew.stb0 group by tbname;
select last_row(c5) from dbnew.stb0 group by tbname;
select last_row(t0) from dbnew.stb0 group by tbname;
select last_row(t1) from dbnew.stb0 group by tbname;
#insert into dbnew.stb0_401 select * from dbnew.stb0_400;
select last_row(*) from dbnew.stb0 partition by tbname;
select last_row(ts) from dbnew.stb0 partition by tbname;
select last_row(c0) from dbnew.stb0 partition by tbname;
select last_row(c1) from dbnew.stb0 partition by tbname;
select last_row(c2) from dbnew.stb0 partition by tbname;
select last_row(c3) from dbnew.stb0 partition by tbname;
select last_row(c4) from dbnew.stb0 partition by tbname;
select last_row(c5) from dbnew.stb0 partition by tbname;
select last_row(t0) from dbnew.stb0 partition by tbname;
select last_row(t1) from dbnew.stb0 partition by tbname;
#insert into dbnew.stb0_501 select * from dbnew.stb0_500;
#flush database dbnew;
select count(*) from dbnew.stb0;
select count(ts) from dbnew.stb0;
select count(c0) from dbnew.stb0;
select count(c1) from dbnew.stb0;
select count(c2) from dbnew.stb0;
select count(c3) from dbnew.stb0;
select count(c4) from dbnew.stb0;
select count(c5) from dbnew.stb0;
select count(t0) from dbnew.stb0;
select count(t1) from dbnew.stb0;
#insert into dbnew.stb0_1  select * from dbnew.stb0_0;
#compact database dbnew;
select count(*) from dbnew.stb0;
select count(ts) from dbnew.stb0;
select count(c0) from dbnew.stb0;
select count(c1) from dbnew.stb0;
select count(c2) from dbnew.stb0;
select count(c3) from dbnew.stb0;
select count(c4) from dbnew.stb0;
select count(c5) from dbnew.stb0;
select count(t0) from dbnew.stb0;
select count(t1) from dbnew.stb0;
select count(*) from dbnew.stb0 group by tbname;
select count(ts) from dbnew.stb0 group by tbname;
select count(c0) from dbnew.stb0 group by tbname;
select count(c1) from dbnew.stb0 group by tbname;
select count(c2) from dbnew.stb0 group by tbname;
select count(c3) from dbnew.stb0 group by tbname;
select count(c4) from dbnew.stb0 group by tbname;
select count(c5) from dbnew.stb0 group by tbname;
select count(t0) from dbnew.stb0 group by tbname;
select count(t1) from dbnew.stb0 group by tbname;
select count(*) from dbnew.stb0 partition by tbname;
select count(ts) from dbnew.stb0 partition by tbname;
select count(c0) from dbnew.stb0 partition by tbname;
select count(c1) from dbnew.stb0 partition by tbname;
select count(c2) from dbnew.stb0 partition by tbname;
select count(c3) from dbnew.stb0 partition by tbname;
select count(c4) from dbnew.stb0 partition by tbname;
select count(c5) from dbnew.stb0 partition by tbname;
select count(t0) from dbnew.stb0 partition by tbname;
select count(t1) from dbnew.stb0 partition by tbname;
select count(*) from dbnew.stb0 group by tbname;
select count(ts) from dbnew.stb0 group by tbname;
select count(c0) from dbnew.stb0 group by tbname;
select count(c1) from dbnew.stb0 group by tbname;
select count(c2) from dbnew.stb0 group by tbname;
select count(c3) from dbnew.stb0 group by tbname;
select count(c4) from dbnew.stb0 group by tbname;
select count(c5) from dbnew.stb0 group by tbname;
select count(t0) from dbnew.stb0 group by tbname;
select count(t1) from dbnew.stb0 group by tbname;
select count(*) from dbnew.stb0 partition by tbname;
select count(ts) from dbnew.stb0 partition by tbname;
select count(c0) from dbnew.stb0 partition by tbname;
select count(c1) from dbnew.stb0 partition by tbname;
select count(c2) from dbnew.stb0 partition by tbname;
select count(c3) from dbnew.stb0 partition by tbname;
select count(c4) from dbnew.stb0 partition by tbname;
select count(c5) from dbnew.stb0 partition by tbname;
select count(t0) from dbnew.stb0 partition by tbname;
select count(t1) from dbnew.stb0 partition by tbname;
#flush database dbnew;