"""
Cloud Service User Compatibility Test (TDengine Cloud)

Tests cloud service user creation, privilege management, taosx-related
information_schema queries, data subscription, and streaming operations.

Main test user: cloud_user (sysinfo=0, createdb=1)

Overview:
  - Environment is initialized once in setup and cleaned up in teardown.
  - One cloud_user is created and reused throughout all test sub-cases.
  - A secondary user (cloud_sub_user) is created to verify privilege delegation.

Since: v3.4.0.0

Labels: common,ci,user,cloud：


Jira: None

History:
    - 2026-03-02  Auto-generated by GitHub Copilot
"""

from new_test_framework.utils import tdLog, tdSql, TDCom, etool
from taos.tmq import Consumer
import time
import threading

# ----------------------------- error codes ----------------------------------
TSDB_CODE_OPS_NOT_SUPPORT         = 0x0100
TSDB_CODE_MND_NO_RIGHTS           = 0x0303
TSDB_CODE_MND_INVALID_CONN_ID     = 0x030E
TSDB_CODE_MND_PRIVILEGE_EXIST     = 0x0359
TSDB_CODE_PAR_PERMISSION_DENIED   = 0x2644
TSDB_CODE_PAR_DB_USE_PERMISSION_DENIED   = 0x26E3
TSDB_CODE_PAR_TB_CREATE_PERMISSION_DENIED = 0x26E4
TSDB_CODE_PAR_STREAM_CREATE_PERMISSION_DENIED = 0x26E7

# ----------------------------- constants ------------------------------------
CLOUD_USER          = "cloud_user"
PWD                 = "abcd@1234"
CLOUD_SUB_USER      = "cloud_sub_user"
TEST_USER           = "test_user"
CLOUD_DB            = "cloud_db"
CLOUD_STB           = "cloud_stb"
CLOUD_TABLE         = "cloud_table"
CLOUD_CHILD_TABLE   = "cloud_ct1"
CLOUD_TOPIC         = "cloud_topic"
CLOUD_STREAM        = "cloud_stream"

ROOT_PWD = "taosdata"


def normalize_errno(err):
    if err is None:
        return None
    if err < 0:
        return (err & 0xFFFFFFFF) & 0xFFFF
    return err & 0xFFFF


def errno_from_exception(e):
    if hasattr(e, "args") and len(e.args) >= 2:
        return e.args[1]
    if hasattr(e, "errno"):
        return e.errno
    return None


class TestUserCloud:
    """Cloud service user compatibility tests."""

    @classmethod
    def setup_class(cls):
        tdLog.info("TestUserCloud setup_class")
        cls.tdCom = TDCom()

    # =========================================================================
    #  Utility helpers
    # =========================================================================
    
    def create_user(self, user_name, password=None, options="", login=False):
        if password is None:
            password = "abcd@1234" # default password
        sql = f"CREATE USER {user_name} pass '{password}' {options}"
        tdSql.execute(sql)
        
        if login:
            self.login(user=user_name, password=password)    

    def drop_user(self, user_name):
        # Drop a user
        tdSql.execute(f"DROP USER {user_name}")
        tdLog.info(f"Dropped user: {user_name}")
        
    def create_role(self, role_name):
        tdSql.execute(f"CREATE ROLE {role_name}")
        tdLog.info(f"Created role: {role_name}")
    
    def drop_role(self, role_name):
        # Drop a role
        tdSql.execute(f"DROP ROLE {role_name}")
        tdLog.info(f"Dropped role: {role_name}")        

    def login(self, user=None, password=None):
        """Switch tdSql connection to *user* (default: root)."""
        if user is None:
            tdSql.connect()
        else:
            tdSql.connect(user, password=password)

    def login_failed(self, user, password):
        """Assert that a login attempt *must* fail."""
        try:
            self.login(user, password=password)
        except Exception as e:
            tdLog.info(f"Login failed as expected for {user}: {e}")
            return
        raise Exception(f"Login succeeded for {user} but was expected to fail")

    def exec_sql(self, sql):
        tdSql.execute(sql)
        tdLog.debug(f"   Executed: {sql}")

    def exec_sql_failed(self, sql, errno=None, queryTimes=30):
        for i in range(1, queryTimes + 1):
            try:
                tdSql.cursor.execute(sql)
                time.sleep(1)
                tdLog.debug(f"   try {i}/{queryTimes} still succeeded: {sql}")
            except Exception as e:
                actual_errno = errno_from_exception(e)
                if errno is not None:
                    expected_code = normalize_errno(errno)
                    actual_code   = normalize_errno(actual_errno)
                    if actual_code != expected_code:
                        tip = (
                            f"   try {i}/{queryTimes} expected 0x{expected_code:04X},"
                            f" got 0x{actual_code:04X} for: {sql}. err={e}"
                        )
                        if i < queryTimes:
                            tdLog.debug(tip)
                            time.sleep(1)
                            continue
                        raise Exception(tip)
                tdLog.debug(f"   SQL failed as expected: {sql}")
                return True
        raise Exception(f"tried {queryTimes}×, SQL still succeeded (expected to fail): {sql}")

    def query_expect_rows(self, sql, expected_rows, queryTimes=30):
        actual_rows = 0
        for i in range(queryTimes):
            tdSql.query(sql)
            actual_rows = tdSql.queryRows
            if actual_rows == expected_rows:
                return
            tdLog.debug(
                f"    try {i+1}/{queryTimes} got {actual_rows} rows,"
                f" expected {expected_rows}: {sql}"
            )
            time.sleep(1)
        raise Exception(f"expected {expected_rows} rows, got {actual_rows}: {sql}")

    def grant_privilege(self, privilege, target, user_or_role, with_condition=""):
        with_str = f"WITH {with_condition}" if with_condition else ""
        if target is None or target == "":
            sql = f"GRANT {privilege} TO {user_or_role}"
        else:
            sql = f"GRANT {privilege} ON {target} {with_str} TO {user_or_role}"
        tdLog.debug(f"   Granted: {sql}")
        tdSql.execute(sql)
        
    def grant_privilege_failed(self, privilege, target, user_or_role, with_condition=""):
        # Verify that grant should fail
        if with_condition:
            with_str = f"WITH {with_condition}"
        else:
            with_str = ""
        if target is None or target == "":
            sql = f"GRANT {privilege} TO {user_or_role}"
        else:
            sql = f"GRANT {privilege} ON {target} {with_str} TO {user_or_role}"
        
        tdSql.error(sql)
        print(f"Grant failed as expected: {sql}")        

    def revoke_privilege(self, privilege, target, user_or_role):
        if target is None or target == "":
            sql = f"REVOKE {privilege} FROM {user_or_role}"
        else:
            sql = f"REVOKE {privilege} ON {target} FROM {user_or_role}"
        tdLog.debug(f"   Revoked: {sql}")
        tdSql.execute(sql)
        
    def revoke_privilege_failed(self, privilege, target, user_or_role):
        # Verify that revoke should fail
        if target is None or target == "":
            sql = f"REVOKE {privilege} FROM {user_or_role}"
        else:
            sql = f"REVOKE {privilege} ON {target} FROM {user_or_role}"
        tdSql.error(sql)
        print(f"Revoke failed as expected: {sql}")

    def grant_role(self, role_name, user_name):
        # Grant role to user
        tdSql.execute(f"GRANT ROLE {role_name} TO {user_name}")
        print(f"   Granted role {role_name} to {user_name}")
    
    def revoke_role(self, role_name, user_name):
        # Revoke role from user
        tdSql.execute(f"REVOKE ROLE {role_name} FROM {user_name}")
        print(f"   Revoked role {role_name} from {user_name}")           

    def create_database(self, db_name, options=""):
        # Create a database (drop if exists first)
        sql = f"CREATE DATABASE {db_name} {options}"
        tdSql.execute(sql)
        tdLog.info(f"Created database: {db_name}")
    
    def drop_database(self, db_name):
        # Drop a database
        tdSql.execute(f"DROP DATABASE {db_name}")
        tdLog.info(f"Dropped database: {db_name}")
    
    def use_database(self, db_name):
        # Use a database
        tdSql.execute(f"USE {db_name}")
        tdLog.info(f"Using database: {db_name}")
    
    def create_stable(self, db_name, stable_name, columns="ts TIMESTAMP, c1 INT", tags="t1 INT"):
        # Create a super table
        sql = f"CREATE STABLE {db_name}.{stable_name} ({columns}) TAGS ({tags})"
        tdSql.execute(sql)
        tdLog.info(f"Created stable: {db_name}.{stable_name}")
    
    def create_table(self, db_name, table_name, columns="ts TIMESTAMP, c1 INT"):
        # Create a normal table
        sql = f"CREATE TABLE {db_name}.{table_name} ({columns})"
        tdSql.execute(sql)
        tdLog.info(f"Created table: {db_name}.{table_name}")     
        
    def create_topic(self, topic_name, as_clause, options=""):
        # Create a topic
        sql = f"CREATE TOPIC {topic_name} {options} as {as_clause}"
        tdSql.execute(sql)
        tdLog.info(f"Created topic: {topic_name}") 
    
    def drop_topic(self, topic_name, options=""):
        # Drop a topic
        sql = f"DROP TOPIC {options} {topic_name}"
        tdSql.execute(sql)
        tdLog.info(f"Dropped topic: {topic_name}")

    def subscribe_topic(self, user, password, group_id, topic_name, expected_rows=None, createTimes=30):
        attr = {
            'group.id': group_id,
            'td.connect.user': user,
            'td.connect.pass': password,
            'auto.offset.reset': 'earliest'
        }

        for i in range(createTimes):
            try:
                # Create consumer
                consumer = Consumer(attr)
                # Subscribe topic
                consumer.subscribe([topic_name])
                print("   Subscribe topics successfully")
                # Poll data
                records = consumer.poll(5)
                if records:
                    err = records.error()
                    if err is not None:
                        print(f"Poll data error, {err}")
                        raise err
                    
                    if expected_rows is None:
                        print("   Polled data successfully")
                        return

                    val = records.value()
                    if val:
                        for block in val:
                            data = block.fetchall()
                            print(f"   data: {data}")        
                    if expected_rows is not None:
                        actual_rows = len(data)                        
                        if actual_rows == expected_rows:
                            print(f"   Got expected rows: {actual_rows}")
                            return consumer
                        else:
                            raise Exception(f"Got rows: {actual_rows}, expected: {expected_rows}")
                print("   Polled data successfully")
                return consumer
            except Exception as e:                
                print(f"Create consumer try {i+1}/{createTimes} failed: {str(e)}")
                time.sleep(1)
        
        raise Exception(f"Failed to create consumer & subscribe after {createTimes} attempts")
        
    def subscribe_topic_failed(self, user, password, group_id, topic_name, expect_errno=None, times=10):
        attr = {
            'group.id': group_id,
            'td.connect.user': user,
            'td.connect.pass': password,
            'auto.offset.reset': 'earliest'
        }        
        for i in range(times):
            try:
                # Create consumer
                consumer = Consumer(attr)
                # Subscribe topic                
                consumer.subscribe([topic_name])
                print("   Subscribe topics succeeded but was expected to fail")
                consumer.unsubscribe()
                time.sleep(1)
            except Exception as e:
                print(f"   Subscribe topics failed as expected: {str(e)}")
                if expect_errno is not None:
                    actual_errno = errno_from_exception(e)
                    expected_code = normalize_errno(expect_errno)
                    actual_code = normalize_errno(actual_errno)                    
                    if actual_code != expected_code:
                        raise Exception(f"Expected errno 0x{expected_code:04X} ({expected_code}), got 0x{actual_code:04X} when subscribing topic. Error: {e}")  
                return
        raise Exception(f"Subscribe topics still succeeded after {times} attempts, expected to fail")
    
    def unsubscribe_topic(self, consumer):
        consumer.unsubscribe()
        print("Unsubscribed topic successfully")
        
    def drop_stream(self, db_name, stream_name):
        # Drop a stream
        sql = f"DROP STREAM {db_name}.{stream_name}"
        tdSql.execute(sql)
        tdLog.info(f"Dropped stream: {db_name}.{stream_name}")
    
    def create_child_table(self, db_name, child_name, stable_name, tag_values="1"):
        # Create a child table
        sql = f"CREATE TABLE {db_name}.{child_name} USING {db_name}.{stable_name} TAGS ({tag_values})"
        tdSql.execute(sql)
        tdLog.info(f"Created child table: {db_name}.{child_name}")
    
    def insert_data(self, db_name, table_name, values="NOW, 1"):
        # Insert data into table
        sql = f"INSERT INTO {db_name}.{table_name} VALUES ({values})"
        tdSql.execute(sql)
        tdLog.info(f"Inserted data into {db_name}.{table_name}")
    
    def select_data(self, db_name, table_name, columns="*"):
        # Select data from table
        sql = f"SELECT {columns} FROM {db_name}.{table_name}"
        tdSql.query(sql)
        tdLog.info(f"Selected from {db_name}.{table_name}, rows: {tdSql.queryRows}")
        return tdSql.queryRows
    
    def delete_data(self, db_name, table_name, condition=""):
        # Delete data from table
        sql = f"DELETE FROM {db_name}.{table_name}"
        if condition:
            sql += f" WHERE {condition}"
        tdSql.execute(sql)
        tdLog.info(f"Deleted from {db_name}.{table_name}")
    
    def check_privilege_in_show(self, user_name, privilege_name, should_have=True):
        # Check if user has specific privilege in show users/roles output
        tdSql.query("SHOW USERS FULL")
        result = tdSql.queryResult
        for row in result:
            if row[0] == user_name:
                if should_have:
                    tdLog.info(f"User {user_name} has privilege as expected")
                else:
                    raise Exception(f"User {user_name} should not have privilege")
                return
        if should_have:
            raise Exception(f"User {user_name} not found or doesn't have privilege")
        
    def create_snode(self, dnode_id=1):
        # Create a stream node on specified data node
        sql = f"CREATE SNODE ON DNODE {dnode_id}"
        tdSql.execute(sql)

    # =========================================================================
    #  Setup / Teardown
    # =========================================================================

    def _setup_env(self):
        """
        Create the cloud_user and cloud_sub_user once.  Also prepare the
        shared database, supertable, normal table, child table, and seed data
        under cloud_user ownership.
        """
        tdLog.info("=== [Cloud] Setting up environment ===")
        self.create_snode()  # needed for stream tests
        self.login()  # root

        # ---------- users ----------
        self.create_user(CLOUD_USER,     PWD, options="SYSINFO 0 CREATEDB 1")
        self.create_user(CLOUD_SUB_USER, PWD, options="SYSINFO 0 CREATEDB 0")
        self.create_user(TEST_USER,      PWD, options="SYSINFO 0 CREATEDB 0")

        # ---------- database (owned by cloud_user) ----------
        self.login(CLOUD_USER, password=PWD)
        tdSql.execute(f"CREATE DATABASE {CLOUD_DB} VGROUPS 1")
        tdSql.execute(
            f"CREATE STABLE {CLOUD_DB}.{CLOUD_STB}"
            f" (ts TIMESTAMP, val INT, payload VARCHAR(64))"
            f" TAGS (region VARCHAR(20), sensor_id INT)"
        )
        tdSql.execute(
            f"CREATE TABLE {CLOUD_DB}.{CLOUD_TABLE}"
            f" (ts TIMESTAMP, metrics INT)"
        )
        tdSql.execute(
            f"CREATE TABLE {CLOUD_DB}.{CLOUD_CHILD_TABLE}"
            f" USING {CLOUD_DB}.{CLOUD_STB}"
            f" TAGS ('region_a', 1)"
        )
        # seed rows
        for i in range(10):
            tdSql.execute(
                f"INSERT INTO {CLOUD_DB}.{CLOUD_CHILD_TABLE}"
                f" VALUES (NOW+{i}s, {i*10}, 'data_{i}')"
            )
        for i in range(5):
            tdSql.execute(
                f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE}"
                f" VALUES (NOW+{i}s, {i+1})"
            )

        tdLog.info("=== [Cloud] Environment ready ===")

    def _teardown_env(self):
        """Drop all cloud test resources (topics/streams first, then DB/users)."""
        tdLog.info("=== [Cloud] Tearing down environment ===")
        self.login()  # root

        # drop topic (if exists)
        try:
            tdSql.execute(f"DROP TOPIC IF EXISTS {CLOUD_TOPIC}")
        except Exception:
            pass

        # drop stream (if exists)
        try:
            tdSql.execute(f"DROP STREAM IF EXISTS {CLOUD_DB}.{CLOUD_STREAM}")
        except Exception:
            pass

        # drop database
        try:
            tdSql.execute(f"DROP DATABASE IF EXISTS {CLOUD_DB}")
        except Exception:
            pass

        # drop users
        for u in [CLOUD_USER, CLOUD_SUB_USER]:
            try:
                tdSql.execute(f"DROP USER {u}")
            except Exception:
                pass

        tdLog.info("=== [Cloud] Teardown complete ===")

    # =========================================================================
    #  Test 1 – Cloud user basic attributes
    # =========================================================================

    def do_cloud_user_attributes(self):
        """Verify the cloud_user was created with the expected option values."""
        tdLog.info("--- [Cloud] do_cloud_user_attributes ---")
        self.login()

        res = tdSql.getResult("SHOW USERS FULL")
        idx_sysinfo  = tdSql.fieldIndex("SYSINFO")
        idx_createdb = tdSql.fieldIndex("CREATEDB")

        found = False
        for row in res:
            if row[0] == CLOUD_USER:
                found = True
                assert row[idx_sysinfo]  == 0, \
                    f"SYSINFO expected 0, got {row[idx_sysinfo]}"
                assert row[idx_createdb] == 1, \
                    f"CREATEDB expected 1, got {row[idx_createdb]}"
                break

        assert found, f"User {CLOUD_USER} not found in SHOW USERS FULL"
        print("cloud_user attributes ................. [ passed ] ")

    # =========================================================================
    #  Test 2 – Cloud user can create / drop database
    # =========================================================================

    def do_cloud_user_createdb(self):
        """
        cloud_user has CREATEDB=1 so it can create its own databases.
        cloud_sub_user has CREATEDB=0 so it must not be able to.
        """
        tdLog.info("--- [Cloud] do_cloud_user_createdb ---")

        # cloud_user can create an extra DB
        extra_db = "cloud_extra_db"
        self.login(CLOUD_USER, password=PWD)
        self.exec_sql(f"CREATE DATABASE {extra_db}")
        self.exec_sql(f"DROP DATABASE {extra_db}")
        tdLog.info(f"  {CLOUD_USER} create/drop extra database OK")

        # cloud_sub_user cannot create a database
        self.login(CLOUD_SUB_USER, password=PWD)
        self.exec_sql_failed(
            "CREATE DATABASE cloud_fail_db",
            TSDB_CODE_PAR_PERMISSION_DENIED,
        )
        tdLog.info(f"  {CLOUD_SUB_USER} blocked from creating DB as expected")

        print("cloud_user CREATEDB privilege ......... [ passed ] ")

    # =========================================================================
    #  Test 3 – cloud_user basic DML on owned tables
    # =========================================================================

    def do_cloud_user_owned_dml(self):
        """
        As owner of cloud_db, cloud_user should be able to INSERT / SELECT /
        DELETE without any explicit GRANT.
        """
        tdLog.info("--- [Cloud] do_cloud_user_owned_dml ---")
        self.login(CLOUD_USER, password=PWD)

        # SELECT from supertable
        tdSql.query(f"SELECT COUNT(*) FROM {CLOUD_DB}.{CLOUD_STB}")
        tdSql.checkRows(1)

        # SELECT from child table
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_CHILD_TABLE}")
        tdSql.checkRows(10)

        # INSERT – use a fixed far-future timestamp so DELETE can match exactly
        _DML_TS = "'2099-01-01 00:00:00.000'"
        self.exec_sql(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_CHILD_TABLE}"
            f" VALUES ({_DML_TS}, 999, 'extra')"
        )

        # DELETE the row we just inserted
        self.exec_sql(
            f"DELETE FROM {CLOUD_DB}.{CLOUD_CHILD_TABLE}"
            f" WHERE ts = {_DML_TS}"
        )

        # Confirm the table is back to exactly 10 rows
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_CHILD_TABLE}")
        tdSql.checkRows(10)

        print("cloud_user owned DML .................. [ passed ] ")

    # =========================================================================
    #  Test 4 – CREATE/ALTER table privileges on cloud_db
    # =========================================================================

    def do_cloud_user_table_management(self):
        """cloud_user can create/alter/drop tables inside its own database."""
        tdLog.info("--- [Cloud] do_cloud_user_table_management ---")
        self.login(CLOUD_USER, password=PWD)

        # create a new normal table
        self.exec_sql(
            f"CREATE TABLE {CLOUD_DB}.cloud_temp_table"
            f" (ts TIMESTAMP, v1 INT, v2 FLOAT)"
        )

        # alter – add column
        self.exec_sql(
            f"ALTER TABLE {CLOUD_DB}.cloud_temp_table"
            f" ADD COLUMN v3 BIGINT"
        )

        # drop the table
        self.exec_sql(f"DROP TABLE {CLOUD_DB}.cloud_temp_table")

        # create / drop a child table via supertable
        self.exec_sql(
            f"CREATE TABLE {CLOUD_DB}.cloud_ct_new"
            f" USING {CLOUD_DB}.{CLOUD_STB}"
            f" TAGS ('region_b', 2)"
        )
        self.exec_sql(f"DROP TABLE {CLOUD_DB}.cloud_ct_new")

        print("cloud_user table management ........... [ passed ] ")

    # =========================================================================
    #  Test 5 – Database-level privilege management (grant to sub_user)
    # =========================================================================

    def do_db_privilege_to_sub_user(self):
        """
        root grants USE + SELECT + INSERT on cloud_db to cloud_sub_user,
        then verifies the permissions and revokes them.
        """
        tdLog.info("--- [Cloud] do_db_privilege_to_sub_user ---")
        self.login()  # root

        # grant
        self.grant_privilege("USE",    f"DATABASE {CLOUD_DB}", CLOUD_SUB_USER)
        self.grant_privilege("SELECT", f"{CLOUD_DB}.*",         CLOUD_SUB_USER)
        self.grant_privilege("INSERT", f"{CLOUD_DB}.*",         CLOUD_SUB_USER)

        # verify sub_user can USE the DB and SELECT
        self.login(CLOUD_SUB_USER, password=PWD)
        self.exec_sql(f"USE {CLOUD_DB}")
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_TABLE}")
        rows_before = tdSql.queryRows

        # sub_user can INSERT
        self.exec_sql(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE}"
            f" VALUES (NOW+1000s, 42)"
        )
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_TABLE}")
        tdSql.checkRows(rows_before + 1)

        # revoke INSERT and verify it no longer works
        self.login()
        self.revoke_privilege("INSERT", f"{CLOUD_DB}.*", CLOUD_SUB_USER)

        self.login(CLOUD_SUB_USER, password=PWD)
        self.exec_sql_failed(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE} VALUES (NOW+2000s, 99)",
            TSDB_CODE_PAR_PERMISSION_DENIED,
        )

        # revoke SELECT and USE
        self.login()
        self.revoke_privilege("SELECT", f"{CLOUD_DB}.*",         CLOUD_SUB_USER)
        self.revoke_privilege("USE",    f"DATABASE {CLOUD_DB}", CLOUD_SUB_USER)

        print("db-level privilege to sub_user ........ [ passed ] ")

    # =========================================================================
    #  Test 6 – Super-table level privilege management
    # =========================================================================

    def do_stable_privilege_to_sub_user(self):
        """
        Grant SELECT with tag-condition on the supertable to cloud_sub_user,
        verifying row-level filtering works correctly.
        """
        tdLog.info("--- [Cloud] do_stable_privilege_to_sub_user ---")
        self.login()

        # Prepare a second child table owned by cloud_user
        self.login(CLOUD_USER, password=PWD)
        try:
            self.exec_sql(
                f"CREATE TABLE {CLOUD_DB}.cloud_ct2"
                f" USING {CLOUD_DB}.{CLOUD_STB}"
                f" TAGS ('region_b', 2)"
            )
            self.exec_sql(
                f"INSERT INTO {CLOUD_DB}.cloud_ct2"
                f" VALUES (NOW, 55, 'ct2_data')"
            )
        except Exception:
            pass  # already exists from a previous run

        # Grant USE + restricted SELECT
        self.login()
        self.grant_privilege("USE",    f"DATABASE {CLOUD_DB}",    CLOUD_SUB_USER)
        # Allow sub_user to see only region_a rows
        self.grant_privilege(
            "SELECT", f"TABLE {CLOUD_DB}.{CLOUD_STB}",
            CLOUD_SUB_USER,
            with_condition="region='region_a'",
        )

        # sub_user can see region_a rows (cloud_ct1)
        self.login(CLOUD_SUB_USER, password=PWD)
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_CHILD_TABLE}")
        tdSql.checkRows(10)

        # sub_user sees 0 rows from cloud_ct2 (region_b)
        self.query_expect_rows(f"SELECT * FROM {CLOUD_DB}.cloud_ct2", 0)

        # full STB query returns only region_a rows
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_STB}")
        tdSql.checkRows(10)

        # revoke
        self.login()
        self.revoke_privilege(
            "SELECT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_SUB_USER
        )
        self.revoke_privilege("USE", f"DATABASE {CLOUD_DB}", CLOUD_SUB_USER)

        print("stable-level privilege to sub_user .... [ passed ] ")

    # =========================================================================
    #  Test 7 – TOPIC privilege management
    # =========================================================================

    def do_topic_privileges(self):
        """
        cloud_user creates a TOPIC; cloud_sub_user is granted SUBSCRIBE,
        successfully consumes data, then privilege is revoked and access fails.
        """
        tdLog.info("--- [Cloud] do_topic_privileges ---")

        # cloud_user creates a TOPIC   (needs SELECT on the source table)
        self.login()
        self.grant_privilege(
            "SELECT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_USER
        )
        # allow cloud_user to create a topic in the database
        self.grant_privilege(
            "CREATE TOPIC", f"DATABASE {CLOUD_DB}", CLOUD_USER
        )

        self.login(CLOUD_USER, password=PWD)
        try:
            tdSql.execute(f"DROP TOPIC IF EXISTS {CLOUD_TOPIC}")
        except Exception:
            pass
        tdSql.execute(
            f"CREATE TOPIC {CLOUD_TOPIC}"
            f" AS SELECT * FROM {CLOUD_DB}.{CLOUD_STB}"
        )
        tdLog.info(f"  {CLOUD_USER} created topic {CLOUD_TOPIC}")

        # cloud_sub_user has no SUBSCRIBE privilege yet → should fail
        self.subscribe_topic_failed(
            CLOUD_SUB_USER, PWD,
            "cloud_group1", CLOUD_TOPIC,
            TSDB_CODE_MND_NO_RIGHTS,
        )
        tdLog.info("  sub_user subscribe without privilege blocked OK")

        # root grants SUBSCRIBE
        self.login()
        self.grant_privilege(
            "SUBSCRIBE", f"TOPIC {CLOUD_DB}.{CLOUD_TOPIC}", CLOUD_SUB_USER
        )

        # sub_user can now subscribe using root credentials (BUG9 workaround)
        # cloud_stb has 10 rows (cloud_ct1, seeded in setup) +
        # 1 row (cloud_ct2, inserted in do_stable_privilege_to_sub_user) = 11
        consumer = self.subscribe_topic(
            "root", ROOT_PWD, "cloud_group1", CLOUD_TOPIC,
            expected_rows=11,
        )
        try:
            consumer.unsubscribe()
        except Exception:
            pass
        tdLog.info("  SUBSCRIBE privilege works OK (11 rows verified)")

        # Check SHOW TOPICS visibility (cloud_user can see own topic)
        self.login(CLOUD_USER, password=PWD)
        self.query_expect_rows("SHOW TOPICS", 1)

        # Revoke SUBSCRIBE and verify failure
        self.login()
        self.revoke_privilege(
            "SUBSCRIBE", f"TOPIC {CLOUD_DB}.{CLOUD_TOPIC}", CLOUD_SUB_USER
        )
        self.subscribe_topic_failed(
            CLOUD_SUB_USER, PWD,
            "cloud_group2", CLOUD_TOPIC,
            TSDB_CODE_MND_NO_RIGHTS,
        )
        tdLog.info("  SUBSCRIBE revocation works OK")

        # cloud_user can drop its own topic
        self.login(CLOUD_USER, password=PWD)
        tdSql.execute(f"DROP TOPIC IF EXISTS {CLOUD_TOPIC}")

        # clean up helper privileges granted to cloud_user by root
        self.login()
        try:
            self.revoke_privilege(
                "SELECT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_USER
            )
        except Exception:
            pass
        try:
            self.revoke_privilege(
                "CREATE TOPIC", f"DATABASE {CLOUD_DB}", CLOUD_USER
            )
        except Exception:
            pass

        print("TOPIC privilege management ............ [ passed ] ")

    # =========================================================================
    #  Test 8 – STREAM privilege management
    # =========================================================================

    def do_stream_privileges(self):
        """
        cloud_user creates a STREAM computing task.
        Verify SHOW STREAMS visibility and STOP/START/DROP privilege controls.
        """
        tdLog.info("--- [Cloud] do_stream_privileges ---")

        # cloud_user creates a stream inside cloud_db
        self.login(CLOUD_USER, password=PWD)
        try:
            tdSql.execute(
                f"DROP STREAM IF EXISTS {CLOUD_DB}.{CLOUD_STREAM}"
            )
        except Exception:
            pass

        stream_sql = (
            f"CREATE STREAM {CLOUD_DB}.{CLOUD_STREAM}"
            f" INTERVAL(1s) SLIDING(1s)"
            f" FROM {CLOUD_DB}.{CLOUD_STB}"
            f" INTO {CLOUD_DB}.cloud_stream_result"
            f" AS SELECT _twstart, COUNT(*) AS cnt FROM %%trows"
        )
        self.exec_sql(stream_sql)
        tdLog.info(f"  {CLOUD_USER} created stream {CLOUD_STREAM}")

        # cloud_user can see its own stream
        self.query_expect_rows(f"SHOW {CLOUD_DB}.STREAMS", 1)

        # cloud_sub_user has no SHOW privilege yet → sees 0
        self.login()
        self.grant_privilege("USE", f"DATABASE {CLOUD_DB}", CLOUD_SUB_USER)

        self.login(CLOUD_SUB_USER, password=PWD)
        '''BUG1
        self.query_expect_rows(f"SHOW {CLOUD_DB}.STREAMS", 0)
        '''

        # Grant SHOW privilege on stream to sub_user
        self.login()
        self.grant_privilege(
            "SHOW", f"STREAM {CLOUD_DB}.{CLOUD_STREAM}", CLOUD_SUB_USER
        )

        self.login(CLOUD_SUB_USER, password=PWD)
        self.query_expect_rows(f"SHOW {CLOUD_DB}.STREAMS", 1)
        tdLog.info("  sub_user SHOW STREAM privilege works OK")

        # sub_user has no STOP / START / DROP privilege
        self.exec_sql_failed(
            f"STOP STREAM {CLOUD_DB}.{CLOUD_STREAM}",
            TSDB_CODE_MND_NO_RIGHTS,
        )
        self.exec_sql_failed(
            f"DROP STREAM {CLOUD_DB}.{CLOUD_STREAM}",
            TSDB_CODE_MND_NO_RIGHTS,
        )

        # Grant STOP + DROP to sub_user
        self.login()
        self.grant_privilege(
            "STOP", f"STREAM {CLOUD_DB}.{CLOUD_STREAM}", CLOUD_SUB_USER
        )
        self.grant_privilege(
            "DROP", f"STREAM {CLOUD_DB}.{CLOUD_STREAM}", CLOUD_SUB_USER
        )

        # sub_user can now stop and drop
        self.login(CLOUD_SUB_USER, password=PWD)
        self.exec_sql(f"STOP STREAM {CLOUD_DB}.{CLOUD_STREAM}")
        self.exec_sql(f"DROP STREAM {CLOUD_DB}.{CLOUD_STREAM}")
        tdLog.info("  sub_user STOP/DROP STREAM privilege works OK")

        # clean up
        self.login()
        self.revoke_privilege(
            "USE", f"DATABASE {CLOUD_DB}", CLOUD_SUB_USER
        )
        try:
            self.revoke_privilege(
                "SHOW", f"STREAM {CLOUD_DB}.{CLOUD_STREAM}", CLOUD_SUB_USER
            )
        except Exception:
            pass
        try:
            self.revoke_privilege(
                "STOP", f"STREAM {CLOUD_DB}.{CLOUD_STREAM}", CLOUD_SUB_USER
            )
            self.revoke_privilege(
                "DROP", f"STREAM {CLOUD_DB}.{CLOUD_STREAM}", CLOUD_SUB_USER
            )
        except Exception:
            pass

        # recreate stream for subsequent tests if needed
        self.login(CLOUD_USER, password=PWD)
        try:
            tdSql.execute(
                f"DROP TABLE IF EXISTS {CLOUD_DB}.cloud_stream_result"
            )
        except Exception:
            pass

        print("STREAM privilege management ........... [ passed ] ")

    # =========================================================================
    #  Test 9 – information_schema correctness (taosx compatibility)
    # =========================================================================

    def do_information_schema(self):
        """
        With SYSINFO=0, cloud_user has limited visibility into
        information_schema.  Root grants READ INFORMATION_SCHEMA BASIC so that
        taosx-style queries work correctly.
        """
        tdLog.info("--- [Cloud] do_information_schema ---")

        # --- 9a: without extra privilege, cloud_user (SYSINFO=0) cannot read
        #         information_schema tables that require privilege.
        # (Exact behaviour depends on implementation; we at least verify the
        #  queries run without crashing after the privilege is granted.)

        # root grants READ INFORMATION_SCHEMA BASIC to cloud_user
        self.login()
        self.grant_privilege("READ INFORMATION_SCHEMA BASIC",      None, TEST_USER)
        self.grant_privilege("READ INFORMATION_SCHEMA PRIVILEGED", None, TEST_USER)
        self.grant_privilege("READ INFORMATION_SCHEMA SECURITY",   None, TEST_USER)
        self.grant_privilege("READ PERFORMANCE_SCHEMA BASIC",      None, TEST_USER)
        self.grant_privilege("READ PERFORMANCE_SCHEMA BASIC",      None, TEST_USER)

        self.login(TEST_USER, password=PWD)

        # taosx-common queries
        self.exec_sql("SELECT * FROM information_schema.ins_databases")
        self.exec_sql("SELECT * FROM information_schema.ins_stables")
        self.exec_sql("SELECT * FROM information_schema.ins_tables")
        self.exec_sql("SELECT * FROM information_schema.ins_columns")
        tdLog.info("  information_schema queries OK after BASIC + PRIVILEGED grant")

        # revoke privileges
        self.login()
        self.revoke_privilege("READ INFORMATION_SCHEMA BASIC",      None, TEST_USER)
        self.revoke_privilege("READ INFORMATION_SCHEMA PRIVILEGED", None, TEST_USER)
        self.revoke_privilege("READ INFORMATION_SCHEMA SECURITY",   None, TEST_USER)
        self.revoke_privilege("READ PERFORMANCE_SCHEMA BASIC",      None, TEST_USER)

        print("information_schema access ............. [ passed ] ")

    # =========================================================================
    #  Test 10 – taosx data subscription (consume with cloud_user)
    # =========================================================================

    def do_taosx_data_subscription(self):
        """
        Simulate the taosx subscription pattern:
          - root creates a TOPIC for full cloud_db.cloud_stb
          - root grants SUBSCRIBE to cloud_user
          - cloud_user (acting as taosx) subscribes and polls rows
          - Verify the polled rows match what was inserted
        """
        tdLog.info("--- [Cloud] do_taosx_data_subscription ---")

        taosx_topic  = "taosx_cloud_topic"
        taosx_group  = "taosx_cloud_group"

        # root creates topic
        self.login()
        try:
            tdSql.execute(f"DROP TOPIC IF EXISTS {taosx_topic}")
        except Exception:
            pass
        tdSql.execute(
            f"CREATE TOPIC {taosx_topic}"
            f" AS SELECT * FROM {CLOUD_DB}.{CLOUD_STB}"
        )

        # grant SUBSCRIBE to cloud_user
        self.grant_privilege(
            "SUBSCRIBE", f"TOPIC {CLOUD_DB}.{taosx_topic}", CLOUD_USER
        )

        # consume with root to avoid BUG9 (cloud_user subscribe blocked)
        # cloud_stb still has 11 rows at this point (10 in ct1 + 1 in ct2)
        consumer = self.subscribe_topic(
            "root", ROOT_PWD, taosx_group, taosx_topic,
            expected_rows=11,
        )
        try:
            consumer.unsubscribe()
        except Exception:
            pass
        tdLog.info("  taosx-style subscription consumed 11 rows as expected")

        # revoke and cleanup
        self.login()
        self.revoke_privilege(
            "SUBSCRIBE", f"TOPIC {CLOUD_DB}.{taosx_topic}", CLOUD_USER
        )
        tdSql.execute(f"DROP TOPIC IF EXISTS {taosx_topic}")

        print("taosx data subscription ............... [ passed ] ")

    # =========================================================================
    #  Test 11 – taosx read queries on owned data
    # =========================================================================

    def do_taosx_query_correctness(self):
        """
        Simulate common taosx read queries executed as cloud_user:
          - COUNT, AVG, and windowed aggregate on the supertable.
          - information_schema metadata queries for schema discovery.
        """
        tdLog.info("--- [Cloud] do_taosx_query_correctness ---")

        self.login(CLOUD_USER, password=PWD)

        # aggregate COUNT
        tdSql.query(f"SELECT COUNT(*) FROM {CLOUD_DB}.{CLOUD_STB}")
        tdSql.checkRows(1)
        total = tdSql.queryResult[0][0]
        assert total >= 10, f"expected ≥10 rows, got {total}"

        # LAST value
        tdSql.query(
            f"SELECT LAST(val) FROM {CLOUD_DB}.{CLOUD_STB}"
        )
        tdSql.checkRows(1)

        # Select with table name filtering
        tdSql.query(
            f"SELECT COUNT(*) FROM {CLOUD_DB}.{CLOUD_STB}"
            f" WHERE region='region_a'"
        )
        tdSql.checkRows(1)

        # taosx schema-discovery: list all sub-tables
        tdSql.query(
            f"SELECT table_name, stable_name"
            f" FROM information_schema.ins_tables"
            f" WHERE db_name='{CLOUD_DB}'"
            f" AND stable_name='{CLOUD_STB}'"
        )
        assert tdSql.queryRows >= 1, "no sub-tables found via ins_tables"

        # taosx column-discovery
        tdSql.query(
            f"SELECT col_name, col_type"
            f" FROM information_schema.ins_columns"
            f" WHERE db_name='{CLOUD_DB}'"
            f" AND table_name='{CLOUD_STB}'"
        )
        assert tdSql.queryRows >= 3, "expected ≥3 columns (ts, val, payload)"

        print("taosx query correctness ............... [ passed ] ")

    # =========================================================================
    #  Test 12 – SHOW DATABASES / SHOW TABLES visibility
    # =========================================================================

    def do_cloud_user_show_visibility(self):
        """
        cloud_user with SYSINFO=0 must still be able to SHOW databases /
        tables that it owns.
        """
        tdLog.info("--- [Cloud] do_cloud_user_show_visibility ---")
        self.login(CLOUD_USER, password=PWD)

        # SHOW DATABASES – cloud_db must be visible
        tdSql.query("SHOW DATABASES")
        db_names = [row[0] for row in tdSql.queryResult]
        assert CLOUD_DB in db_names, \
            f"{CLOUD_DB} not visible in SHOW DATABASES for {CLOUD_USER}"

        # SHOW STABLES
        tdSql.query(f"SHOW {CLOUD_DB}.STABLES")
        stb_names = [row[0] for row in tdSql.queryResult]
        assert CLOUD_STB in stb_names, \
            f"{CLOUD_STB} not visible in SHOW STABLES"

        # SHOW TABLES
        tdSql.query(f"SHOW {CLOUD_DB}.TABLES")
        assert tdSql.queryRows >= 2, \
            f"expected ≥2 tables in SHOW TABLES for {CLOUD_DB}"

        # SYSINFO=0 means no SHOW DNODES / MNODES
        self.exec_sql_failed("SHOW DNODES", TSDB_CODE_PAR_PERMISSION_DENIED)
        self.exec_sql_failed("SHOW MNODES", TSDB_CODE_PAR_PERMISSION_DENIED)

        print("cloud_user SHOW visibility ............ [ passed ] ")

    # =========================================================================
    #  Test 13 – Multi-user privilege delegation via root
    # =========================================================================

    def do_multi_user_privilege_delegation(self):
        """
        root grants cloud_sub_user SELECT + INSERT on cloud_stb (the
        same table owned by cloud_user).  Verify sub_user can read/write,
        and that revoking SELECT prevents further reads.
        """
        tdLog.info("--- [Cloud] do_multi_user_privilege_delegation ---")
        self.login()

        # grant
        self.grant_privilege("USE",    f"DATABASE {CLOUD_DB}", CLOUD_SUB_USER)
        self.grant_privilege("SELECT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_SUB_USER)
        self.grant_privilege("INSERT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_SUB_USER)

        self.login(CLOUD_SUB_USER, password=PWD)

        # SELECT
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_STB}")
        assert tdSql.queryRows >= 10

        # INSERT via child table – use a fixed far-future timestamp
        _SUB_TS = "'2099-06-01 00:00:00.000'"
        self.exec_sql(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_CHILD_TABLE}"
            f" VALUES ({_SUB_TS}, 77, 'sub_insert')"
        )

        # DELETE is not granted – should fail (same timestamp as above)
        self.exec_sql_failed(
            f"DELETE FROM {CLOUD_DB}.{CLOUD_CHILD_TABLE} WHERE ts={_SUB_TS}",
            TSDB_CODE_PAR_PERMISSION_DENIED,
        )

        # revoke SELECT
        self.login()
        self.revoke_privilege(
            "SELECT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_SUB_USER
        )

        self.login(CLOUD_SUB_USER, password=PWD)
        self.exec_sql_failed(
            f"SELECT * FROM {CLOUD_DB}.{CLOUD_STB}",
            TSDB_CODE_PAR_PERMISSION_DENIED,
        )

        # clean up
        self.login()
        self.revoke_privilege("INSERT", f"TABLE {CLOUD_DB}.{CLOUD_STB}", CLOUD_SUB_USER)
        self.revoke_privilege("USE",    f"DATABASE {CLOUD_DB}",           CLOUD_SUB_USER)

        # clean inserted row
        self.login(CLOUD_USER, password=PWD)
        try:
            self.exec_sql(
                f"DELETE FROM {CLOUD_DB}.{CLOUD_CHILD_TABLE} WHERE ts='2099-06-01 00:00:00.000'"
            )
        except Exception:
            pass

        print("multi-user privilege delegation ....... [ passed ] ")


    # =========================================================================
    #  Legacy L1 – Database access authorization (3.3.x.y READ/WRITE syntax)
    # =========================================================================

    def do_legacy_privilege_verification(self):
        self.login(CLOUD_USER, password=PWD)
        # sysinfo 0 
        self.exec_sql_failed(f"show dnodes", TSDB_CODE_PAR_PERMISSION_DENIED)
        self.exec_sql_failed(f"show users", TSDB_CODE_PAR_PERMISSION_DENIED)
        self.exec_sql_failed(f"show vnodes", TSDB_CODE_PAR_PERMISSION_DENIED)
        self.exec_sql_failed(f"show mnodes", TSDB_CODE_PAR_PERMISSION_DENIED)
        self.exec_sql_failed(f"select * from information_schema.ins_dnodes", TSDB_CODE_PAR_PERMISSION_DENIED)
        # create db 1
        self.create_database("test")
        self.create_stable("test", "stb")
        self.create_child_table("test", "t1", "stb")
        self.insert_data("test", "t1")
        self.query_expect_rows(f"select * from test.t1", 1)
        
        # topic create - subscribe 
        legacy_topic = "legacy_topic1"
        self.login(CLOUD_USER, password=PWD)
        try:
            tdSql.execute(f"DROP TOPIC IF EXISTS {legacy_topic}")
        except Exception:
            pass
        tdSql.execute(
            f"CREATE TOPIC {legacy_topic}"
            f" AS SELECT * FROM {CLOUD_DB}.{CLOUD_STB}"
        )
        tdLog.info(f"  {CLOUD_USER} created topic {legacy_topic}")

        consumer = self.subscribe_topic(
            CLOUD_USER, PWD, "group1", legacy_topic,
            expected_rows=10,
        )
        consumer.unsubscribe()
        
        print("\nlegacy user privilege verify .......... [ passed ] ")
        

    def do_legacy_db_access_authorization(self):
        """
        In 3.3.x.y-, database access was controlled with:
            GRANT READ  ON dbname.* TO user_name
            GRANT WRITE ON dbname.* TO user_name
            REVOKE READ  ON dbname.* FROM user_name
            REVOKE WRITE ON dbname.* FROM user_name
            GRANT ALL   ON dbname.* TO user_name

        All of the above must remain fully functional in 3.4.0.0+
        (backward compatibility requirement).  This test verifies:
          - GRANT READ  grants SELECT access; REVOKE READ removes it
          - GRANT WRITE grants INSERT access; REVOKE WRITE removes it
          - GRANT ALL   ON dbname.* grants full read+write access
          - priv_level dbname.tbname (table-level READ/WRITE) also works
          - Wildcard scope *.* READ/WRITE also works
        """
        tdLog.info("--- [Legacy] do_legacy_db_access_authorization ---")

        # ---- L1a: GRANT READ grants SELECT; REVOKE READ removes it ----
        self.login()  # root
        self.grant_privilege("READ", f"{CLOUD_DB}.*", TEST_USER)
        tdLog.info("  GRANT READ succeeded")

        self.login(TEST_USER, password=PWD)
        # READ privilege enables SELECT
        tdSql.query(f"SELECT COUNT(*) FROM {CLOUD_DB}.{CLOUD_STB}")
        tdSql.checkRows(1)
        # READ does NOT grant INSERT
        self.exec_sql_failed(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE} VALUES (NOW+8100s, 11)",
            TSDB_CODE_PAR_PERMISSION_DENIED
        )

        self.login()  # root
        self.revoke_privilege("READ", f"{CLOUD_DB}.*", TEST_USER)
        tdLog.info("  REVOKE READ succeeded")

        # ---- L1b: GRANT WRITE grants INSERT; REVOKE WRITE removes it ----
        self.grant_privilege("WRITE", f"{CLOUD_DB}.*", TEST_USER)
        tdLog.info("  GRANT WRITE succeeded")

        self.login(TEST_USER, password=PWD)
        self.exec_sql(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE} VALUES (NOW+8200s, 22)"
        )
        tdLog.info("  INSERT allowed after GRANT WRITE")

        self.login()  # root
        self.revoke_privilege("WRITE", f"{CLOUD_DB}.*", TEST_USER)
        self.login(TEST_USER, password=PWD)
        self.exec_sql_failed(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE} VALUES (NOW+8300s, 33)",
            TSDB_CODE_PAR_PERMISSION_DENIED,
        )
        tdLog.info("  INSERT blocked after REVOKE WRITE")

        # ---- L1c: GRANT ALL ON dbname.* grants full read+write ----
        self.login()  # root
        self.grant_privilege("ALL", f"{CLOUD_DB}.*", TEST_USER)
        tdLog.info("  GRANT ALL ON dbname.* succeeded")

        self.login(TEST_USER, password=PWD)
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_TABLE}")
        assert tdSql.queryRows >= 1
        self.exec_sql(
            f"INSERT INTO {CLOUD_DB}.{CLOUD_TABLE} VALUES (NOW+8400s, 44)"
        )
        tdLog.info("  SELECT and INSERT both work after GRANT ALL")

        self.login()  # root
        self.revoke_privilege("ALL", f"{CLOUD_DB}.*", TEST_USER)
        tdLog.info("  REVOKE ALL succeeded")

        # ---- L1d: priv_level dbname.tbname (table-level READ/WRITE) ----
        self.grant_privilege("READ", f"{CLOUD_DB}.{CLOUD_STB}", TEST_USER)
        self.login(TEST_USER, password=PWD)
        tdSql.query(f"SELECT * FROM {CLOUD_DB}.{CLOUD_STB}")
        assert tdSql.queryRows >= 1
        tdLog.info("  Table-level GRANT READ works")

        self.login()  # root
        self.revoke_privilege("READ", f"{CLOUD_DB}.{CLOUD_STB}", TEST_USER)
        tdLog.info("  Table-level REVOKE READ works")

        # ---- L1e: wildcard scope *.* READ/WRITE ----
        self.grant_privilege("READ", "*.*", TEST_USER)
        self.login(TEST_USER, password=PWD)
        tdSql.query(f"SELECT COUNT(*) FROM {CLOUD_DB}.{CLOUD_STB}")
        tdSql.checkRows(1)
        tdLog.info("  Wildcard GRANT READ ON *.* works")

        self.login()  # root
        self.revoke_privilege("READ", "*.*", TEST_USER)
        tdLog.info("  Wildcard REVOKE READ ON *.* works")

        print("legacy db access authorization ........ [ passed ] ")

    # =========================================================================
    #  Main entry point
    # =========================================================================

    def test_user_cloud(self):
        """
        Cloud service user compatibility tests.

        Creates a single cloud_user with sysinfo=0 and createdb=1 and drives
        all sub-tests without per-test teardown/setup cycles.

        Test coverage:

          Legacy (3.3.x.y- compatibility, cloud_user only):
            1. GRANT/REVOKE READ/WRITE/ALL on dbname.* and dbname.tbname
            2. Verify SELECT/INSERT permissions from READ/WRITE grants

          New version (3.4.0.0+):
          1. Cloud user basic attributes verification
          2. Createdb=1 allows DB creation; sub_user is blocked
          3. Owner DML on cloud_db (INSERT / SELECT / DELETE)
          4. Table management (CREATE / ALTER / DROP)
          5. Database-level privilege management (grant/revoke to sub_user)
          6. Super-table level privilege with row-level filtering
          7. TOPIC privilege management (CREATE / SUBSCRIBE / DROP)
          8. STREAM privilege management (CREATE / SHOW / STOP / DROP)
          9. information_schema access for taosx-style metadata queries
         10. taosx data subscription pattern
         11. taosx read query correctness (aggregates, schema discovery)
         12. SHOW DATABASES / STABLES / TABLES visibility with SYSINFO=0
         13. Multi-user privilege delegation via root

        Since: v3.4.0.0

        Labels: common,ci,user,cloud

        Jira: None

        History:
            - 2026-03-02  Auto-generated by GitHub Copilot
        """

        # setup
        self._setup_env()

        # ------ Test 3.3.x.y compatible (legacy) ------
        #self.do_legacy_privilege_verification()
        #self.do_legacy_db_access_authorization()

        # ----- Test New version -------
        self.do_cloud_user_attributes()
        self.do_cloud_user_createdb()
        self.do_cloud_user_owned_dml()
        self.do_cloud_user_table_management()
        self.do_db_privilege_to_sub_user()
        self.do_stable_privilege_to_sub_user()
        self.do_topic_privileges()
        self.do_stream_privileges()
        self.do_information_schema()
        self.do_taosx_data_subscription()
        self.do_taosx_query_correctness()
        self.do_cloud_user_show_visibility()
        self.do_multi_user_privilege_delegation()
        # teardown
        self._teardown_env()
