{
 "title": "TDengineDashboardDemo",
 "tags": [ "demo" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory used percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "sql": "select last_row(value) from telegraf.mem where field=\"used_percent\""
    }
   ]
  },
  {
   "title": "MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MEMUSED-PERCENT",
     "sql": "select avg(value) from telegraf.mem where field=\"used_percent\" interval(1m)"
    }
   ]
  },
  {
   "title": "CPU-USED",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "CPU-SYS",
     "sql": "select last_row(value) from telegraf.cpu where field=\"usage_system\""
    },
    {
     "alias": "CPU-IDLE",
     "sql": "select last_row(value) from telegraf.cpu where field=\"usage_idle\""
    },
    {
     "alias": "CPU-USER",
     "sql": "select last_row(value) from telegraf.cpu where field=\"usage_user\""
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "General CPU monitor",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU-USER",
     "sql": "select avg(value) from telegraf.cpu where field=\"usage_user\" and cpu=\"cpu-total\" interval(1m)"
    },
    {
     "alias": "CPU-SYS",
     "sql": "select avg(value) from telegraf.cpu where field=\"usage_system\" and cpu=\"cpu-total\" interval(1m)"
    },
    {
     "alias": "CPU-IDLE",
     "sql": "select avg(value) from telegraf.cpu where field=\"usage_idle\" and cpu=\"cpu-total\" interval(1m)"
    }
   ]
  }
 ]
}