CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

IF (TD_CLUSTER)
#  ADD_SUBDIRECTORY(dnodeCluster)
#  ADD_SUBDIRECTORY(dnodeGrant)
#  ADD_SUBDIRECTORY(httpAdmin)
  ADD_SUBDIRECTORY(acct)
#  ADD_SUBDIRECTORY(mnodeBalance)
#  ADD_SUBDIRECTORY(mnodeCluster)
#  ADD_SUBDIRECTORY(sdbReplica)
#  ADD_SUBDIRECTORY(multilevelStorage)
#  ADD_SUBDIRECTORY(vnodeCluster)
#  ADD_SUBDIRECTORY(vnodeReplica)
ENDIF()