[package]
name = "taoslog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
tracing-actix-web = { version = "*" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "std"] }
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
parking_lot.workspace = true
snafu.workspace = true
flate2.workspace = true
thread-id = "4.2.2"
regex = "1"
sysinfo = { version = "0.31.4", default-features = false, features = ["disk"] }
flume.workspace = true
arrow-schema.workspace = true
http.workspace = true
nu-ansi-term = { version = "0.50.1", optional = true }
rayon.workspace = true

[dev-dependencies]
crossbeam.workspace = true
log.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["log"] }
tracing-log = "0.2.0"
criterion = { version = "0.5", features = ["html_reports"] }

[features]
ansi = ["dep:nu-ansi-term"]

[[bench]]
name = "log_write_benchmark"
harness = false
