from:
  fromhost: mqtt://{0}
  topics: ["ems/site/site_1/root/allowed_max_p/data",
            "ems/site/site_1/meter/meter_1/hz/data",
            "ems/site/site_1/unit/unit_1/root/run_mode/data",
            "ems/site/site_1/unit/unit_1/pcs/pcs_1/status/data"]
