#plugins_home = "/usr/local/taos/plugins"
#data_dir = "/var/lib/taos/taosx"
#logs_home = "/var/log/taos"
#log_level = "info"
#log_keep_days = 30
#jobs = 0
#otel = false

[serve]
#listen = "0.0.0.0:6050"
#database_url = "sqlite:taosx.db"