select now();
insert into test.d0 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d0.csv';
insert into test.d1 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d1.csv';
insert into test.d2 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d2.csv';
insert into test.d3 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d3.csv';
insert into test.d4 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d4.csv';
insert into test.d5 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d5.csv';
insert into test.d6 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d6.csv';
insert into test.d7 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d7.csv';
insert into test.d8 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d8.csv';
insert into test.d9 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d9.csv';
insert into test.d50 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d50.csv';
insert into test.d51 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d51.csv';
insert into test.d52 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d52.csv';
insert into test.d53 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d53.csv';
insert into test.d54 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d54.csv';
insert into test.d55 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d55.csv';
insert into test.d56 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d56.csv';
insert into test.d57 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d57.csv';
insert into test.d58 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d58.csv';
insert into test.d59 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/0/d59.csv';
select now();