select now();
insert into test.d40 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d40.csv';
insert into test.d41 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d41.csv';
insert into test.d42 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d42.csv';
insert into test.d43 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d43.csv';
insert into test.d44 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d44.csv';
insert into test.d45 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d45.csv';
insert into test.d46 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d46.csv';
insert into test.d47 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d47.csv';
insert into test.d48 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d48.csv';
insert into test.d49 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d49.csv';
insert into test.d90 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d90.csv';
insert into test.d91 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d91.csv';
insert into test.d92 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d92.csv';
insert into test.d93 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d93.csv';
insert into test.d94 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d94.csv';
insert into test.d95 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d95.csv';
insert into test.d96 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d96.csv';
insert into test.d97 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d97.csv';
insert into test.d98 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d98.csv';
insert into test.d99 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/4/d99.csv';
select now();