select now();
insert into test.d20 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d20.csv';
insert into test.d21 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d21.csv';
insert into test.d22 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d22.csv';
insert into test.d23 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d23.csv';
insert into test.d24 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d24.csv';
insert into test.d25 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d25.csv';
insert into test.d26 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d26.csv';
insert into test.d27 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d27.csv';
insert into test.d28 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d28.csv';
insert into test.d29 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d29.csv';
insert into test.d70 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d70.csv';
insert into test.d71 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d71.csv';
insert into test.d72 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d72.csv';
insert into test.d73 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d73.csv';
insert into test.d74 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d74.csv';
insert into test.d75 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d75.csv';
insert into test.d76 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d76.csv';
insert into test.d77 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d77.csv';
insert into test.d78 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d78.csv';
insert into test.d79 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/2/d79.csv';
select now();