select now();
insert into test.d30 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d30.csv';
insert into test.d31 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d31.csv';
insert into test.d32 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d32.csv';
insert into test.d33 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d33.csv';
insert into test.d34 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d34.csv';
insert into test.d35 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d35.csv';
insert into test.d36 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d36.csv';
insert into test.d37 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d37.csv';
insert into test.d38 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d38.csv';
insert into test.d39 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d39.csv';
insert into test.d80 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d80.csv';
insert into test.d81 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d81.csv';
insert into test.d82 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d82.csv';
insert into test.d83 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d83.csv';
insert into test.d84 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d84.csv';
insert into test.d85 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d85.csv';
insert into test.d86 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d86.csv';
insert into test.d87 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d87.csv';
insert into test.d88 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d88.csv';
insert into test.d89 file '/data4/guoxy/td_iotdb/tdengine/csv/tdout/3/d89.csv';
select now();