/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_datax_plugin_writer_JniConnection */

#ifndef _Included_com_alibaba_datax_plugin_writer_JniConnection
#define _Included_com_alibaba_datax_plugin_writer_JniConnection
#ifdef __cplusplus
extern "C" {
#endif
#undef com_alibaba_datax_plugin_writer_JniConnection_JNI_NULL_POINTER
#define com_alibaba_datax_plugin_writer_JniConnection_JNI_NULL_POINTER 0LL
#undef com_alibaba_datax_plugin_writer_JniConnection_JNI_SUCCESSFUL
#define com_alibaba_datax_plugin_writer_JniConnection_JNI_SUCCESSFUL 0L
/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    initImp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_initImp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    setOptions
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_setOptions
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    connectImp
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_connectImp
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    getErrCodeImp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_getErrCodeImp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    getErrMsgImp
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_getErrMsgImp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    freeResultSetImp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_freeResultSetImp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    closeConnectionImp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_closeConnectionImp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alibaba_datax_plugin_writer_JniConnection
 * Method:    insertOpentsdbJson
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_datax_plugin_writer_JniConnection_insertOpentsdbJson
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
