! Configuration File for keepalived

global_defs {
   router_id bbb
}

vrrp_script chk_nginx {
    script "killall -0 nginx"
#    script "/home/zz/opt/etc/keepalived/check_nginx.sh"
    interval 2
    weight -5
    fall 3
    rise 2
}

vrrp_instance VI_2 {
    state BACKUP
    interface enp0s8
    mcast_src_ip 192.168.1.242
    virtual_router_id 51
    priority 99
    advert_int 2
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.1.150
    }
    track_script {
       chk_nginx
    }
}

