CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

IF ((TD_LINUX_64) OR (TD_LINUX_32 AND TD_ARM))
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/inc)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/dnode/inc)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/mnode/detail/inc)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/mnode/sdb/inc)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/vnode/detail/inc)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/client/inc)
  INCLUDE_DIRECTORIES(${TD_OS_DIR}/inc)
  INCLUDE_DIRECTORIES(inc)
  INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/src/modules/multilevel_storage/inc)
  AUX_SOURCE_DIRECTORY(src SRC)
  ADD_LIBRARY(mreplica ${SRC})
  TARGET_LINK_LIBRARIES(mreplica trpc tutil pthread)
ENDIF ()