use db1;

select 1 in (select 1 from st1) from st1;
select 1 not in (select 1 from v1) from st1;
select 1 in (select 1 from st1) a from st1;
select 1 not in (select 1 from v1) a from st1;
select distinct 1 in (select 1 from st1) from st1;
select distinct 1 not in (select 1 from v1) from st1;
select distinct 1 in (select 1 from st1), f1 from st1;
select distinct 1 not in (select 1 from v1), f1 from st1;
select distinct tags 1 in (select 1 from st1) + 1 from st1;
select distinct tags 1 not in (select 1 from v1) + 1 from st1;
select 1 in (select 1 from st1), 1 in (select 1 from st1) from st1;
select 1 not in (select 1 from v1), 1 not in (select 1 from v1) from st1;
select abs(1 in (select 1 from st1)) from st1;
select abs(1 not in (select 1 from v1)) from st1;
select abs(1 in (select 1 from st1) + 1) from st1;
select abs(1 not in (select 1 from v1) + 1) from st1;
select sum(1 in (select 1 from st1)) from st1;
select sum(1 not in (select 1 from v1)) from st1;
select case when 1 in (select 1 from st1) > 0 then 1 else 2 end, sum(f1) from st1 group by f1;
select case when 1 not in (select 1 from v1) > 0 then 1 else 2 end, sum(f1) from st1 group by f1;
select case when 1 = 1 then 2 / 1 in (select 1 from st1) else 2 end, sum(f1) from st1 group by f1;
select case when 1 = 1 then 2 / 1 not in (select 1 from v1) else 2 end, sum(f1) from st1 group by f1;
select case when 0 = 1 then 1 else 1 in (select 1 from st1) is null end, sum(f1) from st1 group by f1;
select case when 0 = 1 then 1 else 1 not in (select 1 from v1) is null end, sum(f1) from st1 group by f1;
select 1 in (select 1 from st1) from information_schema.ins_tables limit 3;
select 1 not in (select 1 from v1) from information_schema.ins_tables limit 3;
select 1 in (select 1 from st1) from vtb1;
select 1 not in (select 1 from v1) from vtb1;
select a.ts from st1 a join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select b.ts from st1 a left join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select b.ts from st1 a left join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a right join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a right join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a full join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a full join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select b.ts from st1 a left semi join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select b.ts from st1 a left semi join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a right semi join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a right semi join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select b.ts from st1 a left anti join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select b.ts from st1 a left anti join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a right anti join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a right anti join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select b.ts from st1 a left asof join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select b.ts from st1 a left asof join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a right asof join st1 b on a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a right asof join st1 b on a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select b.ts from st1 a left asof join st1 b on a.ts = b.ts jlimit 1 in (select 1 from st1) order by 1;
select b.ts from st1 a left asof join st1 b on a.ts = b.ts jlimit 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a right asof join st1 b on a.ts = b.ts jlimit 1 in (select 1 from st1) order by 1;
select a.ts from st1 a right asof join st1 b on a.ts = b.ts jlimit 1 not in (select 1 from v1) order by 1;
select b.ts from st1 a left window join st1 b on 1 in (select 1 from st1) window_offset(-1d, 1d) order by 1;
select b.ts from st1 a left window join st1 b on 1 not in (select 1 from v1) window_offset(-1d, 1d) order by 1;
select a.ts from st1 a right window join st1 b on 1 in (select 1 from st1) window_offset(-1d, 1d) order by 1;
select a.ts from st1 a right window join st1 b on 1 not in (select 1 from v1) window_offset(-1d, 1d) order by 1;
select b.ts from st1 a left window join st1 b window_offset(-1d, 1d) jlimit 1 in (select 1 from st1) order by 1;
select b.ts from st1 a left window join st1 b window_offset(-1d, 1d) jlimit 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a right window join st1 b window_offset(-1d, 1d) jlimit 1 in (select 1 from st1) order by 1;
select a.ts from st1 a right window join st1 b window_offset(-1d, 1d) jlimit 1 not in (select 1 from v1) order by 1;
select a.ts from st1 a , st1 b where a.ts = b.ts and 1 in (select 1 from st1) order by 1;
select a.ts from st1 a , st1 b where a.ts = b.ts and 1 not in (select 1 from v1) order by 1;
select f1 from st1 where 1 in (select 1 from st1) order by 1;
select f1 from st1 where 1 not in (select 1 from v1) order by 1;
select f1 from st1 where 1 in (select 1 from st1) is null order by 1;
select f1 from st1 where 1 not in (select 1 from v1) is null order by 1;
select f1 from st1 where 1 in (select 1 from st1) is not null order by 1;
select f1 from st1 where 1 not in (select 1 from v1) is not null order by 1;
select f1 from st1 where abs(1 in (select 1 from st1)) > 0 order by 1;
select f1 from st1 where abs(1 not in (select 1 from v1)) > 0 order by 1;
select f1 from st1 where f1 > (1 in (select 1 from st1)) order by 1;
select f1 from st1 where f1 > (1 not in (select 1 from v1)) order by 1;
select f1 from st1 where f1 between 1 in (select 1 from st1) and 1 in (select 1 from st1) + 1 order by 1;
select f1 from st1 where f1 between 1 not in (select 1 from v1) and 1 not in (select 1 from v1) + 1 order by 1;
select f1 from st1 where tg1 in (select f1 from st1) order by 1;
select f1 from st1 where tg1 in (select f1 from st1) order by 1;
select f1 from st1 where tbname = cast(1 in (select 1 from st1) as varchar) order by 1;
select f1 from st1 where tbname = cast(1 not in (select 1 from v1) as varchar) order by 1;
select f1 from st1 where ts in (select first(ts) from st1) and 1 in (select 1 from st1) order by 1;
select f1 from st1 where ts in (select first(ts) from st1) and 1 not in (select 1 from v1) order by 1;
select table_name from information_schema.ins_tables where 1 in (select 1 from st1) order by 1 limit 3;
select table_name from information_schema.ins_tables where 1 not in (select 1 from v1) order by 1 limit 3;
select * from information_schema.ins_tables where db_name = cast(1 in (select 1 from st1) as varchar) order by 1 limit 3;
select * from information_schema.ins_tables where db_name = cast(1 not in (select 1 from v1) as varchar) order by 1 limit 3;
select * from vtb1 where 1 in (select 1 from st1) order by 1;
select * from vtb1 where 1 not in (select 1 from v1) order by 1;
select count(*) from st1 where tbname in (select tags tbname from st1 where tg1 > 2);
select count(*) from st1 where tbname in (select tags tbname from st1 where tg1 > 2);
select f1 from st1 partition by 1 in (select 1 from st1) order by 1;
select f1 from st1 partition by 1 not in (select 1 from v1) order by 1;
select f1 from st1 partition by 1 in (select 1 from st1) + 1 order by 1;
select f1 from st1 partition by 1 not in (select 1 from v1) + 1 order by 1;
select f1 from st1 partition by tbname, 1 in (select 1 from st1) order by 1;
select f1 from st1 partition by tbname, 1 not in (select 1 from v1) order by 1;
select avg(f1) from st1 INTERVAL(1 in (select 1 from st1));
select avg(f1) from st1 INTERVAL(1 not in (select 1 from v1));
select avg(f1) from st1 INTERVAL(1 in (select 1 from st1)d);
select avg(f1) from st1 INTERVAL(1 not in (select 1 from v1)d);
select avg(f1) from st1 INTERVAL(1d, 1 in (select 1 from st1));
select avg(f1) from st1 INTERVAL(1d, 1 not in (select 1 from v1));
select avg(f1) from st1 INTERVAL(1d, 1 in (select 1 from st1)d);
select avg(f1) from st1 INTERVAL(1d, 1 not in (select 1 from v1)d);
select avg(f1) from st1 INTERVAL(1d) FILL(1 in (select 1 from st1));
select avg(f1) from st1 INTERVAL(1d) FILL(1 not in (select 1 from v1));
select avg(f1) from st1 where ts >= '2025-12-01 00:00:00.000' and ts <= '2025-12-05 00:00:00.000' INTERVAL(1d) FILL(value, 1 in (select 1 from st1));
select avg(f1) from st1 where ts >= '2025-12-01 00:00:00.000' and ts <= '2025-12-05 00:00:00.000' INTERVAL(1d) FILL(value, 1 not in (select 1 from v1));
select avg(f1) from st1 INTERVAL(1d) SLIDING(1 in (select 1 from st1));
select avg(f1) from st1 INTERVAL(1d) SLIDING(1 not in (select 1 from v1));
select avg(f1) from st1 INTERVAL(1d) SLIDING(1 in (select 1 from st1)h);
select avg(f1) from st1 INTERVAL(1d) SLIDING(1 not in (select 1 from v1)h);
select avg(f1) from st1 SESSION(ts, 1 in (select 1 from st1));
select avg(f1) from st1 SESSION(ts, 1 not in (select 1 from v1));
select avg(f1) from st1 SESSION(ts, 1 in (select 1 from st1)h);
select avg(f1) from st1 SESSION(ts, 1 not in (select 1 from v1)h);
select avg(f1) from st1 SESSION(1 in (select 1 from st1), 1d);
select avg(f1) from st1 SESSION(1 not in (select 1 from v1), 1d);
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(1 in (select 1 from st1));
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(1 not in (select 1 from v1));
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(f1, 1 in (select 1 from st1));
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(f1, 1 not in (select 1 from v1));
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(f1) TRUE_FOR(1 in (select 1 from st1));
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(f1) TRUE_FOR(1 not in (select 1 from v1));
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(f1) TRUE_FOR(1 in (select 1 from st1)d);
select avg(f1) from st1 where tbname = 'tb1' STATE_WINDOW(f1) TRUE_FOR(1 not in (select 1 from v1)d);
select avg(f1) from st1 where tbname = 'tb1' EVENT_WINDOW START WITH f1 >= 1 in (select 1 from st1) END WITH f1 <= 1 in (select 1 from st1) + 1;
select avg(f1) from st1 where tbname = 'tb1' EVENT_WINDOW START WITH f1 >= 1 not in (select 1 from v1) END WITH f1 <= 1 not in (select 1 from v1) + 1;
select avg(f1) from st1 COUNT_WINDOW(1 in (select 1 from st1));
select avg(f1) from st1 COUNT_WINDOW(1 not in (select 1 from v1));
select avg(f1) from st1 COUNT_WINDOW(1 in (select 1 from st1), 1 in (select 1 from st1));
select avg(f1) from st1 COUNT_WINDOW(1 not in (select 1 from v1), 1 not in (select 1 from v1));
select avg(f1) from st1 COUNT_WINDOW(3, 1, 1 in (select 1 from st1));
select avg(f1) from st1 COUNT_WINDOW(3, 1, 1 not in (select 1 from v1));
select avg(f1) from st1 group by 1 in (select 1 from st1);
select avg(f1) from st1 group by 1 not in (select 1 from v1);
select avg(f1) from st1 group by f1, 1 in (select 1 from st1);
select avg(f1) from st1 group by f1, 1 not in (select 1 from v1);
select avg(f1) from st1 group by 1 in (select 1 from st1) + 1;
select avg(f1) from st1 group by 1 not in (select 1 from v1) + 1;
select avg(f1) from st1 group by f1 having avg(1 in (select 1 from st1)) > 0;
select avg(f1) from st1 group by f1 having avg(1 not in (select 1 from v1)) > 0;
select avg(f1) from st1 group by f1 having 1 in (select 1 from st1);
select avg(f1) from st1 group by f1 having 1 not in (select 1 from v1);
select interp(f1) from st1 range(1 in (select 1 from st1)) FILL(PREV);
select interp(f1) from st1 range(1 not in (select 1 from v1)) FILL(PREV);
select interp(f1) from st1 range(1 in (select 1 from st1), 1 in (select 1 from st1)) every(1d);
select interp(f1) from st1 range(1 not in (select 1 from v1), 1 not in (select 1 from v1)) every(1d);
select interp(f1) from st1 range(now - 1d, now, 1 in (select 1 from st1)) every(1d);
select interp(f1) from st1 range(now - 1d, now, 1 not in (select 1 from v1)) every(1d);
select interp(f1) from st1 range(now - 1d, now) every(1 in (select 1 from st1));
select interp(f1) from st1 range(now - 1d, now) every(1 not in (select 1 from v1));
select interp(f1) from st1 range(now - 1d, now) every(1 in (select 1 from st1)m);
select interp(f1) from st1 range(now - 1d, now) every(1 not in (select 1 from v1)m);
select interp(f1) from st1 range(now - 1d, now) every(1h) fill(1 in (select 1 from st1));
select interp(f1) from st1 range(now - 1d, now) every(1h) fill(1 not in (select 1 from v1));
select interp(f1) from st1 range(now - 1d, now) every(1h) fill(value, 1 in (select 1 from st1));
select interp(f1) from st1 range(now - 1d, now) every(1h) fill(value, 1 not in (select 1 from v1));
select f1 from tb1 order by 1 in (select 1 from st1);
select f1 from tb1 order by 1 not in (select 1 from v1);
select f1 from tb1 order by 1 in (select 1 from st1) desc;
select f1 from tb1 order by 1 not in (select 1 from v1) desc;
select f1 from tb1 order by f1 + 1 in (select 1 from st1);
select f1 from tb1 order by f1 + 1 not in (select 1 from v1);
select f1 from st1 order by f1, 1 in (select 1 from st1);
select f1 from st1 order by f1, 1 not in (select 1 from v1);
select f1 from tb1 order by abs(1 in (select 1 from st1));
select f1 from tb1 order by abs(1 not in (select 1 from v1));
select avg(f1) from tb1 order by sum(1 in (select 1 from st1));
select avg(f1) from tb1 order by sum(1 not in (select 1 from v1));
select f1 from st1 limit 1 in (select 1 from st1);
select f1 from st1 limit 1 not in (select 1 from v1);
select f1 from st1 limit 1 offset 1 in (select 1 from st1);
select f1 from st1 limit 1 offset 1 not in (select 1 from v1);
select f1 from st1 partition by tbname slimit 1 in (select 1 from st1);
select f1 from st1 partition by tbname slimit 1 not in (select 1 from v1);
select f1 from st1 partition by tbname slimit 1 soffset 1 in (select 1 from st1);
select f1 from st1 partition by tbname slimit 1 soffset 1 not in (select 1 from v1);
select f1 from st1 where f1 > 1 in (select 1 from st1) union select f1 from st1 order by f1;
select f1 from st1 where f1 > 1 not in (select 1 from v1) union select f1 from st1 order by f1;
select f1 from st1 union all select 1 in (select 1 from st1) from st1 order by f1;
select f1 from st1 union all select 1 not in (select 1 from v1) from st1 order by f1;
select f1 from tb1 union select f1 from tb1 order by 1 in (select 1 from st1);
select f1 from tb1 union select f1 from tb1 order by 1 not in (select 1 from v1);
select f1 from tb1 union all select f1 from tb1 limit 1 in (select 1 from st1);
select f1 from tb1 union all select f1 from tb1 limit 1 not in (select 1 from v1);
explain select f1 from st1 where 1 in (select 1 from st1)\G;
explain select f1 from st1 where 1 not in (select 1 from v1)\G;
explain verbose true select f1 from st1 where 1 in (select 1 from st1)\G;
explain verbose true select f1 from st1 where 1 not in (select 1 from v1)\G;
explain analyze select f1 from st1 where 1 in (select 1 from st1)\G;
explain analyze select f1 from st1 where 1 not in (select 1 from v1)\G;
explain analyze verbose true select f1 from st1 where 1 in (select 1 from st1)\G;
explain analyze verbose true select f1 from st1 where 1 not in (select 1 from v1)\G;
explain select avg(f1), 1 in (select 1 from st1) from st1 group by f1 having 1 in (select 1 from st1)\G;
explain select avg(f1), 1 not in (select 1 from v1) from st1 group by f1 having 1 not in (select 1 from v1)\G;
explain verbose true select avg(f1), 1 in (select 1 from st1) from st1 group by f1 having 1 in (select 1 from st1)\G;
explain verbose true select avg(f1), 1 not in (select 1 from v1) from st1 group by f1 having 1 not in (select 1 from v1)\G;
explain analyze select avg(f1), 1 in (select 1 from st1) from st1 group by f1 having 1 in (select 1 from st1)\G;
explain analyze select avg(f1), 1 not in (select 1 from v1) from st1 group by f1 having 1 not in (select 1 from v1)\G;
explain analyze verbose true select avg(f1), 1 in (select 1 from st1) from st1 group by f1 having 1 in (select 1 from st1)\G;
explain analyze verbose true select avg(f1), 1 not in (select 1 from v1) from st1 group by f1 having 1 not in (select 1 from v1)\G;
select f1 from st1 where f1 in (select * from v1) order by 1;
select f1 from st1 where f1 in (select * from v1) order by 1;
select f1 from v2 where 1 in (select 1 from st1) order by 1;
select f1 from v2 where 1 not in (select 1 from v1) order by 1;
select f1 from v3 where 1 in (select 1 from st1) order by 1;
select f1 from v3 where 1 not in (select 1 from v1) order by 1;
select f1 from v4 where 1 in (select 1 from st1) order by 1;
select f1 from v4 where 1 not in (select 1 from v1) order by 1;
insert into tbb select now, 1 in (select 1 from st1) from tb1;
insert into tbb select now, 1 not in (select 1 from v1) from tb1;
select f1 from st1 where ts >= (select last(_c0) from st1) and ts <= (select last(_c0) from st1) order by 1;
select f1 from st1 where ts >= (select first(_c0) from st1) and ts <= (select last(_c0) from st1) order by 1;
select f1 from st1 where _c0 between (select last(_c0) from st1) and (select last(_c0) from st1) order by 1;
select f1 from st1 where _c0 between (select first(_c0) from st1) and (select last(_c0) from st1) order by 1;
create stream stm1 interval(1d) sliding(1d) from tb1 partition by 1 in (select 1 from tb3) into out1 as select * from tb3;
create stream stm1 interval(1d) sliding(1d) from tb1 into out2 as select ts, 1 in (select 1 from tb3) from tb3;
create topic topic1 as select 1 in (select 1 from tb3) from tb3;
insert into tb1 values(now, 1 in (select 1 from tb3), 1);
alter table tb1 set tag tg1 = 1 in (select 1 from tb3);
