<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TDengine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--    <Nullable>enable</Nullable>-->
    <TargetFrameworks>net5;net6;net7;net8;net9;net46;netcoreapp3.1</TargetFrameworks>
    <NoWarn>NETSDK1138</NoWarn>
  </PropertyGroup>

</Project>
