#!/usr/bin/env bash
set -euo pipefail

GITHUB_ENV="${GITHUB_ENV:?GITHUB_ENV is required}"
PORT_6060="${PORT_6060:?PORT_6060 is required}"
PORT_6041="${PORT_6041:?PORT_6041 is required}"

echo "Writing common integration test variables to GITHUB_ENV"
cat >> "$GITHUB_ENV" <<EOF
INTEGRATION_TEST_TAOSX_API_BASE_URL=http://localhost:${PORT_6060}/api/x/
INTEGRATION_TEST_TAOSX_API_USERNAME=root
INTEGRATION_TEST_TAOSX_API_PASSWORD=taosdata
INTEGRATION_TEST_HOST_TARGET_DSN=taos+ws://localhost:${PORT_6041}/integration_test
INTEGRATION_TEST_CONTAINER_TARGET_DSN=taos+ws://localhost:6041/integration_test
INTEGRATION_TEST_AGENT_NAME=integration_test_agent

EOF

echo "Writing datasource-specific integration test variables to GITHUB_ENV"
cat >> "$GITHUB_ENV" <<EOF
INTEGRATION_TEST_MQTT_HOST=192.168.1.45
INTEGRATION_TEST_MQTT_PORT=1883
INTEGRATION_TEST_MQTT_AUTH_PORT=1884
INTEGRATION_TEST_MQTT_TLS_PORT=8884
INTEGRATION_TEST_MQTT_USERNAME=taosx
INTEGRATION_TEST_MQTT_PASSWORD=taosx

INTEGRATION_TEST_KAFKA_BROKER=192.168.1.45:19092

INTEGRATION_TEST_OPCUA_HOST=192.168.0.34
INTEGRATION_TEST_OPCUA_PORT=53530
INTEGRATION_TEST_OPCUA_SUBJECT=OPCUA/SimulationServer
EOF

echo "Configured integration test environment variables in GITHUB_ENV"
