CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/client/inc)
INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/deps/libcurl/include)

IF (TD_LINUX)         
  AUX_SOURCE_DIRECTORY(. SRC)
  ADD_EXECUTABLE(lowa ${SRC})
  
  find_program(HAVE_CURL NAMES curl)   
  IF (HAVE_CURL)    
    ADD_DEFINITIONS(-DTD_LOWA_CURL)
    LINK_DIRECTORIES(${TD_ENTERPRISE_DIR}/deps/libcurl/lib)
    ADD_LIBRARY(curl STATIC IMPORTED)
    SET_PROPERTY(TARGET curl PROPERTY IMPORTED_LOCATION ${TD_ENTERPRISE_DIR}/deps/libcurl/lib/libcurl.a)
    TARGET_LINK_LIBRARIES(lowa curl) 
  ENDIF ()
  
  IF (TD_SOMODE_STATIC)
    TARGET_LINK_LIBRARIES(lowa taos_static cJson)
  ELSE ()
    TARGET_LINK_LIBRARIES(lowa taos cJson)
  ENDIF ()
ENDIF ()
