CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/client/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/plugins/http/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/deps/zlib-1.2.11/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/deps/cJson/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/deps/lz4/inc)
INCLUDE_DIRECTORIES(inc)
AUX_SOURCE_DIRECTORY(src SRC)
  
IF (TD_LINUX OR TD_WINDOWS)
  ADD_LIBRARY(admin ${SRC})
  TARGET_LINK_LIBRARIES(admin z)

  AUX_SOURCE_DIRECTORY(src/backup SRC)
  ADD_EXECUTABLE(httpMain ${SRC})
  TARGET_LINK_LIBRARIES(httpMain mnode monitor http tsdb twal vnode cJson lz4 taos_static)
ENDIF ()
