[package]
name = "taosx-core"
version = { workspace = true }
edition = "2021"
homepage = "https://taosdata.com"
publish = false
description = "taosX - TDengine data integration tool"

[dependencies]
anyhow = "1"
chrono = { workspace = true }
chrono-tz = { workspace = true }

arrow = { workspace = true }
arrow-schema = { workspace = true, features = ["serde"] }
arrow-flight = { workspace = true }
faststr = { workspace = true }
parquet = { workspace = true }
rayon = { workspace = true }
tonic = { workspace = true, features = ["gzip"] }
zerocopy = { workspace = true }

dlopen2 = "0.7.0"

regex = { workspace = true }

arrow-cast-guess-precision = "0.4.0"
arrow-compute-ext = { workspace = true }
ring-channel = "0.12"

async-compression = { version = "*", features = ["all"] }
async-trait = "0.1"
bytes = "1"
bitflags = "2"
rhai = { version = "1.18.0", features = ["sync"] }
rhai-dylib = { version = "0.3.0", features = ["sync"] }
paste = "1"
half = "2.3"
humantime = "2.1"

clap = { workspace = true, features = ["default", "derive"] }
config = "0.13.2"
convert_case = "0.6.0"
csv-async = { version = "1.2.4", features = ["tokio"] }
dashmap = "5.4.0"
flate2 = { version = "1.0" }
futures = { version = "0.3", features = ["thread-pool"] }
itertools = { workspace = true }
lazy_static = "1.4"
linked-hash-map = { version = "0.5.6", features = ["serde_impl"] }
log = "0.4"
parse_duration = "2.1"
scc = "2.0.16"
semver = { version = "1.0.22" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
sha2 = "0.10"
thiserror = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "io-std",
    "net",
    "time",
    "process",
    "macros",
    "sync",
    "signal",
    "fs",
] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = "0.1.14"
tokio-process-terminate = { version = "0.3" }
toml = "0.8.5"
zstd = "0.13.0"
either = "1.8"
serde_regex = "1"
tinytemplate = "1.2.1"
serde_json_path = "0.6.0"
csv_lib = { version = "1.2", package = "csv" }
glob = "0.3.1"
notify = "6.1.1"
futures-ext = { path = "../crates/futures-ext" }

file-rotate = "0.7.5"
ringbuf = { version = "0.3.3" }
deadpool = "0.10"

actix-cors = "0.6.4"
actix-web = "4"
serde_json = { version = "1.0", features = ["raw_value", "preserve_order"] }
utoipa = { version = "4.0.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["actix-web"] }

cfg-if = "1.0.0"
const_format = "0.2.30"
metrics = { workspace = true }

async-backtrace = "0.2.2"
dotenv = "0.15.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3.17"
tracing-core = { version = "0.1.32", features = [] }

flume = "0.11.0"
futures-util = "0.3.30"
serde_with = "3.3"
tokio-cron-scheduler = "0.9.4"

bitvec = "1"
tempfile = "3"

reqwest = "0.11.15"
taosx-ipc = { path = "../taosx-ipc" }

taos = { workspace = true }
shadow-rs = { workspace = true }

md5 = "0.7.0"
kafka = "0.10.0"
rand = "0.8"
base64 = "0.21.2"
tiberius = { version = "0.12.2", default-features = false, features = [
    "chrono",
    "tds73",
    "time",
    "winauth",
    "bigdecimal",
] }

sled = "0.34.7"
socket2 = "0.5.5"
sysinfo = { workspace = true }
chardetng = "0.1.17"
encoding_rs = "0.8.33"

sqlx = { version = "0.7.4", features = [
    "mysql",
    "runtime-tokio",
    "chrono",
    "bigdecimal",
    "tls-rustls",
] }
bigdecimal = "0.3.0"
bit-vec = "0.6.3"
uuid = "1.4.0"
sqlx-postgres = { version = "0.7.4", features = [
    "chrono",
    "bigdecimal",
    "bit-vec",
] }
oracle = { version = "0.5", features = ["chrono"] }
rumqttc = "0.24.0"
rustls-pemfile = "2"
rustls-native-certs = "0.7"

mongodb = { version = "3.0.0", features = [
    "aws-auth",
    "zstd-compression",
    "zlib-compression",
    "snappy-compression",
    "openssl-tls"
] }

#rdkafka = { version = "0.36.2", features = ["dynamic-linking"] }
rdkafka = { version = "0.36.2", features = ["cmake-build", "ssl", "tracing"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi"] }
openssl = "0.10.55"

[target.'cfg(not(windows))'.dependencies]
rdkafka = { version = "0.36.2", features = ["cmake-build", "ssl", "gssapi-vendored"] }
#rdkafka = { version = "0.36.2", features = ["dynamic-linking"] }


[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(all(unix, not(target_arch = "loongarch64")))'.dependencies]
openssl = { version = "0.10.55", features = ["vendored"] }
#openssl = { version = "0.10.55" }

[target.'cfg(target_arch="loongarch64")'.dependencies]
openssl = { version = "0.10.55" }

[features]
default = ["optin", "native-tls"]
optin = ["taos/optin"]
rustls = ["taos/ws-rustls"]
native-tls = ["taos/ws-native-tls"]
disable-enterprise-only-validation = []
disable-enterprise-connector-validation = []

[build-dependencies]
dotenv = "0.15.0"
shadow-rs = { workspace = true }


[dev-dependencies]
pretty_env_logger = "0.5.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

shadow-rs = { workspace = true }
