[package]
name = "taosx-core"
version = "0.5.0"
edition = "2021"
homepage = "https://taosdata.com"
publish = false
description = "taosX - TDengine data integration tool"

[dependencies]
anyhow = "1"

arrow = { workspace = true }
arrow-flight = { workspace = true }
parquet = { workspace = true }
tonic = { workspace = true }

async-compression = { version = "*", features = ["all"] }
async-trait = "0.1"
bytes = "1"
bitflags = "1"
chrono = "0.4"
clap = { version = "4.0.11", features = ["default", "derive"] }
clap-verbosity-flag = "2.0.0"
config = "0.13.2"
convert_case = "0.6.0"
csv-async = { version = "1.2.4", features = ["tokio"] }
dashmap = "5.4.0"
futures = "0.3"
itertools = "0.10.4"
lazy_static = "1.4"
linked-hash-map = { version = "0.5.6", features = ["serde_impl"] }
log = "0.4"
parse_duration = "2.1"
pretty_env_logger = "0.4"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
sha2 = "0.10"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
tokio-stream = "*"
toml = "0.7.2"
zstd = "0.12.1"
either = "1.8"
serde_regex = "1"
chrono-tz = "0.8"
tinytemplate = "1.2.1"
serde_json_path = "0.6.0"

file-rotate = "0.7.5"

actix-cors = "0.6.4"
actix-web = "4"
serde_json = { version = "1.0", features = ["raw_value"] }
# utoipa = { version = "3", features = ["actix_extras", "chrono"] }
# utoipa-swagger-ui = { version = "3.0.2", features = ["actix-web"] }

# lru = "0.7.5"
cfg-if = "1.0.0"
const_format = "0.2.30"
metrics = "0.20.1"
metrics-exporter-prometheus = { version = "0.11.0", default-features = false, features = ["push-gateway"] }
# palaver = "0.2.8"
sysinfo = "0.28.0"

async-backtrace = "0.2.2"
dotenv = "0.15.0"
tracing = "0.1"

flume = "0.10"
futures-util = "0.3"
r2d2 = "0.8.10"
serde_with = "2.3.1"
tokio-cron-scheduler = "0.9.4"

bitvec = "1"
socket2 = "0.5"
tempfile = "3"

reqwest = "0.11.15"
taosx-ipc = { path = "../taosx-ipc" }

taos = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = ["optin", "rustls"]
optin = ["taos/optin"]
sys = ["taos/native"]
rustls = ["taos/ws-rustls"]
native-tls = ["taos/ws-native-tls"]
disable-enterprise-only-validation = []
disable-enterprise-connector-validation = []

[build-dependencies]
dotenv = "0.15.0"
