[package]
name = "taos-sys"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
serde = { version = "1", features = ["derive"], optional = true }
serde_repr = { version = "0.1.7", optional = true }
taos-error = { path = "../taos-error" }
taos-macros = { path = "../taos-macros" }

[build-dependencies]
dotenv = "0.15.0"
libloading = "0.7.3"

[features]
default = ["backport"]
backport = []
serde1 = ["serde", "serde_repr"]
