; TDGPT Windows Installer Script
; Generated by win_release.py

#define MyAppName "TDGPT"
#define MyAppPublisher "taosdata"
#define MyAppURL "http://www.taosdata.com/"
#define MyAppVersion "{{VERSION}}"
#define MyAppInstallName "{{PACKAGE_NAME}}"
#define MyProductFullName "TDGPT - TDengine Analytics Node"
#define MyAppInstallDir "C:\TDengine\taosanode"
#define MyAppSourceDir "{{SOURCE_DIR}}"
#define MyAppIco "{{ICON_FILE}}"

[Setup]
AppId={{a77a678d-8806-48a5-8017-1d55749b6895}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={#MyAppInstallDir}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir={{OUTPUT_DIR}}
OutputBaseFilename={#MyAppInstallName}
SetupIconFile={#MyAppIco}
UninstallDisplayIcon={#MyAppIco}
Compression=lzma
SolidCompression=yes
CloseApplications=force
DisableDirPage=yes
Uninstallable=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SetupLogging=yes

[Languages]
Name: "chinesesimp"; MessagesFile: "compiler:Default.isl"

[Files]
; Configuration files
Source: "{#MyAppSourceDir}\cfg\*"; DestDir: "{app}\cfg"; Flags: ignoreversion recursesubdirs createallsubdirs onlyifdoesntexist uninsneveruninstall

; Library files (Python)
Source: "{#MyAppSourceDir}\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs

; Resource files
Source: "{#MyAppSourceDir}\resource\*"; DestDir: "{app}\resource"; Flags: ignoreversion recursesubdirs createallsubdirs

; Model files (required for production)
Source: "{#MyAppSourceDir}\model\*"; DestDir: "{app}\model"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

; Requirements files
Source: "{#MyAppSourceDir}\requirements*.txt"; DestDir: "{app}"; Flags: ignoreversion

; Service management scripts
Source: "{#MyAppSourceDir}\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\install.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\uninstall.bat"; DestDir: "{app}"; Flags: ignoreversion

[Dirs]
Name: "{app}\log"; Permissions: everyone-modify
Name: "{app}\model"; Permissions: everyone-modify
Name: "{app}\data"; Permissions: everyone-modify
Name: "{app}\data\pids"; Permissions: everyone-modify
Name: "{app}\venv"; Permissions: everyone-modify
Name: "{app}\timesfm_venv"; Permissions: everyone-modify
Name: "{app}\moirai_venv"; Permissions: everyone-modify
Name: "{app}\chronos_venv"; Permissions: everyone-modify
Name: "{app}\momentfm_venv"; Permissions: everyone-modify

[Run]
; Run install script after installation with user-selected flags
Filename: "{app}\install.bat"; Parameters: "{code:GetInstallFlags}"; Description: "Run installation script"; Flags: postinstall runascurrentuser waituntilidle

[UninstallRun]
; Run uninstall script before uninstallation
Filename: "{app}\uninstall.bat"; Flags: runhidden

[UninstallDelete]
; Only delete log files during uninstall
; Preserve: cfg, model, data, venv (consistent with Linux behavior)
Name: "{app}\log"; Type: filesandordirs

[Icons]
Name: "{group}\Start Taosanode"; Filename: "{app}\bin\start-taosanode.bat"
Name: "{group}\Stop Taosanode"; Filename: "{app}\bin\stop-taosanode.bat"
Name: "{group}\Status Taosanode"; Filename: "{app}\bin\status-taosanode.bat"
Name: "{group}\Log Viewer"; Filename: "{app}\bin\log-viewer.bat"; Comment: "View TDGPT logs"
Name: "{group}\Configuration Wizard"; Filename: "{app}\bin\config-wizard.bat"; Comment: "Configure TDGPT settings"
Name: "{group}\Check for Updates"; Filename: "{app}\bin\check-update.bat"; Comment: "Check for new versions"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Start Taosanode"; Filename: "{app}\bin\start-taosanode.bat"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Registry]
; Add to PATH environment variable
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\bin"; \
    Check: NeedsAddPath('{app}\bin')

[Code]
var
  InstallModePage: TInputOptionWizardPage;
  ModelSelectionPage: TInputOptionWizardPage;
  IsOnlineMode: Boolean;
  InstallAllModels: Boolean;

function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;

function DirExists(const Dir: string): Boolean;
begin
  Result := DirectoryExists(Dir);
end;

procedure InitializeWizard();
begin
  // Create custom page for installation mode selection
  InstallModePage := CreateInputOptionPage(wpSelectDir,
    'Installation Mode', 'Select installation options',
    'Choose how you want to install TDGPT:',
    True, False);

  // Add installation mode options
  InstallModePage.Add('Online Mode (Recommended)');
  InstallModePage.Add('Offline Mode');

  // Set default to Online Mode
  InstallModePage.Values[0] := True;

  // Create another page for model selection
  ModelSelectionPage := CreateInputOptionPage(InstallModePage.ID,
    'Model Selection', 'Select which models to install',
    'Choose the models you want to install:',
    True, False);

  // Add model selection options
  ModelSelectionPage.Add('Install required models only (tdtsfm, timemoe)');
  ModelSelectionPage.Add('Install all models (includes chronos, timesfm, moirai, moment)');

  // Set default to required models only
  ModelSelectionPage.Values[0] := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  // Save user selections when leaving the installation mode page
  if CurPageID = InstallModePage.ID then
  begin
    IsOnlineMode := InstallModePage.Values[0];
  end;

  // Save user selections when leaving the model selection page
  if CurPageID = ModelSelectionPage.ID then
  begin
    InstallAllModels := ModelSelectionPage.Values[1];
  end;
end;

function GetInstallFlags(Param: String): String;
begin
  Result := '';

  // Add offline flag if offline mode is selected
  if not IsOnlineMode then
    Result := Result + '-o ';

  // Add all models flag if selected
  if InstallAllModels then
    Result := Result + '-a ';

  // Trim trailing space
  Result := Trim(Result);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  case CurUninstallStep of
    usPostUninstall:
      begin
        // Clean up any remaining files
        if FileExists(ExpandConstant('{app}\taosanode.pid')) then
          DeleteFile(ExpandConstant('{app}\taosanode.pid'));
      end;
  end;
end;
