; TDGPT Windows Installer Script
; Generated by win_release.py

#define MyAppName "TDGPT"
#define MyAppPublisher "taosdata"
#define MyAppURL "http://www.taosdata.com/"
#define MyAppVersion "{{VERSION}}"
#define MyAppInstallName "{{PACKAGE_NAME}}"
#define MyProductFullName "TDGPT - TDengine Analytics Node"
#define MyAppInstallDir "C:\TDengine\taosanode"
#define MyAppSourceDir "{{SOURCE_DIR}}"

[Setup]
AppId={{A0F7A93C-79C4-485D-B2B8-F0D03DF42FAB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={#MyAppInstallDir}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir={{OUTPUT_DIR}}
OutputBaseFilename={#MyAppInstallName}
Compression=lzma
SolidCompression=yes
CloseApplications=force
DisableDirPage=yes
Uninstallable=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SetupLogging=yes

[Languages]
Name: "chinesesimp"; MessagesFile: "compiler:Default.isl"

[Files]
; Configuration files
Source: "{#MyAppSourceDir}\cfg\*"; DestDir: "{app}\cfg"; Flags: ignoreversion recursesubdirs createallsubdirs onlyifdoesntexist uninsneveruninstall

; Library files (Python)
Source: "{#MyAppSourceDir}\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs

; Resource files
Source: "{#MyAppSourceDir}\resource\*"; DestDir: "{app}\resource"; Flags: ignoreversion recursesubdirs createallsubdirs

; Model files (required for production)
Source: "{#MyAppSourceDir}\model\*"; DestDir: "{app}\model"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

; Requirements files
Source: "{#MyAppSourceDir}\requirements*.txt"; DestDir: "{app}"; Flags: ignoreversion

; Service management scripts
Source: "{#MyAppSourceDir}\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\install.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\uninstall.bat"; DestDir: "{app}"; Flags: ignoreversion

[Dirs]
Name: "{app}\log"; Permissions: everyone-modify
Name: "{app}\model"; Permissions: everyone-modify
Name: "{app}\data"; Permissions: everyone-modify
Name: "{app}\data\pids"; Permissions: everyone-modify

[Run]
; Run install script after installation
Filename: "{app}\install.bat"; Description: "Run installation script"; Flags: postinstall runascurrentuser waituntilidle

[UninstallRun]
; Run uninstall script before uninstallation
Filename: "{app}\uninstall.bat"; Flags: runhidden

[UninstallDelete]
Name: "{app}\log"; Type: filesandordirs
Name: "{app}\data"; Type: filesandordirs
Name: "{app}\venv"; Type: filesandordirs

[Icons]
Name: "{group}\Start Taosanode"; Filename: "{app}\bin\start-taosanode.bat"
Name: "{group}\Stop Taosanode"; Filename: "{app}\bin\stop-taosanode.bat"
Name: "{group}\Status Taosanode"; Filename: "{app}\bin\status-taosanode.bat"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Start Taosanode"; Filename: "{app}\bin\start-taosanode.bat"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Registry]
; Add to PATH environment variable
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\bin"; \
    Check: NeedsAddPath('{app}\bin')

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE,
    'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
    'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;

function DirExists(const Dir: string): Boolean;
begin
  Result := DirectoryExists(Dir);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  case CurUninstallStep of
    usPostUninstall:
      begin
        // Clean up any remaining files
        if FileExists(ExpandConstant('{app}\taosanode.pid')) then
          DeleteFile(ExpandConstant('{app}\taosanode.pid'));
      end;
  end;
end;
