; TDGPT Windows Installer Script
; Generated by win_release.py

#define MyAppName "{{APP_NAME}}"
#define MyAppPublisher "taosdata"
#define MyAppURL "http://www.taosdata.com/"
#define MyAppVersion "{{VERSION}}"
#define MyAppInstallName "{{PACKAGE_NAME}}"
#define MyProductFullName "{{PRODUCT_FULL_NAME}}"
#define MyAppInstallDir "C:\TDengine\taosanode"
#define MyAppSourceDir "{{SOURCE_DIR}}"
#define MyAppIco "{{ICON_FILE}}"
#define DefaultResourcePackageUrl "{{RESOURCE_PACKAGE_URL}}"
#define MinVCRuntimeMajor 14
#define MinVCRuntimeMinor 44
#define MinVCRuntimeBuild 0
#define MinVCRuntimeRbld 0

[Setup]
AppId={{a77a678d-8806-48a5-8017-1d55749b6895}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={#MyAppInstallDir}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir={{OUTPUT_DIR}}
OutputBaseFilename={#MyAppInstallName}
SetupIconFile={#MyAppIco}
UninstallDisplayIcon={#MyAppIco}
Compression=lzma
SolidCompression=yes
CloseApplications=no
DisableDirPage=yes
Uninstallable=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SetupLogging=yes
ExtraDiskSpaceRequired=21474836480

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#MyAppSourceDir}\cfg\*"; DestDir: "{app}\cfg"; Flags: ignoreversion recursesubdirs createallsubdirs onlyifdoesntexist uninsneveruninstall
Source: "{#MyAppSourceDir}\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyAppSourceDir}\resource\*"; DestDir: "{app}\resource"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyAppSourceDir}\model\*"; DestDir: "{app}\model"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist
Source: "{#MyAppSourceDir}\requirements\*"; DestDir: "{app}\requirements"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyAppSourceDir}\python\*"; DestDir: "{app}\python"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyAppSourceDir}\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\install.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\install.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\uninstall.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppSourceDir}\uninstall.py"; DestDir: "{app}"; Flags: ignoreversion

[Dirs]
Name: "{app}\cfg"; Permissions: everyone-modify; Flags: uninsneveruninstall
Name: "{app}\log"; Permissions: everyone-modify; Flags: uninsneveruninstall
Name: "{app}\model"; Permissions: everyone-modify; Flags: uninsneveruninstall
Name: "{app}\data"; Permissions: everyone-modify; Flags: uninsneveruninstall
Name: "{app}\data\pids"; Permissions: everyone-modify; Flags: uninsneveruninstall

[Run]
Filename: "notepad.exe"; Parameters: """{app}\log\install.log"""; Description: "View the installation log now (clear this checkbox to skip opening it)"; Flags: postinstall nowait skipifsilent

[UninstallRun]
Filename: "{cmd}"; Parameters: "/C call ""{app}\uninstall.bat"" & exit /b 0"; Flags: runhidden waituntilterminated

[Icons]
Name: "{group}\Start Taosanode"; Filename: "{app}\bin\start-taosanode.bat"
Name: "{group}\Stop Taosanode"; Filename: "{app}\bin\stop-taosanode.bat"
Name: "{group}\Status Taosanode"; Filename: "{app}\bin\status-taosanode.bat"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Start Taosanode"; Filename: "{app}\bin\start-taosanode.bat"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Registry]
Root: HKLM; Subkey: "Software\taosdata\TDgpt"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletevalue uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\taosdata\TDgpt"; ValueType: string; ValueName: "Version"; ValueData: "{#MyAppVersion}"; Flags: uninsdeletevalue uninsdeletekeyifempty

[Code]
const
  InstallMetadataKey = 'Software\taosdata\TDgpt';
  ServiceRegistryKey = 'SYSTEM\CurrentControlSet\Services\Taosanode';

var
  InstallModePage: TInputOptionWizardPage;
  PipSourcePage: TInputOptionWizardPage;
  CustomPipPage: TInputQueryWizardPage;
  PythonOptionsPage: TInputOptionWizardPage;
  ModelSourcePage: TInputOptionWizardPage;
  ModelSelectionPage: TInputOptionWizardPage;
  ModelMirrorPage: TInputOptionWizardPage;
  CustomModelMirrorPage: TInputQueryWizardPage;
  OfflinePackagePage: TInputFileWizardPage;
  InstallProgressPage: TOutputProgressWizardPage;
  FinishNotesLabel: TNewStaticText;
  IsOnlineMode: Boolean;
  UseResourcePackage: Boolean;
  UseClassicOnlineInstall: Boolean;
  UseCustomPip: Boolean;
  UseCustomModelMirror: Boolean;
  PipIndexUrl: String;
  PipTrustedHost: String;
  ResourcePackageUrl: String;
  ModelEndpoint: String;
  ModelSource: String;
  InstallTensorFlow: Boolean;
  SelectTdtsfm: Boolean;
  SelectTimemoe: Boolean;
  SelectChronos: Boolean;
  SelectTimesfm: Boolean;
  SelectMoirai: Boolean;
  SelectMoment: Boolean;
  PostInstallCompleted: Boolean;
  ExistingInstallConfirmedDir: String;
  LockedInstallDir: String;
  LockedInstallSource: String;

procedure LogTdgpt(MessageText: String);
begin
  Log('[TDgpt-DIAG] ' + MessageText);
end;

function NormalizeDir(Value: string): string;
begin
  Result := RemoveBackslashUnlessRoot(Trim(Value));
end;

function PreferredOfflineAssetsBaseName(): string;
begin
  Result := 'tdengine-tdgpt-offline-assets-' + ExpandConstant('{#MyAppVersion}') + '-windows-x64';
end;

function PreferredResourcePackagePattern(): string;
begin
  Result := 'tdengine-tdgpt-resource-*.tar';
end;

function PreferredResourcePackagePatternGz(): string;
begin
  Result := 'tdengine-tdgpt-resource-*.tar.gz';
end;

function PreferredResourcePackagePatternTgz(): string;
begin
  Result := 'tdengine-tdgpt-resource-*.tgz';
end;

function GetConfiguredResourcePackageFileName(): string;
var
  UrlValue: string;
  SlashPos: Integer;
  QueryPos: Integer;
  I: Integer;
begin
  Result := '';
  UrlValue := Trim(ExpandConstant('{#DefaultResourcePackageUrl}'));
  if UrlValue = '' then
    exit;

  QueryPos := Pos('?', UrlValue);
  if QueryPos > 0 then
    UrlValue := Copy(UrlValue, 1, QueryPos - 1);

  SlashPos := 0;
  for I := Length(UrlValue) downto 1 do
  begin
    if UrlValue[I] = '/' then
    begin
      SlashPos := I;
      break;
    end;
  end;
  if SlashPos > 0 then
    Result := Copy(UrlValue, SlashPos + 1, MaxInt)
  else
    Result := UrlValue;
end;

function FindOfflinePackageByPattern(BaseDir: string; Pattern: string): string;
var
  FindRec: TFindRec;
begin
  Result := '';
  if not FindFirst(AddBackslash(BaseDir) + Pattern, FindRec) then
    exit;
  try
    Result := AddBackslash(BaseDir) + FindRec.Name;
  finally
    FindClose(FindRec);
  end;
end;

function DetectDefaultOfflinePackage(): string;
var
  SearchDir: string;
  BaseName: string;
  ResourcePackageFileName: string;
begin
  Result := '';
  SearchDir := ExtractFileDir(ExpandConstant('{srcexe}'));
  if SearchDir = '' then
    exit;

  Result := FindOfflinePackageByPattern(SearchDir, 'tdengine-tdgpt-resource.tar');
  if Result <> '' then
    exit;

  Result := FindOfflinePackageByPattern(SearchDir, 'tdengine-tdgpt-resource.tar.gz');
  if Result <> '' then
    exit;

  Result := FindOfflinePackageByPattern(SearchDir, 'tdengine-tdgpt-resource.tgz');
  if Result <> '' then
    exit;

  Result := FindOfflinePackageByPattern(SearchDir, PreferredResourcePackagePattern());
  if Result <> '' then
    exit;

  Result := FindOfflinePackageByPattern(SearchDir, PreferredResourcePackagePatternGz());
  if Result <> '' then
    exit;

  Result := FindOfflinePackageByPattern(SearchDir, PreferredResourcePackagePatternTgz());
  if Result <> '' then
    exit;

  ResourcePackageFileName := GetConfiguredResourcePackageFileName();
  if ResourcePackageFileName <> '' then
  begin
    Result := FindOfflinePackageByPattern(SearchDir, ResourcePackageFileName);
    if Result <> '' then
      exit;
  end;

  BaseName := PreferredOfflineAssetsBaseName();
  Result := FindOfflinePackageByPattern(SearchDir, BaseName + '.tar');
  if Result <> '' then
    exit;
  Result := FindOfflinePackageByPattern(SearchDir, BaseName + '.tar.gz');
  if Result <> '' then
    exit;
  Result := FindOfflinePackageByPattern(SearchDir, BaseName + '.tgz');
  if Result <> '' then
    exit;
end;

procedure TryPopulateDefaultOfflinePackage();
var
  DetectedPath: string;
begin
  if OfflinePackagePage = nil then
    exit;
  if Trim(OfflinePackagePage.Values[0]) <> '' then
    exit;
  if ExpandConstant('{param:OFFLINE|}') <> '' then
    exit;

  DetectedPath := DetectDefaultOfflinePackage();
  if DetectedPath = '' then
    exit;

  OfflinePackagePage.Values[0] := DetectedPath;
  LogTdgpt('Detected default offline package: ' + DetectedPath);
end;

function ExtractExecutablePath(CommandLine: string): string;
var
  TrimmedCmd: string;
  SpacePos: Integer;
begin
  TrimmedCmd := Trim(CommandLine);
  if TrimmedCmd = '' then
  begin
    Result := '';
    exit;
  end;

  if TrimmedCmd[1] = '"' then
  begin
    Delete(TrimmedCmd, 1, 1);
    SpacePos := Pos('"', TrimmedCmd);
    if SpacePos > 0 then
      Result := Copy(TrimmedCmd, 1, SpacePos - 1)
    else
      Result := TrimmedCmd;
    exit;
  end;

  SpacePos := Pos(' ', TrimmedCmd);
  if SpacePos > 0 then
    Result := Copy(TrimmedCmd, 1, SpacePos - 1)
  else
    Result := TrimmedCmd;
end;

function TryReadRegisteredInstallDir(var InstallDir: string): Boolean;
begin
  InstallDir := '';
  Result := RegQueryStringValue(HKEY_LOCAL_MACHINE, InstallMetadataKey, 'InstallDir', InstallDir);
  InstallDir := NormalizeDir(InstallDir);
  Result := Result and (InstallDir <> '');
end;

function TryGetServiceInstallDir(var InstallDir: string): Boolean;
var
  ImagePath: string;
  ExePath: string;
begin
  InstallDir := '';
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE, ServiceRegistryKey, 'ImagePath', ImagePath) then
  begin
    Result := False;
    exit;
  end;

  ExePath := ExtractExecutablePath(ImagePath);
  ExePath := NormalizeDir(ExePath);
  if ExePath = '' then
  begin
    Result := False;
    exit;
  end;

  InstallDir := NormalizeDir(ExtractFileDir(ExtractFileDir(ExePath)));
  Result := InstallDir <> '';
end;

function ResolveLockedInstallDir(var ErrorMessage: string): Boolean;
var
  MetadataDir: string;
  ServiceDir: string;
begin
  ErrorMessage := '';
  LockedInstallDir := '';
  LockedInstallSource := '';
  MetadataDir := '';
  ServiceDir := '';

  TryReadRegisteredInstallDir(MetadataDir);
  TryGetServiceInstallDir(ServiceDir);

  if (MetadataDir <> '') and (ServiceDir <> '') and (CompareText(MetadataDir, ServiceDir) <> 0) then
  begin
    ErrorMessage :=
      'An inconsistent {#MyAppName} installation state was detected on this machine.' + #13#10 + #13#10 +
      'Registry install directory: ' + MetadataDir + #13#10 +
      'Taosanode service directory: ' + ServiceDir + #13#10 + #13#10 +
      'Please repair or uninstall the existing installation before running setup again.';
    Result := False;
    exit;
  end;

  if MetadataDir <> '' then
  begin
    LockedInstallDir := MetadataDir;
    LockedInstallSource := 'registry';
  end
  else if ServiceDir <> '' then
  begin
    LockedInstallDir := ServiceDir;
    LockedInstallSource := 'service';
  end;

  Result := True;
end;

function GetHostFromUrl(Url: string): string;
var
  NormalizedUrl: string;
  SchemePos: Integer;
  SlashPos: Integer;
begin
  NormalizedUrl := Trim(Url);
  SchemePos := Pos('://', NormalizedUrl);
  if SchemePos > 0 then
    Delete(NormalizedUrl, 1, SchemePos + 2);
  SlashPos := Pos('/', NormalizedUrl);
  if SlashPos > 0 then
    Result := Copy(NormalizedUrl, 1, SlashPos - 1)
  else
    Result := NormalizedUrl;
end;

function ReadCommandOutput(CommandName: string; var OutputText: AnsiString): Boolean;
var
  TempFile: string;
  ResultCode: Integer;
  CmdArgs: string;
begin
  TempFile := ExpandConstant('{tmp}\tdgpt-precheck-output.txt');
  DeleteFile(TempFile);
  CmdArgs := '/C ""' + CommandName + '" --version > "' + TempFile + '" 2>&1"';
  Result := Exec(ExpandConstant('{cmd}'), CmdArgs, '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
  OutputText := '';
  if FileExists(TempFile) then
  begin
    LoadStringFromFile(TempFile, OutputText);
    DeleteFile(TempFile);
  end;
  OutputText := Trim(OutputText);
end;

function RunCommandCapture(CmdLine: string; var OutputText: AnsiString): Boolean;
var
  TempFile: string;
  ResultCode: Integer;
  CmdArgs: string;
begin
  TempFile := ExpandConstant('{tmp}\tdgpt-command-output.txt');
  DeleteFile(TempFile);
  CmdArgs := '/C ' + CmdLine + ' > "' + TempFile + '" 2>&1';
  Result := Exec(ExpandConstant('{cmd}'), CmdArgs, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  OutputText := '';
  if FileExists(TempFile) then
  begin
    LoadStringFromFile(TempFile, OutputText);
    DeleteFile(TempFile);
  end;
  OutputText := Trim(OutputText);
  Result := Result and (ResultCode = 0);
end;

function EscapePowerShellSingleQuoted(Value: string): string;
begin
  Result := Value;
  StringChangeEx(Result, '''', '''''', True);
end;

function GetInstallTreeProcessSummary(TargetDir: string): string;
var
  OutputText: AnsiString;
  PsExe: string;
  PsCommand: string;
  CmdLine: string;
begin
  Result := '';
  TargetDir := RemoveBackslashUnlessRoot(Trim(TargetDir));
  if TargetDir = '' then
    exit;

  PsExe := ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe');
  if not FileExists(PsExe) then
    exit;

  PsCommand :=
    '$procs = Get-CimInstance Win32_Process | Where-Object { $_.ExecutablePath -like ''' +
    EscapePowerShellSingleQuoted(AddBackslash(TargetDir) + '*') +
    ''' }; ' +
    'if ($procs) { ' +
    '$procs | Select-Object -First 6 @{Name=''Info'';Expression={ $_.Name + '' PID='' + $_.ProcessId + '' EXE='' + $_.ExecutablePath }} | ' +
    'ForEach-Object { $_.Info } ' +
    '}';
  CmdLine := '""' + PsExe + '" -NoProfile -ExecutionPolicy Bypass -Command "' + PsCommand + '""';
  RunCommandCapture(CmdLine, OutputText);
  Result := Trim(OutputText);
end;

function BuildLockedFileMessage(TargetDir: string; LockedPath: string): string;
var
  ProcessSummary: string;
begin
  Result :=
    'The existing installation is still locking this file and the upgrade cannot continue:' + #13#10 + #13#10 +
    LockedPath + #13#10 + #13#10;

  ProcessSummary := GetInstallTreeProcessSummary(TargetDir);
  if ProcessSummary <> '' then
  begin
    LogTdgpt('Install-tree processes still running before upgrade:' + #13#10 + ProcessSummary);
    Result := Result +
      'Processes still running under the install directory:' + #13#10 +
      ProcessSummary + #13#10 + #13#10;
  end;

  Result := Result +
    'Close the remaining Taosanode, model, Python, or command prompt processes that are using this installation, then run the installer again.';
end;

function IsSupportedPythonVersion(OutputText: AnsiString): Boolean;
var
  VersionText: AnsiString;
begin
  Result := False;
  if Pos('Python ', OutputText) <> 1 then
    exit;
  VersionText := Copy(OutputText, 8, MaxInt);
  Result :=
    (Pos('3.10.', VersionText) = 1) or
    (Pos('3.11.', VersionText) = 1) or
    (Pos('3.12.', VersionText) = 1) or
    (VersionText = '3.10') or
    (VersionText = '3.11') or
    (VersionText = '3.12');
end;

function TryDetectPython(CommandName: string; var VersionText: AnsiString): Boolean;
begin
  Result := ReadCommandOutput(CommandName, VersionText) and IsSupportedPythonVersion(VersionText);
end;

function CheckPythonPrerequisite(var VersionText: AnsiString): Boolean;
begin
  Result :=
    TryDetectPython('python', VersionText) or
    TryDetectPython('python3', VersionText) or
    TryDetectPython('python3.10', VersionText) or
    TryDetectPython('python3.11', VersionText) or
    TryDetectPython('python3.12', VersionText);
end;

function TryReadVCRuntimeVersionFromKey(const KeyName: string; var VersionText: string): Boolean;
var
  Installed: Cardinal;
  Major: Cardinal;
  Minor: Cardinal;
  Build: Cardinal;
  Revision: Cardinal;
begin
  Result := False;
  if not RegQueryDWordValue(HKEY_LOCAL_MACHINE, KeyName, 'Installed', Installed) then
    exit;
  if Installed <> 1 then
    exit;
  if not RegQueryDWordValue(HKEY_LOCAL_MACHINE, KeyName, 'Major', Major) then
    exit;
  if not RegQueryDWordValue(HKEY_LOCAL_MACHINE, KeyName, 'Minor', Minor) then
    exit;
  if not RegQueryDWordValue(HKEY_LOCAL_MACHINE, KeyName, 'Bld', Build) then
    exit;
  if not RegQueryDWordValue(HKEY_LOCAL_MACHINE, KeyName, 'Rbld', Revision) then
    exit;
  VersionText := IntToStr(Major) + '.' + IntToStr(Minor) + '.' + IntToStr(Build) + '.' + IntToStr(Revision);
  Result := True;
end;

function SplitVersionText(const Value: string; Delimiter: Char): TArrayOfString;
var
  Count: Integer;
  Index: Integer;
  StartPos: Integer;
  I: Integer;
begin
  Count := 1;
  for I := 1 to Length(Value) do
    if Value[I] = Delimiter then
      Count := Count + 1;

  SetArrayLength(Result, Count);
  Index := 0;
  StartPos := 1;
  for I := 1 to Length(Value) do
  begin
    if Value[I] = Delimiter then
    begin
      Result[Index] := Copy(Value, StartPos, I - StartPos);
      Index := Index + 1;
      StartPos := I + 1;
    end;
  end;
  Result[Index] := Copy(Value, StartPos, Length(Value) - StartPos + 1);
end;

function IsVCRuntimeVersionSupported(VersionText: string): Boolean;
var
  Parts: TArrayOfString;
  Major: Integer;
  Minor: Integer;
  Build: Integer;
  Revision: Integer;
begin
  Result := False;
  Parts := SplitVersionText(VersionText, '.');
  if GetArrayLength(Parts) < 4 then
    exit;

  Major := StrToIntDef(Parts[0], 0);
  Minor := StrToIntDef(Parts[1], 0);
  Build := StrToIntDef(Parts[2], 0);
  Revision := StrToIntDef(Parts[3], 0);

  if Major > {#MinVCRuntimeMajor} then
  begin
    Result := True;
    exit;
  end;
  if Major < {#MinVCRuntimeMajor} then
    exit;
  if Minor > {#MinVCRuntimeMinor} then
  begin
    Result := True;
    exit;
  end;
  if Minor < {#MinVCRuntimeMinor} then
    exit;
  if Build > {#MinVCRuntimeBuild} then
  begin
    Result := True;
    exit;
  end;
  if Build < {#MinVCRuntimeBuild} then
    exit;
  Result := Revision >= {#MinVCRuntimeRbld};
end;

function CheckVCRuntimePrerequisite(var DetectedVersion: string): Boolean;
begin
  DetectedVersion := '';
  Result :=
    TryReadVCRuntimeVersionFromKey('SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', DetectedVersion) or
    TryReadVCRuntimeVersionFromKey('SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', DetectedVersion);
  if not Result then
    exit;
  Result := IsVCRuntimeVersionSupported(DetectedVersion);
end;

function IsExistingTaosanodeInstall(TargetDir: string): Boolean;
begin
  TargetDir := RemoveBackslashUnlessRoot(Trim(TargetDir));
  if TargetDir = '' then
  begin
    Result := False;
    exit;
  end;

  Result :=
    FileExists(AddBackslash(TargetDir) + 'bin\taosanode_service.py') or
    FileExists(AddBackslash(TargetDir) + 'cfg\taosanode.config.py') or
    FileExists(AddBackslash(TargetDir) + 'install.py') or
    DirExists(AddBackslash(TargetDir) + 'venvs') or
    DirExists(AddBackslash(TargetDir) + 'model');
end;

function HasExistingMainVenvPython(): Boolean;
var
  ExistingPython: string;
  OutputText: AnsiString;
begin
  Result := False;
  if LockedInstallDir = '' then
    exit;
  ExistingPython := AddBackslash(LockedInstallDir) + 'venvs\venv\Scripts\python.exe';
  if not FileExists(ExistingPython) then
    exit;
  Result := ReadCommandOutput(ExistingPython, OutputText);
  if not Result then
    LogTdgpt('Ignoring unusable existing main venv python: ' + ExistingPython);
end;

function HasExistingResourceAssets(TargetDir: string): Boolean;
begin
  TargetDir := NormalizeDir(TargetDir);
  if TargetDir = '' then
  begin
    Result := False;
    exit;
  end;

  Result :=
    FileExists(AddBackslash(TargetDir) + 'venvs\venv\Scripts\python.exe') and
    DirExists(AddBackslash(TargetDir) + 'model\moirai') and
    DirExists(AddBackslash(TargetDir) + 'venvs\moirai_venv') and
    DirExists(AddBackslash(TargetDir) + 'model\moment') and
    DirExists(AddBackslash(TargetDir) + 'venvs\momentfm_venv');
end;

function ConfirmExistingInstall(TargetDir: string): Boolean;
var
  MessageText: string;
begin
  TargetDir := NormalizeDir(TargetDir);
  if TargetDir = '' then
  begin
    Result := True;
    exit;
  end;

  if (LockedInstallDir <> '') and (CompareText(TargetDir, LockedInstallDir) = 0) then
  begin
    ExistingInstallConfirmedDir := TargetDir;
    Result := True;
    exit;
  end;

  if CompareText(ExistingInstallConfirmedDir, TargetDir) = 0 then
  begin
    Result := True;
    exit;
  end;

  if not IsExistingTaosanodeInstall(TargetDir) then
  begin
    ExistingInstallConfirmedDir := '';
    Result := True;
    exit;
  end;

  MessageText :=
    'An existing {#MyAppName} / Taosanode installation was detected in this directory:' + #13#10 + #13#10 +
    TargetDir + #13#10 + #13#10 +
    'Continuing will update packaged files and reuse existing cfg, log, model, and venv directories when possible.' + #13#10 +
    'Before replacing packaged files, Setup will stop the existing Taosanode service and any running model services under this installation.' + #13#10 +
    'Standard uninstall still keeps the model directory unless it is removed explicitly.' + #13#10 +
    'To use a different directory, uninstall the existing installation first.' + #13#10 + #13#10 +
    'Do you want to continue with this install location?';

  Result := MsgBox(MessageText, mbConfirmation, MB_YESNO) = IDYES;
  if Result then
    ExistingInstallConfirmedDir := TargetDir;
end;

function ServiceExists(ServiceName: string): Boolean;
var
  OutputText: AnsiString;
begin
  RunCommandCapture('sc query "' + ServiceName + '"', OutputText);
  Result := Pos('SERVICE_NAME:', Uppercase(OutputText)) > 0;
end;

function IsServiceStopped(ServiceName: string): Boolean;
var
  OutputText: AnsiString;
  UpperText: string;
begin
  RunCommandCapture('sc query "' + ServiceName + '"', OutputText);
  UpperText := Uppercase(OutputText);
  Result :=
    (Pos('FAILED 1060', UpperText) > 0) or
    (Pos('STATE', UpperText) > 0) and (Pos('STOPPED', UpperText) > 0);
end;

function WaitForServiceStop(ServiceName: string; TimeoutSeconds: Integer): Boolean;
var
  I: Integer;
begin
  for I := 0 to TimeoutSeconds * 2 do
  begin
    if IsServiceStopped(ServiceName) then
    begin
      Result := True;
      exit;
    end;
    Sleep(500);
  end;
  Result := IsServiceStopped(ServiceName);
end;

function WaitForFileUnlock(FilePath: string; TimeoutSeconds: Integer): Boolean;
var
  I: Integer;
  TempPath: string;
begin
  LogTdgpt('WaitForFileUnlock start: ' + FilePath);
  if not FileExists(FilePath) then
  begin
    LogTdgpt('WaitForFileUnlock skipped because file does not exist: ' + FilePath);
    Result := True;
    exit;
  end;

  TempPath := FilePath + '.tdgpt-check';
  if FileExists(TempPath) then
    DeleteFile(TempPath);

  for I := 0 to TimeoutSeconds * 2 do
  begin
    if RenameFile(FilePath, TempPath) then
    begin
      RenameFile(TempPath, FilePath);
      LogTdgpt('WaitForFileUnlock succeeded: ' + FilePath);
      Result := True;
      exit;
    end;
    Sleep(500);
  end;

  LogTdgpt('WaitForFileUnlock timed out: ' + FilePath);
  Result := False;
end;

function GetExistingServiceManagerPython(TargetDir: string): string;
var
  CandidatePath: string;
  OutputText: AnsiString;
begin
  Result := '';
  TargetDir := RemoveBackslashUnlessRoot(Trim(TargetDir));
  if TargetDir = '' then
    exit;

  CandidatePath := AddBackslash(TargetDir) + 'venvs\venv\Scripts\python.exe';
  if FileExists(CandidatePath) and ReadCommandOutput(CandidatePath, OutputText) then
  begin
    Result := CandidatePath;
    exit;
  end;

  CandidatePath := AddBackslash(TargetDir) + 'python\runtime\python.exe';
  if FileExists(CandidatePath) and ReadCommandOutput(CandidatePath, OutputText) then
    Result := CandidatePath;
end;

procedure StopExistingModelServices(TargetDir: string);
var
  ResultCode: Integer;
  PythonExe: string;
  ServiceScript: string;
begin
  TargetDir := RemoveBackslashUnlessRoot(Trim(TargetDir));
  if TargetDir = '' then
    exit;

  ServiceScript := AddBackslash(TargetDir) + 'bin\taosanode_service.py';
  if not FileExists(ServiceScript) then
    exit;

  PythonExe := GetExistingServiceManagerPython(TargetDir);
  if PythonExe = '' then
  begin
    LogTdgpt('StopExistingModelServices skipped because no usable python was found for ' + TargetDir);
    exit;
  end;

  LogTdgpt('Stopping existing model services via ' + ServiceScript);
  Exec(PythonExe, '"' + ServiceScript + '" model-stop all', TargetDir, SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(1000);

  LogTdgpt('Stopping existing taosanode process via ' + ServiceScript);
  Exec(PythonExe, '"' + ServiceScript + '" stop', TargetDir, SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(1000);
end;

procedure KillProcessByPidFile(PidFilePath: string);
var
  ResultCode: Integer;
  PidText: AnsiString;
begin
  if not FileExists(PidFilePath) then
    exit;
  if not LoadStringFromFile(PidFilePath, PidText) then
    exit;

  PidText := Trim(PidText);
  if PidText = '' then
    exit;

  LogTdgpt('Issuing taskkill for PID ' + PidText + ' from ' + PidFilePath);
  Exec(ExpandConstant('{cmd}'), '/C taskkill /F /T /PID ' + PidText + ' >nul 2>&1', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure KillProcessesFromPidDir(PidDir: string);
var
  FindRec: TFindRec;
begin
  if not DirExists(PidDir) then
    exit;
  if not FindFirst(AddBackslash(PidDir) + '*.pid', FindRec) then
    exit;

  try
    repeat
      KillProcessByPidFile(AddBackslash(PidDir) + FindRec.Name);
    until not FindNext(FindRec);
  finally
    FindClose(FindRec);
  end;
end;

procedure KillExistingPidTrackedProcesses(TargetDir: string);
begin
  TargetDir := RemoveBackslashUnlessRoot(Trim(TargetDir));
  if TargetDir = '' then
    exit;

  KillProcessByPidFile(AddBackslash(TargetDir) + 'taosanode.pid');
  KillProcessesFromPidDir(AddBackslash(TargetDir) + 'data\pids');
  Sleep(1000);
end;

procedure StopExistingTaosanodeProcesses(TargetDir: string);
var
  ResultCode: Integer;
  WinSWPath: string;
begin
  TargetDir := RemoveBackslashUnlessRoot(Trim(TargetDir));
  if TargetDir = '' then
    exit;

  LogTdgpt('StopExistingTaosanodeProcesses start for ' + TargetDir);

  if ServiceExists('Taosanode') then
  begin
    LogTdgpt('Stopping existing Windows service: Taosanode');
    Exec(ExpandConstant('{cmd}'), '/C sc stop "Taosanode" >nul 2>&1', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    if WaitForServiceStop('Taosanode', 15) then
      LogTdgpt('Taosanode service reported STOPPED before upgrade.')
    else
      LogTdgpt('Taosanode service did not stop cleanly within timeout. Continuing with process cleanup.');
  end;

  StopExistingModelServices(TargetDir);
  KillExistingPidTrackedProcesses(TargetDir);

  WinSWPath := AddBackslash(TargetDir) + 'bin\taosanode-winsw.exe';
  if FileExists(WinSWPath) then
  begin
    LogTdgpt('Stopping existing WinSW process via ' + WinSWPath);
    Exec(WinSWPath, 'stop', TargetDir, SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Sleep(1000);
  end;

  LogTdgpt('Issuing taskkill for taosanode-winsw.exe');
  Exec(ExpandConstant('{cmd}'), '/C taskkill /F /T /IM taosanode-winsw.exe >nul 2>&1', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(1000);
  LogTdgpt('StopExistingTaosanodeProcesses finished');
end;

function InitializeSetup(): Boolean;
var
  MessageText: string;
  DetectedVCRuntimeVersion: string;
begin
  Result := ResolveLockedInstallDir(MessageText);
  if not Result then
  begin
    MsgBox(MessageText, mbCriticalError, MB_OK);
    exit;
  end;

  Result := CheckVCRuntimePrerequisite(DetectedVCRuntimeVersion);
  if Result then
    exit;

  MessageText :=
    'Microsoft Visual C++ Redistributable x64 14.44 or later is required.' + #13#10 + #13#10;
  if DetectedVCRuntimeVersion <> '' then
    MessageText := MessageText + 'Detected version: ' + DetectedVCRuntimeVersion + #13#10 + #13#10;
  MessageText := MessageText +
    'Please install or update to the latest supported Visual C++ Redistributable before continuing.' + #13#10 +
    'Download: https://aka.ms/vc14/vc_redist.x64.exe';
  MsgBox(MessageText, mbCriticalError, MB_OK);
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  TargetDir: string;
  WinSWPath: string;
  RuntimePythonPath: string;
  RuntimeDllPath: string;
begin
  Result := '';
  if LockedInstallDir <> '' then
    TargetDir := LockedInstallDir
  else
    TargetDir := NormalizeDir(WizardDirValue());
  LogTdgpt('PrepareToInstall enter, target=' + TargetDir);
  if (TargetDir = '') or ((not IsExistingTaosanodeInstall(TargetDir)) and (not ServiceExists('Taosanode'))) then
  begin
    LogTdgpt('PrepareToInstall: no existing install detected');
    exit;
  end;

  LogTdgpt('PrepareToInstall: existing install detected');
  StopExistingTaosanodeProcesses(TargetDir);
  WinSWPath := AddBackslash(TargetDir) + 'bin\taosanode-winsw.exe';
  if not WaitForFileUnlock(WinSWPath, 15) then
  begin
    LogTdgpt('PrepareToInstall: file unlock failed for ' + WinSWPath);
    Result := BuildLockedFileMessage(TargetDir, WinSWPath);
    exit;
  end;

  RuntimePythonPath := AddBackslash(TargetDir) + 'python\runtime\python.exe';
  if not WaitForFileUnlock(RuntimePythonPath, 15) then
  begin
    LogTdgpt('PrepareToInstall: runtime python is locked: ' + RuntimePythonPath);
    Result := BuildLockedFileMessage(TargetDir, RuntimePythonPath);
    exit;
  end;

  RuntimeDllPath := AddBackslash(TargetDir) + 'python\runtime\python3.dll';
  if not WaitForFileUnlock(RuntimeDllPath, 15) then
  begin
    LogTdgpt('PrepareToInstall: runtime DLL is locked: ' + RuntimeDllPath);
    Result := BuildLockedFileMessage(TargetDir, RuntimeDllPath);
    exit;
  end;
  LogTdgpt('PrepareToInstall exit successfully');
end;

function GetSelectedModelCount(): Integer;
begin
  Result := 0;
  if SelectTdtsfm then Result := Result + 1;
  if SelectTimemoe then Result := Result + 1;
  if SelectChronos then Result := Result + 1;
  if SelectTimesfm then Result := Result + 1;
  if SelectMoirai then Result := Result + 1;
  if SelectMoment then Result := Result + 1;
end;

function IsUpgradeInstall(): Boolean;
forward;

function GetModelSelectionSummary(): String;
begin
  if ModelSource = 'none' then
  begin
    if IsUpgradeInstall() then
      Result := 'Reuse existing model files'
    else
      Result := 'None';
    exit;
  end;
  if ModelSource = 'offline' then
  begin
    if Trim(OfflinePackagePage.Values[0]) <> '' then
      Result := 'Import from one local resource package'
    else if UseResourcePackage then
      Result := 'Download and import resource package'
    else
      Result := 'Reuse existing resource files';
    exit;
  end;
  Result := '';
  if SelectTdtsfm then Result := Result + 'TDTSFM, ';
  if SelectTimemoe then Result := Result + 'TimeMoE 200M, ';
  if SelectMoirai then Result := Result + 'Moirai Small, ';
  if SelectChronos then Result := Result + 'Chronos Bolt Base, ';
  if SelectTimesfm then Result := Result + 'TimesFM 2.0 500M, ';
  if SelectMoment then Result := Result + 'MOMENT Base, ';
  if Result <> '' then
    Delete(Result, Length(Result) - 1, 2)
  else
    Result := 'None';
end;

function GetInstallerPackageSummary(): String;
begin
  Result := 'Base installer';
end;

function GetModelSourceSummary(): String;
begin
  if ModelSource = 'none' then
  begin
    if IsUpgradeInstall() then
      Result := 'Keep existing model files'
    else
      Result := 'Do not install models now';
    exit;
  end;
  if ModelSource = 'offline' then
  begin
    Result := 'TDgpt resource package';
    exit;
  end;
  if ModelSource = 'online' then
  begin
    Result := 'Online download';
    exit;
  end;
  Result := ModelSource;
end;

function IsUpgradeInstall(): Boolean;
begin
  Result := ExistingInstallConfirmedDir <> '';
  if (not Result) and (LockedInstallDir <> '') then
    Result := IsExistingTaosanodeInstall(LockedInstallDir) or ServiceExists('Taosanode');
end;

procedure ClearModelSelections();
begin
  SelectTdtsfm := False;
  SelectTimemoe := False;
  SelectMoirai := False;
  SelectChronos := False;
  SelectTimesfm := False;
  SelectMoment := False;
  if ModelSelectionPage <> nil then
  begin
    ModelSelectionPage.Values[0] := False;
    ModelSelectionPage.Values[1] := False;
    ModelSelectionPage.Values[2] := False;
    ModelSelectionPage.Values[3] := False;
    ModelSelectionPage.Values[4] := False;
    ModelSelectionPage.Values[5] := False;
  end;
end;

procedure SetDefaultOnlineModelSelections();
begin
  ClearModelSelections();
  SelectMoirai := True;
  SelectMoment := True;
  if ModelSelectionPage <> nil then
  begin
    ModelSelectionPage.Values[2] := True;
    ModelSelectionPage.Values[5] := True;
  end;
end;

procedure ApplyInstallDefaults(UpgradeInstall: Boolean);
begin
  if UpgradeInstall then
  begin
    if InstallModePage <> nil then
    begin
      InstallModePage.Values[0] := False;
      InstallModePage.Values[1] := True;
    end;
    UseResourcePackage := False;
    UseClassicOnlineInstall := False;
    IsOnlineMode := False;
    ModelSource := 'none';
    InstallTensorFlow := True;
    if PythonOptionsPage <> nil then
      PythonOptionsPage.Values[0] := True;
    if ModelSourcePage <> nil then
    begin
      ModelSourcePage.Values[0] := False;
      ModelSourcePage.Values[1] := True;
    end;
    ClearModelSelections();
    exit;
  end;

  if InstallModePage <> nil then
  begin
    InstallModePage.Values[0] := True;
    InstallModePage.Values[1] := False;
  end;
  UseResourcePackage := True;
  UseClassicOnlineInstall := False;
  IsOnlineMode := False;
  ModelSource := 'offline';
  InstallTensorFlow := True;
  if PythonOptionsPage <> nil then
    PythonOptionsPage.Values[0] := True;
  if ModelSourcePage <> nil then
  begin
    ModelSourcePage.Values[0] := False;
    ModelSourcePage.Values[1] := True;
  end;
  ClearModelSelections();
end;

function IsTruthyParam(const Value: string): Boolean;
var
  Normalized: string;
begin
  Normalized := Uppercase(Trim(Value));
  Result :=
    (Normalized <> '') and
    (Normalized <> '0') and
    (Normalized <> 'FALSE') and
    (Normalized <> 'NO') and
    (Normalized <> 'OFF');
end;

procedure ApplyCommandLineModeOverrides();
var
  ForceOnlineValue: string;
begin
  ForceOnlineValue := ExpandConstant('{param:ONLINE|}');
  if IsTruthyParam(ForceOnlineValue) then
  begin
    if InstallModePage <> nil then
    begin
      InstallModePage.Values[0] := False;
      InstallModePage.Values[1] := False;
    end;
    UseResourcePackage := False;
    UseClassicOnlineInstall := True;
    IsOnlineMode := True;
    if IsUpgradeInstall() then
    begin
      ModelSource := 'none';
      InstallTensorFlow := False;
      ClearModelSelections();
      if PythonOptionsPage <> nil then
        PythonOptionsPage.Values[0] := False;
      if ModelSourcePage <> nil then
      begin
        ModelSourcePage.Values[0] := False;
        ModelSourcePage.Values[1] := True;
      end;
    end
    else
    begin
      ModelSource := 'online';
      InstallTensorFlow := True;
      SetDefaultOnlineModelSelections();
      if PythonOptionsPage <> nil then
        PythonOptionsPage.Values[0] := True;
      if ModelSourcePage <> nil then
      begin
        ModelSourcePage.Values[0] := True;
        ModelSourcePage.Values[1] := False;
      end;
    end;
  end;

  if ExpandConstant('{param:OFFLINE|}') <> '' then
  begin
    if InstallModePage <> nil then
    begin
      InstallModePage.Values[0] := True;
      InstallModePage.Values[1] := False;
    end;
    UseResourcePackage := True;
    UseClassicOnlineInstall := False;
    IsOnlineMode := False;
    ModelSource := 'offline';
    OfflinePackagePage.Values[0] := ExpandConstant('{param:OFFLINE|}');
  end;
end;

procedure InitializeWizard();
begin
  IsOnlineMode := False;
  UseResourcePackage := True;
  UseClassicOnlineInstall := False;
  UseCustomPip := False;
  UseCustomModelMirror := False;
  PipIndexUrl := '';
  PipTrustedHost := '';
  ResourcePackageUrl := ExpandConstant('{#DefaultResourcePackageUrl}');
  ModelEndpoint := '';
  ModelSource := 'none';
  InstallTensorFlow := True;
  SelectTdtsfm := False;
  SelectTimemoe := False;
  SelectChronos := False;
  SelectTimesfm := False;
  SelectMoirai := True;
  SelectMoment := True;
  PostInstallCompleted := False;
  ExistingInstallConfirmedDir := '';

  InstallModePage := CreateInputOptionPage(
    wpWelcome,
    'TDgpt Resource Package',
    'Choose whether to install the TDgpt resource package',
    'The recommended flow downloads one TDgpt resource package from a configured remote URL and then reuses the validated offline import logic. You can also skip the resource package for now.',
    True,
    False);
  InstallModePage.Add('Download and install the TDgpt resource package (recommended)');
  InstallModePage.Add('Do not install the TDgpt resource package now');
  InstallModePage.Values[0] := True;

  PipSourcePage := CreateInputOptionPage(
    InstallModePage.ID,
    'Python Package Source',
    'Choose a pip source for Python packages',
    'The default keeps the official PyPI source. China users can choose a mirror for faster downloads.',
    True,
    False);
  PipSourcePage.Add('Official PyPI');
  PipSourcePage.Add('Tsinghua mirror');
  PipSourcePage.Add('Aliyun mirror');
  PipSourcePage.Add('Custom mirror URL');
  PipSourcePage.Values[0] := True;

  CustomPipPage := CreateInputQueryPage(
    PipSourcePage.ID,
    'Custom Python Package Source',
    'Enter a custom pip index URL',
    'This value is used only when "Custom mirror URL" is selected.');
  CustomPipPage.Add('pip index URL:', False);

  PythonOptionsPage := CreateInputOptionPage(
    CustomPipPage.ID,
    'Python Runtime Options',
    'Choose optional Python runtime components',
    'TensorFlow CPU support is optional. Keep it enabled if you need TensorFlow-based features. It adds roughly 700 MB of downloads.',
    False,
    False);
  PythonOptionsPage.Add('Install TensorFlow CPU support (default)');
  PythonOptionsPage.Values[0] := True;

  ModelSourcePage := CreateInputOptionPage(
    PythonOptionsPage.ID,
    'Model Installation Source',
    'Choose how models should be prepared',
    'New installs can download selected models online. Upgrade installs keep existing model files by default.',
    True,
    False);
  ModelSourcePage.Add('Download selected models online');
  ModelSourcePage.Add('Do not install models now');
  ModelSourcePage.Values[1] := True;

  ModelSelectionPage := CreateInputOptionPage(
    ModelSourcePage.ID,
    'Model Selection',
    'Choose which models to prepare',
    'Online defaults are Moirai Small and MOMENT Base. Approximate download sizes are shown in each option.',
    False,
    False);
  ModelSelectionPage.Add('Taos time-series foundation model (TDtsfm v1.0, offline package only)');
  ModelSelectionPage.Add('TimeMoE 200M (~865 MB download)');
  ModelSelectionPage.Add('Moirai Small (~447 MB download, default)');
  ModelSelectionPage.Add('Chronos Bolt Base (~783 MB download)');
  ModelSelectionPage.Add('TimesFM 2.0 500M (~1.90 GB download)');
  ModelSelectionPage.Add('MOMENT Base (~433 MB download, default)');
  ModelSelectionPage.Values[2] := True;
  ModelSelectionPage.Values[5] := True;

  ModelMirrorPage := CreateInputOptionPage(
    ModelSelectionPage.ID,
    'Model Download Source',
    'Choose a model mirror',
    'This endpoint is used only for online model downloads.',
    True,
    False);
  ModelMirrorPage.Add('Official Hugging Face');
  ModelMirrorPage.Add('HF Mirror');
  ModelMirrorPage.Add('Custom endpoint URL');
  ModelMirrorPage.Values[0] := True;

  CustomModelMirrorPage := CreateInputQueryPage(
    ModelMirrorPage.ID,
    'Custom Model Mirror',
    'Enter a Hugging Face compatible endpoint',
    'Examples: https://hf-mirror.com');
  CustomModelMirrorPage.Add('Endpoint URL:', False);

  OfflinePackagePage := CreateInputFilePage(
    CustomModelMirrorPage.ID,
    'Offline Package Import',
    'Select one offline tar package',
    'This page is reserved for command-line compatible offline imports. The interactive installer no longer asks users to browse for a local offline package.');
  OfflinePackagePage.Add('Offline package:', 'Tar archives|*.tar.gz;*.tgz;*.tar|All files|*.*', '.tar.gz');

  InstallProgressPage := CreateOutputProgressPage(
    'Installing {#MyAppName}',
    'Installing packaged files, preparing Python environments, and registering the Windows service');

  FinishNotesLabel := TNewStaticText.Create(WizardForm.FinishedPage);
  FinishNotesLabel.Parent := WizardForm.FinishedPage;
  FinishNotesLabel.Left := WizardForm.FinishedLabel.Left;
  FinishNotesLabel.Top := WizardForm.FinishedLabel.Top + WizardForm.FinishedLabel.Height + ScaleY(6);
  FinishNotesLabel.Width := ScaleX(420);
  FinishNotesLabel.Height := ScaleY(130);
  FinishNotesLabel.AutoSize := False;
  FinishNotesLabel.WordWrap := True;
  FinishNotesLabel.Visible := False;

  if LockedInstallDir <> '' then
    WizardForm.DirEdit.Text := LockedInstallDir;
  ApplyInstallDefaults(IsUpgradeInstall());

  // Support /OFFLINE and /ONLINE command-line parameters for silent installation
  ApplyCommandLineModeOverrides();
 
    TryPopulateDefaultOfflinePackage();
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if (PageID = InstallModePage.ID) and UseClassicOnlineInstall then
    Result := True
  else if (PageID = PipSourcePage.ID) and (not UseClassicOnlineInstall) then
    Result := True
  else if (PageID = CustomPipPage.ID) and ((not UseClassicOnlineInstall) or (not UseCustomPip)) then
    Result := True
  else if (PageID = PythonOptionsPage.ID) and (not UseClassicOnlineInstall) then
    Result := True
  else if (PageID = ModelSourcePage.ID) and (not UseClassicOnlineInstall) then
    Result := True
  else if (PageID = ModelSelectionPage.ID) and (ModelSource <> 'online') then
    Result := True
  else if (PageID = ModelMirrorPage.ID) and (ModelSource <> 'online') then
    Result := True
  else if (PageID = CustomModelMirrorPage.ID) and ((ModelSource <> 'online') or (not UseCustomModelMirror)) then
    Result := True
  else if (PageID = OfflinePackagePage.ID) then
    Result := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  TargetDir: string;
  WarningText: string;
begin
  Result := True;

  if CurPageID = wpSelectDir then
  begin
    if (LockedInstallDir <> '') and (CompareText(NormalizeDir(WizardDirValue()), LockedInstallDir) <> 0) then
    begin
      MsgBox(
        'This machine already has a registered {#MyAppName} installation.' + #13#10 + #13#10 +
        'Existing install directory: ' + LockedInstallDir + #13#10 +
        'Detection source: ' + LockedInstallSource + #13#10 + #13#10 +
        'Windows setup only supports a single installed instance. Setup will continue only with the existing install directory.' + #13#10 +
        'To use a different directory, uninstall the existing installation first.',
        mbError,
        MB_OK
      );
      WizardForm.DirEdit.Text := LockedInstallDir;
      Result := False;
      exit;
    end;
    if not ConfirmExistingInstall(WizardDirValue()) then
    begin
      Result := False;
      exit;
    end;
    ApplyInstallDefaults(IsUpgradeInstall());
    ApplyCommandLineModeOverrides();
  end;

  if CurPageID = InstallModePage.ID then
  begin
    UseResourcePackage := InstallModePage.Values[0];
    IsOnlineMode := UseClassicOnlineInstall;

    if UseClassicOnlineInstall then
    begin
      if IsUpgradeInstall() then
      begin
        ModelSource := 'none';
        InstallTensorFlow := False;
      end
      else
      begin
        ModelSource := 'online';
        InstallTensorFlow := True;
      end;
      if PythonOptionsPage <> nil then
        PythonOptionsPage.Values[0] := InstallTensorFlow;
    end
    else
    begin
      InstallTensorFlow := True;
      ClearModelSelections();
      if UseResourcePackage then
        ModelSource := 'offline'
      else
        ModelSource := 'none';

      TargetDir := LockedInstallDir;
      if TargetDir = '' then
        TargetDir := NormalizeDir(WizardDirValue());
      if (not UseResourcePackage) and (not HasExistingResourceAssets(TargetDir)) then
      begin
        WarningText :=
          'The TDgpt resource package will not be installed.' + #13#10 + #13#10 +
          'IDMP features that depend on the time-series foundation model service will not work normally:' + #13#10 +
          '  - prediction algorithms that depend on the time-series foundation model service' + #13#10 +
          '  - value imputation' + #13#10 + #13#10 +
          'Do you want to continue without the TDgpt resource package?';
        if MsgBox(WarningText, mbConfirmation, MB_YESNO) <> IDYES then
        begin
          Result := False;
          exit;
        end;
      end;
    end;
  end;

  if CurPageID = PipSourcePage.ID then
  begin
    UseCustomPip := PipSourcePage.Values[3];
    PipIndexUrl := '';
    PipTrustedHost := '';
    if PipSourcePage.Values[1] then
    begin
      PipIndexUrl := 'https://pypi.tuna.tsinghua.edu.cn/simple';
      PipTrustedHost := 'pypi.tuna.tsinghua.edu.cn';
    end
    else if PipSourcePage.Values[2] then
    begin
      PipIndexUrl := 'https://mirrors.aliyun.com/pypi/simple';
      PipTrustedHost := 'mirrors.aliyun.com';
    end;
  end;

  if CurPageID = CustomPipPage.ID then
  begin
    PipIndexUrl := Trim(CustomPipPage.Values[0]);
    if PipIndexUrl = '' then
    begin
      MsgBox('Please enter a valid pip index URL.', mbError, MB_OK);
      Result := False;
      exit;
    end;
    PipTrustedHost := GetHostFromUrl(PipIndexUrl);
  end;

  if CurPageID = PythonOptionsPage.ID then
    InstallTensorFlow := PythonOptionsPage.Values[0];

  if CurPageID = ModelSourcePage.ID then
  begin
    if ModelSourcePage.Values[0] then ModelSource := 'online';
    if ModelSourcePage.Values[1] then ModelSource := 'none';
    if ModelSource <> 'online' then
    begin
      SelectTdtsfm := False;
      SelectTimemoe := False;
      SelectMoirai := False;
      SelectChronos := False;
      SelectTimesfm := False;
      SelectMoment := False;
    end;
  end;

  if CurPageID = ModelSelectionPage.ID then
  begin
    SelectTdtsfm := ModelSelectionPage.Values[0];
    SelectTimemoe := ModelSelectionPage.Values[1];
    SelectMoirai := ModelSelectionPage.Values[2];
    SelectChronos := ModelSelectionPage.Values[3];
    SelectTimesfm := ModelSelectionPage.Values[4];
    SelectMoment := ModelSelectionPage.Values[5];
    if (ModelSource = 'online') and SelectTdtsfm then
    begin
      MsgBox('TDTSFM online download is not available yet. Use an offline archive instead.', mbError, MB_OK);
      Result := False;
      exit;
    end;
  end;

  if CurPageID = ModelMirrorPage.ID then
  begin
    UseCustomModelMirror := ModelMirrorPage.Values[2];
    ModelEndpoint := '';
    if ModelMirrorPage.Values[1] then
      ModelEndpoint := 'https://hf-mirror.com';
  end;

  if CurPageID = CustomModelMirrorPage.ID then
  begin
    ModelEndpoint := Trim(CustomModelMirrorPage.Values[0]);
    if ModelEndpoint = '' then
    begin
      MsgBox('Please enter a valid model endpoint URL.', mbError, MB_OK);
      Result := False;
      exit;
    end;
  end;

  if (CurPageID = OfflinePackagePage.ID) and ((not IsOnlineMode) or (ModelSource = 'offline')) then
  begin
    if Trim(OfflinePackagePage.Values[0]) = '' then
    begin
      if not IsUpgradeInstall() then
      begin
        MsgBox('Please select one offline tar package.', mbError, MB_OK);
        Result := False;
        exit;
      end;
      ModelSource := 'none';
    end
    else if not IsOnlineMode then
    begin
      ModelSource := 'offline';
    end;
  end;
end;

function GetInstallFlags(Param: String): String;
begin
  Result := '';
  if IsUpgradeInstall() then
    Result := Result + '--existing-install ';

  if UseResourcePackage then
  begin
    Result := Result + '-o --model-source offline ';
    if Trim(OfflinePackagePage.Values[0]) <> '' then
      Result := Result + '--offline-package ' + AddQuotes(Trim(OfflinePackagePage.Values[0])) + ' '
    else if Trim(ResourcePackageUrl) <> '' then
      Result := Result + '--resource-package-url ' + AddQuotes(Trim(ResourcePackageUrl)) + ' ';
  end;
  if UseClassicOnlineInstall and (not InstallTensorFlow) then
    Result := Result + '--skip-tensorflow ';
  if UseClassicOnlineInstall and (ModelSource <> 'none') then
  begin
    Result := Result + '--model-source ' + ModelSource + ' ';
    if ModelSource = 'online' then
    begin
      if SelectTdtsfm then Result := Result + '--model tdtsfm ';
      if SelectTimemoe then Result := Result + '--model timemoe ';
      if SelectMoirai then Result := Result + '--model moirai ';
      if SelectChronos then Result := Result + '--model chronos ';
      if SelectTimesfm then Result := Result + '--model timesfm ';
      if SelectMoment then Result := Result + '--model moment ';
    end;
  end;
  if UseClassicOnlineInstall and (PipIndexUrl <> '') then
  begin
    Result := Result + '--pip-index-url ' + AddQuotes(PipIndexUrl) + ' ';
    if PipTrustedHost <> '' then
      Result := Result + '--pip-trusted-host ' + AddQuotes(PipTrustedHost) + ' ';
  end;
  if UseClassicOnlineInstall and (ModelSource = 'online') and (ModelEndpoint <> '') then
    Result := Result + '--model-endpoint ' + AddQuotes(ModelEndpoint) + ' ';
  Result := Trim(Result);
end;

function UpdateReadyMemo(Space, NewLine, MemoUserInfoInfo, MemoDirInfo, MemoTypeInfo,
  MemoComponentsInfo, MemoGroupInfo, MemoTasksInfo: String): String;
var
  S: String;
begin
  S := MemoDirInfo + NewLine + NewLine;
  if IsUpgradeInstall() then
    S := S + 'Install type:' + NewLine + Space + 'Upgrade (reuse existing venv/model by default)' + NewLine
  else
    S := S + 'Install type:' + NewLine + Space + 'First install' + NewLine;
  S := S + 'Installer package:' + NewLine + Space + GetInstallerPackageSummary() + NewLine;
  S := S + 'TDgpt resource package:' + NewLine + Space;
  if UseResourcePackage then
    S := S + 'Download and import' + NewLine
  else if UseClassicOnlineInstall then
    S := S + 'Classic online installation' + NewLine
  else
    S := S + 'Do not install now' + NewLine;
  S := S + 'TensorFlow CPU support:' + NewLine + Space;
  if UseResourcePackage then
  begin
    S := S + 'Included in the imported resource package' + NewLine;
  end
  else if InstallTensorFlow then
    S := S + 'Install' + NewLine
  else
    S := S + 'Skip' + NewLine;
  S := S + 'Model source:' + NewLine + Space + GetModelSourceSummary() + NewLine;
  S := S + 'Model handling:' + NewLine + Space + GetModelSelectionSummary() + NewLine;
  if Trim(OfflinePackagePage.Values[0]) <> '' then
    S := S + 'Local resource package:' + NewLine + Space + Trim(OfflinePackagePage.Values[0]) + NewLine;
  if UseResourcePackage and (Trim(OfflinePackagePage.Values[0]) = '') and (Trim(ResourcePackageUrl) <> '') then
    S := S + 'Resource package URL:' + NewLine + Space + Trim(ResourcePackageUrl) + NewLine;
  if UseResourcePackage and (Trim(OfflinePackagePage.Values[0]) = '') and IsUpgradeInstall() and (Trim(ResourcePackageUrl) = '') then
    S := S + 'Resource package:' + NewLine + Space + 'Reuse current resource files' + NewLine;
  if PipIndexUrl <> '' then
    S := S + 'pip source:' + NewLine + Space + PipIndexUrl + NewLine;
  if ModelEndpoint <> '' then
    S := S + 'Model endpoint:' + NewLine + Space + ModelEndpoint + NewLine;
  if not UseResourcePackage and not UseClassicOnlineInstall then
    S := S + 'IDMP impact:' + NewLine + Space + 'Prediction algorithms that depend on the time-series foundation model service and value imputation will not work normally.' + NewLine;
  S := S + 'Windows service:' + NewLine + Space + 'Installed automatically' + NewLine;
  Result := S;
end;

procedure UpdateFinishedPageText();
var
  Notes: String;
begin
  WizardForm.FinishedHeadingLabel.Caption := '{#MyAppName} installation completed';
  WizardForm.FinishedLabel.AutoSize := False;
  WizardForm.FinishedLabel.Width := WizardForm.FinishedPage.ClientWidth - WizardForm.FinishedLabel.Left;
  WizardForm.FinishedLabel.Caption :=
    'Installation is complete. Please review the installation log before closing Setup. ' +
    'The log checkbox below is selected by default; clear it if you do not want to open the log file.';
  WizardForm.AdjustLabelHeight(WizardForm.FinishedLabel);
  FinishNotesLabel.Top := WizardForm.FinishedLabel.Top + WizardForm.FinishedLabel.Height + ScaleY(6);
  Notes := 'Installation log:' + #13#10 + '  ' + ExpandConstant('{app}\log\install.log') + #13#10 + #13#10;
  Notes := Notes + 'Windows service commands:' + #13#10;
  Notes := Notes + '  Start: net start Taosanode' + #13#10;
  Notes := Notes + '  Stop:  net stop Taosanode' + #13#10;
  Notes := Notes + '  Status: ' + ExpandConstant('{app}\bin\status-taosanode.bat') + #13#10 + #13#10;
  Notes := Notes + 'Prepared models:' + #13#10 + '  ' + GetModelSelectionSummary() + #13#10 + #13#10;
  Notes := Notes + 'Script commands:' + #13#10;
  Notes := Notes + '  Start: ' + ExpandConstant('{app}\bin\start-taosanode.bat') + #13#10;
  Notes := Notes + '  Stop:  ' + ExpandConstant('{app}\bin\stop-taosanode.bat') + #13#10;
  Notes := Notes + '  Models start: ' + ExpandConstant('{app}\bin\start-model.bat') + ' (no argument defaults to all existing models)' + #13#10;
  Notes := Notes + '  Models stop:  ' + ExpandConstant('{app}\bin\stop-model.bat all') + #13#10;
  Notes := Notes + '  Models status: ' + ExpandConstant('{app}\bin\status-model.bat');
  FinishNotesLabel.Caption := Notes;
  WizardForm.AdjustLabelHeight(FinishNotesLabel);
  FinishNotesLabel.Visible := True;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpFinished then
    UpdateFinishedPageText()
  else
    FinishNotesLabel.Visible := False;
end;

procedure ShowInstallFailureAndAbort(TitleValue: String; DetailValue: String);
var
  MessageText: String;
begin
  if Trim(TitleValue) = '' then
    TitleValue := 'Installation failed';
  if Trim(DetailValue) = '' then
    DetailValue := 'See install.log for details.';

  MessageText := TitleValue + #13#10 + #13#10 +
    DetailValue + #13#10 + #13#10 +
    'Log file:' + #13#10 + ExpandConstant('{app}\log\install.log');

  MsgBox(MessageText, mbCriticalError, MB_OK);
  WizardForm.Close;
  Abort;
end;

function TryParseProgressLine(LineValue: String; var StatusValue: String; var PercentValue: Integer;
  var TitleValue: String; var DetailValue: String): Boolean;
var
  Pos1: Integer;
  Pos2: Integer;
  Pos3: Integer;
  Rest: String;
begin
  Result := False;
  LineValue := Trim(LineValue);
  if LineValue = '' then
    exit;

  Pos1 := Pos('|', LineValue);
  if Pos1 = 0 then
    exit;
  StatusValue := Copy(LineValue, 1, Pos1 - 1);
  Rest := Copy(LineValue, Pos1 + 1, MaxInt);

  Pos2 := Pos('|', Rest);
  if Pos2 = 0 then
    exit;
  PercentValue := StrToIntDef(Copy(Rest, 1, Pos2 - 1), -1);
  if PercentValue < 0 then
    exit;
  Rest := Copy(Rest, Pos2 + 1, MaxInt);

  Pos3 := Pos('|', Rest);
  if Pos3 = 0 then
    exit;
  TitleValue := Copy(Rest, 1, Pos3 - 1);
  DetailValue := Copy(Rest, Pos3 + 1, MaxInt);
  Result := True;
end;

function ReadLatestProgressEntry(ProgressFile: String; var StatusValue: String; var PercentValue: Integer;
  var TitleValue: String; var DetailValue: String): Boolean;
var
  RawText: String;
  RawTextAnsi: AnsiString;
  LineValue: String;
  BreakPos: Integer;
  I: Integer;
begin
  Result := False;
  if not FileExists(ProgressFile) then
    exit;
  if not LoadStringFromFile(ProgressFile, RawTextAnsi) then
    exit;
  RawText := RawTextAnsi;

  StringChangeEx(RawText, #13#10, #10, True);
  StringChangeEx(RawText, #13, #10, True);
  RawText := Trim(RawText);
  while RawText <> '' do
  begin
    BreakPos := 0;
    for I := Length(RawText) downto 1 do
    begin
      if RawText[I] = #10 then
      begin
        BreakPos := I;
        break;
      end;
    end;
    if BreakPos > 0 then
    begin
      LineValue := Copy(RawText, BreakPos + 1, MaxInt);
      RawText := Trim(Copy(RawText, 1, BreakPos - 1));
    end
    else
    begin
      LineValue := RawText;
      RawText := '';
    end;
    if TryParseProgressLine(LineValue, StatusValue, PercentValue, TitleValue, DetailValue) then
    begin
      Result := True;
      exit;
    end;
  end;
end;

procedure WaitForPostInstall();
var
  ResultCode: Integer;
  ProgressFile: String;
  CmdArgs: String;
  StatusValue: String;
  PercentValue: Integer;
  TitleValue: String;
  DetailValue: String;
  FirstProgressSeen: Boolean;
begin
  ProgressFile := ExpandConstant('{app}\log\install-progress.log');
  FirstProgressSeen := False;
  DeleteFile(ProgressFile);
  LogTdgpt('WaitForPostInstall start, progress file=' + ProgressFile);
  InstallProgressPage.SetText('Installing {#MyAppName}', 'Preparing post-install tasks...');
  InstallProgressPage.SetProgress(0, 100);
  WizardForm.CancelButton.Enabled := False;
  InstallProgressPage.Show;
  try
    CmdArgs := '/C set "TDGPT_PROGRESS_FILE=' + ProgressFile + '" && call "' +
      ExpandConstant('{app}\install.bat') + '" ' + GetInstallFlags('');
    LogTdgpt('WaitForPostInstall launching helper: ' + CmdArgs);
    if not Exec(ExpandConstant('{cmd}'), CmdArgs, '', SW_HIDE, ewNoWait, ResultCode) then
      RaiseException('Failed to start the {#MyAppName} installation helper.');

    while True do
    begin
      if not ReadLatestProgressEntry(ProgressFile, StatusValue, PercentValue, TitleValue, DetailValue) then
      begin
        StatusValue := '';
        TitleValue := 'Installing {#MyAppName}';
        DetailValue := 'Please wait...';
        PercentValue := 0;
      end;
      if (not FirstProgressSeen) and (StatusValue <> '') then
      begin
        FirstProgressSeen := True;
        LogTdgpt('WaitForPostInstall received first progress event: ' + StatusValue + '|' + IntToStr(PercentValue) + '|' + TitleValue);
      end;
      InstallProgressPage.SetText(TitleValue, DetailValue);
      InstallProgressPage.SetProgress(PercentValue, 100);
      if StatusValue = 'success' then
      begin
        LogTdgpt('WaitForPostInstall completed successfully');
        break;
      end;
      if StatusValue = 'error' then
      begin
        LogTdgpt('WaitForPostInstall received error status: ' + TitleValue + ' | ' + DetailValue);
        ShowInstallFailureAndAbort(TitleValue, DetailValue);
      end;
      Sleep(400);
    end;
  finally
    LogTdgpt('WaitForPostInstall end');
    InstallProgressPage.Hide;
    WizardForm.CancelButton.Enabled := True;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  case CurStep of
    ssInstall: LogTdgpt('CurStepChanged: ssInstall');
    ssPostInstall: LogTdgpt('CurStepChanged: ssPostInstall');
    ssDone: LogTdgpt('CurStepChanged: ssDone');
  end;
  if (CurStep = ssPostInstall) and (not PostInstallCompleted) then
  begin
    PostInstallCompleted := True;
    WaitForPostInstall();
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    if FileExists(ExpandConstant('{app}\taosanode.pid')) then
      DeleteFile(ExpandConstant('{app}\taosanode.pid'));
  end;
end;
