PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/client/inc)
INCLUDE_DIRECTORIES(inc)

IF(TD_LINUX)
  AUX_SOURCE_DIRECTORY(./src SRC)
  ADD_LIBRARY(taosodbc SHARED ${SRC})
  TARGET_LINK_LIBRARIES(taosodbc taos_static odbcinst)
  SET_TARGET_PROPERTIES(taosodbc PROPERTIES CLEAN_DIRECT_OUTPUT 1)
ELSEIF(TD_WINDOWS)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/deps/pthread)
  INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/deps/regex)
  AUX_SOURCE_DIRECTORY(./src SRC)
  LIST(APPEND SRC ./res/odbcResource.rc)
  ADD_LIBRARY(taosodbc SHARED ${SRC})
  TARGET_LINK_LIBRARIES(taosodbc taos_static odbc32 odbccp32)
  SET_TARGET_PROPERTIES(taosodbc PROPERTIES LINK_FLAGS /DEF:${TD_ENTERPRISE_DIR}/source/connector/odbc/src/odbc.def)
ELSEIF(TD_DARWIN)
ENDIF()
