import math
import numpy as np
import platform
import random
import re
import subprocess
import sys
import time

from new_test_framework.utils import tdLog, tdSql, sc, clusterComCheck,tdDnodes
from wsgiref.headers import tspecials

msec_per_min=60*1000


class TestFunFillforward:

    def setup_class(cls):
        tdLog.debug(f"start to execute {__file__}")

    #
    # ------------------ main ------------------
    #
    def test_func_win_fill_forward(self):
        """ Fun: fill_forward()

        1. Sim case for LIKE, timestamp comparisons, and ordinary column comparisons.
        2. Basic query for input different params
        3. Query on super/child/normal table
        4. Support types
        5. Error cases
        6. Query with where condition
        7. Query with group/partition/order by
        8. Query with tags
        9. Query with join/union/nest/interval
        10. Query with limit/slimit/offset/soffset
        11. Check null value

        Since: v3.4.0.0

        Labels: common,ci

        Jira: None

        History:
        History:
            - 2025-11-28 Stephen Jin Create the fill_forward function

        """
        self.fill_forward_smoke()
        self.fill_forward_input_types()
        self.fill_forward_with_stable()
        self.fill_forward_with_vtable()
        self.fill_forward_error()

    #
    # ------------------ smoke case ------------------
    #
    def fill_forward_smoke(self):
        self.basic()
        print("\nsmoke testing ......................... [passed]")

    def basic(self):
        vgroups = 1
        dbName = "db"
        tbName = "tb"

        tdLog.info(f"=============== step 0")
        tdSql.execute(f"create database {dbName} vgroups {vgroups}")
        tdLog.info(f"=============== step 1 bool, int, float, double")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 float, f3 bool, f4 double)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', 1, 2, 1, 3)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 4, null, 5)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null, 0, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 8, 1, 9)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)

        tdLog.info(f"=============== step 2")
        tdSql.execute(f"drop table {dbName}.{tbName}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 float, f3 bool, f4 double)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', null, null, null, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 4, null, 7)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null, 1, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 8, 0, 9)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, None)
        tdSql.checkData(0, 2, None)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, None)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, None)
        tdSql.checkData(0, 7, None)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, None)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, None)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, None)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, None)
        tdSql.checkData(1, 4, None)
        tdSql.checkData(1, 5, None)
        tdSql.checkData(1, 6, None)
        tdSql.checkData(1, 7, 7)
        tdSql.checkData(1, 8, None)
        tdSql.checkData(1, 9, 28)
        tdSql.checkData(1, 10, None)
        tdSql.checkData(1, 11, 49)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 1)
        tdSql.checkData(2, 5, 4)
        tdSql.checkData(2, 6, 5)
        tdSql.checkData(2, 7, 7)
        tdSql.checkData(2, 8, 35)
        tdSql.checkData(2, 9, 28)
        tdSql.checkData(2, 10, 7)
        tdSql.checkData(2, 11, 49)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 0)
        tdSql.checkData(3, 5, 0)
        tdSql.checkData(3, 6, 0)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 0)
        tdSql.checkData(3, 11, 81)

        tdLog.info(f"=============== step 3 decimal")
        tdSql.execute(f"drop table {dbName}.{tbName}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 decimal(8, 6))")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', 1, 2)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 4)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 8)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)

        tdLog.info(f"=============== step 4")
        tdSql.execute(f"drop table {dbName}.{tbName}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 decimal(8, 6))")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', null, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 4)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 8)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, None)
        tdSql.checkData(0, 2, None)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, None)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, None)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)

        tdLog.info(f"=============== step 5 varchar")
        tdSql.execute(f"drop table {dbName}.{tbName}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 varchar(8))")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', 1, 'a')")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 'ab')")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 'cdef')")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 'a')
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 'ab')
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 'ab')
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 'cdef')

        tdLog.info(f"=============== step 6")
        tdSql.execute(f"drop table {dbName}.{tbName}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 varchar(8))")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', null, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 'abc')")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 'def')")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, None)
        tdSql.checkData(0, 2, None)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, None)
        tdSql.checkData(1, 2, 'abc')
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 'abc')
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 'def')

    def fill_forward_input_types(self):
        vgroups = 4
        dbName = "db"
        tbName = "tb"

        tdLog.info(f"=============== step 0")
        tdSql.execute(f"drop database if exists {dbName}")
        tdSql.execute(f"create database {dbName} vgroups {vgroups}")
        tdLog.info(f"=============== step 1 all supported types")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 float, f3 bool, f4 double, f5 tinyint, f6 smallint, f7 bigint, f8 varchar(8), f9 nchar(8), f10 varbinary(8), f11 binary(8), f12 decimal(8,6))")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', 1, 2, 1, 3, null, 6, null, 'vc', null, 'vb', null, 12)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 4, null, 5, 5, null, 7, null, 'nc', null, 'binary', null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null, 0, null, null, null, null, null, null, null, null, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 8, 1, 9, null, null, null, null, null, null, null, null)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4), fill_forward(f5), fill_forward(f6), fill_forward(f7), fill_forward(f8), fill_forward(f9), fill_forward(f10), fill_forward(f11), fill_forward(f12) from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(0, 12, None) # f5
        tdSql.checkData(0, 13, 6) # f6
        tdSql.checkData(0, 14, None) # f7
        tdSql.checkData(0, 15, 'vc') # f8
        tdSql.checkData(0, 16, None) # f9
        tdSql.checkData(0, 17, b'vb') # f10
        tdSql.checkData(0, 18, None) # f11
        tdSql.checkData(0, 19, 12) # f12
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(1, 12, 5)
        tdSql.checkData(1, 13, 6)
        tdSql.checkData(1, 14, 7)
        tdSql.checkData(1, 15, 'vc')
        tdSql.checkData(1, 16, 'nc')
        tdSql.checkData(1, 17, b'vb')
        tdSql.checkData(1, 18, 'binary')
        tdSql.checkData(1, 19, 12)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(2, 12, 5)
        tdSql.checkData(2, 13, 6)
        tdSql.checkData(2, 14, 7)
        tdSql.checkData(2, 15, 'vc')
        tdSql.checkData(2, 16, 'nc')
        tdSql.checkData(2, 17, b'vb')
        tdSql.checkData(2, 18, 'binary')
        tdSql.checkData(2, 19, 12)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)
        tdSql.checkData(3, 12, 5)
        tdSql.checkData(3, 13, 6)
        tdSql.checkData(3, 14, 7)
        tdSql.checkData(3, 15, 'vc')
        tdSql.checkData(3, 16, 'nc')
        tdSql.checkData(3, 17, b'vb')
        tdSql.checkData(3, 18, 'binary')
        tdSql.checkData(3, 19, 12)

        tdSql.query(f"SELECT fill_forward(null)")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, None)

    def fill_forward_with_stable(self):
        vgroups = 4
        dbName = "db"
        tbName = "stb"
        ctbName = "ctb"

        tdLog.info(f"=============== step 0")
        tdSql.execute(f"drop database if exists {dbName}")
        tdSql.execute(f"create database {dbName} vgroups {vgroups}")
        tdLog.info(f"=============== step 1 bool, int, float, double")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 float, f3 bool, f4 double) tags(t1 int)")
        tdSql.execute(f"insert into {dbName}.{ctbName}0 using {dbName}.{tbName} tags(0) values('2025-12-2 1:1:1', 1, 2, 1, 3)")
        tdSql.execute(f"insert into {dbName}.{ctbName}1 using {dbName}.{tbName} tags(1) values('2025-12-2 1:1:2', null, 4, null, 5)")
        tdSql.execute(f"insert into {dbName}.{ctbName}2 using {dbName}.{tbName} tags(2) values('2025-12-2 1:1:3', 5, null, 0, null)")
        tdSql.execute(f"insert into {dbName}.{ctbName}3 using {dbName}.{tbName} tags(3) values('2025-12-2 1:1:4', 7, 8, 1, 9)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)

        tdSql.execute(f"insert into {dbName}.{ctbName}0 using {dbName}.{tbName} tags(0) values('2025-12-2 1:1:2', null, 4, null, 5)")
        tdSql.execute(f"insert into {dbName}.{ctbName}0 using {dbName}.{tbName} tags(0) values('2025-12-2 1:1:3', 5, null, 0, null)")
        tdSql.execute(f"insert into {dbName}.{ctbName}0 using {dbName}.{tbName} tags(0) values('2025-12-2 1:1:4', 7, 8, 1, 9)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{ctbName}0")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)

        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{ctbName}0 where _rowts <= '2025-12-2 1:1:4' and _rowts >= '2025-12-2 1:1:1'")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)

        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{ctbName}0 where _rowts <= '2025-12-2 1:1:3' and _rowts >= '2025-12-2 1:1:2' order by _rowts asc")
        tdSql.checkRows(2)
        tdSql.checkData(0, 0, '2025-12-2 1:1:2')
        tdSql.checkData(0, 1, None)
        tdSql.checkData(0, 2, 4)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, None)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, None)
        tdSql.checkData(0, 7, 5)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, 20)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, 25)
        tdSql.checkData(1, 0, '2025-12-2 1:1:3')
        tdSql.checkData(1, 1, 5)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 20)
        tdSql.checkData(1, 4, 0)
        tdSql.checkData(1, 5, 0)
        tdSql.checkData(1, 6, 0)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 25)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 0)
        tdSql.checkData(1, 11, 25)

        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from (select * from {dbName}.{ctbName}0 where _rowts <= '2025-12-2 1:1:3' and _rowts >= '2025-12-2 1:1:2' order by _rowts desc)")
        tdSql.checkRows(2)
        tdSql.checkData(0, 0, '2025-12-2 1:1:3')
        tdSql.checkData(0, 1, 5)
        tdSql.checkData(0, 2, None)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, 0)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, 0)
        tdSql.checkData(0, 7, None)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, None)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, None)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 5)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 20)
        tdSql.checkData(1, 4, 0)
        tdSql.checkData(1, 5, 0)
        tdSql.checkData(1, 6, 0)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 25)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 0)
        tdSql.checkData(1, 11, 25)

        tdLog.info(f"=============== step 2 partition by")
        tdSql.execute(f"drop database if exists {dbName}")
        tdSql.execute(f"create database {dbName} vgroups {vgroups}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 double) tags(t1 int)")
        tdSql.execute(f"insert into {dbName}.{ctbName}0 using {dbName}.{tbName} tags(0) values('2025-12-2 1:1:1', 1, 2)")
        tdSql.execute(f"insert into {dbName}.{ctbName}0 using {dbName}.{tbName} tags(0) values('2025-12-2 1:1:2', null, null)")
        tdSql.execute(f"insert into {dbName}.{ctbName}1 using {dbName}.{tbName} tags(1) values('2025-12-2 1:1:1', null, null)")
        tdSql.execute(f"insert into {dbName}.{ctbName}1 using {dbName}.{tbName} tags(1) values('2025-12-2 1:1:2', 1, 2)")
        tdSql.execute(f"insert into {dbName}.{ctbName}2 using {dbName}.{tbName} tags(2) values('2025-12-2 1:1:1', 1, null)")
        tdSql.execute(f"insert into {dbName}.{ctbName}2 using {dbName}.{tbName} tags(2) values('2025-12-2 1:1:2', null, 2)")
        tdSql.execute(f"insert into {dbName}.{ctbName}3 using {dbName}.{tbName} tags(3) values('2025-12-2 1:1:1', null, 1)")
        tdSql.execute(f"insert into {dbName}.{ctbName}3 using {dbName}.{tbName} tags(3) values('2025-12-2 1:1:2', null, null)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p from {dbName}.{tbName} partition by tbname")
        tdSql.checkRows(8)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 2)
        tdSql.checkData(1, 3, 2)
        tdSql.checkData(2, 0, '2025-12-2 1:1:1')
        tdSql.checkData(2, 1, None)
        tdSql.checkData(2, 2, None)
        tdSql.checkData(2, 3, None)
        tdSql.checkData(3, 0, '2025-12-2 1:1:2')
        tdSql.checkData(3, 1, 1)
        tdSql.checkData(3, 2, 2)
        tdSql.checkData(3, 3, 2)
        tdSql.checkData(4, 0, '2025-12-2 1:1:1')
        tdSql.checkData(4, 1, 1)
        tdSql.checkData(4, 2, None)
        tdSql.checkData(4, 3, None)
        tdSql.checkData(5, 0, '2025-12-2 1:1:2')
        tdSql.checkData(5, 1, 1)
        tdSql.checkData(5, 2, 2)
        tdSql.checkData(5, 3, 2)
        tdSql.checkData(6, 0, '2025-12-2 1:1:1')
        tdSql.checkData(6, 1, None)
        tdSql.checkData(6, 2, 1)
        tdSql.checkData(6, 3, None)
        tdSql.checkData(7, 0, '2025-12-2 1:1:2')
        tdSql.checkData(7, 1, None)
        tdSql.checkData(7, 2, 1)
        tdSql.checkData(7, 3, None)

    def fill_forward_with_vtable(self):
        vgroups = 4
        dbName = "db"
        tbName = "tb"
        vtName = "vt"

        tdLog.info(f"=============== step 0")
        tdSql.execute(f"drop database if exists {dbName}")
        tdSql.execute(f"create database {dbName} vgroups {vgroups}")
        tdLog.info(f"=============== step 1 bool, int, float, double")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 int, f2 float, f3 bool, f4 double)")
        tdSql.execute(f"create vtable {dbName}.{vtName}(ts timestamp, f1 int from {dbName}.{tbName}.f1, f2 float from {dbName}.{tbName}.f2, f3 bool from {dbName}.{tbName}.f3, f4 double from {dbName}.{tbName}.f4)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:1', 1, 2, 1, 3)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:2', null, 4, null, 5)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:3', 5, null, 0, null)")
        tdSql.execute(f"insert into {dbName}.{tbName} values('2025-12-2 1:1:4', 7, 8, 1, 9)")
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{tbName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{vtName}")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)

        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{tbName} where _rowts <= '2025-12-2 1:1:4' and _rowts >= '2025-12-2 1:1:1'")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{vtName} where _rowts <= '2025-12-2 1:1:4' and _rowts >= '2025-12-2 1:1:1'")
        tdSql.checkRows(4)
        tdSql.checkData(0, 0, '2025-12-2 1:1:1')
        tdSql.checkData(0, 1, 1)
        tdSql.checkData(0, 2, 2)
        tdSql.checkData(0, 3, 2)
        tdSql.checkData(0, 4, 1)
        tdSql.checkData(0, 5, 2)
        tdSql.checkData(0, 6, 1)
        tdSql.checkData(0, 7, 3)
        tdSql.checkData(0, 8, 3)
        tdSql.checkData(0, 9, 6)
        tdSql.checkData(0, 10, 3)
        tdSql.checkData(0, 11, 9)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 1)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 4)
        tdSql.checkData(1, 4, 1)
        tdSql.checkData(1, 5, 4)
        tdSql.checkData(1, 6, 1)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 5)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 5)
        tdSql.checkData(1, 11, 25)
        tdSql.checkData(2, 0, '2025-12-2 1:1:3')
        tdSql.checkData(2, 1, 5)
        tdSql.checkData(2, 2, 4)
        tdSql.checkData(2, 3, 20)
        tdSql.checkData(2, 4, 0)
        tdSql.checkData(2, 5, 0)
        tdSql.checkData(2, 6, 0)
        tdSql.checkData(2, 7, 5)
        tdSql.checkData(2, 8, 25)
        tdSql.checkData(2, 9, 20)
        tdSql.checkData(2, 10, 0)
        tdSql.checkData(2, 11, 25)
        tdSql.checkData(3, 0, '2025-12-2 1:1:4')
        tdSql.checkData(3, 1, 7)
        tdSql.checkData(3, 2, 8)
        tdSql.checkData(3, 3, 56)
        tdSql.checkData(3, 4, 1)
        tdSql.checkData(3, 5, 8)
        tdSql.checkData(3, 6, 7)
        tdSql.checkData(3, 7, 9)
        tdSql.checkData(3, 8, 63)
        tdSql.checkData(3, 9, 72)
        tdSql.checkData(3, 10, 9)
        tdSql.checkData(3, 11, 81)

        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{tbName} where _rowts <= '2025-12-2 1:1:3' and _rowts >= '2025-12-2 1:1:2' order by _rowts asc")
        tdSql.checkRows(2)
        tdSql.checkData(0, 0, '2025-12-2 1:1:2')
        tdSql.checkData(0, 1, None)
        tdSql.checkData(0, 2, 4)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, None)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, None)
        tdSql.checkData(0, 7, 5)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, 20)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, 25)
        tdSql.checkData(1, 0, '2025-12-2 1:1:3')
        tdSql.checkData(1, 1, 5)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 20)
        tdSql.checkData(1, 4, 0)
        tdSql.checkData(1, 5, 0)
        tdSql.checkData(1, 6, 0)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 25)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 0)
        tdSql.checkData(1, 11, 25)
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from {dbName}.{vtName} where _rowts <= '2025-12-2 1:1:3' and _rowts >= '2025-12-2 1:1:2' order by _rowts asc")
        tdSql.checkRows(2)
        tdSql.checkData(0, 0, '2025-12-2 1:1:2')
        tdSql.checkData(0, 1, None)
        tdSql.checkData(0, 2, 4)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, None)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, None)
        tdSql.checkData(0, 7, 5)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, 20)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, 25)
        tdSql.checkData(1, 0, '2025-12-2 1:1:3')
        tdSql.checkData(1, 1, 5)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 20)
        tdSql.checkData(1, 4, 0)
        tdSql.checkData(1, 5, 0)
        tdSql.checkData(1, 6, 0)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 25)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 0)
        tdSql.checkData(1, 11, 25)

        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from (select * from {dbName}.{tbName} where _rowts <= '2025-12-2 1:1:3' and _rowts >= '2025-12-2 1:1:2' order by _rowts desc)")
        tdSql.checkRows(2)
        tdSql.checkData(0, 0, '2025-12-2 1:1:3')
        tdSql.checkData(0, 1, 5)
        tdSql.checkData(0, 2, None)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, 0)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, 0)
        tdSql.checkData(0, 7, None)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, None)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, None)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 5)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 20)
        tdSql.checkData(1, 4, 0)
        tdSql.checkData(1, 5, 0)
        tdSql.checkData(1, 6, 0)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 25)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 0)
        tdSql.checkData(1, 11, 25)
        tdSql.query(f"SELECT _rowts, fill_forward(f1) f1l, fill_forward(f2) f2l, fill_forward(f1)*fill_forward(f2) p, fill_forward(f3), fill_forward(f3)*fill_forward(f2), fill_forward(f3)*fill_forward(f1), fill_forward(f4), fill_forward(f4)*fill_forward(f1), fill_forward(f4)*fill_forward(f2), fill_forward(f4)*fill_forward(f3), fill_forward(f4)*fill_forward(f4) from (select * from {dbName}.{vtName} where _rowts <= '2025-12-2 1:1:3' and _rowts >= '2025-12-2 1:1:2' order by _rowts desc)")
        tdSql.checkRows(2)
        tdSql.checkData(0, 0, '2025-12-2 1:1:3')
        tdSql.checkData(0, 1, 5)
        tdSql.checkData(0, 2, None)
        tdSql.checkData(0, 3, None)
        tdSql.checkData(0, 4, 0)
        tdSql.checkData(0, 5, None)
        tdSql.checkData(0, 6, 0)
        tdSql.checkData(0, 7, None)
        tdSql.checkData(0, 8, None)
        tdSql.checkData(0, 9, None)
        tdSql.checkData(0, 10, None)
        tdSql.checkData(0, 11, None)
        tdSql.checkData(1, 0, '2025-12-2 1:1:2')
        tdSql.checkData(1, 1, 5)
        tdSql.checkData(1, 2, 4)
        tdSql.checkData(1, 3, 20)
        tdSql.checkData(1, 4, 0)
        tdSql.checkData(1, 5, 0)
        tdSql.checkData(1, 6, 0)
        tdSql.checkData(1, 7, 5)
        tdSql.checkData(1, 8, 25)
        tdSql.checkData(1, 9, 20)
        tdSql.checkData(1, 10, 0)
        tdSql.checkData(1, 11, 25)

    def fill_forward_error(self):
        vgroups = 1
        dbName = "db"
        tbName = "tb"

        tdSql.execute(f"drop database if exists {dbName}")
        tdSql.execute(f"create database {dbName} vgroups {vgroups}")

        tdLog.info(f"====> fill_forward blob")

        f = 'fill_forward'
        
        tdSql.execute(f"drop table if exists {dbName}.{tbName}")
        tdSql.execute(f"create table {dbName}.{tbName}(ts timestamp, f1 blob)")
        tdSql.execute(f"insert into {dbName}.{tbName} values(now, 'abc')")
        tdSql.errors([f"select {f}(f1) from {dbName}.{tbName}"])
