#define TK_OR                               1
#define TK_AND                              2
#define TK_UNION                            3
#define TK_ALL                              4
#define TK_MINUS                            5
#define TK_EXCEPT                           6
#define TK_INTERSECT                        7
#define TK_NK_BITAND                        8
#define TK_NK_BITOR                         9
#define TK_NK_LSHIFT                       10
#define TK_NK_RSHIFT                       11
#define TK_NK_PLUS                         12
#define TK_NK_MINUS                        13
#define TK_NK_STAR                         14
#define TK_NK_SLASH                        15
#define TK_NK_REM                          16
#define TK_NK_CONCAT                       17
#define TK_CREATE                          18
#define TK_ACCOUNT                         19
#define TK_NK_ID                           20
#define TK_PASS                            21
#define TK_NK_STRING                       22
#define TK_ALTER                           23
#define TK_PPS                             24
#define TK_TSERIES                         25
#define TK_STORAGE                         26
#define TK_STREAMS                         27
#define TK_QTIME                           28
#define TK_DBS                             29
#define TK_USERS                           30
#define TK_CONNS                           31
#define TK_STATE                           32
#define TK_NK_COMMA                        33
#define TK_HOST                            34
#define TK_IS_IMPORT                       35
#define TK_NK_INTEGER                      36
#define TK_CREATEDB                        37
#define TK_USER                            38
#define TK_ENABLE                          39
#define TK_SYSINFO                         40
#define TK_ADD                             41
#define TK_DROP                            42
#define TK_GRANT                           43
#define TK_ON                              44
#define TK_TO                              45
#define TK_REVOKE                          46
#define TK_FROM                            47
#define TK_SUBSCRIBE                       48
#define TK_READ                            49
#define TK_WRITE                           50
#define TK_NK_DOT                          51
#define TK_WITH                            52
#define TK_ENCRYPT_KEY                     53
#define TK_ANODE                           54
#define TK_UPDATE                          55
#define TK_ANODES                          56
#define TK_DNODE                           57
#define TK_PORT                            58
#define TK_DNODES                          59
#define TK_RESTORE                         60
#define TK_NK_IPTOKEN                      61
#define TK_FORCE                           62
#define TK_UNSAFE                          63
#define TK_CLUSTER                         64
#define TK_LOCAL                           65
#define TK_QNODE                           66
#define TK_BNODE                           67
#define TK_SNODE                           68
#define TK_MNODE                           69
#define TK_VNODE                           70
#define TK_DATABASE                        71
#define TK_USE                             72
#define TK_FLUSH                           73
#define TK_TRIM                            74
#define TK_S3MIGRATE                       75
#define TK_COMPACT                         76
#define TK_VGROUPS                         77
#define TK_IN                              78
#define TK_NK_LP                           79
#define TK_NK_RP                           80
#define TK_IF                              81
#define TK_NOT                             82
#define TK_EXISTS                          83
#define TK_BUFFER                          84
#define TK_CACHEMODEL                      85
#define TK_CACHESIZE                       86
#define TK_COMP                            87
#define TK_DURATION                        88
#define TK_NK_VARIABLE                     89
#define TK_MAXROWS                         90
#define TK_MINROWS                         91
#define TK_KEEP                            92
#define TK_PAGES                           93
#define TK_PAGESIZE                        94
#define TK_TSDB_PAGESIZE                   95
#define TK_PRECISION                       96
#define TK_REPLICA                         97
#define TK_SINGLE_STABLE                   98
#define TK_RETENTIONS                      99
#define TK_SCHEMALESS                     100
#define TK_WAL_LEVEL                      101
#define TK_WAL_FSYNC_PERIOD               102
#define TK_WAL_RETENTION_PERIOD           103
#define TK_WAL_RETENTION_SIZE             104
#define TK_WAL_ROLL_PERIOD                105
#define TK_WAL_SEGMENT_SIZE               106
#define TK_STT_TRIGGER                    107
#define TK_TABLE_PREFIX                   108
#define TK_TABLE_SUFFIX                   109
#define TK_S3_CHUNKPAGES                  110
#define TK_S3_KEEPLOCAL                   111
#define TK_S3_COMPACT                     112
#define TK_KEEP_TIME_OFFSET               113
#define TK_ENCRYPT_ALGORITHM              114
#define TK_COMPACT_INTERVAL               115
#define TK_COMPACT_TIME_RANGE             116
#define TK_COMPACT_TIME_OFFSET            117
#define TK_NK_COLON                       118
#define TK_BWLIMIT                        119
#define TK_START                          120
#define TK_TIMESTAMP                      121
#define TK_END                            122
#define TK_TABLE                          123
#define TK_USING                          124
#define TK_FILE                           125
#define TK_STABLE                         126
#define TK_COLUMN                         127
#define TK_MODIFY                         128
#define TK_RENAME                         129
#define TK_TAG                            130
#define TK_NK_EQ                          131
#define TK_SET                            132
#define TK_TAGS                           133
#define TK_BOOL                           134
#define TK_TINYINT                        135
#define TK_SMALLINT                       136
#define TK_INT                            137
#define TK_INTEGER                        138
#define TK_BIGINT                         139
#define TK_FLOAT                          140
#define TK_DOUBLE                         141
#define TK_BINARY                         142
#define TK_NCHAR                          143
#define TK_UNSIGNED                       144
#define TK_JSON                           145
#define TK_VARCHAR                        146
#define TK_MEDIUMBLOB                     147
#define TK_BLOB                           148
#define TK_VARBINARY                      149
#define TK_GEOMETRY                       150
#define TK_DECIMAL                        151
#define TK_COMMENT                        152
#define TK_MAX_DELAY                      153
#define TK_WATERMARK                      154
#define TK_ROLLUP                         155
#define TK_TTL                            156
#define TK_SMA                            157
#define TK_DELETE_MARK                    158
#define TK_FIRST                          159
#define TK_LAST                           160
#define TK_SHOW                           161
#define TK_FULL                           162
#define TK_PRIVILEGES                     163
#define TK_DATABASES                      164
#define TK_TABLES                         165
#define TK_STABLES                        166
#define TK_MNODES                         167
#define TK_QNODES                         168
#define TK_ARBGROUPS                      169
#define TK_FUNCTIONS                      170
#define TK_INDEXES                        171
#define TK_ACCOUNTS                       172
#define TK_APPS                           173
#define TK_CONNECTIONS                    174
#define TK_LICENCES                       175
#define TK_GRANTS                         176
#define TK_LOGS                           177
#define TK_MACHINES                       178
#define TK_ENCRYPTIONS                    179
#define TK_QUERIES                        180
#define TK_SCORES                         181
#define TK_TOPICS                         182
#define TK_VARIABLES                      183
#define TK_BNODES                         184
#define TK_SNODES                         185
#define TK_TRANSACTIONS                   186
#define TK_TRANSACTION                    187
#define TK_DISTRIBUTED                    188
#define TK_CONSUMERS                      189
#define TK_SUBSCRIPTIONS                  190
#define TK_VNODES                         191
#define TK_ALIVE                          192
#define TK_VIEWS                          193
#define TK_VIEW                           194
#define TK_COMPACTS                       195
#define TK_DISK_INFO                      196
#define TK_NORMAL                         197
#define TK_CHILD                          198
#define TK_LIKE                           199
#define TK_TBNAME                         200
#define TK_QTAGS                          201
#define TK_AS                             202
#define TK_SYSTEM                         203
#define TK_TSMA                           204
#define TK_INTERVAL                       205
#define TK_RECURSIVE                      206
#define TK_TSMAS                          207
#define TK_FUNCTION                       208
#define TK_INDEX                          209
#define TK_COUNT                          210
#define TK_LAST_ROW                       211
#define TK_META                           212
#define TK_ONLY                           213
#define TK_TOPIC                          214
#define TK_CONSUMER                       215
#define TK_GROUP                          216
#define TK_DESC                           217
#define TK_DESCRIBE                       218
#define TK_RESET                          219
#define TK_QUERY                          220
#define TK_CACHE                          221
#define TK_EXPLAIN                        222
#define TK_ANALYZE                        223
#define TK_VERBOSE                        224
#define TK_NK_BOOL                        225
#define TK_RATIO                          226
#define TK_NK_FLOAT                       227
#define TK_OUTPUTTYPE                     228
#define TK_AGGREGATE                      229
#define TK_BUFSIZE                        230
#define TK_LANGUAGE                       231
#define TK_REPLACE                        232
#define TK_STREAM                         233
#define TK_INTO                           234
#define TK_PAUSE                          235
#define TK_RESUME                         236
#define TK_PRIMARY                        237
#define TK_KEY                            238
#define TK_TRIGGER                        239
#define TK_AT_ONCE                        240
#define TK_WINDOW_CLOSE                   241
#define TK_FORCE_WINDOW_CLOSE             242
#define TK_IGNORE                         243
#define TK_EXPIRED                        244
#define TK_FILL_HISTORY                   245
#define TK_SUBTABLE                       246
#define TK_UNTREATED                      247
#define TK_KILL                           248
#define TK_CONNECTION                     249
#define TK_BALANCE                        250
#define TK_VGROUP                         251
#define TK_LEADER                         252
#define TK_MERGE                          253
#define TK_REDISTRIBUTE                   254
#define TK_SPLIT                          255
#define TK_DELETE                         256
#define TK_INSERT                         257
#define TK_NK_BIN                         258
#define TK_NK_HEX                         259
#define TK_NULL                           260
#define TK_NK_QUESTION                    261
#define TK_NK_ALIAS                       262
#define TK_NK_ARROW                       263
#define TK_ROWTS                          264
#define TK_QSTART                         265
#define TK_QEND                           266
#define TK_QDURATION                      267
#define TK_WSTART                         268
#define TK_WEND                           269
#define TK_WDURATION                      270
#define TK_IROWTS                         271
#define TK_ISFILLED                       272
#define TK_FLOW                           273
#define TK_FHIGH                          274
#define TK_FROWTS                         275
#define TK_IROWTS_ORIGIN                  276
#define TK_CAST                           277
#define TK_POSITION                       278
#define TK_FOR                            279
#define TK_NOW                            280
#define TK_TODAY                          281
#define TK_RAND                           282
#define TK_SUBSTR                         283
#define TK_SUBSTRING                      284
#define TK_BOTH                           285
#define TK_TRAILING                       286
#define TK_LEADING                        287
#define TK_TIMEZONE                       288
#define TK_CLIENT_VERSION                 289
#define TK_SERVER_VERSION                 290
#define TK_SERVER_STATUS                  291
#define TK_CURRENT_USER                   292
#define TK_PI                             293
#define TK_CASE                           294
#define TK_WHEN                           295
#define TK_THEN                           296
#define TK_ELSE                           297
#define TK_BETWEEN                        298
#define TK_IS                             299
#define TK_NK_LT                          300
#define TK_NK_GT                          301
#define TK_NK_LE                          302
#define TK_NK_GE                          303
#define TK_NK_NE                          304
#define TK_MATCH                          305
#define TK_NMATCH                         306
#define TK_CONTAINS                       307
#define TK_JOIN                           308
#define TK_INNER                          309
#define TK_LEFT                           310
#define TK_RIGHT                          311
#define TK_OUTER                          312
#define TK_SEMI                           313
#define TK_ANTI                           314
#define TK_ASOF                           315
#define TK_WINDOW                         316
#define TK_WINDOW_OFFSET                  317
#define TK_JLIMIT                         318
#define TK_SELECT                         319
#define TK_NK_HINT                        320
#define TK_DISTINCT                       321
#define TK_WHERE                          322
#define TK_PARTITION                      323
#define TK_BY                             324
#define TK_SESSION                        325
#define TK_STATE_WINDOW                   326
#define TK_AUTO                           327
#define TK_EVENT_WINDOW                   328
#define TK_COUNT_WINDOW                   329
#define TK_ANOMALY_WINDOW                 330
#define TK_SLIDING                        331
#define TK_FILL                           332
#define TK_VALUE                          333
#define TK_VALUE_F                        334
#define TK_NONE                           335
#define TK_NULL_F                         336
#define TK_LINEAR                         337
#define TK_PREV                           338
#define TK_NEXT                           339
#define TK_NEAR                           340
#define TK_HAVING                         341
#define TK_RANGE                          342
#define TK_EVERY                          343
#define TK_ORDER                          344
#define TK_SLIMIT                         345
#define TK_SOFFSET                        346
#define TK_LIMIT                          347
#define TK_OFFSET                         348
#define TK_ASC                            349
#define TK_NULLS                          350
#define TK_ABORT                          351
#define TK_AFTER                          352
#define TK_ATTACH                         353
#define TK_BEFORE                         354
#define TK_BEGIN                          355
#define TK_BITAND                         356
#define TK_BITNOT                         357
#define TK_BITOR                          358
#define TK_BLOCKS                         359
#define TK_CHANGE                         360
#define TK_COMMA                          361
#define TK_CONCAT                         362
#define TK_CONFLICT                       363
#define TK_COPY                           364
#define TK_DEFERRED                       365
#define TK_DELIMITERS                     366
#define TK_DETACH                         367
#define TK_DIVIDE                         368
#define TK_DOT                            369
#define TK_EACH                           370
#define TK_FAIL                           371
#define TK_GLOB                           372
#define TK_ID                             373
#define TK_IMMEDIATE                      374
#define TK_IMPORT                         375
#define TK_INITIALLY                      376
#define TK_INSTEAD                        377
#define TK_ISNULL                         378
#define TK_MODULES                        379
#define TK_NK_BITNOT                      380
#define TK_NK_SEMI                        381
#define TK_NOTNULL                        382
#define TK_OF                             383
#define TK_PLUS                           384
#define TK_PRIVILEGE                      385
#define TK_RAISE                          386
#define TK_RESTRICT                       387
#define TK_ROW                            388
#define TK_STAR                           389
#define TK_STATEMENT                      390
#define TK_STRICT                         391
#define TK_STRING                         392
#define TK_TIMES                          393
#define TK_VALUES                         394
#define TK_VARIABLE                       395
#define TK_WAL                            396
