#define TK_OR                               1
#define TK_AND                              2
#define TK_UNION                            3
#define TK_ALL                              4
#define TK_MINUS                            5
#define TK_EXCEPT                           6
#define TK_INTERSECT                        7
#define TK_NK_BITAND                        8
#define TK_NK_BITOR                         9
#define TK_NK_LSHIFT                       10
#define TK_NK_RSHIFT                       11
#define TK_NK_PLUS                         12
#define TK_NK_MINUS                        13
#define TK_NK_STAR                         14
#define TK_NK_SLASH                        15
#define TK_NK_REM                          16
#define TK_NK_CONCAT                       17
#define TK_INNER                           18
#define TK_LEFT                            19
#define TK_RIGHT                           20
#define TK_FULL                            21
#define TK_OUTER                           22
#define TK_SEMI                            23
#define TK_ANTI                            24
#define TK_ASOF                            25
#define TK_WINDOW                          26
#define TK_JOIN                            27
#define TK_ON                              28
#define TK_WINDOW_OFFSET                   29
#define TK_JLIMIT                          30
#define TK_CREATE                          31
#define TK_ACCOUNT                         32
#define TK_NK_ID                           33
#define TK_PASS                            34
#define TK_NK_STRING                       35
#define TK_ALTER                           36
#define TK_PPS                             37
#define TK_TSERIES                         38
#define TK_STORAGE                         39
#define TK_STREAMS                         40
#define TK_QTIME                           41
#define TK_DBS                             42
#define TK_USERS                           43
#define TK_CONNS                           44
#define TK_STATE                           45
#define TK_NK_COMMA                        46
#define TK_HOST                            47
#define TK_IS_IMPORT                       48
#define TK_NK_INTEGER                      49
#define TK_CREATEDB                        50
#define TK_USER                            51
#define TK_ENABLE                          52
#define TK_SYSINFO                         53
#define TK_ADD                             54
#define TK_DROP                            55
#define TK_GRANT                           56
#define TK_TO                              57
#define TK_REVOKE                          58
#define TK_FROM                            59
#define TK_SUBSCRIBE                       60
#define TK_READ                            61
#define TK_WRITE                           62
#define TK_NK_DOT                          63
#define TK_WITH                            64
#define TK_ENCRYPT_KEY                     65
#define TK_ANODE                           66
#define TK_UPDATE                          67
#define TK_ANODES                          68
#define TK_DNODE                           69
#define TK_PORT                            70
#define TK_DNODES                          71
#define TK_RESTORE                         72
#define TK_NK_IPTOKEN                      73
#define TK_FORCE                           74
#define TK_UNSAFE                          75
#define TK_CLUSTER                         76
#define TK_LOCAL                           77
#define TK_QNODE                           78
#define TK_BNODE                           79
#define TK_SNODE                           80
#define TK_MNODE                           81
#define TK_VNODE                           82
#define TK_DATABASE                        83
#define TK_USE                             84
#define TK_FLUSH                           85
#define TK_TRIM                            86
#define TK_S3MIGRATE                       87
#define TK_COMPACT                         88
#define TK_VGROUPS                         89
#define TK_IN                              90
#define TK_NK_LP                           91
#define TK_NK_RP                           92
#define TK_IF                              93
#define TK_NOT                             94
#define TK_EXISTS                          95
#define TK_BUFFER                          96
#define TK_CACHEMODEL                      97
#define TK_CACHESIZE                       98
#define TK_COMP                            99
#define TK_DURATION                       100
#define TK_NK_VARIABLE                    101
#define TK_MAXROWS                        102
#define TK_MINROWS                        103
#define TK_KEEP                           104
#define TK_PAGES                          105
#define TK_PAGESIZE                       106
#define TK_TSDB_PAGESIZE                  107
#define TK_PRECISION                      108
#define TK_REPLICA                        109
#define TK_SINGLE_STABLE                  110
#define TK_RETENTIONS                     111
#define TK_SCHEMALESS                     112
#define TK_WAL_LEVEL                      113
#define TK_WAL_FSYNC_PERIOD               114
#define TK_WAL_RETENTION_PERIOD           115
#define TK_WAL_RETENTION_SIZE             116
#define TK_WAL_ROLL_PERIOD                117
#define TK_WAL_SEGMENT_SIZE               118
#define TK_STT_TRIGGER                    119
#define TK_TABLE_PREFIX                   120
#define TK_TABLE_SUFFIX                   121
#define TK_S3_CHUNKPAGES                  122
#define TK_S3_KEEPLOCAL                   123
#define TK_S3_COMPACT                     124
#define TK_KEEP_TIME_OFFSET               125
#define TK_ENCRYPT_ALGORITHM              126
#define TK_COMPACT_INTERVAL               127
#define TK_COMPACT_TIME_RANGE             128
#define TK_COMPACT_TIME_OFFSET            129
#define TK_NK_COLON                       130
#define TK_BWLIMIT                        131
#define TK_START                          132
#define TK_TIMESTAMP                      133
#define TK_END                            134
#define TK_TABLE                          135
#define TK_USING                          136
#define TK_FILE                           137
#define TK_STABLE                         138
#define TK_COLUMN                         139
#define TK_MODIFY                         140
#define TK_RENAME                         141
#define TK_TAG                            142
#define TK_NK_EQ                          143
#define TK_SET                            144
#define TK_TAGS                           145
#define TK_BOOL                           146
#define TK_TINYINT                        147
#define TK_SMALLINT                       148
#define TK_INT                            149
#define TK_INTEGER                        150
#define TK_BIGINT                         151
#define TK_FLOAT                          152
#define TK_DOUBLE                         153
#define TK_BINARY                         154
#define TK_NCHAR                          155
#define TK_UNSIGNED                       156
#define TK_JSON                           157
#define TK_VARCHAR                        158
#define TK_MEDIUMBLOB                     159
#define TK_BLOB                           160
#define TK_VARBINARY                      161
#define TK_GEOMETRY                       162
#define TK_DECIMAL                        163
#define TK_COMMENT                        164
#define TK_MAX_DELAY                      165
#define TK_WATERMARK                      166
#define TK_ROLLUP                         167
#define TK_TTL                            168
#define TK_SMA                            169
#define TK_DELETE_MARK                    170
#define TK_FIRST                          171
#define TK_LAST                           172
#define TK_SHOW                           173
#define TK_PRIVILEGES                     174
#define TK_DATABASES                      175
#define TK_TABLES                         176
#define TK_STABLES                        177
#define TK_MNODES                         178
#define TK_QNODES                         179
#define TK_ARBGROUPS                      180
#define TK_FUNCTIONS                      181
#define TK_INDEXES                        182
#define TK_ACCOUNTS                       183
#define TK_APPS                           184
#define TK_CONNECTIONS                    185
#define TK_LICENCES                       186
#define TK_GRANTS                         187
#define TK_LOGS                           188
#define TK_MACHINES                       189
#define TK_ENCRYPTIONS                    190
#define TK_QUERIES                        191
#define TK_SCORES                         192
#define TK_TOPICS                         193
#define TK_VARIABLES                      194
#define TK_BNODES                         195
#define TK_SNODES                         196
#define TK_TRANSACTIONS                   197
#define TK_TRANSACTION                    198
#define TK_DISTRIBUTED                    199
#define TK_CONSUMERS                      200
#define TK_SUBSCRIPTIONS                  201
#define TK_VNODES                         202
#define TK_ALIVE                          203
#define TK_VIEWS                          204
#define TK_VIEW                           205
#define TK_COMPACTS                       206
#define TK_DISK_INFO                      207
#define TK_NORMAL                         208
#define TK_CHILD                          209
#define TK_LIKE                           210
#define TK_TBNAME                         211
#define TK_QTAGS                          212
#define TK_AS                             213
#define TK_SYSTEM                         214
#define TK_TSMA                           215
#define TK_INTERVAL                       216
#define TK_RECURSIVE                      217
#define TK_TSMAS                          218
#define TK_FUNCTION                       219
#define TK_INDEX                          220
#define TK_COUNT                          221
#define TK_LAST_ROW                       222
#define TK_META                           223
#define TK_ONLY                           224
#define TK_TOPIC                          225
#define TK_CONSUMER                       226
#define TK_GROUP                          227
#define TK_DESC                           228
#define TK_DESCRIBE                       229
#define TK_RESET                          230
#define TK_QUERY                          231
#define TK_CACHE                          232
#define TK_EXPLAIN                        233
#define TK_ANALYZE                        234
#define TK_VERBOSE                        235
#define TK_NK_BOOL                        236
#define TK_RATIO                          237
#define TK_NK_FLOAT                       238
#define TK_OUTPUTTYPE                     239
#define TK_AGGREGATE                      240
#define TK_BUFSIZE                        241
#define TK_LANGUAGE                       242
#define TK_REPLACE                        243
#define TK_STREAM                         244
#define TK_INTO                           245
#define TK_PAUSE                          246
#define TK_RESUME                         247
#define TK_PRIMARY                        248
#define TK_KEY                            249
#define TK_TRIGGER                        250
#define TK_AT_ONCE                        251
#define TK_WINDOW_CLOSE                   252
#define TK_FORCE_WINDOW_CLOSE             253
#define TK_IGNORE                         254
#define TK_EXPIRED                        255
#define TK_FILL_HISTORY                   256
#define TK_SUBTABLE                       257
#define TK_UNTREATED                      258
#define TK_NOTIFY                         259
#define TK_ON_FAILURE                     260
#define TK_NOTIFY_HISTORY                 261
#define TK_KILL                           262
#define TK_CONNECTION                     263
#define TK_BALANCE                        264
#define TK_VGROUP                         265
#define TK_LEADER                         266
#define TK_MERGE                          267
#define TK_REDISTRIBUTE                   268
#define TK_SPLIT                          269
#define TK_DELETE                         270
#define TK_INSERT                         271
#define TK_NK_BIN                         272
#define TK_NK_HEX                         273
#define TK_NULL                           274
#define TK_NK_QUESTION                    275
#define TK_NK_ALIAS                       276
#define TK_NK_ARROW                       277
#define TK_ROWTS                          278
#define TK_QSTART                         279
#define TK_QEND                           280
#define TK_QDURATION                      281
#define TK_WSTART                         282
#define TK_WEND                           283
#define TK_WDURATION                      284
#define TK_IROWTS                         285
#define TK_ISFILLED                       286
#define TK_FLOW                           287
#define TK_FHIGH                          288
#define TK_FROWTS                         289
#define TK_IROWTS_ORIGIN                  290
#define TK_CAST                           291
#define TK_POSITION                       292
#define TK_FOR                            293
#define TK_NOW                            294
#define TK_TODAY                          295
#define TK_RAND                           296
#define TK_SUBSTR                         297
#define TK_SUBSTRING                      298
#define TK_BOTH                           299
#define TK_TRAILING                       300
#define TK_LEADING                        301
#define TK_TIMEZONE                       302
#define TK_CLIENT_VERSION                 303
#define TK_SERVER_VERSION                 304
#define TK_SERVER_STATUS                  305
#define TK_CURRENT_USER                   306
#define TK_PI                             307
#define TK_CASE                           308
#define TK_WHEN                           309
#define TK_THEN                           310
#define TK_ELSE                           311
#define TK_BETWEEN                        312
#define TK_IS                             313
#define TK_NK_LT                          314
#define TK_NK_GT                          315
#define TK_NK_LE                          316
#define TK_NK_GE                          317
#define TK_NK_NE                          318
#define TK_MATCH                          319
#define TK_NMATCH                         320
#define TK_CONTAINS                       321
#define TK_SELECT                         322
#define TK_NK_HINT                        323
#define TK_DISTINCT                       324
#define TK_WHERE                          325
#define TK_PARTITION                      326
#define TK_BY                             327
#define TK_SESSION                        328
#define TK_STATE_WINDOW                   329
#define TK_AUTO                           330
#define TK_EVENT_WINDOW                   331
#define TK_COUNT_WINDOW                   332
#define TK_ANOMALY_WINDOW                 333
#define TK_SLIDING                        334
#define TK_FILL                           335
#define TK_VALUE                          336
#define TK_VALUE_F                        337
#define TK_NONE                           338
#define TK_NULL_F                         339
#define TK_LINEAR                         340
#define TK_PREV                           341
#define TK_NEXT                           342
#define TK_NEAR                           343
#define TK_HAVING                         344
#define TK_RANGE                          345
#define TK_EVERY                          346
#define TK_ORDER                          347
#define TK_SLIMIT                         348
#define TK_SOFFSET                        349
#define TK_LIMIT                          350
#define TK_OFFSET                         351
#define TK_ASC                            352
#define TK_NULLS                          353
#define TK_ABORT                          354
#define TK_AFTER                          355
#define TK_ATTACH                         356
#define TK_BEFORE                         357
#define TK_BEGIN                          358
#define TK_BITAND                         359
#define TK_BITNOT                         360
#define TK_BITOR                          361
#define TK_BLOCKS                         362
#define TK_CHANGE                         363
#define TK_COMMA                          364
#define TK_CONCAT                         365
#define TK_CONFLICT                       366
#define TK_COPY                           367
#define TK_DEFERRED                       368
#define TK_DELIMITERS                     369
#define TK_DETACH                         370
#define TK_DIVIDE                         371
#define TK_DOT                            372
#define TK_EACH                           373
#define TK_FAIL                           374
#define TK_GLOB                           375
#define TK_ID                             376
#define TK_IMMEDIATE                      377
#define TK_IMPORT                         378
#define TK_INITIALLY                      379
#define TK_INSTEAD                        380
#define TK_ISNULL                         381
#define TK_MODULES                        382
#define TK_NK_BITNOT                      383
#define TK_NK_SEMI                        384
#define TK_NOTNULL                        385
#define TK_OF                             386
#define TK_PLUS                           387
#define TK_PRIVILEGE                      388
#define TK_RAISE                          389
#define TK_RESTRICT                       390
#define TK_ROW                            391
#define TK_STAR                           392
#define TK_STATEMENT                      393
#define TK_STRICT                         394
#define TK_STRING                         395
#define TK_TIMES                          396
#define TK_VALUES                         397
#define TK_VARIABLE                       398
#define TK_WAL                            399
