#!server_ver: ver:3.3.6.14.0712
#!taosdump_ver: 3.3.6.14.0711_fceced930a0056dbf7d1d782203fef2d12798bea
#!os_id: LINUX
#!escape_char: true
#!loose_mode: false
#!charset: UTF-8
CREATE DATABASE IF NOT EXISTS idmp_sample_tobacco REPLICA 1   DURATION 10d KEEP 3650d,3650d,3650d     PRECISION 'ms'   MINROWS 100 MAXROWS 4096 COMP 2 ;

CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`cutting_public_point` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`public_point` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `recipe_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`feeding_machine2` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`chain_conveyor` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`belt_conveyor` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium') TAGS (`device_id` NCHAR(256))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`drum_type_stem_rehumidifier` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `valve_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `recipe_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`fragrance_public_point` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`metering_pipe` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`electronic_belt_scale` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`feeding_machine` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `valve_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`flip_box_feeder` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`drying_public_point` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `valve_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `recipe_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`fragrance_machine` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `valve_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`jet_vacuum_rehumidifier` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `valve_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `recipe_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`thin_plate_dryer` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `recipe_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`leaf_storage_cabinet` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `equipment_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`drum_air_flow_dryer` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `pid` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `valve_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `fault_alarm` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `control_setpoint` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `recipe_parameters` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium', `measured_value` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`wind_fiber_feed_public_point` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `equipment_status` BOOL ENCODE 'bit-packing' COMPRESS 'zstd' LEVEL 'medium', `production_information` VARCHAR(512) ENCODE 'disabled' COMPRESS 'zstd' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
CREATE TABLE IF NOT EXISTS `idmp_sample_tobacco`.`vibrating_conveyor` (`ts` TIMESTAMP ENCODE 'delta-i' COMPRESS 'lz4' LEVEL 'medium', `motor_signal` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium', `vibration_amplitude` FLOAT ENCODE 'delta-d' COMPRESS 'lz4' LEVEL 'medium') TAGS (`tobacco_asset` NCHAR(256), `process_stage` NCHAR(32), `process_step` NCHAR(32), `equipment_type` NCHAR(32))
