taostest --setup=demo.yaml --case=customer_scenarios/gyrx/gyrx_1.py --keep
taostest --use=demo.yaml --case=customer_scenarios/gyrx/gyrx_5.py --keep
taostest --use=demo.yaml --case=customer_scenarios/gyrx/gyrx_6-12.py --keep
taostest --use=demo.yaml --case=customer_scenarios/gyrx/gyrx_13.py --keep
taostest --setup=cluster_3_dnodes.yaml --case=customer_scenarios/gyrx/gyrx_15.py --keep
taostest --setup=demo.yaml --case=customer_scenarios/gyrx/gyrx_17.py --keep
taostest --setup=demo.yaml --case=customer_scenarios/gyrx/gyrx_18.py --keep
taostest --setup=demo.yaml --case=customer_scenarios/gyrx/gyrx_20.py --keep
taostest --setup=demo.yaml --case=customer_scenarios/gyrx/gyrx_21.py --keep
taostest --setup=cluster_3_dnodes.yaml --case=customer_scenarios/gyrx/gyrx_26.py --keep
taostest --setup=cluster_3_dnodes.yaml --case=customer_scenarios/gyrx/gyrx_28.py --keep
taostest --setup=demo.yaml --case=customer_scenarios/gyrx/gyrx_30.py --keep