
#user  nobody;
worker_processes  1;
daemon off;
master_process off;
#error_log logs/error.log debug;
error_log logs/error.log warn;
events {
    worker_connections 1024;
}
http {
    log_format timed_combined '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" '
        '$request_time $upstream_response_time $pipe';
    access_log logs/access.log timed_combined;

    lua_package_path "/home/zz/opt/lualib/resty/?.lua;;";
    lua_shared_dict state 10m;
    lua_shared_dict mutex 1m;
    lua_shared_dict locks 1m;
    lua_shared_dict config 10m;
    lua_shared_dict _ups 1m;

    server {
        listen              0.0.0.0:6300;
        include             mime.types;
        default_type        application/octet-stream;
        sendfile            on;
        keepalive_timeout   65;

        location / {
            root   /home/zz/opt/web/admin;
            index  login.html;
        }
        location /admin/ {
            proxy_pass    http://10.0.2.15:6320/admin/;
            proxy_redirect default ;
        }
        location /rest/ {
            proxy_pass    http://10.0.2.15:6320/rest/;
            proxy_redirect default ;
        }
        location /gc/ {
            proxy_pass    http://10.0.2.15:6320/gc/;
            proxy_redirect default ;
        }
    }
}

