from util.log import *
from util.cases import *
from util.sql import *
import numpy as np


class TDTestCase:
    def init(self, conn, logSql):
        tdLog.debug("start to execute %s" % __file__)
        tdSql.init(conn.cursor())

        self.rowNum = 10
        self.ts = 1537146000000
        
    def run(self):
        tdSql.prepare()

        tdSql.execute('''create table stb(ts timestamp, col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 float, col6 double, 
                    col7 bool, col8 binary(20), col9 nchar(20), col11 tinyint unsigned, col12 smallint unsigned, col13 int unsigned, col14 bigint unsigned) tags(loc nchar(20))''')
        tdSql.execute("create table stb_1 using stb tags('beijing')")
        tdSql.execute("insert into stb_1(ts) values(%d)" % (self.ts - 1))

        # last verifacation         
        tdSql.query("select last(*) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, None)
        tdSql.query("select last(*) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, None)
        tdSql.query("select last(col1) from stb_1")
        tdSql.checkRows(0) 
        tdSql.query("select last(col1) from db.stb_1")
        tdSql.checkRows(0)       
        tdSql.query("select last(col2) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col2) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col3) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col3) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col4) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col4) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col11) from stb_1")
        tdSql.checkRows(0)    
        tdSql.query("select last(col11) from db.stb_1")
        tdSql.checkRows(0)      
        tdSql.query("select last(col12) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col12) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col13) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col13) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col14) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col14) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col5) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col5) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col6) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col6) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col7) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col7) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col8) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col8) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col9) from stb_1")
        tdSql.checkRows(0)
        tdSql.query("select last(col9) from db.stb_1")
        tdSql.checkRows(0)
        tdSql.query("select count(col1) from stb_1 group by col7")
        tdSql.checkRows(1)

        for i in range(self.rowNum):
            tdSql.execute("insert into stb_1 values(%d, %d, %d, %d, %d, %f, %f, %d, 'taosdata%d', '涛思数据%d', %d, %d, %d, %d)" 
                        % (self.ts + i, i + 1, i + 1, i + 1, i + 1, i + 0.1, i + 0.1, i % 2, i + 1, i + 1, i + 1, i + 1, i + 1, i + 1))            

        tdSql.query("select last(*) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, 10)
        tdSql.query("select last(*) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, 10)
        tdSql.query("select last(col1) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col1) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col2) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col2) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col3) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col3) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col4) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col4) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col11) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col11) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col12) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col12) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col13) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col13) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col14) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col14) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col5) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col5) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col6) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col6) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col7) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, True)
        tdSql.query("select last(col7) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, True)
        tdSql.query("select last(col8) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 'taosdata10')
        tdSql.query("select last(col8) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 'taosdata10')
        tdSql.query("select last(col9) from stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, '涛思数据10')
        tdSql.query("select last(col9) from db.stb_1")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, '涛思数据10')
        tdSql.query("select last(col1,col2,col3) from stb_1")
        tdSql.checkData(0,2,10)

        tdSql.query("select last(*) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, 10)
        tdSql.query("select last(*) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, 10)
        tdSql.query("select last(col1) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col1) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col2) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col2) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col3) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col3) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col4) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col4) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col11) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col11) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col12) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col12) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col13) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col13) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col14) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col14) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col5) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col5) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col6) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col6) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col7) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, True)
        tdSql.query("select last(col7) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, True)
        tdSql.query("select last(col8) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 'taosdata10')
        tdSql.query("select last(col8) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 'taosdata10')
        tdSql.query("select last(col9) from stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, '涛思数据10')
        tdSql.query("select last(col9) from db.stb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, '涛思数据10')
        tdSql.query("select last(col1,col2,col3) from stb")
        tdSql.checkData(0,2,10)
        

        tdSql.execute('''create table ntb(ts timestamp, col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 float, col6 double, 
                    col7 bool, col8 binary(20), col9 nchar(20), col11 tinyint unsigned, col12 smallint unsigned, col13 int unsigned, col14 bigint unsigned)''')
        tdSql.execute("insert into ntb(ts) values(%d)" % (self.ts - 1))
        tdSql.query("select last(*) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, None)
        tdSql.query("select last(*) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, None)
        tdSql.query("select last(col1) from ntb")
        tdSql.checkRows(0) 
        tdSql.query("select last(col1) from db.ntb")
        tdSql.checkRows(0)       
        tdSql.query("select last(col2) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col2) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col3) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col3) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col4) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col4) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col11) from ntb")
        tdSql.checkRows(0)    
        tdSql.query("select last(col11) from db.ntb")
        tdSql.checkRows(0)      
        tdSql.query("select last(col12) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col12) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col13) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col13) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col14) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col14) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col5) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col5) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col6) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col6) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col7) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col7) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col8) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col8) from db.ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col9) from ntb")
        tdSql.checkRows(0)
        tdSql.query("select last(col9) from db.ntb")
        tdSql.checkRows(0)

        for i in range(self.rowNum):
            tdSql.execute("insert into ntb values(%d, %d, %d, %d, %d, %f, %f, %d, 'taosdata%d', '涛思数据%d', %d, %d, %d, %d)" 
                        % (self.ts + i, i + 1, i + 1, i + 1, i + 1, i + 0.1, i + 0.1, i % 2, i + 1, i + 1, i + 1, i + 1, i + 1, i + 1))            

        tdSql.query("select last(*) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, 10)
        tdSql.query("select last(*) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 1, 10)
        tdSql.query("select last(col1) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col1) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col2) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col2) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col3) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col3) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col4) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col4) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col11) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col11) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col12) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col12) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col13) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col13) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col14) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col14) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 10)
        tdSql.query("select last(col5) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col5) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col6) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col6) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 9.1)
        tdSql.query("select last(col7) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, True)
        tdSql.query("select last(col7) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, True)
        tdSql.query("select last(col8) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 'taosdata10')
        tdSql.query("select last(col8) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, 'taosdata10')
        tdSql.query("select last(col9) from ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, '涛思数据10')
        tdSql.query("select last(col9) from db.ntb")
        tdSql.checkRows(1)
        tdSql.checkData(0, 0, '涛思数据10')
        tdSql.query("select last(col1,col2,col3) from ntb")
        tdSql.checkData(0,2,10)

        tdSql.error("select col1 from stb where last(col9)='涛思数据10'")
        tdSql.error("select col1 from ntb where last(col9)='涛思数据10'")
        tdSql.error("select col1 from stb_1 where last(col9)='涛思数据10'")
    def stop(self):
        tdSql.close()
        tdLog.success("%s successfully executed" % __file__)

tdCases.addWindows(__file__, TDTestCase())
tdCases.addLinux(__file__, TDTestCase())