DROP DATABASE IF EXISTS db_bintest;
CREATE DATABASE db_bintest VGROUPS 2;
USE db_bintest;
CREATE STABLE src_stb (ts TIMESTAMP, c1 INT, c2 FLOAT, c3 INT) TAGS (region INT);
CREATE TABLE src_c1 USING src_stb TAGS(3);
INSERT INTO src_c1 VALUES ('2023-01-01 00:00:05', 30, 3.1, 300);
CREATE TABLE src_g1 USING src_stb TAGS(5);
INSERT INTO src_g1 VALUES ('2023-01-01 00:00:09', 50, 5.1, 500);
CREATE STABLE parent_vst (ts TIMESTAMP, val INT) TAGS (t1 INT) VIRTUAL 1;
CREATE VIRTUAL STABLE child_vst BASE ON parent_vst (extra FLOAT) TAGS (t2 BINARY(16)) VIRTUAL 1;
CREATE VIRTUAL STABLE grandchild_vst BASE ON child_vst (deep INT) TAGS (t3 INT) VIRTUAL 1;
CREATE VTABLE vct_c1 (val FROM `db_bintest`.`src_c1`.`c1`, extra FROM `db_bintest`.`src_c1`.`c2`) USING child_vst (t1, t2) TAGS(10, 'hello');
CREATE VTABLE vct_g1 (val FROM `db_bintest`.`src_g1`.`c1`, extra FROM `db_bintest`.`src_g1`.`c2`, deep FROM `db_bintest`.`src_g1`.`c3`) USING grandchild_vst (t1, t2, t3) TAGS(100, 'world', 999);
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(0) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
DROP DATABASE IF EXISTS db_bintest;
CREATE DATABASE db_bintest VGROUPS 2;
USE db_bintest;
CREATE STABLE src_stb (ts TIMESTAMP, c1 INT, c2 FLOAT, c3 INT) TAGS (region INT);
CREATE TABLE src_c1 USING src_stb TAGS(3);
INSERT INTO src_c1 VALUES ('2023-01-01 00:00:05', 30, 3.1, 300);
CREATE TABLE src_g1 USING src_stb TAGS(5);
INSERT INTO src_g1 VALUES ('2023-01-01 00:00:09', 50, 5.1, 500);
CREATE STABLE parent_vst (ts TIMESTAMP, val INT) TAGS (t1 INT) VIRTUAL 1;
CREATE VIRTUAL STABLE child_vst BASE ON parent_vst (extra FLOAT) TAGS (t2 BINARY(16)) VIRTUAL 1;
CREATE VIRTUAL STABLE grandchild_vst BASE ON child_vst (deep INT) TAGS (t3 INT) VIRTUAL 1;
CREATE VTABLE vct_c1 (val FROM `db_bintest`.`src_c1`.`c1`, extra FROM `db_bintest`.`src_c1`.`c2`) USING child_vst (t1, t2) TAGS(10, 'hello');
CREATE VTABLE vct_g1 (val FROM `db_bintest`.`src_g1`.`c1`, extra FROM `db_bintest`.`src_g1`.`c2`, deep FROM `db_bintest`.`src_g1`.`c3`) USING grandchild_vst (t1, t2, t3) TAGS(100, 'world', 999);
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(0) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
DROP DATABASE IF EXISTS db_bintest;
CREATE DATABASE db_bintest VGROUPS 2;
USE db_bintest;
CREATE STABLE src_stb (ts TIMESTAMP, c1 INT, c2 FLOAT, c3 INT) TAGS (region INT);
CREATE TABLE src_c1 USING src_stb TAGS(3);
INSERT INTO src_c1 VALUES ('2023-01-01 00:00:05', 30, 3.1, 300);
CREATE TABLE src_g1 USING src_stb TAGS(5);
INSERT INTO src_g1 VALUES ('2023-01-01 00:00:09', 50, 5.1, 500);
CREATE STABLE parent_vst (ts TIMESTAMP, val INT) TAGS (t1 INT) VIRTUAL 1;
CREATE VIRTUAL STABLE child_vst BASE ON parent_vst (extra FLOAT) TAGS (t2 BINARY(16)) VIRTUAL 1;
CREATE VIRTUAL STABLE grandchild_vst BASE ON child_vst (deep INT) TAGS (t3 INT) VIRTUAL 1;
CREATE VTABLE vct_c1 (val FROM `db_bintest`.`src_c1`.`c1`, extra FROM `db_bintest`.`src_c1`.`c2`) USING child_vst (t1, t2) TAGS(10, 'hello');
CREATE VTABLE vct_g1 (val FROM `db_bintest`.`src_g1`.`c1`, extra FROM `db_bintest`.`src_g1`.`c2`, deep FROM `db_bintest`.`src_g1`.`c3`) USING grandchild_vst (t1, t2, t3) TAGS(100, 'world', 999);
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(0) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
DROP DATABASE IF EXISTS db_bintest;
CREATE DATABASE db_bintest VGROUPS 2;
USE db_bintest;
CREATE STABLE src_stb (ts TIMESTAMP, c1 INT, c2 FLOAT, c3 INT) TAGS (region INT);
CREATE TABLE src_c1 USING src_stb TAGS(3);
INSERT INTO src_c1 VALUES ('2023-01-01 00:00:05', 30, 3.1, 300);
CREATE TABLE src_g1 USING src_stb TAGS(5);
INSERT INTO src_g1 VALUES ('2023-01-01 00:00:09', 50, 5.1, 500);
CREATE STABLE parent_vst (ts TIMESTAMP, val INT) TAGS (t1 INT) VIRTUAL 1;
CREATE VIRTUAL STABLE child_vst BASE ON parent_vst (extra FLOAT) TAGS (t2 BINARY(16)) VIRTUAL 1;
CREATE VIRTUAL STABLE grandchild_vst BASE ON child_vst (deep INT) TAGS (t3 INT) VIRTUAL 1;
CREATE VTABLE vct_c1 (val FROM `db_bintest`.`src_c1`.`c1`, extra FROM `db_bintest`.`src_c1`.`c2`) USING child_vst (t1, t2) TAGS(10, 'hello');
CREATE VTABLE vct_g1 (val FROM `db_bintest`.`src_g1`.`c1`, extra FROM `db_bintest`.`src_g1`.`c2`, deep FROM `db_bintest`.`src_g1`.`c3`) USING grandchild_vst (t1, t2, t3) TAGS(100, 'world', 999);
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(0) ORDER BY val;
SELECT tbname, val, t1, t2 FROM child_vst EXPAND(1) ORDER BY val;
DROP DATABASE db_bintest;
