[package]
name = "taosx-agent"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cfg-if = "1"
clap = { version = "4", features = ["derive", "env"] }
clap-verbosity-flag = "2.0.0"
const_format = "0.2"
dotenv = "0.15.0"
log = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde"] }

thiserror = "1"
twelf = { version = "0.15.0", default-features = false, features = [
  "toml",
  "env",
  "clap",
] }
itertools = { workspace = true }

dashmap = "5.4.0"
flume = "0.11.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

arrow = { workspace = true, features = ["chrono-tz"] }
arrow-flight = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
tonic = { workspace = true, features = ["gzip"] }
shadow-rs = { workspace = true }
metrics = { workspace = true }
futures = "0.3"
tokio = { version = "1", features = [
  "rt",
  "rt-multi-thread",
  "io-util",
  "io-std",
  "net",
  "time",
  "process",
  "macros",
  "sync",
  "signal",
  "fs",
] }
tokio-util = { version = "0.7" }
tracing = { version = "0.1", features = ["log"] }

taosx-core = { path = "../taosx-core" }
taosx-metrics = { path = "../taosx-metrics" }

time = { version = "0.3", features = ["formatting", "macros"] }
tracing-subscriber = { version = "0.3", features = [
  "time",
  "local-time",
  "env-filter",
] }

taoslog = { workspace = true }
bytes = { workspace = true }
sysinfo = { workspace = true }

[build-dependencies]
dotenv = "0.15.0"
shadow-rs = { workspace = true }
