{
 "title": "新流计算性能基准benchmark",
 "time": { "from": "2025-11-30T23:10:27.919Z", "to": "2025-12-01T09:00:56.491Z" },
 "templating": {
  "list": [
   {
    "name": "scenario",
    "query": "select scenario from stream_bench.stb_tp where run_type='DAILY' group by scenario;"
   }
  ]
 },
 "panels": [
  {
   "title": "吞吐量 （rec/s）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select end_time, tp as `3.0` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='3.0' and scenario ='$scenario' "
    },
    {
     "formatType": "Time series",
     "sql": "select end_time, tp as `main` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='main' and scenario ='$scenario' "
    }
   ]
  },
  {
   "title": "平均延时 (秒)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_avg as `3.0` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='3.0' and scenario ='$scenario' "
    },
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_avg as `main` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='main' and scenario ='$scenario' "
    }
   ]
  },
  {
   "title": "延时 P10 (秒)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p10 as `3.0` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='3.0' and scenario ='$scenario' "
    },
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p10 as `main` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='main' and scenario ='$scenario' "
    }
   ]
  },
  {
   "title": "延时 P50 (秒)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p50 as `3.0` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='3.0' and scenario ='$scenario' "
    },
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p50 as `main` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='main' and scenario ='$scenario' "
    }
   ]
  },
  {
   "title": "延时 P90 (秒)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p90 as `3.0` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='3.0' and scenario ='$scenario' "
    },
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p90 as `main` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='main' and scenario ='$scenario' "
    }
   ]
  },
  {
   "title": "延时 P99 (秒)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p99 as `3.0` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='3.0' and scenario ='$scenario' "
    },
    {
     "formatType": "Time series",
     "sql": "select end_time, delay_p99 as `main` from stream_bench.stb_tp where end_time >= $from-1d and end_time <= $to and version='main' and scenario ='$scenario' "
    }
   ]
  }
 ]
}