CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` INTERVAL(30m) SLIDING(5m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _twstart+0s as output_timestamp, AVG(`电机信号`) AS `电机信号平均值` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >=_twstart and ts <=_twend;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` SESSION(ts,10m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _twstart+0s as output_timestamp, LAST(`振动幅度`) AS `最后振动幅度` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >= _twstart and ts <=_twend;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` INTERVAL(1h) SLIDING(15m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _twstart+0s as output_timestamp, MAX(`电机信号`) AS `电机信号最大值` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >=_twstart and ts <=_twend;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` SLIDING(10m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _tcurrent_ts+0s as output_timestamp, SUM(`振动幅度`) AS `振动幅度总和` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >=_tprev_ts and ts <=_tcurrent_ts;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` SESSION(ts,5m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _twstart+0s as output_timestamp, LAST(`电机信号`) AS `最后电机信号` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >= _twstart and ts <=_twend;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` SLIDING(20m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _tcurrent_ts+0s as output_timestamp, STDDEV(`振动幅度`) AS `振动幅度标准差` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >=_tprev_ts and ts <=_tcurrent_ts;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` SLIDING(30m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _tcurrent_ts+0s as output_timestamp, SPREAD(`电机信号`) AS `电机信号极差` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >=_tprev_ts and ts <=_tcurrent_ts;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` SESSION(ts,15m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _twstart+0s as output_timestamp, LAST(`电机信号`) AS `最后电机信号` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >= _twstart and ts <=_twend;
CREATE STREAM IF NOT EXISTS `idmp`.`%STREAM_NAME` INTERVAL(15m) SLIDING(5m) FROM `idmp`.`vst_振动输送机_891902` OPTIONS(IGNORE_DISORDER) NOTIFY('ws://idmp:6042/eventReceive') ON(WINDOW_OPEN|WINDOW_CLOSE) INTO `idmp`.`%STREAM_NAME` AS SELECT _twstart+0s as output_timestamp, SPREAD(`振动幅度`)/FIRST(`振动幅度`) AS `振动幅度变化率` FROM `idmp`.`vst_振动输送机_891902` WHERE `设备类型` = '振动输送机' AND ts >=_twstart and ts <=_twend;

