### 设置###
log4j.rootLogger=ERROR,stdout
log4j.logger.com.taosdata=DEBUG

### 输出信息到控制抬 ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5p - [%t] %l: %m%n
### 输出DEBUG 级别以上的日志到debug.log ###
log4j.appender.D=org.apache.log4j.DailyRollingFileAppender
log4j.appender.D.File=logs/debug.log
log4j.appender.D.Append=true
log4j.appender.D.Threshold=DEBUG
log4j.appender.D.layout=org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5p - [%t] %l: %m%n
#### 输出ERROR 级别以上的日志到error.log ###
log4j.appender.E=org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File=logs/error.log
log4j.appender.E.Append=true
log4j.appender.E.Threshold=ERROR
log4j.appender.E.layout=org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5p - [%t] %l: %m%n
#### 输出ERROR 级别以上的日志到trace.log ###
log4j.appender.T=org.apache.log4j.DailyRollingFileAppender
log4j.appender.T.File=logs/trace.log
log4j.appender.T.Append=false
log4j.appender.T.Threshold=TRACE
log4j.appender.T.layout=org.apache.log4j.PatternLayout
log4j.appender.T.layout.ConversionPattern=%m%n