[package]
name = "taosx-metrics"
version = { workspace = true }
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metrics = { workspace = true }
metrics-util = { workspace = true }
flume = "0.11.0"
quanta = { version = "0.12", default-features = true }
indexmap = { version = "1", default-features = true }
bincode = "2.0.0-rc.3"
serde = { version = "1", features = ["derive"] }
sysinfo = { workspace = true }
