[package]
name = "taosx-metrics"
version = { workspace = true }
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metrics = { workspace = true }
metrics-util = { workspace = true }
flume.workspace = true
quanta = { version = "0.12", default-features = true }
bincode = "2"
serde = { workspace = true, features = ["derive"] }
