# =========================================================
# Deps options
# =========================================================

option(BUILD_CLOUD "Build cloud edition" OFF)
option(BUILD_CFG_GRANTS "Build with config grants" OFF)

set(BUILD_GRANT_VALUE "" CACHE STRING "Grant value")
set(BUILD_GRANT_DNODES "" CACHE STRING "Grant dnodes limit")
set(BUILD_GRANT_TIMESERIES "" CACHE STRING "Grant timeseries limit")
set(BUILD_GRANT_DATAIN_EXPIRE "" CACHE STRING "Grant datain expire")
set(BUILD_GRANT_DATAIN_NUMBER "" CACHE STRING "Grant datain number")
set(BUILD_GRANT_IDMP_BASIC_EXPIRE "" CACHE STRING "Grant idmp basic expire")
set(BUILD_GRANT_IDMP_TS_ATTR "" CACHE STRING "Grant idmp ts attr")
set(BUILD_GRANT_IDMP_NTS_ATTR "" CACHE STRING "Grant idmp nts attr")
set(BUILD_GRANT_IDMP_ELEMENT "" CACHE STRING "Grant idmp element")
set(BUILD_GRANT_IDMP_SERVER "" CACHE STRING "Grant idmp server")
set(BUILD_GRANT_IDMP_CPU_CORE "" CACHE STRING "Grant idmp cpu core")
set(BUILD_GRANT_IDMP_USER "" CACHE STRING "Grant idmp user")
set(BUILD_GRANT_IDMP_VERSION_CTRL_EXPIRE "" CACHE STRING "Grant idmp version ctrl expire")
set(BUILD_GRANT_IDMP_DATA_FORECAST_EXPIRE "" CACHE STRING "Grant idmp data forecast expire")
set(BUILD_GRANT_IDMP_DATA_DETECT_EXPIRE "" CACHE STRING "Grant idmp data detect expire")
set(BUILD_GRANT_IDMP_DATA_QUALITY_EXPIRE "" CACHE STRING "Grant idmp data quality expire")
set(BUILD_GRANT_IDMP_AI_CHAT_GEN_EXPIRE "" CACHE STRING "Grant idmp ai chat gen expire")

set(TD_ENTERPRISE TRUE)
set(TD_ACCOUNT TRUE)
set(TD_ADMIN TRUE)
set(TD_VNODE_PLUGINS TRUE)
set(TD_MQTT FALSE)
set(TD_STORAGE TRUE)
set(TD_TOPIC TRUE)
set(TD_MODULE TRUE)
set(TD_MEM_CHECK FALSE)
set(TD_PAGMODE_LITE FALSE)
set(TD_SOMODE_STATIC FALSE)
set(TD_POWER FALSE)
set(TD_GODLL FALSE)
set(TD_PRIVILEGE TRUE)
set(TD_GRANT TRUE)
set(TD_DM_MODULE TRUE)

if(TD_LINUX_64 AND NOT TD_NINGSI)
  set(TD_USB_DONGLE TRUE)
else()
  set(TD_USB_DONGLE FALSE)
endif()

if(TD_WINDOWS OR TD_DARWIN)
  set(TD_SOMODE_STATIC TRUE)
endif()
