<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5;net6;net7;net8;net9;netstandard2.0;netstandard2.1;net45;net451;</TargetFrameworks>
    <PackageId>TDengine.Connector</PackageId>
    <PackageIcon>image\logo.jpg</PackageIcon>
    <PackageReadmeFile>docs\README.md</PackageReadmeFile>
    <Version>3.1.8</Version>
    <Authors>taosdata</Authors>
    <Company>https://tdengine.com/</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>Taos;Data;Microsoft.NET.Sdk;IOT;bigdata;TDengine;taosdata</PackageTags>
    <Description>
      The official TDengine C# connector.
    </Description>
    <PackageProjectUrl>https://docs.tdengine.com/client-libraries/csharp/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/taosdata/taos-connector-dotnet.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryBranch>"3.0"</RepositoryBranch>
    <NoWarn>CS1591;NETSDK1138</NoWarn>
<!--    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
    <IsPackable>true</IsPackable>
    <!--<Nullable>enable</Nullable>-->
  </PropertyGroup>
  <ItemGroup>
    <None Include="resource\logo.jpg" Pack="true" PackagePath="image" />
    <None Include="../README.md" Pack="True" PackagePath="docs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>