/*
 * Copyright (c) 2019 TAOS Data, Inc. <jhtao@taosdata.com>
 *
 * This program is free software: you can use, redistribute, and/or modify
 * it under the terms of the GNU Affero General Public License, version 3
 * or later ("AGPL"), as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#define _DEFAULT_SOURCE
#include "tpriv.h"
#include "tdef.h"

static TdThreadOnce privInit = PTHREAD_ONCE_INIT;

static SPrivInfo privInfoTable[] = {
    // ==================== system privileges ====================
    {PRIV_VG_BALANCE, PRIV_CATEGORY_SYSTEM, 0, "BALANCE VGROUP"},
    {PRIV_VG_MERGER, PRIV_CATEGORY_SYSTEM, 0, "MERGER VGROUP"},
    {PRIV_VG_REDISTRIBUTE, PRIV_CATEGORY_SYSTEM, 0, "REDISTRIBUTE VGROUP"},
    {PRIV_VG_SPLIT, PRIV_CATEGORY_SYSTEM, 0, "SPLIT VGROUP"},

    {PRIV_SHOW_DATABASES, PRIV_CATEGORY_SYSTEM, 0, "SHOW DATABASES"},
    {PRIV_SHOW_VNODES, PRIV_CATEGORY_SYSTEM, 0, "SHOW VNODES"},
    {PRIV_SHOW_VGROUPS, PRIV_CATEGORY_SYSTEM, 0, "SHOW VGROUPS"},
    {PRIV_SHOW_COMPACTS, PRIV_CATEGORY_SYSTEM, 0, "SHOW COMPACTS"},
    {PRIV_SHOW_RETENTIONS, PRIV_CATEGORY_SYSTEM, 0, "SHOW RETENTIONS"},
    {PRIV_SHOW_SCANS, PRIV_CATEGORY_SYSTEM, 0, "SHOW SCANS"},
    {PRIV_SHOW_SSMIGRATES, PRIV_CATEGORY_SYSTEM, 0, "SHOW SSMIGRATES"},

    {PRIV_PASS_ALTER, PRIV_CATEGORY_SYSTEM, 0, "ALTER PASS"},
    {PRIV_PASS_ALTER_SELF, PRIV_CATEGORY_SYSTEM, 0, "ALTER SELF PASS"},

    {PRIV_ROLE_CREATE, PRIV_CATEGORY_SYSTEM, 0, "CREATE ROLE"},
    {PRIV_ROLE_DROP, PRIV_CATEGORY_SYSTEM, 0, "DROP ROLE"},
    {PRIV_ROLE_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW ROLES"},

    {PRIV_USER_CREATE, PRIV_CATEGORY_SYSTEM, 0, "CREATE USER"},
    {PRIV_USER_DROP, PRIV_CATEGORY_SYSTEM, 0, "DROP USER"},
    {PRIV_USER_SET_SECURITY, PRIV_CATEGORY_SYSTEM, 0, "SET USER SECURITY"},
    {PRIV_USER_SET_AUDIT, PRIV_CATEGORY_SYSTEM, 0, "SET USER AUDIT"},
    {PRIV_USER_SET_BASIC, PRIV_CATEGORY_SYSTEM, 0, "SET USER BASIC"},
    {PRIV_USER_ENABLE, PRIV_CATEGORY_SYSTEM, 0, "ENABLE USER"},
    {PRIV_USER_DISABLE, PRIV_CATEGORY_SYSTEM, 0, "DISABLE USER"},
    {PRIV_USER_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW USERS"},

    {PRIV_TOKEN_CREATE, PRIV_CATEGORY_SYSTEM, 0, "CREATE TOKEN"},
    {PRIV_TOKEN_DROP, PRIV_CATEGORY_SYSTEM, 0, "DROP TOKEN"},
    {PRIV_TOKEN_ALTER, PRIV_CATEGORY_SYSTEM, 0, "ALTER TOKEN"},
    {PRIV_TOKEN_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW TOKENS"},

    {PRIV_KEY_UPDATE, PRIV_CATEGORY_SYSTEM, 0, "UPDATE KEY"},
    {PRIV_TOTP_CREATE, PRIV_CATEGORY_SYSTEM, 0, "CREATE TOTP"},
    {PRIV_TOTP_DROP, PRIV_CATEGORY_SYSTEM, 0, "DROP TOTP"},
    {PRIV_TOTP_UPDATE, PRIV_CATEGORY_SYSTEM, 0, "UPDATE TOTP"},

    {PRIV_GRANT_PRIVILEGE, PRIV_CATEGORY_SYSTEM, 0, "GRANT PRIVILEGE"},
    {PRIV_REVOKE_PRIVILEGE, PRIV_CATEGORY_SYSTEM, 0, "REVOKE PRIVILEGE"},
    {PRIV_GRANT_SYSDBA, PRIV_CATEGORY_SYSTEM, 0, "GRANT SYSDBA"},
    {PRIV_REVOKE_SYSDBA, PRIV_CATEGORY_SYSTEM, 0, "REVOKE SYSDBA"},
    {PRIV_GRANT_SYSSEC, PRIV_CATEGORY_SYSTEM, 0, "GRANT SYSSEC"},
    {PRIV_REVOKE_SYSSEC, PRIV_CATEGORY_SYSTEM, 0, "REVOKE SYSSEC"},
    {PRIV_GRANT_SYSAUDIT, PRIV_CATEGORY_SYSTEM, 0, "GRANT SYSAUDIT"},
    {PRIV_REVOKE_SYSAUDIT, PRIV_CATEGORY_SYSTEM, 0, "REVOKE SYSAUDIT"},

    {PRIV_NODE_CREATE, PRIV_CATEGORY_SYSTEM, 0, "CREATE NODE"},
    {PRIV_NODE_DROP, PRIV_CATEGORY_SYSTEM, 0, "DROP NODE"},
    {PRIV_NODES_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW NODES"},

    {PRIV_VAR_SECURITY_ALTER, PRIV_CATEGORY_SYSTEM, 0, "ALTER SECURITY VAR"},
    {PRIV_VAR_AUDIT_ALTER, PRIV_CATEGORY_SYSTEM, 0, "ALTER AUDIT VAR"},
    {PRIV_VAR_SYSTEM_ALTER, PRIV_CATEGORY_SYSTEM, 0, "ALTER SYSTEM VAR"},
    {PRIV_VAR_DEBUG_ALTER, PRIV_CATEGORY_SYSTEM, 0, "ALTER DEBUG VAR"},
    {PRIV_VAR_SECURITY_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW SECURITY VARS"},
    {PRIV_VAR_AUDIT_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW AUDIT VARS"},
    {PRIV_VAR_SYSTEM_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW SYSTEM VARS"},
    {PRIV_VAR_DEBUG_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW DEBUG VARS"},

    {PRIV_CONSUMER_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW CONSUMERS"},
    {PRIV_SUBSCRIPTION_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW SUBSCRIPTIONS"},

    {PRIV_STREAM_START, PRIV_CATEGORY_SYSTEM, 0, "START STREAM"},
    {PRIV_STREAM_STOP, PRIV_CATEGORY_SYSTEM, 0, "STOP STREAM"},
    {PRIV_STREAM_RECALC, PRIV_CATEGORY_SYSTEM, 0, "RECALC STREAM"},

    {PRIV_TRANS_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW TRANS"},
    {PRIV_TRANS_KILL, PRIV_CATEGORY_SYSTEM, 0, "KILL TRANS"},
    {PRIV_CONNECTION_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW CONNECTIONS"},
    {PRIV_CONNECTION_KILL, PRIV_CATEGORY_SYSTEM, 0, "KILL CONNECTION"},
    {PRIV_QUERY_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW QUERIES"},
    {PRIV_QUERY_KILL, PRIV_CATEGORY_SYSTEM, 0, "KILL QUERY"},

    {PRIV_INFO_SCHEMA_USE, PRIV_CATEGORY_SYSTEM, 0, "USE INFO SCHEMA"},
    {PRIV_PERF_SCHEMA_USE, PRIV_CATEGORY_SYSTEM, 0, "USE PERF SCHEMA"},
    {PRIV_INFO_SCHEMA_READ_LIMIT, PRIV_CATEGORY_SYSTEM, 0, "READ INFO SCHEMA LIMIT"},
    {PRIV_INFO_SCHEMA_READ_SEC, PRIV_CATEGORY_SYSTEM, 0, "READ INFO SCHEMA SEC"},
    {PRIV_INFO_SCHEMA_READ_AUDIT, PRIV_CATEGORY_SYSTEM, 0, "READ INFO SCHEMA AUDIT"},
    {PRIV_INFO_SCHEMA_READ_BASIC, PRIV_CATEGORY_SYSTEM, 0, "READ INFO SCHEMA BASIC"},
    {PRIV_PERF_SCHEMA_READ_LIMIT, PRIV_CATEGORY_SYSTEM, 0, "READ PERF SCHEMA LIMIT"},
    {PRIV_PERF_SCHEMA_READ_BASIC, PRIV_CATEGORY_SYSTEM, 0, "READ PERF SCHEMA BASIC"},
    {PRIV_GRANTS_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW GRANTS"},
    {PRIV_CLUSTER_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW CLUSTER"},
    {PRIV_APPS_SHOW, PRIV_CATEGORY_SYSTEM, 0, "SHOW APPS"},

    // ==================== object priv - DB ====================
    {PRIV_DB_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "CREATE DATABASE"},
    {PRIV_DB_ALTER, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "ALTER DATABASE"},
    {PRIV_DB_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "DROP DATABASE"},
    {PRIV_DB_USE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "USE DATABASE"},
    {PRIV_DB_FLUSH, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "FLUSH DATABASE"},
    {PRIV_DB_COMPACT, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "COMPACT DATABASE"},
    {PRIV_DB_TRIM, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "TRIM DATABASE"},
    {PRIV_DB_ROLLUP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "ROLLUP DATABASE"},
    {PRIV_DB_SCAN, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "SCAN DATABASE"},
    {PRIV_DB_SSMIGRATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_DB, "SSMIGRATE DATABASE"},

    // ==================== object - Table ====================
    {PRIV_TBL_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "CREATE TABLE"},
    {PRIV_TBL_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "DROP TABLE"},
    {PRIV_TBL_ALTER, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "ALTER TABLE"},
    {PRIV_TBL_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "SHOW TABLES"},
    {PRIV_TBL_SHOW_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "SHOW CREATE TABLE"},
    {PRIV_TBL_READ, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "READ TABLE"},
    {PRIV_TBL_WRITE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "WRITE TABLE"},
    {PRIV_TBL_UPDATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "UPDATE TABLE"},
    {PRIV_TBL_DELETE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "DELETE TABLE"},

    {PRIV_COL_READ_DATA, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "READ COLUMN DATA"},
    {PRIV_COL_WRITE_DATA, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "WRITE COLUMN DATA"},
    {PRIV_ROW_READ_DATA, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "READ ROW DATA"},
    {PRIV_ROW_WRITE_DATA, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TABLE, "WRITE ROW DATA"},

    // ==================== object priv - Function ====================
    {PRIV_FUNC_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_FUNCTION, "CREATE FUNCTION"},
    {PRIV_FUNC_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_FUNCTION, "DROP FUNCTION"},
    {PRIV_FUNC_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_FUNCTION, "SHOW FUNCTIONS"},

    // ==================== object priv - Index ====================
    {PRIV_IDX_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_INDEX, "CREATE INDEX"},
    {PRIV_IDX_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_INDEX, "DROP INDEX"},
    {PRIV_IDX_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_INDEX, "SHOW INDEXES"},

    // ==================== object priv - View ====================
    {PRIV_VIEW_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_VIEW, "CREATE VIEW"},
    {PRIV_VIEW_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_VIEW, "DROP VIEW"},
    {PRIV_VIEW_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_VIEW, "SHOW VIEWS"},
    {PRIV_VIEW_READ, PRIV_CATEGORY_OBJECT, OBJ_TYPE_VIEW, "READ VIEW"},

    // ==================== object priv - RSMA ====================
    {PRIV_RSMA_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_RSMA, "CREATE RSMA"},
    {PRIV_RSMA_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_RSMA, "DROP RSMA"},
    {PRIV_RSMA_ALTER, PRIV_CATEGORY_OBJECT, OBJ_TYPE_RSMA, "ALTER RSMA"},
    {PRIV_RSMA_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_RSMA, "SHOW RSMAS"},
    {PRIV_RSMA_SHOW_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_RSMA, "SHOW CREATE RSMA"},

    // ==================== object priv - TSMA ====================
    {PRIV_TSMA_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TSMA, "CREATE TSMA"},
    {PRIV_TSMA_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TSMA, "DROP TSMA"},
    {PRIV_TSMA_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TSMA, "SHOW TSMAS"},

    // ==================== object priv - Mount ====================
    {PRIV_MOUNT_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_MOUNT, "CREATE MOUNT"},
    {PRIV_MOUNT_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_MOUNT, "DROP MOUNT"},
    {PRIV_MOUNT_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_MOUNT, "SHOW MOUNTS"},

    // ==================== object priv - Audit ====================
    {PRIV_AUDIT_DB_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_AUDIT, "CREATE AUDIT DB"},
    {PRIV_AUDIT_DB_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_AUDIT, "DROP AUDIT DB"},
    {PRIV_AUDIT_DB_ALTER, PRIV_CATEGORY_OBJECT, OBJ_TYPE_AUDIT, "ALTER AUDIT DB"},
    {PRIV_AUDIT_DB_READ, PRIV_CATEGORY_OBJECT, OBJ_TYPE_AUDIT, "READ AUDIT DB"},
    {PRIV_AUDIT_DB_WRITE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_AUDIT, "WRITE AUDIT DB"},

    // ==================== object priv - Topic ====================
    {PRIV_TOPIC_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TOPIC, "CREATE TOPIC"},
    {PRIV_TOPIC_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TOPIC, "DROP TOPIC"},
    {PRIV_TOPIC_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_TOPIC, "SHOW TOPICS"},

    // ==================== object priv - Stream ====================
    {PRIV_STREAM_CREATE, PRIV_CATEGORY_OBJECT, OBJ_TYPE_STREAM, "CREATE STREAM"},
    {PRIV_STREAM_DROP, PRIV_CATEGORY_OBJECT, OBJ_TYPE_STREAM, "DROP STREAM"},
    {PRIV_STREAM_SHOW, PRIV_CATEGORY_OBJECT, OBJ_TYPE_STREAM, "SHOW STREAMS"},

    // ==================== legacy privileges ====================
    {PRIV_TYPE_ALL, PRIV_CATEGORY_LEGACY, 0, "ALL PRIVILEGES"},
    {PRIV_TYPE_READ, PRIV_CATEGORY_LEGACY, 0, "READ PRIVILEGE"},
    {PRIV_TYPE_WRITE, PRIV_CATEGORY_LEGACY, 0, "WRITE PRIVILEGE"},
    {PRIV_TYPE_SUBSCRIBE, PRIV_CATEGORY_LEGACY, 0, "SUBSCRIBE PRIVILEGE"},
    {PRIV_TYPE_ALTER, PRIV_CATEGORY_LEGACY, 0, "ALTER PRIVILEGE"},
};

static SPrivInfo* privLookup[MAX_PRIV_TYPE + 1] = {0};

static void initPrivLookup(void) {
  for (size_t i = 0; i < sizeof(privInfoTable) / sizeof(privInfoTable[0]); ++i) {
    if (privInfoTable[i].privType <= MAX_PRIV_TYPE) {
      privLookup[privInfoTable[i].privType] = &privInfoTable[i];
    }
  }
}

int32_t checkPrivConflicts(const SPrivSet* privSet) {
  if (!privSet) return 0;

  (void)taosThreadOnce(&privInit, initPrivLookup);

  bool hasSystemPriv = false;
  bool hasObjectPriv = false;
  bool hasLegacyPriv = false;

  EObjType objectType = OBJ_TYPE_UNKNOWN;

  for (EPrivType privType = 0; privType <= MAX_PRIV_TYPE; ++privType) {
    if (!PRIV_HAS(privSet, privType)) {
      continue;
    }

    const SPrivInfo* privInfo = privLookup[privType];
    if (privInfo == NULL) {
      continue;
    }

    switch (privInfo->category) {
      case PRIV_CATEGORY_SYSTEM:
        hasSystemPriv = true;
        break;
      case PRIV_CATEGORY_OBJECT:
        hasObjectPriv = true;
        if (objectType == OBJ_TYPE_UNKNOWN) {
          objectType = privInfo->objType;
        } else if (objectType != privInfo->objType) {
          return 2;
        }
        break;
      case PRIV_CATEGORY_LEGACY:
        hasLegacyPriv = true;
        break;
      default:
        break;
    }

    if ((hasSystemPriv && hasObjectPriv) || (hasSystemPriv && hasLegacyPriv) || (hasObjectPriv && hasLegacyPriv)) {
      return 1;
    }
  }

  return 0;
}