if(TD_COMMUNITY_STANDALONE)
  option(BUILD_ENTERPRISE    "If build enterprise edition (requires sibling taos-internal repo)" OFF)
  option(BUILD_TEST          "If build unit tests using googletest"  OFF)
  option(BUILD_TOOLS         "Build tools component"                 OFF)
  option(BUILD_SANITIZER     "Enable sanitizers"                     OFF)
  option(BUILD_COVERAGE      "Enable code coverage"                  OFF)
  option(BUILD_JEMALLOC      "Enable jemalloc allocator"             OFF)

  set(BUILD_VER_NUMBER      "" CACHE STRING "Version number override")
  set(BUILD_VER_COMPATIBLE  "" CACHE STRING "Compatible version number override")
  set(BUILD_VER_TYPE        "" CACHE STRING "Version type override (e.g. stable)")
  set(BUILD_VER_DATE        "" CACHE STRING "Version date override (e.g. %Y-%m-%d %H:%M:%S %z)")
  set(BUILD_VER_CPUTYPE     "" CACHE STRING "CPU type override")
  set(BUILD_VER_OSTYPE      "" CACHE STRING "OS type override")
  set(BUILD_GITINFO         "" CACHE STRING "Git commit ID override")
  set(BUILD_GITINFOI        "" CACHE STRING "Internal git commit ID override")
endif()

option(USE_CONAN               "Use Conan for dependency management"  OFF)
option(BUILD_ADVANCED_SECURITY "If enable advanced security"          OFF)
option(BUILD_ASSERT_NOT_CORE   "If assert not generate core file"     OFF)
option(BUILD_WEBSOCKET         "Enable websocket"                     OFF)
option(BUILD_PTHREAD_TWEAK     "Tweak pthread for CentOS7.9/Ubuntu18" OFF)
option(BUILD_ASTRA             "Build for Astra platform"             OFF)
option(BUILD_ASTRA_RPC         "Build with Astra RPC transport"       OFF)

if(TD_WINDOWS AND NOT BUILD_ASTRA)
  option(BUILD_PTHREAD     "If build pthread on Windows"            ON)
  option(BUILD_GNUREGEX    "If build gnu regex on Windows"          ON)
  option(BUILD_WITH_ICONV  "If build iconv on Windows"              ON)
  option(BUILD_MSVCREGEX   "If build msvcregex on Windows"          ON)
  option(BUILD_WCWIDTH     "If build wcwidth on Windows"            ON)
  option(BUILD_WINGETOPT   "If build wingetopt on Windows"          ON)
  option(BUILD_CRASHDUMP   "If build crashdump on Windows"          ON)
endif()

option(BUILD_WITH_LEMON    "If build with lemon"                    ON)
option(BUILD_WITH_UDF      "If build with UDF"                      ON)
option(BUILD_PYUDF         "If build Python UDF plugin (libtaospyudf)" ON)

# Python UDF: auto-download a single CPython SDK from python-build-standalone
# for compile-time headers/import-lib. Runtime still probes installed Python at
# execution time via udfd.
set(BUILD_PYUDF_PYTHON_VERSION  "3.15.0b1" CACHE STRING
  "Single Python version for pyudf SDK selection (must match PBS release)")

if(NOT BUILD_ASTRA)
  option(BUILD_GEOS          "If build with geos"                   ON)
  option(BUILD_SHARED_LIBS   "If build shared libraries"            OFF)
  option(RUST_BINDINGS       "If build with rust-bindings"          ON)
  option(BUILD_PCRE2         "If build with pcre2"                  ON)
  option(BUILD_ADDR2LINE     "If build addr2line"                   OFF)
  option(BUILD_WITH_LEVELDB  "If build with leveldb"                OFF)
  if(TD_LINUX)
    option(BUILD_ROCKSDB     "If build rocksdb from source"         OFF)
    option(ROCKSDB_USE_DEPS  "If use prebuilt rocksdb from deps/"   ON)
  else()
    option(BUILD_ROCKSDB     "If build rocksdb from source"         ON)
    option(ROCKSDB_USE_DEPS  "If use prebuilt rocksdb from deps/"   OFF)
  endif()
  option(TD_USE_ROCKSDB      "If enable rocksdb support"            ON)
  option(BUILD_WITH_LZ4      "If build with lz4"                    ON)
else()
  option(BUILD_ROCKSDB     "If build rocksdb from source"           OFF)
  option(TD_USE_ROCKSDB      "If enable rocksdb support"            OFF)
  option(BUILD_WITH_LZMA2    "If build with lzma2"                  ON)
endif()

if(TD_LINUX OR TD_WINDOWS)
  option(BUILD_SHARED_STORAGE "If build with shared storage"        ON)
  option(BUILD_WITH_S3        "If build with s3"                    ON)
  option(BUILD_WITH_COS       "If build with cos"                   OFF)
endif()

if(TD_LINUX)
  option(BUILD_WITH_LZMA2     "If build with lzma2"                 ON)
endif()

if(TD_LINUX OR TD_WINDOWS)
  option(BUILD_WITH_ANALYSIS  "If build with analysis"              ON)
else()
  option(BUILD_WITH_ANALYSIS  "If build with analysis"              OFF)
endif()

# NOTE: set option variable in this ways is not a good practice
if(NOT TD_ENTERPRISE)
  MESSAGE("switch shared storage off with community edition")
  set(BUILD_SHARED_STORAGE OFF)
  set(BUILD_WITH_S3 OFF)
  set(BUILD_WITH_COS OFF)
ELSE()
  MESSAGE("switch shared storage ON with enterprise edition")
  set(BUILD_SHARED_STORAGE ON)
  set(BUILD_WITH_S3 ON)
ENDIF ()

IF(${BUILD_SHARED_STORAGE})
  IF(${BUILD_WITH_S3})
    # NOTE: BUILD_WITH_S3 does NOT coexist with BUILD_WITH_COS?
    option(BUILD_WITH_COS "If build with cos" OFF)
  ELSE ()
    # NOTE1: BUILD_WITH_S3 does NOT coexist with BUILD_WITH_COS?
    # option(BUILD_WITH_COS "If build with cos" ON)
    MESSAGE("shared storage does not support COS at present, please use s3 instead")
  ENDIF ()
ELSE ()
  option(BUILD_WITH_S3 "If build with s3" OFF)
  option(BUILD_WITH_COS "If build with cos" OFF)
ENDIF ()


option(BUILD_WITH_SQLITE   "If build with sqlite"                  OFF)
option(BUILD_WITH_BDB      "If build with BDB"                     OFF)
option(BUILD_WITH_LUCENE   "If build with lucene"                  OFF)
option(BUILD_WITH_NURAFT   "If build with NuRaft"                  OFF)

if(NOT BUILD_ASTRA)
  option(BUILD_WITH_UV            "If build with libuv"            ON)
  option(BUILD_WITH_UV_TRANS      "If build with libuv_trans"      ON)
  if(TD_LINUX)
    option(BUILD_DEPENDENCY_TESTS "If build dependency tests"      ON)
  endif()
  option(BUILD_WITH_INVERTEDINDEX "If use invertedIndex"           ON)
endif()

option(BUILD_TAOSD_INTEGRATED "Build taosd as integrated library"    OFF)
option(BUILD_AS_LIB           "Build TDengine as library"            OFF)
option(BUILD_RELEASE          "If build release version"             OFF)
if(TD_LINUX)
  option(BUILD_CONTRIB        "If build thirdpart from source"       OFF)
else()
  option(BUILD_CONTRIB        "If build thirdpart from source"       ON)
endif()
option(BUILD_LIBSASL          "If build libsasl2"                    ON)
option(BUILD_FLEX_DEPLOY      "If enable flexible deployment mode"   OFF)
option(BUILD_WITH_RAND_ERR    "If build with random error injection" OFF)
option(BUILD_TSZ_ENABLED      "If build with TSZ compression"        ON)
option(BUILD_USE_PUBLIC_DEPS "Use public (internet) URLs for all external dependencies instead of internal mirrors" OFF)

# When BUILD_RELEASE is ON, force CMAKE_BUILD_TYPE to Release so that
# CMake built-in Release flags and ExternalProject configuration align.
if(BUILD_RELEASE)
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
  message(STATUS "[options] BUILD_RELEASE=ON => CMAKE_BUILD_TYPE forced to Release")
endif()

message(STATUS
  "[options] BUILD_CONTRIB=${BUILD_CONTRIB}, BUILD_ROCKSDB=${BUILD_ROCKSDB}"
)
