if(TD_COMMUNITY_STANDALONE)
  option(BUILD_ENTERPRISE    "If build enterprise edition (requires sibling taos-internal repo)" OFF)
  option(BUILD_TEST          "If build unit tests using googletest"  OFF)
  option(BUILD_TOOLS         "Build tools component"                 OFF)
  option(BUILD_SANITIZER     "Enable sanitizers"                     OFF)
  option(BUILD_COVERAGE      "Enable code coverage"                  OFF)
  option(BUILD_JEMALLOC      "Enable jemalloc allocator"             OFF)
  option(BUILD_CONTRIB       "Build thirdpart from source"           ON)
  option(BUILD_USE_PUBLIC_DEPS "Use public (internet) URLs for all external dependencies instead of internal mirrors" ON)

  set(BUILD_VER_NUMBER      "" CACHE STRING "Version number override")
  set(BUILD_VER_COMPATIBLE  "" CACHE STRING "Compatible version number override")
  set(BUILD_VER_TYPE        "" CACHE STRING "Version type override (e.g. stable)")
  set(BUILD_VER_DATE        "" CACHE STRING "Version date override (e.g. %Y-%m-%d %H:%M:%S %z)")
  set(BUILD_VER_CPUTYPE     "" CACHE STRING "CPU type override")
  set(BUILD_VER_OSTYPE      "" CACHE STRING "OS type override")
  set(BUILD_GITINFO         "" CACHE STRING "Git commit ID override")
  set(BUILD_GITINFOI        "" CACHE STRING "Internal git commit ID override")
endif()

option(BUILD_ASSERT_NOT_CORE "If assert not generate core file"     OFF)
option(BUILD_WEBSOCKET     "Enable websocket"                       OFF)
option(BUILD_PTHREAD_TWEAK "Tweak pthread for CentOS7.9/Ubuntu18"   OFF)
option(BUILD_ASTRA         "Build for Astra platform"               OFF)
option(BUILD_ASTRA_RPC     "Build with Astra RPC transport"         OFF)

if(TD_WINDOWS AND NOT BUILD_ASTRA)
  option(BUILD_PTHREAD     "If build pthread on Windows"            ON)
  option(BUILD_GNUREGEX    "If build gnu regex on Windows"          ON)
  option(BUILD_WITH_ICONV  "If build iconv on Windows"              ON)
  option(BUILD_MSVCREGEX   "If build msvcregex on Windows"          ON)
  option(BUILD_WCWIDTH     "If build wcwidth on Windows"            ON)
  option(BUILD_WINGETOPT   "If build wingetopt on Windows"          ON)
  option(BUILD_CRASHDUMP   "If build crashdump on Windows"          ON)
endif()

option(BUILD_WITH_LEMON    "If build with lemon"                    ON)
option(BUILD_WITH_UDF      "If build with UDF"                      ON)

if(NOT BUILD_ASTRA)
  option(BUILD_GEOS          "If build with geos"                   ON)
  option(BUILD_SHARED_LIBS   "If build shared libraries"            OFF)
  option(RUST_BINDINGS       "If build with rust-bindings"          ON)
  option(BUILD_PCRE2         "If build with pcre2"                  ON)
  option(BUILD_ADDR2LINE     "If build addr2line"                   OFF)
  option(BUILD_WITH_LEVELDB  "If build with leveldb"                OFF)
  if(TD_LINUX)
    option(BUILD_ROCKSDB     "If build rocksdb from source"         OFF)
    option(ROCKSDB_USE_DEPS  "If use prebuilt rocksdb from deps/"   ON)
  else()
    option(BUILD_ROCKSDB     "If build rocksdb from source"         ON)
    option(ROCKSDB_USE_DEPS  "If use prebuilt rocksdb from deps/"   OFF)
  endif()
  option(TD_USE_ROCKSDB      "If enable rocksdb support"            ON)
  option(BUILD_WITH_LZ4      "If build with lz4"                    ON)
else()
  option(BUILD_ROCKSDB     "If build rocksdb from source"           OFF)
  option(TD_USE_ROCKSDB      "If enable rocksdb support"            OFF)
  option(BUILD_WITH_LZMA2    "If build with lzma2"                  ON)
endif()

if(TD_LINUX)
  option(BUILD_S3             "If build s3"                         ON)
  option(BUILD_WITH_S3        "If build with s3"                    ON)
  option(BUILD_WITH_COS       "If build with cos"                   OFF)
  option(BUILD_WITH_LZMA2     "If build with lzma2"                 ON)
  option(BUILD_WITH_ANALYSIS  "If build with analysis"              ON)
endif()

# NOTE: set option variable in this ways is not a good practice
if(NOT TD_ENTERPRISE)
  message(STATUS "switch s3 off with community version")
  set(BUILD_S3 OFF)
  set(BUILD_WITH_S3 OFF)
  set(BUILD_WITH_COS OFF)
  set(BUILD_WITH_ANALYSIS OFF)
endif()

# NOTE: set option variable in this ways is not a good practice
if(TD_LINUX)
  set(BUILD_WITH_ANALYSIS ON)
endif()

# NOTE: set option variable in this ways is not a good practice
if(BUILD_WITH_ANALYSIS)
  message("build with analysis")
  if(TD_ENTERPRISE)
    set(BUILD_S3 ON)
    set(BUILD_WITH_S3 ON)
  endif()
endif()

if(BUILD_S3)
  if(BUILD_WITH_S3)
    add_definitions(-DUSE_S3)
    # NOTE: BUILD_WITH_S3 does NOT coexist with BUILD_WITH_COS?
    option(BUILD_WITH_COS "If build with cos" OFF)
  else()
    # NOTE: BUILD_WITH_S3 does NOT coexist with BUILD_WITH_COS?
    option(BUILD_WITH_COS "If build with cos" ON)
  endif()
else()
  option(BUILD_WITH_S3  "If build with s3"  OFF)
  option(BUILD_WITH_COS "If build with cos" OFF)
endif()

option(BUILD_WITH_SQLITE   "If build with sqlite"                  OFF)
option(BUILD_WITH_BDB      "If build with BDB"                     OFF)
option(BUILD_WITH_LUCENE   "If build with lucene"                  OFF)
option(BUILD_WITH_NURAFT   "If build with NuRaft"                  OFF)

if(NOT BUILD_ASTRA)
  option(BUILD_WITH_UV            "If build with libuv"            ON)
  option(BUILD_WITH_UV_TRANS      "If build with libuv_trans"      ON)
  if(TD_LINUX)
    option(BUILD_DEPENDENCY_TESTS "If build dependency tests"      ON)
  endif()
  option(BUILD_DOCS               "If use doxygen build documents" OFF)
  option(BUILD_WITH_INVERTEDINDEX "If use invertedIndex"           ON)
endif()

option(BUILD_TAOSD_INTEGRATED "Build taosd as integrated library"    OFF)
option(BUILD_AS_LIB           "Build TDengine as library"            OFF)
option(BUILD_RELEASE          "If build release version"             OFF)
if(TD_LINUX)
  option(BUILD_CONTRIB        "If build thirdpart from source"       OFF)
else()
  option(BUILD_CONTRIB        "If build thirdpart from source"       ON)
endif()
option(BUILD_LIBSASL          "If build libsasl2"                    OFF)
option(BUILD_FLEX_DEPLOY      "If enable flexible deployment mode"   OFF)
option(BUILD_WITH_RAND_ERR    "If build with random error injection" OFF)
option(BUILD_TSZ_ENABLED      "If build with TSZ compression"        ON)
option(BUILD_USE_PUBLIC_DEPS "Use public (internet) URLs for all external dependencies instead of internal mirrors" OFF)

message(STATUS
  "[options] BUILD_CONTRIB=${BUILD_CONTRIB}, BUILD_ROCKSDB=${BUILD_ROCKSDB}"
)
