#define TK_OR                               1
#define TK_AND                              2
#define TK_UNION                            3
#define TK_ALL                              4
#define TK_MINUS                            5
#define TK_EXCEPT                           6
#define TK_INTERSECT                        7
#define TK_NK_BITAND                        8
#define TK_NK_BITOR                         9
#define TK_NK_LSHIFT                       10
#define TK_NK_RSHIFT                       11
#define TK_NK_PH                           12
#define TK_NK_LT                           13
#define TK_NK_GT                           14
#define TK_NK_LE                           15
#define TK_NK_GE                           16
#define TK_NK_EQ                           17
#define TK_NK_NE                           18
#define TK_LIKE                            19
#define TK_MATCH                           20
#define TK_NMATCH                          21
#define TK_REGEXP                          22
#define TK_CONTAINS                        23
#define TK_BETWEEN                         24
#define TK_IS                              25
#define TK_IN                              26
#define TK_NK_PLUS                         27
#define TK_NK_MINUS                        28
#define TK_NK_STAR                         29
#define TK_NK_SLASH                        30
#define TK_NK_REM                          31
#define TK_NK_CONCAT                       32
#define TK_NOT                             33
#define TK_NK_ARROW                        34
#define TK_INNER                           35
#define TK_LEFT                            36
#define TK_RIGHT                           37
#define TK_FULL                            38
#define TK_OUTER                           39
#define TK_SEMI                            40
#define TK_ANTI                            41
#define TK_ASOF                            42
#define TK_WINDOW                          43
#define TK_JOIN                            44
#define TK_ON                              45
#define TK_WINDOW_OFFSET                   46
#define TK_JLIMIT                          47
#define TK_CREATE                          48
#define TK_ACCOUNT                         49
#define TK_NK_ID                           50
#define TK_PASS                            51
#define TK_NK_STRING                       52
#define TK_ALTER                           53
#define TK_PPS                             54
#define TK_TSERIES                         55
#define TK_STORAGE                         56
#define TK_STREAMS                         57
#define TK_QTIME                           58
#define TK_DBS                             59
#define TK_USERS                           60
#define TK_CONNS                           61
#define TK_STATE                           62
#define TK_DEFAULT                         63
#define TK_UNLIMITED                       64
#define TK_NK_INTEGER                      65
#define TK_LOCK                            66
#define TK_UNLOCK                          67
#define TK_ENABLE                          68
#define TK_TOTPSEED                        69
#define TK_NULL                            70
#define TK_SYSINFO                         71
#define TK_IS_IMPORT                       72
#define TK_CREATEDB                        73
#define TK_CHANGEPASS                      74
#define TK_SESSION_PER_USER                75
#define TK_CONNECT_TIME                    76
#define TK_CONNECT_IDLE_TIME               77
#define TK_CALL_PER_SESSION                78
#define TK_VNODE_PER_CALL                  79
#define TK_FAILED_LOGIN_ATTEMPTS           80
#define TK_PASSWORD_LIFE_TIME              81
#define TK_PASSWORD_REUSE_TIME             82
#define TK_PASSWORD_REUSE_MAX              83
#define TK_PASSWORD_LOCK_TIME              84
#define TK_PASSWORD_GRACE_TIME             85
#define TK_INACTIVE_ACCOUNT_TIME           86
#define TK_ALLOW_TOKEN_NUM                 87
#define TK_NK_COMMA                        88
#define TK_HOST                            89
#define TK_NOT_ALLOW_HOST                  90
#define TK_ALLOW_DATETIME                  91
#define TK_NOT_ALLOW_DATETIME              92
#define TK_ADD                             93
#define TK_DROP                            94
#define TK_USER                            95
#define TK_PROVIDER                        96
#define TK_TTL                             97
#define TK_EXTRA_INFO                      98
#define TK_TOKEN                           99
#define TK_FROM                           100
#define TK_TOTP_SECRET                    101
#define TK_FOR                            102
#define TK_ROLE                           103
#define TK_GRANT                          104
#define TK_TO                             105
#define TK_REVOKE                         106
#define TK_PRIVILEGES                     107
#define TK_SHOW                           108
#define TK_START                          109
#define TK_STOP                           110
#define TK_KILL                           111
#define TK_RECALCULATE                    112
#define TK_SUBSCRIBE                      113
#define TK_READ                           114
#define TK_WRITE                          115
#define TK_DATABASE                       116
#define TK_USE                            117
#define TK_FLUSH                          118
#define TK_COMPACT                        119
#define TK_TRIM                           120
#define TK_ROLLUP                         121
#define TK_SCAN                           122
#define TK_SSMIGRATE                      123
#define TK_DATABASES                      124
#define TK_VNODES                         125
#define TK_VGROUPS                        126
#define TK_COMPACTS                       127
#define TK_RETENTIONS                     128
#define TK_SCANS                          129
#define TK_SSMIGRATES                     130
#define TK_TABLE                          131
#define TK_TABLES                         132
#define TK_FUNCTION                       133
#define TK_FUNCTIONS                      134
#define TK_INDEX                          135
#define TK_INDEXES                        136
#define TK_VIEW                           137
#define TK_VIEWS                          138
#define TK_SELECT                         139
#define TK_RSMA                           140
#define TK_RSMAS                          141
#define TK_TSMA                           142
#define TK_TSMAS                          143
#define TK_MOUNT                          144
#define TK_MOUNTS                         145
#define TK_ROLES                          146
#define TK_TOKENS                         147
#define TK_UPDATE                         148
#define TK_KEY                            149
#define TK_TOTP                           150
#define TK_PRIVILEGE                      151
#define TK_NODE                           152
#define TK_NODES                          153
#define TK_TOPIC                          154
#define TK_TOPICS                         155
#define TK_CONSUMERS                      156
#define TK_SUBSCRIPTIONS                  157
#define TK_STREAM                         158
#define TK_TRANSACTIONS                   159
#define TK_TRANSACTION                    160
#define TK_CONNECTIONS                    161
#define TK_CONNECTION                     162
#define TK_QUERIES                        163
#define TK_QUERY                          164
#define TK_GRANTS                         165
#define TK_CLUSTER                        166
#define TK_APPS                           167
#define TK_INSERT                         168
#define TK_DELETE                         169
#define TK_SET                            170
#define TK_SYSTEM                         171
#define TK_VARIABLES                      172
#define TK_NK_DOT                         173
#define TK_WITH                           174
#define TK_ENCRYPT_KEY                    175
#define TK_ENCRYPT_ALGR                   176
#define TK_ALGR_NAME                      177
#define TK_DESC                           178
#define TK_ALGR_TYPE                      179
#define TK_OSSL_ALGR_NAME                 180
#define TK_SVR_KEY                        181
#define TK_DB_KEY                         182
#define TK_KEY_EXPIRATION                 183
#define TK_DAYS                           184
#define TK_STRATEGY                       185
#define TK_ANODE                          186
#define TK_ANODES                         187
#define TK_TRIGGER                        188
#define TK_XNODE                          189
#define TK_FORCE                          190
#define TK_DRAIN                          191
#define TK_REBALANCE                      192
#define TK_WHERE                          193
#define TK_XNODES                         194
#define TK_DNODE                          195
#define TK_PORT                           196
#define TK_DNODES                         197
#define TK_RELOAD                         198
#define TK_RESTORE                        199
#define TK_NK_IPTOKEN                     200
#define TK_UNSAFE                         201
#define TK_LOCAL                          202
#define TK_QNODE                          203
#define TK_SNODE                          204
#define TK_BNODE                          205
#define TK_MNODE                          206
#define TK_VNODE                          207
#define TK_WAL                            208
#define TK_NK_LP                          209
#define TK_NK_RP                          210
#define TK_META_ONLY                      211
#define TK_IF                             212
#define TK_EXISTS                         213
#define TK_BUFFER                         214
#define TK_CACHEMODEL                     215
#define TK_CACHESIZE                      216
#define TK_COMP                           217
#define TK_DURATION                       218
#define TK_NK_VARIABLE                    219
#define TK_MAXROWS                        220
#define TK_MINROWS                        221
#define TK_KEEP                           222
#define TK_PAGES                          223
#define TK_PAGESIZE                       224
#define TK_TSDB_PAGESIZE                  225
#define TK_PRECISION                      226
#define TK_REPLICAS                       227
#define TK_REPLICA                        228
#define TK_SINGLE_STABLE                  229
#define TK_SCHEMALESS                     230
#define TK_WAL_LEVEL                      231
#define TK_WAL_FSYNC_PERIOD               232
#define TK_WAL_RETENTION_PERIOD           233
#define TK_WAL_RETENTION_SIZE             234
#define TK_WAL_ROLL_PERIOD                235
#define TK_WAL_SEGMENT_SIZE               236
#define TK_STT_TRIGGER                    237
#define TK_TABLE_PREFIX                   238
#define TK_TABLE_SUFFIX                   239
#define TK_SS_CHUNKPAGES                  240
#define TK_SS_KEEPLOCAL                   241
#define TK_SS_COMPACT                     242
#define TK_KEEP_TIME_OFFSET               243
#define TK_ENCRYPT_ALGORITHM              244
#define TK_COMPACT_INTERVAL               245
#define TK_COMPACT_TIME_RANGE             246
#define TK_COMPACT_TIME_OFFSET            247
#define TK_IS_AUDIT                       248
#define TK_ALLOW_DROP                     249
#define TK_NK_COLON                       250
#define TK_BWLIMIT                        251
#define TK_TIMESTAMP                      252
#define TK_END                            253
#define TK_USING                          254
#define TK_FILE                           255
#define TK_STABLE                         256
#define TK_VTABLE                         257
#define TK_TAGS                           258
#define TK_COLUMN                         259
#define TK_MODIFY                         260
#define TK_RENAME                         261
#define TK_TAG                            262
#define TK_BOOL                           263
#define TK_TINYINT                        264
#define TK_SMALLINT                       265
#define TK_INT                            266
#define TK_INTEGER                        267
#define TK_BIGINT                         268
#define TK_FLOAT                          269
#define TK_DOUBLE                         270
#define TK_BINARY                         271
#define TK_NCHAR                          272
#define TK_UNSIGNED                       273
#define TK_JSON                           274
#define TK_VARCHAR                        275
#define TK_MEDIUMBLOB                     276
#define TK_BLOB                           277
#define TK_VARBINARY                      278
#define TK_GEOMETRY                       279
#define TK_DECIMAL                        280
#define TK_COMMENT                        281
#define TK_MAX_DELAY                      282
#define TK_WATERMARK                      283
#define TK_SMA                            284
#define TK_DELETE_MARK                    285
#define TK_VIRTUAL                        286
#define TK_FIRST                          287
#define TK_LAST                           288
#define TK_TBNAME                         289
#define TK_MASK                           290
#define TK_VTABLES                        291
#define TK_STABLES                        292
#define TK_MNODES                         293
#define TK_QNODES                         294
#define TK_ARBGROUPS                      295
#define TK_ACCOUNTS                       296
#define TK_LICENCES                       297
#define TK_LOGS                           298
#define TK_INSTANCES                      299
#define TK_MACHINES                       300
#define TK_ENCRYPTIONS                    301
#define TK_ENCRYPT_ALGORITHMS             302
#define TK_ENCRYPT_STATUS                 303
#define TK_SCORES                         304
#define TK_SNODES                         305
#define TK_BNODES                         306
#define TK_DISTRIBUTED                    307
#define TK_ALIVE                          308
#define TK_DISK_INFO                      309
#define TK_VALIDATE                       310
#define TK_NORMAL                         311
#define TK_CHILD                          312
#define TK_QTAGS                          313
#define TK_AS                             314
#define TK_INTERVAL                       315
#define TK_RETENTION                      316
#define TK_RECURSIVE                      317
#define TK_COUNT                          318
#define TK_LAST_ROW                       319
#define TK_META                           320
#define TK_ONLY                           321
#define TK_CONSUMER                       322
#define TK_GROUP                          323
#define TK_DESCRIBE                       324
#define TK_RESET                          325
#define TK_CACHE                          326
#define TK_EXPLAIN                        327
#define TK_ANALYZE                        328
#define TK_VERBOSE                        329
#define TK_NK_BOOL                        330
#define TK_RATIO                          331
#define TK_NK_FLOAT                       332
#define TK_OUTPUTTYPE                     333
#define TK_AGGREGATE                      334
#define TK_BUFSIZE                        335
#define TK_LANGUAGE                       336
#define TK_REPLACE                        337
#define TK_INTO                           338
#define TK_SESSION                        339
#define TK_STATE_WINDOW                   340
#define TK_SLIDING                        341
#define TK_EVENT_WINDOW                   342
#define TK_COUNT_WINDOW                   343
#define TK_PERIOD                         344
#define TK_PARTITION                      345
#define TK_BY                             346
#define TK_STREAM_OPTIONS                 347
#define TK_CALC_NOTIFY_ONLY               348
#define TK_DELETE_RECALC                  349
#define TK_DELETE_OUTPUT_TABLE            350
#define TK_EXPIRED_TIME                   351
#define TK_FILL_HISTORY                   352
#define TK_FILL_HISTORY_FIRST             353
#define TK_FORCE_OUTPUT                   354
#define TK_IGNORE_DISORDER                355
#define TK_LOW_LATENCY_CALC               356
#define TK_PRE_FILTER                     357
#define TK_EVENT_TYPE                     358
#define TK_IGNORE_NODATA_TRIGGER          359
#define TK_NOTIFY                         360
#define TK_NOTIFY_OPTIONS                 361
#define TK_NOTIFY_HISTORY                 362
#define TK_WINDOW_OPEN                    363
#define TK_WINDOW_CLOSE                   364
#define TK_OUTPUT_SUBTABLE                365
#define TK_PRIMARY                        366
#define TK_COMPOSITE                      367
#define TK_IGNORE                         368
#define TK_UNTREATED                      369
#define TK_BALANCE                        370
#define TK_VGROUP                         371
#define TK_ASSIGN                         372
#define TK_LEADER                         373
#define TK_MERGE                          374
#define TK_REDISTRIBUTE                   375
#define TK_SPLIT                          376
#define TK_NK_BIN                         377
#define TK_NK_HEX                         378
#define TK_NK_QUESTION                    379
#define TK_NK_ALIAS                       380
#define TK_ROWTS                          381
#define TK_QSTART                         382
#define TK_QEND                           383
#define TK_QDURATION                      384
#define TK_WSTART                         385
#define TK_WEND                           386
#define TK_WDURATION                      387
#define TK_IROWTS                         388
#define TK_ISFILLED                       389
#define TK_FLOW                           390
#define TK_FHIGH                          391
#define TK_FROWTS                         392
#define TK_IROWTS_ORIGIN                  393
#define TK_TPREV_TS                       394
#define TK_TCURRENT_TS                    395
#define TK_TNEXT_TS                       396
#define TK_TWSTART                        397
#define TK_TWEND                          398
#define TK_TWDURATION                     399
#define TK_TWROWNUM                       400
#define TK_TPREV_LOCALTIME                401
#define TK_TNEXT_LOCALTIME                402
#define TK_TLOCALTIME                     403
#define TK_TGRPID                         404
#define TK_IMPROWTS                       405
#define TK_IMPMARK                        406
#define TK_ANOMALYMARK                    407
#define TK_CAST                           408
#define TK_POSITION                       409
#define TK_NOW                            410
#define TK_TODAY                          411
#define TK_RAND                           412
#define TK_SUBSTR                         413
#define TK_SUBSTRING                      414
#define TK_BOTH                           415
#define TK_TRAILING                       416
#define TK_LEADING                        417
#define TK_TIMEZONE                       418
#define TK_CLIENT_VERSION                 419
#define TK_SERVER_VERSION                 420
#define TK_SERVER_STATUS                  421
#define TK_CURRENT_USER                   422
#define TK_PI                             423
#define TK_COLS                           424
#define TK_IFNULL                         425
#define TK_NVL                            426
#define TK_NVL2                           427
#define TK_NULLIF                         428
#define TK_COALESCE                       429
#define TK_CASE                           430
#define TK_WHEN                           431
#define TK_THEN                           432
#define TK_ELSE                           433
#define TK_ISNULL                         434
#define TK_ISNOTNULL                      435
#define TK_TROWS                          436
#define TK_NK_HINT                        437
#define TK_DISTINCT                       438
#define TK_AUTO                           439
#define TK_ANOMALY_WINDOW                 440
#define TK_FILL                           441
#define TK_VALUE                          442
#define TK_VALUE_F                        443
#define TK_NONE                           444
#define TK_NULL_F                         445
#define TK_LINEAR                         446
#define TK_PREV                           447
#define TK_NEXT                           448
#define TK_NEAR                           449
#define TK_HAVING                         450
#define TK_RANGE                          451
#define TK_EVERY                          452
#define TK_TRUE_FOR                       453
#define TK_ORDER                          454
#define TK_SLIMIT                         455
#define TK_SOFFSET                        456
#define TK_LIMIT                          457
#define TK_OFFSET                         458
#define TK_ASC                            459
#define TK_NULLS                          460
#define TK_ABORT                          461
#define TK_AFTER                          462
#define TK_ATTACH                         463
#define TK_BEFORE                         464
#define TK_BEGIN                          465
#define TK_BITAND                         466
#define TK_BITNOT                         467
#define TK_BITOR                          468
#define TK_BLOCKS                         469
#define TK_CHANGE                         470
#define TK_COMMA                          471
#define TK_CONCAT                         472
#define TK_CONFLICT                       473
#define TK_COPY                           474
#define TK_DEFERRED                       475
#define TK_DELIMITERS                     476
#define TK_DETACH                         477
#define TK_DIVIDE                         478
#define TK_DOT                            479
#define TK_EACH                           480
#define TK_FAIL                           481
#define TK_GLOB                           482
#define TK_ID                             483
#define TK_IMMEDIATE                      484
#define TK_IMPORT                         485
#define TK_INITIALLY                      486
#define TK_INSTEAD                        487
#define TK_MODULES                        488
#define TK_NK_BITNOT                      489
#define TK_NK_SEMI                        490
#define TK_NOTNULL                        491
#define TK_OF                             492
#define TK_PLUS                           493
#define TK_RAISE                          494
#define TK_RESTRICT                       495
#define TK_ROW                            496
#define TK_STAR                           497
#define TK_STATEMENT                      498
#define TK_STRICT                         499
#define TK_STRING                         500
#define TK_TIMES                          501
#define TK_VALUES                         502
#define TK_VARIABLE                       503
