CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(TDengine)

INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/os/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/util/inc)
INCLUDE_DIRECTORIES(${TD_COMMUNITY_DIR}/src/common/inc)
INCLUDE_DIRECTORIES(${TD_ENTERPRISE_DIR}/src/inc)
INCLUDE_DIRECTORIES(../deps/libmseed)

ADD_EXECUTABLE(databaseToFile databaseToFile.c)
TARGET_LINK_LIBRARIES(databaseToFile taos mseed)

ADD_EXECUTABLE(fileToDatabase fileToDatabase.c)
TARGET_LINK_LIBRARIES(fileToDatabase taos mseed)
