# cd /home/yihao/TDengine/tests/script; sh/stop_dnodes.sh;
# cd /home/yihao/TDengine/tests/script; sh/deploy.sh -n dnode1 -i 1;
# cd /home/yihao/TDengine/tests/script; sh/deploy.sh -n dnode2 -i 2;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode1 -s start;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode2 -s start;
create dnode localhost port 7200;
create database db vgroups 3;
create database db vgroups 3;
use db;
create table stb (ts timestamp, c int) tags (t int);
create table t0 using stb tags (0);
create table tba (ts timestamp, c1 binary(10), c2 nchar(10));;
select * from information_schema.ins_dnodes;
select * from information_schema.ins_mnodes;
select * from information_schema.ins_databases;
show stables;
show tables;
select * from information_schema.ins_users;
show vgroups;
select * from information_schema.ins_dnodes;
select * from information_schema.ins_mnodes;
select * from information_schema.ins_databases;
select * from information_schema.ins_stables;
select * from information_schema.ins_tables;
select * from information_schema.ins_users;
select * from information_schema.ins_vgroups;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode1 -s stop -x SIGINT;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode2 -s stop -x SIGINT;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode1 -s start;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode2 -s start;
# sleep 200;
select * from information_schema.ins_dnodes;
# sleep 200;
select * from information_schema.ins_dnodes;
# sleep 200;
select * from information_schema.ins_dnodes;
# sleep 200;
select * from information_schema.ins_dnodes;
# sleep 200;
select * from information_schema.ins_dnodes;
select * from information_schema.ins_dnodes;
select * from information_schema.ins_mnodes;
select * from information_schema.ins_databases;
show stables;
show tables;
select * from information_schema.ins_users;
show vgroups;
select * from information_schema.ins_dnodes;
select * from information_schema.ins_mnodes;
select * from information_schema.ins_databases;
select * from information_schema.ins_stables;
select * from information_schema.ins_tables;
select * from information_schema.ins_users;
select * from information_schema.ins_vgroups;
show create stable stb;;
show create table t0;;
show create table tba;;
show variables;;
show dnode 1 variables;;
show local variables;;
show cluster alive;;
show db.alive;;
# cd /home/yihao/TDengine/tests/script; taos -P7100 -d db -s " show create table db.t0";
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode1 -s stop -x SIGINT;
# cd /home/yihao/TDengine/tests/script; sh/exec.sh -n dnode2 -s stop -x SIGINT;
