package sqlparser

// Compile-time interface contract checks.
// These assertions fail compilation when required methods are missing.
var (
	_ Statement = (*AlterClusterStmt)(nil)
	_ Statement = (*AlterDatabaseStmt)(nil)
	_ Statement = (*AlterDnodeStmt)(nil)
	_ Statement = (*AlterDnodesReloadStmt)(nil)
	_ Statement = (*AlterEncryptKeyStmt)(nil)
	_ Statement = (*AlterLocalStmt)(nil)
	_ Statement = (*AlterNamedStmt)(nil)
	_ Statement = (*AlterRoleStmt)(nil)
	_ Statement = (*AlterTableStmt)(nil)
	_ Statement = (*AlterTokenStmt)(nil)
	_ Statement = (*AlterUserStmt)(nil)
	_ Statement = (*AlterVgroupKeepStmt)(nil)
	_ Statement = (*AssignLeaderStmt)(nil)
	_ Statement = (*BalanceVgroupLeaderStmt)(nil)
	_ Statement = (*BalanceVgroupStmt)(nil)
	_ Statement = (*CompactStmt)(nil)
	_ Statement = (*CreateAnodeStmt)(nil)
	_ Statement = (*CreateBnodeStmt)(nil)
	_ Statement = (*CreateComponentNodeStmt)(nil)
	_ Statement = (*CreateDatabaseStmt)(nil)
	_ Statement = (*CreateDnodeStmt)(nil)
	_ Statement = (*CreateEncryptAlgrStmt)(nil)
	_ Statement = (*CreateMountStmt)(nil)
	_ Statement = (*CreateNamedStmt)(nil)
	_ Statement = (*CreateRoleStmt)(nil)
	_ Statement = (*CreateSubTableFromFileStmt)(nil)
	_ Statement = (*CreateTableStmt)(nil)
	_ Statement = (*CreateTokenStmt)(nil)
	_ Statement = (*CreateUserStmt)(nil)
	_ Statement = (*CreateViewStmt)(nil)
	_ Statement = (*CreateVSubTableStmt)(nil)
	_ Statement = (*DeleteStmt)(nil)
	_ Statement = (*DescribeStmt)(nil)
	_ Statement = (*DropAnodeStmt)(nil)
	_ Statement = (*DropBnodeStmt)(nil)
	_ Statement = (*DropComponentNodeStmt)(nil)
	_ Statement = (*DropDatabaseStmt)(nil)
	_ Statement = (*DropDnodeStmt)(nil)
	_ Statement = (*DropEncryptAlgrStmt)(nil)
	_ Statement = (*CreateFunctionStmt)(nil)
	_ Statement = (*DropFunctionStmt)(nil)
	_ Statement = (*DropMountStmt)(nil)
	_ Statement = (*DropNamedStmt)(nil)
	_ Statement = (*DropRoleStmt)(nil)
	_ Statement = (*DropTableStmt)(nil)
	_ Statement = (*DropTokenStmt)(nil)
	_ Statement = (*DropUserStmt)(nil)
	_ Statement = (*DropViewStmt)(nil)
	_ Statement = (*ExplainStmt)(nil)
	_ Statement = (*FlushDatabaseStmt)(nil)
	_ Statement = (*GrantRoleStmt)(nil)
	_ Statement = (*GrantStmt)(nil)
	_ Statement = (*InsertQueryStmt)(nil)
	_ Statement = InsertStatement{}
	_ Statement = (*KillStmt)(nil)
	_ Statement = (*MergeVgroupStmt)(nil)
	_ Statement = (*MultiCreateTableStmt)(nil)
	_ Statement = (*RevokeRoleStmt)(nil)
	_ Statement = (*RedistributeVgroupStmt)(nil)
	_ Statement = (*ResetQueryCacheStmt)(nil)
	_ Statement = (*RestoreComponentNodeStmt)(nil)
	_ Statement = (*RestoreDnodeStmt)(nil)
	_ Statement = (*RollupStmt)(nil)
	_ Statement = (*ScanStmt)(nil)
	_ Statement = (*SelectStmt)(nil)
	_ Statement = (*ShowStmt)(nil)
	_ Statement = (*SplitVgroupStmt)(nil)
	_ Statement = (*SsMigrateDatabaseStmt)(nil)
	_ Statement = (*StreamStmt)(nil)
	_ Statement = (*TopicStmt)(nil)
	_ Statement = (*TrimDatabaseStmt)(nil)
	_ Statement = (*TrimDatabaseWalStmt)(nil)
	_ Statement = (*UpdateAnodeStmt)(nil)
	_ Statement = (*UseDatabaseStmt)(nil)
	_ Statement = (*XnodeStmt)(nil)

	_ Expr = (*AliasedExpr)(nil)
	_ Expr = BoolVal(false)
	_ Expr = Literal{}
	_ Expr = (*RawExpr)(nil)
	_ Expr = (*SQLVal)(nil)
	_ Expr = (*SelectStmt)(nil)
	_ Expr = (*StarExpr)(nil)

	_ SelectExpr = (*AliasedExpr)(nil)
	_ SelectExpr = (*StarExpr)(nil)

	_ TableExpr = (*JoinTableExpr)(nil)
	_ TableExpr = (*SubqueryTableExpr)(nil)
	_ TableExpr = (*TableNameExpr)(nil)
)
