name: CI

on:
  pull_request:
    paths:
    - 'src/**'
    - 'tests/**'
    - 'Cargo.toml'
    - '.github/workflows/build.yaml'
    - 'build.rs'
    - 'migrations/**'
    - 'taosx-*/**'
  workflow_dispatch:

env:
  RUSTFLAGS: "--cfg tokio_unstable"

jobs:
  check:
    name: Check
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Compile check
        run: |
          cargo check --all

      - name: Format check
        run: |
          cargo fmt --check --all
