name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

      - uses: actions/cache@v3
        name: Cargo Caches
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo

      - uses: actions/cache@v3
        name: Target Caches
        with:
          path: |
            target
          key: ${{ runner.os }}-target

      - name: Build taosX
        run: |
          cargo build

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

