name: CI

on:
  pull_request:
    paths:
    - 'src/**'
    - 'tests/**'
    - 'Cargo.toml'
    - '.github/workflows/build.yaml'
    - 'build.rs'
    - 'migrations/**'
    - 'taosx-*/**'
  workflow_dispatch:

env:
  RUSTFLAGS: "--cfg tokio_unstable"

jobs:
  stable:
    name: Stable Channel
    runs-on: [self-hosted, linux, x64, app2]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Compile check
        run: |
          cargo +stable check --locked --workspace --all --tests --examples --target-dir targets/stable

  check:
    name: Check
    runs-on: [self-hosted, linux, x64, app2]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Compile check
        run: |
          cargo check --locked --workspace --all --tests --examples

      - name: Format check
        run: |
          cargo fmt --locked --check --all

      - name: Typos check
        run: |
          typos src taosx-* README.md
