name: Bundle

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions

jobs:
  # build-for-macos-m1:
  #   runs-on: macos-11
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #     - run: npm install
  #     - run: npm run build

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: aarch64-apple-darwin
  #     - uses: actions/cache@v3
  #       name: Cargo Caches
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #         key: ${{ runner.os }}-cargo

  #     - uses: actions/cache@v3
  #       name: Target Caches
  #       with:
  #         path: |
  #           target
  #         key: ${{ runner.os }}-cargo-target-aarch64

  #     - name: Build
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --release --target aarch64-apple-darwin

  #     - name: Upload
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-11-m1
  #         path: target/aarch64-apple-darwin/release/tao-explorer

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build

      - uses: dtolnay/rust-toolchain@nightly

      - uses: actions/cache@v3
        name: Cargo Caches
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo
      - uses: actions/cache@v3
        name: Target Caches
        with:
          path: |
            target
          key: ${{ runner.os }}-cargo-target

      - name: Install cargo bundle
        run: |
          command -v cargo-bundle || cargo install cargo-bundle

      - name: Bundle
        run: |
          cargo bundle --release
          cd target/release/bundle/
          tar -cavf osx.tar.gz *

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: App
          path: target/release/bundle/osx.tar.gz

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: dtolnay/rust-toolchain@nightly

  #     - uses: actions/cache@v3
  #       name: Cargo Caches
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #         key: ${{ runner.os }}-cargo

  #     - uses: actions/cache@v3
  #       name: Target Caches
  #       with:
  #         path: |
  #           target
  #         key: ${{ runner.os }}-cargo-target

  #     - name: Install cargo bundle
  #       run: |
  #         cargo install cargo-bundle -f

  #     - name: Bundle
  #       run: |
  #         cargo build --release

  #     - name: Upload
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: App
  #         path: target/release/*.exe

  # linux:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |
  #         sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev

  #     - uses: dtolnay/rust-toolchain@nightly

  #     - uses: actions/cache@v3
  #       name: Cargo Caches
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #         key: ${{ runner.os }}-cargo

  #     - uses: actions/cache@v3
  #       name: Target Caches
  #       with:
  #         path: |
  #           target
  #         key: ${{ runner.os }}-cargo-target

  #     - name: Install cargo bundle
  #       run: |
  #         cargo install cargo-bundle -f

  #     - name: Bundle
  #       run: |
  #         cargo bundle --release

  #     - name: Upload
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: App
  #         path: target/release/bundle/deb/*.deb
