name: ci

on:
  push:
    branches:
      # TODO update to main
      - github-actions
  pull_request:
    branches:
      - github-actions

jobs:
  build-package:
    name: build-package
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS: ""
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
      # Build static releases with PCRE2.
      PCRE2_SYS_STATIC: 1
    strategy:
      matrix:
        build: [linux, linux-aarch64, macos, win-msvc]
        include:
        - build: linux
          os: ubuntu-22.04
          rust: nightly
          target: x86_64-unknown-linux-musl
        - build: linux-arm
          os: ubuntu-22.04
          rust: nightly
          target: aarch64-unknown-linux-musl
        - build: macos
          os: macos-12
          rust: nightly
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-2022
          rust: nightly
          target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Use Cross
        shell: bash
        run: |
          cargo install cross
          echo "CARGO=cross" >> $GITHUB_ENV
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

      - name: Show command used for Cargo
        run: |
          echo "cargo command is: ${{ env.CARGO }}"
          echo "target flag is: ${{ env.TARGET_FLAGS }}"
          echo "target dir is: ${{ env.TARGET_DIR }}"

      - name: Build release binary
        run: ${{ env.CARGO }} build --verbose --release --features pcre2 ${{ env.TARGET_FLAGS }}
      
      - name: Strip release binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/rg"

      - name: Strip release binary (arm)
        if: matrix.build == 'linux-arm'
        run: |
          docker run --rm -v \
            "$PWD/target:/target:Z" \
            rustembedded/cross:aarch64-unknown-linux-musl \
            arm-linux-gnueabihf-strip \
            /target/aarch64-unknown-linux-musl/release/
      
      - name: Build archive
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-2022" ]; then
            cd target/${{ matrix.target }}/release/
            7z a taos-explorer-${{ matrix.target }}.zip *.exe
            archive-file=taos-explorer-${{ matrix.target }}.zip
            echo "ASSET=archive-file" >> $GITHUB_ENV
          else
            # The man page is only generated on Unix systems. ¯\_(ツ)_/¯
            cd "target/${{ matrix.target }}/release/" 
            tar czf taos-explorer-${{ matrix.target }}.tar.gz taos-explorer
            archive-file=taos-explorer-${{ matrix.target }}.tar.gz
            echo "ASSET=archive-file" >> $GITHUB_ENV
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ASSET }}
          path: target/${{ matrix.target }}/release/
          