name: Code Coverage

on:
  # workflow_dispatch:
  push:
    branches:
      - main
      - "3.0"

env:
  REPORT_BASE_URL: http://192.168.1.45:8787
  GRANT_SSH: root@192.168.1.55
  CARGO_OPTS: --locked

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Code Coverage Test
    runs-on: [self-hosted, linux, x64, app2]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Code Coverage Test
        run: |
          cargo make test
      - name: Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: taosx-coverage-report
          path: target/llvm-cov-merged.lcov
  upload-coverage:
    needs: unit-test
    name: Upload Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: taosx-coverage-report
      - uses: actions/checkout@v4
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: llvm-cov-merged.lcov
          fail_ci_if_error: true
          verbose: true
