name: New Framework Test For Stream Dev

on:
  # push:
  #   branches:
  #     - 'feat/TS-6100-3.0'
  #   paths-ignore:
  #     - 'packaging/**'
  #     - 'docs/**'
  pull_request:
    branches:
      - 'feat/TS-6100-3.0'
    paths-ignore:
      - 'packaging/**'
      - 'docs/**'
      - 'tools/tdgpt/**'
      - 'source/libs/executor/src/forecastoperator.c'
      - 'source/libs/executor/src/anomalywindowoperator.c'
      - 'source/dnode/mnode/impl/src/mndAnode.c'
      - 'include/common/tanalytics.h'
      - 'source/common/src/tanalytics.c'
      - 'tests/parallel/tdgpt_cases.task'
      - 'tests/script/tsim/analytics'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-TDengineNewFramework
  cancel-in-progress: true

jobs:
  test-new-cases:
    uses: taosdata/.github/.github/workflows/new-framework-test-for-stream-dev.yml@feat/TS-6100-3.0
    with:
      tdinternal: false
