name: Build Latest

on:
  push:
    branches:
      - fix/TD-24879-fix-commit-id-lost

jobs:
  centos:
    name: CentOS 7.9
    runs-on: ubuntu-latest
    container: docker.io/centos:7

    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: |
          yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
          yum install -y git

      - uses: actions/checkout@v3

      - name: Set up Rust
        id: setup-rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Install compiler
        run: |
          yum install -y autoconf make automake cmake gcc gcc-g++ openssl-devel

      - uses: Swatinem/rust-cache@v2

      - name: Build taosX
        run: |
          git config --global --add safe.directory $PWD
          cargo build --release --no-default-features --features optin --features native-tls
          target/release/taosx -V
          strip target/release/taosx
          mv target/release/taosx target/release/taosx-amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: taosx
          path: target/release/taosx-amd64
  # release:
  #   needs: centos
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: taosx
  #     - uses: rickstaa/action-create-tag@v1
  #       with:
  #         tag: "latest"
  #         message: "Latest"
  #         force_push_tag: true
  #     - run: |
  #         chmod +x taosx-amd64
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         name: Latest
  #         tag_name: latest
  #         files: |
  #           taosx-amd64
