
name: Review Dog

on:
  pull_request:
    branches:
      - 'main'
      - '3.0'
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@v2
      - name: Report ReviewDog
        uses: huacnlee/autocorrect-action@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true