name: TDengine Test (Manual)

on:
  workflow_dispatch:
    inputs:
      specified_source_branch:
        description: 'Enter the source branch name of TDengine'
        required: false
        default: 'unavailable'
        type: string
      specified_target_branch:
        description: 'Enter the target branch name of TDengine'
        required: false
        default: 'unavailable'
        type: string
      specified_pr_number:
        description: 'Enter the PR number of TDengine'
        required: false
        default: 'unavailable'
        type: string

concurrency:
  group: ${{ github.event.inputs.specified_target_branch }}-${{ github.event.inputs.specified_pr_number }}-TDengine
  cancel-in-progress: true

env:
  WKC: '/var/lib/jenkins/workspace/TDinternal/community'

jobs:
  run-tests-on-linux:
    uses: taosdata/.github/.github/workflows/run-tests-on-linux.yml@ci/test/workflow
    with:
      tdinternal: false
      run_function_test: true
      run_tdgpt_test: false
      specified_source_branch: ${{ github.event.inputs.specified_source_branch }}
      specified_target_branch: ${{ github.event.inputs.specified_target_branch }}
      specified_pr_number: ${{ github.event.inputs.specified_pr_number }}

  run-tests-on-mac:
    uses: taosdata/.github/.github/workflows/run-tests-on-macos.yml@ci/test/workflow
    with:
      tdinternal: false
      specified_source_branch: ${{ github.event.inputs.specified_source_branch }}
      specified_target_branch: ${{ github.event.inputs.specified_target_branch }}
      specified_pr_number: ${{ github.event.inputs.specified_pr_number }}

  run-tests-on-windows:
    uses: taosdata/.github/.github/workflows/run-tests-on-windows.yml@ci/test/workflow
    with:
      tdinternal: false
      specified_source_branch: ${{ github.event.inputs.specified_source_branch }}
      specified_target_branch: ${{ github.event.inputs.specified_target_branch }}
      specified_pr_number: ${{ github.event.inputs.specified_pr_number }}
