name: Enum Check

on:
  pull_request:
    branches:
      - 'main'
      - '3.0'
      - '3.1'
      - '3.3.6'
    paths-ignore:
      - 'packaging/**'
      - 'docs/**'
      - 'tools/tdgpt/**'
      - 'source/libs/executor/src/forecastoperator.c'
      - 'source/libs/executor/src/anomalywindowoperator.c'
      - 'source/dnode/mnode/impl/src/mndAnode.c'
      - 'include/common/tanalytics.h'
      - 'source/common/src/tanalytics.c'
      - 'tests/parallel/tdgpt_cases.task'
      - 'tests/script/tsim/analytics'
      - '**/*.md'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-
    ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || inputs.specified_target_branch }}-
    ${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.specified_pr_number }}-TDengine
  cancel-in-progress: true

env:
  WKC: '/var/lib/jenkins/workspace/TDinternal/community'

jobs:
  enum-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 需要完整历史支持 diff

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libclang-dev python3-clang
          pip install clang

      - name: Determine base branch
        id: base
        run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Get changed C/H files
        id: changed_files
        run: |
          git fetch origin $BASE_BRANCH
          FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD | grep -E '\.(c|h)$' || echo '')
          echo "::set-output name=files::$FILES"

      - name: Run enum check
        if: steps.changed_files.outputs.files != ''
        run: |
          echo "Checking enums in files:"
          echo "${{ steps.changed_files.outputs.files }}"
          python3 .github/scripts/check_enum_append_only.py ${{ steps.changed_files.outputs.files }}

      - name: Skip enum check
        if: steps.changed_files.outputs.files == ''
        run: echo "No changed C/H files, skipping enum check."
