jobs:
  enum-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Show Python info
        run: |
          which python3
          python3 --version
          python3 -m site

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm
          python3 -m pip install --upgrade pip
          python3 -m pip install libclang

      - name: Confirm libclang works
        run: |
          python3 -c "from libclang import get_library_path; print('libclang path:', get_library_path())"

      - name: Determine base branch
        id: base
        run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Get changed C/H files
        id: changed_files
        run: |
          git fetch origin $BASE_BRANCH
          FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD | grep -E '\.(c|h)$' || echo '')
          echo "files=$FILES" >> "$GITHUB_OUTPUT"

      - name: Run enum check
        if: steps.changed_files.outputs.files != ''
        run: |
          echo "Checking enums in files:"
          echo "${{ steps.changed_files.outputs.files }}"
          python3 .github/scripts/check_enum_append_only.py ${{ steps.changed_files.outputs.files }}

      - name: Skip enum check
        if: steps.changed_files.outputs.files == ''
        run: echo "No changed C/H files, skipping enum check."
