name: TDgpt Update Service

on:
  schedule:
    - cron: '30 00 * * *'

env:
  WKC: "/root/TDengine"

jobs:
  update-service:
    runs-on:
      group: CI
      labels: [self-hosted, Linux, X64, tdgpt-anode-service]
    steps:
      - name: Update TDengine codes
        run: |
          set -euo pipefail
          cd ${{ env.WKC }}
          git checkout main
          git pull

      - name: Package the TDGpt Anode Service
        run: |
          set -euo pipefail
          cd ${{ env.WKC }}/tools/tdgpt/script && ./release.sh -e community  -v ${{ vars.TDGPT_VERSION }}

      - name: Reinstall and restart the TDGpt Anode Service
        run: |
          set -euo pipefail
          cd ${{ env.WKC }}/tools/tdgpt/release
          if [[ -f "TDengine-enterprise-anode-1.0.1.tar.gz" ]]; then
            tar -xzf TDengine-enterprise-anode-1.0.1.tar.gz
            cd TDengine-enterprise-anode-1.0.1
            ./install.sh
          fi
          systemctl restart taosanoded

      - name: Clean up
        if: always()
        run: |
          if [[ -f "${{ env.WKC }}/tools/tdgpt/release/TDengine-enterprise-anode-1.0.1" ]]; then 
            rm -rf "${{ env.WKC }}/tools/tdgpt/release/TDengine-enterprise-anode-1.0.1" 
          fi
