name: TDinternal CI Pipelines

description: Only trigger the ci workflow of TDnegine and pass the source branch, target branch and pr number. 

on:
  pull_request:
    types:
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-tdengine-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI Workflow from TDengine repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          repository: taosdata/TDengine
          event-type: run-tests
          client-payload: |
            {
              "tdinternal_source_branch": "${{ github.event.pull_request.head.ref }}",
              "tdinternal_target_branch": "${{ github.event.pull_request.base.ref }}",
              "tdinternal_pr_number": "${{ github.event.pull_request.number }}"
            }
