name: TDinternal CI Pipelines

description: Only trigger the ci workflow of TDnegine and pass the value of source branch, target branch、pr number and github.ref. 

on:
  pull_request:
    branches:
      - 'main'
      - '3.0'
      - '3.1'
    paths-ignore:
      - 'enterprise/documentation/**'
      - 'enterprise/packaging/**'

jobs:
  trigger-tdengine-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI Workflow from TDengine repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          repository: taosdata/TDengine
          event-type: run-tests
          client-payload: |
            {
              "tdinternal_source_branch": "${{ github.event.pull_request.head.ref }}",
              "tdinternal_target_branch": "${{ github.event.pull_request.base.ref }}",
              "tdinternal_pr_number": "${{ github.event.pull_request.number }}",
              "ref": "${{ github.ref }}"
            }
