name: TDinternal CI Pipelines

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - test/ga

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-tdengine-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub App Token
        id: app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.TAOSDATA_BOT_ID }}
          private_key: ${{ secrets.TAOSDATA_BOT_KEY }}
      
      - name: Trigger CI Workflow from TDengine repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: TDengine
          event-type: run-tests
          client-payload: |
            {
              "tdinternal_source_branch": "${{ github.event.pull_request.head.ref }}",
              "tdinternal_target_branch": "${{ github.event.pull_request.base.ref }}",
              "tdinternal_pr_number": "${{ github.event.pull_request.number }}"
            }
