
name: Test-for-win
on:
  pull_request:
    branches:
      - 'main'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-Test-for-win
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      group: CI
      labels: [self-hosted, Windows, X64, test-win, testing]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run your script
        shell: cmd 
        run: where python3

      - name: Run your script
        run: where python3
        
      - name: Run your script
        run: python3 c:\\test.py



        
        
