#!/bin/bash

logging() {
    logLevel=$1
    logMsg=$2
    echo "`date \"+%Y-%m-%d %H:%M:%S.%N\"` td_cluster_check: [$logLevel] $logMsg" 2>&1 | tee -a /var/log/td_cluster_check.log
}

logging "INFO" "td cluster check begins"
taosd -C -c '/var/log' > /var/log/taosdc_out
FQDN=$(cat /var/log/taosdc_out|grep -E 'fqdn.*(\S+)' -o |head -n1|sed 's/fqdn *//')
FIRSET_EP=$(cat /var/log/taosdc_out|grep -E 'firstEp.*(\S+)' -o|head -n1|sed 's/firstEp *//')
SECOND_EP=$(cat /var/log/taosdc_out|grep -E 'secondEp.*(\S+)' -o|head -n1|sed 's/secondEp *//')

# parse first ep host and port
FIRST_EP_HOST=${FIRSET_EP%:*}
FIRST_EP_PORT=${FIRSET_EP#*:}

SECOND_EP_HOST=${SECOND_EP%:*}
SECOND_EP_PORT=${SECOND_EP#*:}


TAOS_TIMEOUT_SECOND=${TAOS_TIMEOUT_SECOND:-10}
ENDPOINT=$FQDN:$SERVER_PORT

logging "INFO" "TAOS_TIMEOUT_SECOND: ${TAOS_TIMEOUT_SECOND}"
logging "INFO" "FIRST_EP_HOST: ${FIRST_EP_HOST}"
logging "INFO" "FIRST_EP_PORT: ${FIRST_EP_PORT}"
logging "INFO" "SECOND_EP_HOST: ${SECOND_EP_HOST}"
logging "INFO" "SECOND_EP_PORT: ${SECOND_EP_PORT}"
logging "INFO" "ENDPOINT: ${ENDPOINT}"

param1=$1
if [[ -z $param1 ]]; then
    nc -z 127.0.0.1 6041
    if [ $? -ne 0 ]; then
        logging "ERROR" "taosadapter port 6041 is not ok"
        exit 1
    fi
fi


if [ "$param1"x = "CheckClusterStatus"x ]; then
    logging "INFO" "CheckClusterStatus begin"
    # get dnode id
    # output=$(timeout $TAOS_TIMEOUT_SECOND taos -w 2000 -s "show dnodes;" | grep -E "td-transport" | grep -E -v "$ENDPOINT"  | awk '{split($0,a,"|");print a[1]}' | awk '{gsub(/ /,"")}1' )
    if [ "$SECOND_EP_HOST"x = "$FIRST_EP_HOST"x ]; then
        logging "INFO" "CheckClusterStatus existed 0 for single node"
        exit 0
    fi
    ShortTime=2
    output=$(timeout $ShortTime curl -L -H "Authorization: Basic cm9vdDp0YW9zZGF0YQ==" -d "show dnodes;" $FIRST_EP_HOST:6041/rest/sql)
    CURRENET_EP=$FIRST_EP_HOST

    if [[ 0 = $(echo "$output" | jq -r '.code') ]]; then
        :
    else
        output=$(timeout $ShortTime curl -L -H "Authorization: Basic cm9vdDp0YW9zZGF0YQ==" -d "show dnodes;" $SECOND_EP_HOST:6041/rest/sql)
        CURRENET_EP=$SECOND_EP_HOST
        if [[ 0 = $(echo "$output" | jq -r '.code') ]]; then
            :
        else 
            logging "INFO" "CheckClusterStatus existed 0 for first and second ep not started"
            exit 0
        fi
    fi        

    logging "INFO" "output: $output"
    sleep 20
    exit 0
    if [[ 0 = $(echo "$output" | jq -r '.code') ]]; then
        i=0
        rows=$(echo "$output" | jq -r '.rows')
        while [ $i -lt $rows ] 
        do
            name=$(echo "$output" | jq -r ".data[$i][1]")
            dnodeId=$(echo "$output" | jq -r ".data[$i][0]")

            logging "INFO" "name: $name"
            logging "INFO" "dnodeId: $dnodeId"


            if [[ $name == *$ENDPOINT* ]]; then
                :
            else
                logging "INFO" "check dnode --$dnodeId--"
                # get vgroup status
                VGroupStatusTmp=$(timeout $TAOS_TIMEOUT_SECOND curl -L -H "Authorization: Basic cm9vdDp0YW9zZGF0YQ==" -d "show vnodes on dnode $dnodeId;" $CURRENET_EP:6041/rest/sql | grep -i false )
                if [[ "$VGroupStatusTmp" != "" ]]; then
                    logging "ERROR" "there is vgroup not ready !! $VGroupStatusTmp"
                    exit 1
                fi
            fi
            let i++
        done
        logging "INFO" "CheckClusterStatus OK"
        exit 0
    else
        logging "ERROR" "CheckClusterStatus failed"
        exit 1
    fi
fi


# get dnode id
DNODETmp=$(timeout $TAOS_TIMEOUT_SECOND taos -h $FIRST_EP_HOST -P $FIRST_EP_PORT -w 2000 -s "show dnodes;" | grep -E "$ENDPOINT" | awk '{split($0,a,"|");print a[1]}' | awk '{gsub(/ /,"")}1' )
if [[ "$DNODETmp" == "" ]]; then
    logging "ERROR" "Could not get dnode number"
    exit 1
fi
logging "INFO" "DNODETmp $DNODETmp"


# get vgroup status
VGroupStatusTmp=$(timeout $TAOS_TIMEOUT_SECOND taos -h $FIRST_EP_HOST -P $FIRST_EP_PORT  -w 2000 -s "show vnodes on dnode $DNODETmp;" | grep -i false)
if [[ "$VGroupStatusTmp" == "" ]]; then
    logging "INFO" "All vgroup is ready!!"
    exit 0
else 
    logging "ERROR" "there is vgroup not ready!! $VGroupStatusTmp"
    exit 1
fi

logging "INFO" "td cluster check finished"
