name: InfluxDB

on:
  pull_request:
    paths:
      - ".github/workflows/influxdb.yaml"
      - "plugins/influxdb/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [self-hosted, linux, x64, app2]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Build taosx-influxdb
        working-directory: plugins/influxdb
        run: mvn clean test

      - name: Generate jacoco report
        working-directory: plugins/influxdb
        run: mvn jacoco:report

      - name: Save Jacoco report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage report of taosx-influxdb
          path: plugins/influxdb/target/site/jacoco/*

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: plugins/influxdb/target/site/jacoco/jacoco.csv
