name: Latest

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.toml"
      - ".github/workflows/latest.yaml"
      - "build.rs"
      - "migrations/**"
      - "taosx-*/**"
    branches:
      - main

jobs:
  centos7:
    name: CentOS 7 Latest
    runs-on: [self-hosted, linux, x64, app2]
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docker-dev:
              - 'docker/dev/**'

      - name: Build dev image
        if: steps.changes.outputs.docker-dev == 'true'
        run: |
          cargo make build-docker-dev

      - name: Build taosx in container taosx/dev
        run: |
          cargo make build-centos7-production

      - name: Test taosx
        run: |
          ./target/centos7/production/taosx --version

      - uses: rickstaa/action-create-tag@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          tag: "latest"
          message: "Latest"
          force_push_tag: true
      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Latest
          tag_name: latest
          files: |
            target/centos7/production/taosx
            target/centos7/production/taosx.dwp
            target/centos7/production/taosx-agent
            target/centos7/production/taosx-agent.dwp
