name: PR-QA-workflow
# run-name: ${{ github.actor }}, your PR is under test. 🚀

on:
  workflow_dispatch:
  #pull_request:
  #push:

env:
  RELEASE_HOST: 192.168.1.45
  RUSTFLAGS: "-C instrument-coverage --cfg tokio_unstable"
  ARTIFACT_BASE_DIR: /data/artifacts
  COVERAGE_BASE_DIR: /data/coverage
  DIR_PATH: ${{ github.event.number }}
  RUN_UNIT_TEST_FILE_FLAG: /etc/taos/taosx_run_unit_test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  remove_artifacts:
    runs-on: [self-hosted, linux, x64, qa, rust]
    steps:
      - name: Remove artifacts
        run: |
          rm -rf $ARTIFACT_BASE_DIR/$DIR_PATH/
          rm -rf $COVERAGE_BASE_DIR/$DIR_PATH/

  build_rust:
    needs: remove_artifacts
    runs-on: [self-hosted, linux, x64, qa, rust]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Env
        run: |
          pwd
          rustup component add llvm-tools-preview
          command -v cargo-llvm-cov || cargo install cargo-llvm-cov
          command -v cargo-nextest || cargo install cargo-nextest
          rustc --version
          echo $DIR_PATH

      - name: Build taosx
        run: |
          # build taosx and taosx-agent
          # export RUSTFLAGS="-C instrument-coverage --cfg tokio_unstable"
          rm -rf ./target/debug/taosx-profraw/
          export LLVM_PROFILE_FILE="./target/debug/taosx-profraw/taosx-%p-%m.profraw"
          cargo build --target-dir ./target/debug/taosx-build/
      - name: taosx unit test
        run: |
          if [ -f "$RUN_UNIT_TEST_FILE_FLAG" ]; then
              echo "run taosx unit test"
              # export LLVM_PROFILE_FILE="./target/debug/taosx-profraw/taosx-%p-%m.profraw"
              # cargo test --target-dir ./target/debug/taosx-build/
              cargo llvm-cov nextest --workspace --ignore-run-fail
              cargo llvm-cov report --lcov --output-path $ARTIFACT_BASE_DIR/$DIR_PATH/taosx-unit-test-lcov.info
              ls $ARTIFACT_BASE_DIR/$DIR_PATH/
          fi
      - name: Build agent
        run: |
          # build agent
          rm -rf ./target/debug/taosx-agent-profraw/
          # export RUSTFLAGS="-C instrument-coverage --cfg tokio_unstable"
          export LLVM_PROFILE_FILE="./target/debug/taosx-agent-profraw/taosx-agent-%p-%m.profraw"
          cargo build --package taosx-agent --target-dir ./target/debug/taosx-agent-build/

      - name: Copy files
        run: |
          ls $ARTIFACT_BASE_DIR/$DIR_PATH/bin || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/bin
          cp ./target/debug/taosx-build/debug/taosx ./target/debug/taosx-agent-build/debug/taosx-agent $ARTIFACT_BASE_DIR/$DIR_PATH/bin/
          cp -r ./target/debug/taosx-profraw/ $ARTIFACT_BASE_DIR/$DIR_PATH/
          cp -r ./target/debug/taosx-agent-profraw/ $ARTIFACT_BASE_DIR/$DIR_PATH/
          cd ..
          tar --exclude=./taosx/target/* -zcvf taosx.tar.gz ./taosx
          cp taosx.tar.gz $ARTIFACT_BASE_DIR/$DIR_PATH/
          rm taosx.tar.gz
          tar -xzf $ARTIFACT_BASE_DIR/$DIR_PATH/taosx.tar.gz -C $ARTIFACT_BASE_DIR/$DIR_PATH/
          rm $ARTIFACT_BASE_DIR/$DIR_PATH/taosx.tar.gz

  build_go:
    needs: remove_artifacts
    runs-on: [self-hosted, linux, x64, qa, go]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Env
        run: |
          pwd
          go version
      - name: Build opc
        run: |
          cd plugins/opc
          go build -cover -o taosx-opc
      - name: Run OPC Unit Test
        continue-on-error: true
        run: |
          cd plugins/opc
          if [ -f "$RUN_UNIT_TEST_FILE_FLAG" ]; then
            echo "run opc unit test"
            go test -coverpkg=./... -coverprofile=opc_unit_report.txt  -timeout=5s ./...
          fi
      - name: Copy OPC Files
        run: |
          cd plugins/opc
          if [-f "opc_unit_report.txt"]; then
            echo "Copy OPC Unit Test Coverage Data"
            ssh root@$RELEASE_HOST "ls $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/ || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/"
            scp opc_unit_report.txt root@$RELEASE_HOST:$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/
            rm opc_unit_report.txt
          fi
          ssh root@$RELEASE_HOST "ls $ARTIFACT_BASE_DIR/$DIR_PATH/bin/opc || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/bin/opc/"
          scp taosx-opc root@$RELEASE_HOST:$ARTIFACT_BASE_DIR/$DIR_PATH/bin/opc/

  build_java:
    needs: remove_artifacts
    runs-on: [self-hosted, linux, x64, qa, java]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Env
        run: |
          pwd
          java -version

      - name: Run InfluxDB Unit Test
        continue-on-error: true
        run: |
          cd plugins/influxdb
          if [ -f "$RUN_UNIT_TEST_FILE_FLAG" ]; then
            echo "run influxdb unit test"
            # 这里只执行单元测试不做覆盖率统计，单元测试的覆盖率统计与端到端的覆盖率一起统计
            mvn test
          fi
      - name: Package influxdb
        run: |
          cd plugins/influxdb
          mvn clean package -Dmaven.test.skip=true
          ssh root@$RELEASE_HOST "ls $ARTIFACT_BASE_DIR/$DIR_PATH/bin/influxdb || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/bin/influxdb/"
          # scp ./target/taosx-influxdb.jar root@$RELEASE_HOST:$ARTIFACT_BASE_DIR/$DIR_PATH/bin/influxdb/
          scp -r ./target/* root@$RELEASE_HOST:$ARTIFACT_BASE_DIR/$DIR_PATH/bin/influxdb/

      - name: Run OpenTSDB Unit Test
        continue-on-error: true
        run: |
          cd plugins/opentsdb
          if [ -f "$RUN_UNIT_TEST_FILE_FLAG" ]; then
            echo "run opentsdb unit test"
            # 这里只执行单元测试不做覆盖率统计，单元测试的覆盖率统计与端到端的覆盖率一起统计
            mvn test
          fi
      - name: Package OpenTSDB
        run: |
          cd plugins/opentsdb
          mvn clean package -Dmaven.test.skip=true
          ssh root@$RELEASE_HOST "ls $ARTIFACT_BASE_DIR/$DIR_PATH/bin/opentsdb || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/bin/opentsdb/"
          #scp ./target/taosx-opentsdb.jar root@$RELEASE_HOST:$ARTIFACT_BASE_DIR/$DIR_PATH/bin/opentsdb/
          scp -r ./target/* root@$RELEASE_HOST:$ARTIFACT_BASE_DIR/$DIR_PATH/bin/opentsdb/

  deploy_for_mqtt:
    runs-on: [self-hosted, linux, x64, qa, rust]
    needs: [build_rust, build_go, build_java]
    steps:
      - name: Deploy taosx
        run: |
          pwd
          ls ${{ github.workspace }}
          # run taosx
          ssh root@$RELEASE_HOST "ls $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data/ || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data/"
          ssh root@$RELEASE_HOST "nohup sh -c 'DATABASE_URL=/var/lib/taos/taosx/taosx.db LLVM_PROFILE_FILE=$ARTIFACT_BASE_DIR/$DIR_PATH/taosx-profraw/taosx-%p-%m.profraw GOCOVERDIR=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data/ PLUGINS_HOME=$ARTIFACT_BASE_DIR/$DIR_PATH/bin/ ENABLE_COVERAGE=true nohup $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx serve > $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx.log 2>&1 &'"

      - name: Deploy taosx-agent
        run: |
          pwd
          ls ${{ github.workspace }}
          # run taosx-agent
          ssh root@$RELEASE_HOST "nohup sh -c 'GOCOVERDIR=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data/ PLUGINS_HOME=$ARTIFACT_BASE_DIR/$DIR_PATH/bin/ ENABLE_COVERAGE=true LLVM_PROFILE_FILE=$ARTIFACT_BASE_DIR/$DIR_PATH/taosx-agent-profraw/taosx-agent-%p-%m.profraw nohup $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx-agent > $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx-agent.log 2>&1 &'"

  test_mqtt:
    runs-on: [self-hosted, linux, x64, qa, rust]
    needs: deploy_for_mqtt
    steps:
      - name: Update Repo
        run: |
          # 这里最好是 TestNG_taosx 已经被拉取到一个固定的位置
          # 重新登录执行 git pull，因为当前的 git 仓库对应的是 taosx
          ssh root@$RELEASE_HOST "cd /data/github/TestNG_taosX && git pull"
      - name: Restart taos-explorer & taosadapter
        run: |
          systemctl restart taos-explorer
          systemctl restart taosadapter

      - name: Run Test
        continue-on-error: true
        run: |
          ls $COVERAGE_BASE_DIR/$DIR_PATH/allure_profile || mkdir -p $COVERAGE_BASE_DIR/$DIR_PATH/allure_profile
          cd /data/github/TestNG_taosX && source ./setenv.sh && poetry install && cd tests && poetry run pytest --alluredir=$COVERAGE_BASE_DIR/$DIR_PATH/allure_profile --timeout=300 -m sanity mqtt_test.py

      - name: Stop taosx-agent & taosx
        shell: bash {0}
        run: |
          pids=$(pgrep "taosx-agent"); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -2 taosx-agent $pid"; kill -2 "$pid"; done; fi
          pids=$(pgrep "taosx"); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -2 taosx $pid"; kill -2 "$pid"; done; fi
      
      - name: Sleep for 20 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      
      - name: Force stop taosx-agent & taosx
        if: always()
        continue-on-error: true
        shell: bash {0}
        run: |
          pids=$(pgrep taosx-agent); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -9 taosx-agent $pid"; kill -9 "$pid"; done; else echo "taosx-agent is safe"; fi
          pids=$(pgrep taosx); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -9 taosx $pid"; kill -9 "$pid"; done; exit 1; else echo "tasox is safe"; fi

  deploy_for_others:
    runs-on: [self-hosted, linux, x64, qa, rust]
    needs: [test_mqtt]
    steps:
      - name: Deploy taosx
        run: |
          pwd
          ls ${{ github.workspace }}
          # run taosx
          ssh root@$RELEASE_HOST "ls $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/ || mkdir -p $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/"
          ssh root@$RELEASE_HOST "nohup sh -c 'DATABASE_URL=/var/lib/taos/taosx/taosx.db LLVM_PROFILE_FILE=$ARTIFACT_BASE_DIR/$DIR_PATH/taosx-profraw/taosx-%p-%m.profraw GOCOVERDIR=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data PLUGINS_HOME=$ARTIFACT_BASE_DIR/$DIR_PATH/bin/ ENABLE_COVERAGE=true nohup $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx serve > $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx.log 2>&1 &'"

      - name: Deploy taosx-agent
        run: |
          pwd
          ls ${{ github.workspace }}
          # run taosx-agent
          ssh root@$RELEASE_HOST "nohup sh -c 'GOCOVERDIR=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/ PLUGINS_HOME=$ARTIFACT_BASE_DIR/$DIR_PATH/bin/ ENABLE_COVERAGE=true LLVM_PROFILE_FILE=$ARTIFACT_BASE_DIR/$DIR_PATH/taosx-agent-profraw/taosx-agent-%p-%m.profraw nohup $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx-agent > $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx-agent.log 2>&1 &'"

  test_others:
    runs-on: [self-hosted, linux, x64, qa, rust]
    needs: deploy_for_others
    steps:
      - name: Update Repo
        run: |
          # 这里最好是 TestNG_taosx 已经被拉取到一个固定的位置
          # 重新登录执行 git pull，因为当前的 git 仓库对应的是 taosx
          ssh root@$RELEASE_HOST "cd /data/github/TestNG_taosX && git pull"
      
      - name: Restart taos-explorer & taosadapter
        run: |
          systemctl restart taos-explorer
          systemctl restart taosadapter
      
      - name: Run Test
        continue-on-error: true
        run: |
          rm -rf $COVERAGE_BASE_DIR/opentsdb/
          rm -rf $COVERAGE_BASE_DIR/influxdb/
          ls $COVERAGE_BASE_DIR/$DIR_PATH/allure_profile || mkdir -p $COVERAGE_BASE_DIR/$DIR_PATH/allure_profile
          cd /data/github/TestNG_taosX && source ./setenv.sh && poetry install && cd tests && poetry run pytest --reruns 3 --reruns-delay 1 --alluredir=$COVERAGE_BASE_DIR/$DIR_PATH/allure_profile --timeout=300 -m sanity -k "not mqtt_test.py"
          #cd /data/github/TestNG_taosX && source ./setenv.sh && poetry install && cd tests && poetry run pytest --reruns 3 --reruns-delay 1 --alluredir=$COVERAGE_BASE_DIR/$DIR_PATH/allure_profile --timeout=300 -m sanity opcua_test.py

      - name: Stop taosx-agent & taosx
        shell: bash {0}
        run: |
          pids=$(pgrep "taosx-agent"); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -2 taosx-agent $pid"; kill -2 "$pid"; done; fi
          pids=$(pgrep "taosx"); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -2 taosx $pid"; kill -2 "$pid"; done; fi
      
      # - name: Sleep for 60 seconds
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '60s'
      
      # - name: Force stop taosx-agent & taosx
      #   if: always()
      #   shell: bash {0}
      #   run: |
      #     pids=$(pgrep taosx-agent); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -9 taosx-agent $pid"; kill -9 "$pid"; done; else echo "taosx-agent is safe"; fi
      #     pids=$(pgrep taosx); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -9 taosx $pid"; kill -9 "$pid"; done; exit 1; else echo "tasox is safe"; fi

  generate_report:
    runs-on: [self-hosted, linux, x64, qa, rust]
    needs: [test_others]
    env:
      REPORT_BASE_URL: http://192.168.1.45:8787
    steps:
      - name: allure report
        run: |
          allure generate $COVERAGE_BASE_DIR/$DIR_PATH/allure_profile -o $COVERAGE_BASE_DIR/$DIR_PATH/allure_report/ --clean
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/allure_report/"
      - name: taosx & agent Report
        run: |
          # taosx report
          grcov $ARTIFACT_BASE_DIR/$DIR_PATH/taosx-profraw/ -s $ARTIFACT_BASE_DIR/$DIR_PATH/taosx --binary-path $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx -t html --branch --ignore-not-existing --ignore build.rs -o $COVERAGE_BASE_DIR/$DIR_PATH/taosx
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/taosx/"
          # taosx-agent report
          grcov $ARTIFACT_BASE_DIR/$DIR_PATH/taosx-agent-profraw/ -s $ARTIFACT_BASE_DIR/$DIR_PATH/taosx --binary-path $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx-agent -t html --branch --ignore-not-existing --ignore build.rs -o $COVERAGE_BASE_DIR/$DIR_PATH/taosx-agent
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/taosx-agent/"

          # taosx merged report
          grcov $ARTIFACT_BASE_DIR/$DIR_PATH/taosx-profraw/ -s $ARTIFACT_BASE_DIR/$DIR_PATH/taosx --binary-path $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx -t lcov --branch --ignore-not-existing --ignore build.rs -o $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_taosx.info
          /root/.cargo/bin/grcov $ARTIFACT_BASE_DIR/$DIR_PATH/taosx-agent-profraw/ -s $ARTIFACT_BASE_DIR/$DIR_PATH/taosx --binary-path $ARTIFACT_BASE_DIR/$DIR_PATH/bin/taosx-agent -t lcov --branch --ignore-not-existing --ignore build.rs -o $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_taosx-agent.info
          # merge filter report
          if [-f "$ARTIFACT_BASE_DIR/$DIR_PATH/taosx-unit-test-lcov.info"]; then
            lcov -a $ARTIFACT_BASE_DIR/$DIR_PATH/taosx-unit-test-lcov.info \
              -a $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_taosx.info \
              -a $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_taosx-agent.info \
              -o $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_combined.info --quiet
          else
            lcov -a $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_taosx.info \
              -a $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_taosx-agent.info \
              -o $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_combined.info --quiet
          fi

          lcov --remove $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_combined.info '*/.cargo/*' '*/report/*' '*/target/*' -o $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_combined_removed.info --quiet

          genhtml -o $COVERAGE_BASE_DIR/$DIR_PATH/taosx-report-merged/ --quiet --ignore-errors source --ignore-errors unmapped --show-details --highlight --legend $ARTIFACT_BASE_DIR/$DIR_PATH/lcov_combined_removed.info
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/taosx-report-merged/"

      - name: mqtt & opc Report
        run: |
          # mqtt report
          ls $COVERAGE_BASE_DIR/$DIR_PATH/mqtt || mkdir -p $COVERAGE_BASE_DIR/$DIR_PATH/mqtt
          cd $ARTIFACT_BASE_DIR/$DIR_PATH/taosx/plugins/mqtt
          # go test -coverpkg=./... -coverprofile=mqtt_unit_report.txt  -timeout=5s ./...
          if [ -f "$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data/mqtt_unit_report.txt" ]; then
            # go test -coverpkg=./... -coverprofile=mqtt_unit_report.txt  -timeout=5s ./...
            mv $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data/mqtt_unit_report.txt .
            go tool covdata textfmt -i=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data -o=mqtt_report.txt
            /root/go/bin/gocov convert mqtt_unit_report.txt mqtt_report.txt | /root/go/bin/gocov-html > $COVERAGE_BASE_DIR/$DIR_PATH/mqtt/index.html
          else
            go tool covdata textfmt -i=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/mqtt_cover_data -o=mqtt_report.txt
            /root/go/bin/gocov convert mqtt_report.txt | /root/go/bin/gocov-html > $COVERAGE_BASE_DIR/$DIR_PATH/mqtt/index.html
          fi
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/mqtt/"
          # opc report
          ls $COVERAGE_BASE_DIR/$DIR_PATH/opc || mkdir -p $COVERAGE_BASE_DIR/$DIR_PATH/opc
          cd $ARTIFACT_BASE_DIR/$DIR_PATH/taosx/plugins/opc
          if [ -f "$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/opc_unit_report.txt" ]; then
            mv $ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data/opc_unit_report.txt .
            go tool covdata textfmt -i=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data -o=opc_report.txt
            /root/go/bin/gocov convert opc_unit_report.txt opc_report.txt | /root/go/bin/gocov-html > $COVERAGE_BASE_DIR/$DIR_PATH/opc/index.html
          else
            go tool covdata textfmt -i=$ARTIFACT_BASE_DIR/$DIR_PATH/go_cover/opc_cover_data -o=opc_report.txt
            /root/go/bin/gocov convert opc_report.txt | /root/go/bin/gocov-html > $COVERAGE_BASE_DIR/$DIR_PATH/opc/index.html
          fi
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/opc/"

      - name: influxdb & opentsdb report
        run: |
          # opentsdb report
          java -jar $COVERAGE_BASE_DIR/jacococli.jar merge $COVERAGE_BASE_DIR/opentsdb/*.exec --destfile $COVERAGE_BASE_DIR/opentsdb/opentsdb.exec
          java -jar $COVERAGE_BASE_DIR/jacococli.jar report $COVERAGE_BASE_DIR/opentsdb/opentsdb.exec --classfiles $ARTIFACT_BASE_DIR/$DIR_PATH/bin/opentsdb/classes --sourcefiles $ARTIFACT_BASE_DIR/$DIR_PATH/taosx/plugins/opentsdb/src/main/java --html $COVERAGE_BASE_DIR/$DIR_PATH/opentsdb/
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/opentsdb/"
          # influxdb report
          java -jar $COVERAGE_BASE_DIR/jacococli.jar merge $COVERAGE_BASE_DIR/influxdb/*.exec --destfile $COVERAGE_BASE_DIR/influxdb/influxdb.exec
          java -jar $COVERAGE_BASE_DIR/jacococli.jar report $COVERAGE_BASE_DIR/influxdb/influxdb.exec --classfiles $ARTIFACT_BASE_DIR/$DIR_PATH/bin/influxdb/classes --sourcefiles $ARTIFACT_BASE_DIR/$DIR_PATH/taosx/plugins/influxdb/src/main/java --html $COVERAGE_BASE_DIR/$DIR_PATH/influxdb/
          echo "see report at $REPORT_BASE_URL/$DIR_PATH/influxdb/"
      
      - name: Force stop taosx-agent & taosx
        if: always()
        shell: bash {0}
        run: |
          pids=$(pgrep taosx-agent); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -9 taosx-agent $pid"; kill -9 "$pid"; done; else echo "taosx-agent is safe"; fi
          pids=$(pgrep taosx); if [ -n "$pids" ]; then for pid in $pids; do echo "run kill -9 taosx $pid"; kill -9 "$pid"; done; else echo "tasox is safe"; fi
  

  feishu_report:
    runs-on: [self-hosted, linux, x64, qa, rust]
    needs: [build_rust, build_go, build_java, deploy_for_mqtt, test_mqtt, deploy_for_others, test_others, generate_report]
    if: failure()
    steps: 
      - name: Send Feishu Message
        # if: ${{ needs.generate_report.result != 'success' }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"msg_type\":\"text\",\"content\":{\"text\":\"${{ github.workflow }} run failed, \n see reason at: https://github.com/taosdata/taosx/actions/runs/${{ github.run_id }}\"}}" \
          https://open.feishu.cn/open-apis/bot/v2/hook/ead5417f-20b9-425c-8ce7-f4b8dd008deb
        