name: create-test-cases-docs
on: # 在什么时候触发工作流
  push: # 在从本地main分支被push到GitHub仓库时
    branches:
      - main
    paths:
      - 'tests/e2e/**/*.py'
  workflow_dispatch:

jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v2 # 先checkout到main分支
      - uses: actions/setup-python@v2 # 再安装Python3和相关环境
        with:
          python-version: 3.x
      - run: pip install mkdocs-material # 使用pip包管理工具安装mkdocs-material
      - run: pip install "mkdocstrings[python]"
      - run: cd tests/e2e && mkdocs gh-deploy --force # 使用mkdocs-material部署gh-pages分支
