.\" testsaslauthd - SASL2 test tool
.\" Dima Barsky 23/12/2002
.\"

.\"
.TH TESTSASLAUTHD 8 "December 23, 2002" "CMU SASL"
.SH NAME
testsaslauthd \- a test tool for saslauthd
.SH SYNOPSIS
.B testsaslauthd -u username -p password
              [-r realm] [-s servicename]
              [-f socket path] [-R repeatnum]

.SH DESCRIPTION
This tool is for testing the saslauthd daemon. Do not use it unless you 
know what you are doing. Read the source code if you need more information.
